import { createFileRoute, Link } from "@tanstack/react-router";
import { PublicPageShell } from "@/components/public-page-shell";

export const Route = createFileRoute("/terms")({
  head: () => ({
    meta: [
      { title: "Terms of Service — CLOE Prep" },
      {
        name: "description",
        content: "The terms that govern your use of CLOE Prep.",
      },
      { property: "og:url", content: "https://cloe.antonyaddy.com/terms" },
    ],
    links: [{ rel: "canonical", href: "https://cloe.antonyaddy.com/terms" }],
  }),
  component: TermsPage,
});

function TermsPage() {
  return (
    <PublicPageShell>
      <h1 className="text-3xl md:text-4xl font-bold text-primary">Terms of Service</h1>
      <p className="mt-2 text-sm text-muted-foreground">Last updated: 27 July 2026</p>

      <div className="mt-8 space-y-8 text-sm md:text-base leading-relaxed text-foreground/90">
        <section>
          <h2 className="text-lg font-semibold text-foreground">1. The service</h2>
          <p className="mt-2">
            CLOE Prep is an independent study tool for the CLOE English certification, published by
            Antony Addy (SIRET 48317889300028, 135 rue Henri Vadon, Résidence des Arènes, 83600
            Fréjus, France). CLOE Prep is not affiliated with, endorsed by, or connected to the
            official CLOE certification or the organisations that deliver it. All practice material
            is original.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground">2. Accounts</h2>
          <p className="mt-2">
            You can use CLOE Prep as an anonymous guest, or create an account with an email and
            password, a magic link, or Google sign-in. You're responsible for keeping your login
            details secure and for all activity under your account.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground">3. Acceptable use</h2>
          <p className="mt-2">You agree not to:</p>
          <ul className="mt-2 list-disc pl-5 space-y-1">
            <li>Use the service to generate or submit unlawful, abusive, or harmful content.</li>
            <li>
              Attempt to scrape, reverse-engineer, or resell the question bank or AI feedback in
              bulk.
            </li>
            <li>Attempt to bypass usage limits, authentication, or paid-plan restrictions.</li>
            <li>Interfere with the normal operation of the service for other users.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground">4. Subscriptions and billing</h2>
          <p className="mt-2">
            Some features may require a paid subscription ("Pro plan"). Where paid plans are
            available, pricing is shown on our{" "}
            <Link to="/pricing" className="underline">
              Pricing
            </Link>{" "}
            page and billing is processed by Stripe. Subscriptions renew automatically until you
            cancel; you can cancel at any time from your account and you'll keep access until the
            end of your current billing period. See our{" "}
            <Link to="/refund-policy" className="underline">
              Refund Policy
            </Link>{" "}
            for details on refunds.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground">5. AI-generated feedback</h2>
          <p className="mt-2">
            Writing and speaking feedback is generated by an AI model based on your submissions.
            It's provided to help you practice and is not a certified assessment of your English
            level or a guarantee of your result on the actual CLOE exam.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground">6. Intellectual property</h2>
          <p className="mt-2">
            All practice content, design, and branding on CLOE Prep belong to Antony Addy unless
            otherwise noted. You may use the service for your own personal study; you may not copy,
            redistribute, or commercially exploit the content.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground">7. Disclaimers and liability</h2>
          <p className="mt-2">
            CLOE Prep is provided "as is," for educational purposes, without any guarantee of exam
            outcomes. To the extent permitted by law, we're not liable for indirect or consequential
            losses arising from your use of the service.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground">8. Termination</h2>
          <p className="mt-2">
            You can stop using the service at any time, and can request deletion of your account and
            data as described in our Privacy Policy. We may suspend or terminate accounts that
            violate these terms.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground">9. Governing law</h2>
          <p className="mt-2">These terms are governed by French law.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground">10. Contact</h2>
          <p className="mt-2">Questions about these terms: formations@antonyaddy.com</p>
        </section>

        <p className="text-xs text-muted-foreground italic">
          This is a plain-language summary of our terms, not a substitute for legal advice specific
          to your situation.
        </p>
      </div>
    </PublicPageShell>
  );
}
