/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as LegalNoticeRouteImport } from './routes/legal-notice'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedMockExamRouteImport } from './routes/_authenticated/mock-exam'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedPracticeRouteImport } from './routes/_authenticated/practice'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedProgressRouteImport } from './routes/_authenticated/progress'
import { Route as AuthenticatedAdminGenerateRouteImport } from './routes/_authenticated/admin.generate'
import { Route as AuthenticatedPracticeIndexRouteImport } from './routes/_authenticated/practice.index'
import { Route as AuthenticatedPracticeGrammarVocabRouteImport } from './routes/_authenticated/practice.grammar-vocab'
import { Route as AuthenticatedPracticeListeningRouteImport } from './routes/_authenticated/practice.listening'
import { Route as AuthenticatedPracticeReadingRouteImport } from './routes/_authenticated/practice.reading'
import { Route as AuthenticatedPracticeSpeakingRouteImport } from './routes/_authenticated/practice.speaking'
import { Route as AuthenticatedPracticeWordBankRouteImport } from './routes/_authenticated/practice.word-bank'
import { Route as AuthenticatedPracticeWritingRouteImport } from './routes/_authenticated/practice.writing'
import { Route as ApiSpeakingEvaluateRouteImport } from './routes/api/speaking/evaluate'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalNoticeRoute = LegalNoticeRouteImport.update({
  id: '/legal-notice',
  path: '/legal-notice',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMockExamRoute = AuthenticatedMockExamRouteImport.update({
  id: '/mock-exam',
  path: '/mock-exam',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPracticeRoute = AuthenticatedPracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProgressRoute = AuthenticatedProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminGenerateRoute =
  AuthenticatedAdminGenerateRouteImport.update({
    id: '/admin/generate',
    path: '/admin/generate',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPracticeIndexRoute =
  AuthenticatedPracticeIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPracticeRoute,
  } as any)
const AuthenticatedPracticeGrammarVocabRoute =
  AuthenticatedPracticeGrammarVocabRouteImport.update({
    id: '/grammar-vocab',
    path: '/grammar-vocab',
    getParentRoute: () => AuthenticatedPracticeRoute,
  } as any)
const AuthenticatedPracticeListeningRoute =
  AuthenticatedPracticeListeningRouteImport.update({
    id: '/listening',
    path: '/listening',
    getParentRoute: () => AuthenticatedPracticeRoute,
  } as any)
const AuthenticatedPracticeReadingRoute =
  AuthenticatedPracticeReadingRouteImport.update({
    id: '/reading',
    path: '/reading',
    getParentRoute: () => AuthenticatedPracticeRoute,
  } as any)
const AuthenticatedPracticeSpeakingRoute =
  AuthenticatedPracticeSpeakingRouteImport.update({
    id: '/speaking',
    path: '/speaking',
    getParentRoute: () => AuthenticatedPracticeRoute,
  } as any)
const AuthenticatedPracticeWordBankRoute =
  AuthenticatedPracticeWordBankRouteImport.update({
    id: '/word-bank',
    path: '/word-bank',
    getParentRoute: () => AuthenticatedPracticeRoute,
  } as any)
const AuthenticatedPracticeWritingRoute =
  AuthenticatedPracticeWritingRouteImport.update({
    id: '/writing',
    path: '/writing',
    getParentRoute: () => AuthenticatedPracticeRoute,
  } as any)
const ApiSpeakingEvaluateRoute = ApiSpeakingEvaluateRouteImport.update({
  id: '/api/speaking/evaluate',
  path: '/api/speaking/evaluate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/auth': typeof AuthRoute
  '/faq': typeof FaqRoute
  '/legal-notice': typeof LegalNoticeRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/mock-exam': typeof AuthenticatedMockExamRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/practice': typeof AuthenticatedPracticeRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/admin/generate': typeof AuthenticatedAdminGenerateRoute
  '/practice/grammar-vocab': typeof AuthenticatedPracticeGrammarVocabRoute
  '/practice/listening': typeof AuthenticatedPracticeListeningRoute
  '/practice/reading': typeof AuthenticatedPracticeReadingRoute
  '/practice/speaking': typeof AuthenticatedPracticeSpeakingRoute
  '/practice/word-bank': typeof AuthenticatedPracticeWordBankRoute
  '/practice/writing': typeof AuthenticatedPracticeWritingRoute
  '/api/speaking/evaluate': typeof ApiSpeakingEvaluateRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/practice/': typeof AuthenticatedPracticeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/auth': typeof AuthRoute
  '/faq': typeof FaqRoute
  '/legal-notice': typeof LegalNoticeRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/mock-exam': typeof AuthenticatedMockExamRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/admin/generate': typeof AuthenticatedAdminGenerateRoute
  '/practice/grammar-vocab': typeof AuthenticatedPracticeGrammarVocabRoute
  '/practice/listening': typeof AuthenticatedPracticeListeningRoute
  '/practice/reading': typeof AuthenticatedPracticeReadingRoute
  '/practice/speaking': typeof AuthenticatedPracticeSpeakingRoute
  '/practice/word-bank': typeof AuthenticatedPracticeWordBankRoute
  '/practice/writing': typeof AuthenticatedPracticeWritingRoute
  '/api/speaking/evaluate': typeof ApiSpeakingEvaluateRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/practice': typeof AuthenticatedPracticeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/accessibility': typeof AccessibilityRoute
  '/auth': typeof AuthRoute
  '/faq': typeof FaqRoute
  '/legal-notice': typeof LegalNoticeRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms': typeof TermsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/mock-exam': typeof AuthenticatedMockExamRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/practice': typeof AuthenticatedPracticeRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/progress': typeof AuthenticatedProgressRoute
  '/_authenticated/admin/generate': typeof AuthenticatedAdminGenerateRoute
  '/_authenticated/practice/grammar-vocab': typeof AuthenticatedPracticeGrammarVocabRoute
  '/_authenticated/practice/listening': typeof AuthenticatedPracticeListeningRoute
  '/_authenticated/practice/reading': typeof AuthenticatedPracticeReadingRoute
  '/_authenticated/practice/speaking': typeof AuthenticatedPracticeSpeakingRoute
  '/_authenticated/practice/word-bank': typeof AuthenticatedPracticeWordBankRoute
  '/_authenticated/practice/writing': typeof AuthenticatedPracticeWritingRoute
  '/api/speaking/evaluate': typeof ApiSpeakingEvaluateRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/_authenticated/practice/': typeof AuthenticatedPracticeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accessibility'
    | '/auth'
    | '/faq'
    | '/legal-notice'
    | '/mentions-legales'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/terms'
    | '/dashboard'
    | '/mock-exam'
    | '/onboarding'
    | '/practice'
    | '/profile'
    | '/progress'
    | '/admin/generate'
    | '/practice/grammar-vocab'
    | '/practice/listening'
    | '/practice/reading'
    | '/practice/speaking'
    | '/practice/word-bank'
    | '/practice/writing'
    | '/api/speaking/evaluate'
    | '/api/stripe/webhook'
    | '/practice/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accessibility'
    | '/auth'
    | '/faq'
    | '/legal-notice'
    | '/mentions-legales'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/terms'
    | '/dashboard'
    | '/mock-exam'
    | '/onboarding'
    | '/profile'
    | '/progress'
    | '/admin/generate'
    | '/practice/grammar-vocab'
    | '/practice/listening'
    | '/practice/reading'
    | '/practice/speaking'
    | '/practice/word-bank'
    | '/practice/writing'
    | '/api/speaking/evaluate'
    | '/api/stripe/webhook'
    | '/practice'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/accessibility'
    | '/auth'
    | '/faq'
    | '/legal-notice'
    | '/mentions-legales'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/terms'
    | '/_authenticated/dashboard'
    | '/_authenticated/mock-exam'
    | '/_authenticated/onboarding'
    | '/_authenticated/practice'
    | '/_authenticated/profile'
    | '/_authenticated/progress'
    | '/_authenticated/admin/generate'
    | '/_authenticated/practice/grammar-vocab'
    | '/_authenticated/practice/listening'
    | '/_authenticated/practice/reading'
    | '/_authenticated/practice/speaking'
    | '/_authenticated/practice/word-bank'
    | '/_authenticated/practice/writing'
    | '/api/speaking/evaluate'
    | '/api/stripe/webhook'
    | '/_authenticated/practice/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AccessibilityRoute: typeof AccessibilityRoute
  AuthRoute: typeof AuthRoute
  FaqRoute: typeof FaqRoute
  LegalNoticeRoute: typeof LegalNoticeRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  TermsRoute: typeof TermsRoute
  ApiSpeakingEvaluateRoute: typeof ApiSpeakingEvaluateRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal-notice': {
      id: '/legal-notice'
      path: '/legal-notice'
      fullPath: '/legal-notice'
      preLoaderRoute: typeof LegalNoticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mock-exam': {
      id: '/_authenticated/mock-exam'
      path: '/mock-exam'
      fullPath: '/mock-exam'
      preLoaderRoute: typeof AuthenticatedMockExamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/practice': {
      id: '/_authenticated/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof AuthenticatedPracticeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/progress': {
      id: '/_authenticated/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AuthenticatedProgressRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/generate': {
      id: '/_authenticated/admin/generate'
      path: '/admin/generate'
      fullPath: '/admin/generate'
      preLoaderRoute: typeof AuthenticatedAdminGenerateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/practice/': {
      id: '/_authenticated/practice/'
      path: '/'
      fullPath: '/practice/'
      preLoaderRoute: typeof AuthenticatedPracticeIndexRouteImport
      parentRoute: typeof AuthenticatedPracticeRoute
    }
    '/_authenticated/practice/grammar-vocab': {
      id: '/_authenticated/practice/grammar-vocab'
      path: '/grammar-vocab'
      fullPath: '/practice/grammar-vocab'
      preLoaderRoute: typeof AuthenticatedPracticeGrammarVocabRouteImport
      parentRoute: typeof AuthenticatedPracticeRoute
    }
    '/_authenticated/practice/listening': {
      id: '/_authenticated/practice/listening'
      path: '/listening'
      fullPath: '/practice/listening'
      preLoaderRoute: typeof AuthenticatedPracticeListeningRouteImport
      parentRoute: typeof AuthenticatedPracticeRoute
    }
    '/_authenticated/practice/reading': {
      id: '/_authenticated/practice/reading'
      path: '/reading'
      fullPath: '/practice/reading'
      preLoaderRoute: typeof AuthenticatedPracticeReadingRouteImport
      parentRoute: typeof AuthenticatedPracticeRoute
    }
    '/_authenticated/practice/speaking': {
      id: '/_authenticated/practice/speaking'
      path: '/speaking'
      fullPath: '/practice/speaking'
      preLoaderRoute: typeof AuthenticatedPracticeSpeakingRouteImport
      parentRoute: typeof AuthenticatedPracticeRoute
    }
    '/_authenticated/practice/word-bank': {
      id: '/_authenticated/practice/word-bank'
      path: '/word-bank'
      fullPath: '/practice/word-bank'
      preLoaderRoute: typeof AuthenticatedPracticeWordBankRouteImport
      parentRoute: typeof AuthenticatedPracticeRoute
    }
    '/_authenticated/practice/writing': {
      id: '/_authenticated/practice/writing'
      path: '/writing'
      fullPath: '/practice/writing'
      preLoaderRoute: typeof AuthenticatedPracticeWritingRouteImport
      parentRoute: typeof AuthenticatedPracticeRoute
    }
    '/api/speaking/evaluate': {
      id: '/api/speaking/evaluate'
      path: '/api/speaking/evaluate'
      fullPath: '/api/speaking/evaluate'
      preLoaderRoute: typeof ApiSpeakingEvaluateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedPracticeRouteChildren {
  AuthenticatedPracticeGrammarVocabRoute: typeof AuthenticatedPracticeGrammarVocabRoute
  AuthenticatedPracticeListeningRoute: typeof AuthenticatedPracticeListeningRoute
  AuthenticatedPracticeReadingRoute: typeof AuthenticatedPracticeReadingRoute
  AuthenticatedPracticeSpeakingRoute: typeof AuthenticatedPracticeSpeakingRoute
  AuthenticatedPracticeWordBankRoute: typeof AuthenticatedPracticeWordBankRoute
  AuthenticatedPracticeWritingRoute: typeof AuthenticatedPracticeWritingRoute
  AuthenticatedPracticeIndexRoute: typeof AuthenticatedPracticeIndexRoute
}

const AuthenticatedPracticeRouteChildren: AuthenticatedPracticeRouteChildren = {
  AuthenticatedPracticeGrammarVocabRoute:
    AuthenticatedPracticeGrammarVocabRoute,
  AuthenticatedPracticeListeningRoute: AuthenticatedPracticeListeningRoute,
  AuthenticatedPracticeReadingRoute: AuthenticatedPracticeReadingRoute,
  AuthenticatedPracticeSpeakingRoute: AuthenticatedPracticeSpeakingRoute,
  AuthenticatedPracticeWordBankRoute: AuthenticatedPracticeWordBankRoute,
  AuthenticatedPracticeWritingRoute: AuthenticatedPracticeWritingRoute,
  AuthenticatedPracticeIndexRoute: AuthenticatedPracticeIndexRoute,
}

const AuthenticatedPracticeRouteWithChildren =
  AuthenticatedPracticeRoute._addFileChildren(
    AuthenticatedPracticeRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMockExamRoute: typeof AuthenticatedMockExamRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPracticeRoute: typeof AuthenticatedPracticeRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedProgressRoute: typeof AuthenticatedProgressRoute
  AuthenticatedAdminGenerateRoute: typeof AuthenticatedAdminGenerateRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMockExamRoute: AuthenticatedMockExamRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPracticeRoute: AuthenticatedPracticeRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedProgressRoute: AuthenticatedProgressRoute,
  AuthenticatedAdminGenerateRoute: AuthenticatedAdminGenerateRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AccessibilityRoute: AccessibilityRoute,
  AuthRoute: AuthRoute,
  FaqRoute: FaqRoute,
  LegalNoticeRoute: LegalNoticeRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  TermsRoute: TermsRoute,
  ApiSpeakingEvaluateRoute: ApiSpeakingEvaluateRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
