-- Round 5: rounding out grammar_vocab, listening, reading, writing, speaking
-- to bring all skills to comparable relative depth.

-- Grammar/vocab (36 mcq)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation) VALUES
  ('grammar_vocab', 'A1', 'mcq', 'tenses', 'This building _____ three lifts.', to_jsonb(ARRAY['has','have','having','is having']::text[]), 'has', '''Has'' is correct because ''This building'' is third-person singular in the simple present. ''Have'' is wrong subject-verb agreement. ''Having'' is not a finite verb and cannot stand alone as the main verb. ''Is having'' is wrong because possession/existence with ''have'' is a stative meaning and is not normally used in the continuous form.'),
  ('grammar_vocab', 'A2', 'mcq', 'tenses', 'I can''t come to the meeting on Thursday - I _____ the dentist that afternoon.', to_jsonb(ARRAY['am seeing','see','saw','have seen']::text[]), 'am seeing', 'The present continuous (''am seeing'') is the standard form for a fixed future arrangement. ''See'' (simple present) suggests a habit, not a scheduled future event. ''Saw'' is past tense, which contradicts the future time reference. ''Have seen'' (present perfect) describes a completed past action, not an upcoming appointment.'),
  ('grammar_vocab', 'B1', 'mcq', 'tenses', 'The IT department _____ the server twice this week already.', to_jsonb(ARRAY['has upgraded','upgraded','upgrades','was upgrading']::text[]), 'has upgraded', '''Has upgraded'' (present perfect) is required because ''this week'' is an unfinished time period and ''already'' signals present relevance. ''Upgraded'' (simple past) is wrong with an unfinished time period. ''Upgrades'' (simple present) doesn''t fit a completed-action count. ''Was upgrading'' (past continuous) wrongly implies an interrupted, single ongoing action rather than two completed events.'),
  ('grammar_vocab', 'B2', 'mcq', 'tenses', 'New passwords _____ automatically every 90 days to keep the system secure.', to_jsonb(ARRAY['are generated','generate','generated','are generating']::text[]), 'are generated', 'Passive present simple (''are generated'') is correct because passwords don''t generate themselves - the system does it to them, and the sentence describes a repeated automatic process. ''Generate'' (active voice) wrongly makes the passwords the ones performing the action. ''Generated'' alone lacks the auxiliary ''are'' and is ungrammatical here. ''Are generating'' (active continuous) is both the wrong voice and the wrong aspect for a routine, repeated process.'),
  ('grammar_vocab', 'C1', 'mcq', 'tenses', 'She told me, ''I''ve already sent the invoice.'' She told me she _____ already sent the invoice.', to_jsonb(ARRAY['had','has','have','was']::text[]), 'had', 'In reported speech, present perfect (''have sent'') backshifts to past perfect (''had sent''). ''Has'' and ''have'' fail to backshift and don''t agree in tense with the reporting verb ''told''. ''Was'' would require a passive construction (''was sent'') and doesn''t fit the active meaning of the original statement.'),
  ('grammar_vocab', 'C2', 'mcq', 'tenses', 'Rarely _____ such a dramatic increase in quarterly profits since the company was founded.', to_jsonb(ARRAY['have we seen','we have seen','did we see','we saw']::text[]), 'have we seen', 'The negative adverbial ''Rarely'' fronted for emphasis requires subject-auxiliary inversion, and ''since the company was founded'' requires the present perfect aspect - together these demand ''have we seen''. ''We have seen'' has the right tense but no inversion. ''Did we see'' inverts correctly but uses the wrong aspect (simple past), which clashes with ''since''. ''We saw'' has neither inversion nor the correct aspect.'),
  ('grammar_vocab', 'A1', 'mcq', 'prepositions', 'The workshop takes place _____ the morning.', to_jsonb(ARRAY['in','on','at','since']::text[]), 'in', '''In the morning'' is the fixed time expression. ''On the morning'' is ungrammatical (we say ''on Monday morning'', not ''on the morning''). ''At the morning'' is wrong because ''at'' is used for clock times, not parts of the day. ''Since the morning'' would need a different sentence structure indicating a starting point, not a general time.'),
  ('grammar_vocab', 'A2', 'mcq', 'prepositions', 'I go to work _____ bus every day.', to_jsonb(ARRAY['by','in','with','on']::text[]), 'by', '''By bus'' is the fixed expression for a method of transport, used without an article. ''In bus'' is ungrammatical - ''in'' requires an article (''in the bus''). ''With bus'' is not a valid transport expression. ''On bus'' is also ungrammatical without an article (''on the bus'').'),
  ('grammar_vocab', 'B1', 'mcq', 'prepositions', 'She''s not afraid _____ making mistakes; she learns from them.', to_jsonb(ARRAY['of','for','with','about']::text[]), 'of', '''Afraid of'' is the correct fixed preposition combination for fearing something. ''Afraid for'' means worried about someone''s safety, which doesn''t fit here. ''Afraid with'' is not a standard combination. ''Afraid about'' is not idiomatic English.'),
  ('grammar_vocab', 'B2', 'mcq', 'prepositions', 'The company decided to invest heavily _____ renewable energy.', to_jsonb(ARRAY['in','on','for','to']::text[]), 'in', '''Invest in'' is the fixed collocation for putting money into something. ''Invest on'' is not standard English. ''Invest for'' and ''invest to'' are also not correct prepositional combinations with ''invest''.'),
  ('grammar_vocab', 'C1', 'mcq', 'prepositions', '_____ light of the recent budget cuts, all travel requests must now be pre-approved by a manager.', to_jsonb(ARRAY['In','By','At','On']::text[]), 'In', '''In light of'' is the fixed formal expression meaning ''considering'' or ''because of''. ''By light of'', ''at light of'', and ''on light of'' are not valid English expressions.'),
  ('grammar_vocab', 'C2', 'mcq', 'prepositions', 'The manager approved the loan _____ the strength of the client''s excellent credit history.', to_jsonb(ARRAY['on','in','by','with']::text[]), 'on', '''On the strength of'' is a fixed idiomatic expression meaning ''on the basis of'' or ''because of''. ''In the strength of'', ''by the strength of'', and ''with the strength of'' are not valid English expressions.'),
  ('grammar_vocab', 'A1', 'mcq', 'business_vocab', 'I get paid my _____ on the last day of each month.', to_jsonb(ARRAY['salary','invoice','receipt','budget']::text[]), 'salary', '''Salary'' is the regular payment an employee receives for their work. ''Invoice'' is a bill sent to a customer requesting payment, not something an employee receives. ''Receipt'' is proof of a purchase. ''Budget'' is a financial plan, not a payment to an employee.'),
  ('grammar_vocab', 'A2', 'mcq', 'business_vocab', 'I have an _____ with a client at 2 p.m.', to_jsonb(ARRAY['appointment','warehouse','budget','supplier']::text[]), 'appointment', '''Appointment'' is a scheduled meeting with someone, which fits the context of meeting a client at a set time. ''Warehouse'' is a storage building. ''Budget'' is a financial plan. ''Supplier'' is a company that provides goods, not an event you can ''have'' at a specific time.'),
  ('grammar_vocab', 'B1', 'mcq', 'business_vocab', 'She works the night _____ three times a week.', to_jsonb(ARRAY['shift','quota','agenda','invoice']::text[]), 'shift', '''Shift'' refers to a scheduled work period, and ''night shift'' is a standard collocation. ''Quota'' is a required target amount, not a work period. ''Agenda'' is a list of meeting topics. ''Invoice'' is a bill for goods or services.'),
  ('grammar_vocab', 'B2', 'mcq', 'business_vocab', 'Rising _____ such as rent and utilities are squeezing the company''s profit margins.', to_jsonb(ARRAY['overheads','turnover','subsidiary','stakeholders']::text[]), 'overheads', '''Overheads'' refers to ongoing operating costs like rent and utilities, which fits the example given. ''Turnover'' is total sales revenue, not a cost, so rising turnover wouldn''t squeeze margins. ''Subsidiary'' is a company owned by another company. ''Stakeholders'' are people or groups with an interest in the business, not expenses.'),
  ('grammar_vocab', 'C1', 'mcq', 'business_vocab', 'To cut costs, the firm decided to _____ its customer support to an external agency.', to_jsonb(ARRAY['outsource','downsize','forecast','liquidate']::text[]), 'outsource', '''Outsource'' means to contract work out to an external company, which matches ''to an external agency''. ''Downsize'' means to reduce staff numbers, not hand work to an outside company. ''Forecast'' means to predict future trends. ''Liquidate'' means to sell off assets or close a business, which doesn''t fit this context.'),
  ('grammar_vocab', 'C2', 'mcq', 'business_vocab', 'The investment bank agreed to _____ the company''s new bond issue.', to_jsonb(ARRAY['underwrite','downsize','forecast','capture']::text[]), 'underwrite', '''Underwrite'' is the specific financial term for a bank guaranteeing or assuming the risk of a securities issue. ''Downsize'' means to cut staff. ''Forecast'' means to predict. ''Capture'' (as in ''capture market share'') doesn''t fit the context of guaranteeing a bond issue.'),
  ('grammar_vocab', 'A1', 'mcq', 'phrasal_verbs', 'Please _____ the stapler when you finish using it.', to_jsonb(ARRAY['give back','give up','give in','give out']::text[]), 'give back', '''Give back'' means to return something you borrowed, which fits returning the stapler. ''Give up'' means to quit or stop trying. ''Give in'' means to surrender or agree reluctantly. ''Give out'' means to distribute something to multiple people.'),
  ('grammar_vocab', 'A2', 'mcq', 'phrasal_verbs', 'Please _____ your laptop before the meeting starts.', to_jsonb(ARRAY['put away','put on','put off','put up']::text[]), 'put away', '''Put away'' means to store something out of use, fitting the instruction to stop using the laptop before the meeting. ''Put on'' means to wear or switch on. ''Put off'' means to postpone. ''Put up'' means to erect something or tolerate something, neither of which fits here.'),
  ('grammar_vocab', 'B1', 'mcq', 'phrasal_verbs', 'The manager promised to _____ the complaint and get back to us by Friday.', to_jsonb(ARRAY['look into','look after','look up','look out']::text[]), 'look into', '''Look into'' means to investigate something, which fits examining a complaint. ''Look after'' means to take care of someone or something. ''Look up'' means to search for information, like a word in a dictionary. ''Look out'' means to be careful or watch for danger.'),
  ('grammar_vocab', 'B2', 'mcq', 'phrasal_verbs', 'Due to the client''s schedule, we need to _____ the meeting to next Monday instead of next Friday.', to_jsonb(ARRAY['bring forward','bring up','bring about','bring in']::text[]), 'bring forward', '''Bring forward'' means to move an event to an earlier time, which fits moving the meeting from Friday to the preceding Monday. ''Bring up'' means to mention a topic. ''Bring about'' means to cause something to happen. ''Bring in'' means to introduce something new, such as a policy or person.'),
  ('grammar_vocab', 'C1', 'mcq', 'phrasal_verbs', 'The shipment was _____ at customs for several days due to a paperwork error.', to_jsonb(ARRAY['held up','held off','held out','held on']::text[]), 'held up', '''Held up'' means delayed, which fits a shipment stuck at customs. ''Held off'' means postponed or kept at a distance, which doesn''t fit a passive description of a delay already happening. ''Held out'' means to endure or last. ''Held on'' means to wait or grip something.'),
  ('grammar_vocab', 'C2', 'mcq', 'phrasal_verbs', 'In his report, the manager tried to _____ the department''s poor performance instead of addressing it directly.', to_jsonb(ARRAY['gloss over','own up to','dwell on','brush up on']::text[]), 'gloss over', '''Gloss over'' means to avoid dealing with something properly or to make it seem less serious, matching ''instead of addressing it directly''. ''Own up to'' means to admit something, the opposite meaning. ''Dwell on'' means to focus on something at length, also the opposite. ''Brush up on'' means to improve a skill you already have, which is unrelated.'),
  ('grammar_vocab', 'A1', 'mcq', 'formal_register', 'You want to formally request a day off from your manager. Which message is appropriate?', to_jsonb(ARRAY['Please, may I have Friday off?','Can I have Friday off? Thanks!','Yo, need Friday off, cool?','I''m taking Friday off, just so you know.']::text[]), 'Please, may I have Friday off?', 'This is a simple, polite request suitable for asking a manager. ''Can I have Friday off? Thanks!'' is a bit too casual for a formal request. ''Yo, need Friday off, cool?'' uses slang and is inappropriately informal. ''I''m taking Friday off, just so you know'' announces the day off instead of asking for it, which is inappropriate when asking a manager.'),
  ('grammar_vocab', 'A2', 'mcq', 'formal_register', 'You are leaving a formal voicemail for a supplier you have never spoken to before. Which message is appropriate?', to_jsonb(ARRAY['Hello, this is Claire Dubois from Acme Ltd. I am calling about our order. Please call me back.','Hey it''s Claire, call me back when you can!','Claire here. Order thing. Call me.','Yo, it''s Claire from Acme, hit me up.']::text[]), 'Hello, this is Claire Dubois from Acme Ltd. I am calling about our order. Please call me back.', 'This message gives a clear name, company, and reason for calling, and closes politely, which fits a first call to a supplier you don''t know. ''Hey it''s Claire, call me back when you can!'' is too casual and does not give a full introduction. ''Claire here. Order thing. Call me.'' is too abrupt and vague. ''Yo, it''s Claire from Acme, hit me up'' uses slang unsuitable for a formal business context.'),
  ('grammar_vocab', 'B1', 'mcq', 'formal_register', 'You need to formally decline a meeting invitation due to a scheduling conflict. Which email response is appropriate?', to_jsonb(ARRAY['Thank you for the invitation. I am sorry, but I have another meeting at that time. Can we choose a different time?','Can''t make it, sorry!','I''m not coming, I''m busy.','No thanks, maybe next time!']::text[]), 'Thank you for the invitation. I am sorry, but I have another meeting at that time. Can we choose a different time?', 'This response thanks the sender, politely explains the problem, and suggests a solution, which fits a formal email. ''Can''t make it, sorry!'' is too casual and abrupt. ''I''m not coming, I''m busy'' sounds blunt and impolite. ''No thanks, maybe next time!'' is too informal for a professional context.'),
  ('grammar_vocab', 'B2', 'mcq', 'formal_register', 'You need to formally request feedback from a client after completing a project. Which email is appropriate?', to_jsonb(ARRAY['We would greatly appreciate any feedback you could provide regarding the recent project, as it helps us continually improve our service.','Tell us what you thought, ok?','Give us some feedback, thanks!','Was everything good or what?']::text[]), 'We would greatly appreciate any feedback you could provide regarding the recent project, as it helps us continually improve our service.', 'This phrasing is polite, professional, and explains the purpose of the request, suitable for a formal client email. ''Tell us what you thought, ok?'' is too casual and blunt. ''Give us some feedback, thanks!'' is an informal, direct command unsuitable for a client. ''Was everything good or what?'' is too casual and vague for a formal request.'),
  ('grammar_vocab', 'C1', 'mcq', 'formal_register', 'You need to formally notify a supplier that their invoice contains an error. Which email opening is appropriate?', to_jsonb(ARRAY['We are writing to bring to your attention a discrepancy identified in your recent invoice.','Your invoice is wrong, please fix it.','Hey, there''s a mistake on the invoice you sent, can you sort it?','We noticed you messed up the invoice again.']::text[]), 'We are writing to bring to your attention a discrepancy identified in your recent invoice.', 'This phrasing is diplomatic and formal, using ''discrepancy'' rather than a blunt accusation, appropriate for professional correspondence with a supplier. ''Your invoice is wrong, please fix it'' is too direct and blunt. ''Hey, there''s a mistake on the invoice you sent, can you sort it?'' is too informal. ''We noticed you messed up the invoice again'' is rude and unprofessional.'),
  ('grammar_vocab', 'C2', 'mcq', 'formal_register', 'You are writing to formally request an extension on a contractual deadline from a business partner, citing unforeseen circumstances. Which phrasing is most appropriate?', to_jsonb(ARRAY['Owing to circumstances beyond our control, we would be grateful if the deadline could be extended by two weeks.','We need more time, things came up.','Sorry, we''re behind schedule, can we get an extension?','Give us two more weeks or we''re done.']::text[]), 'Owing to circumstances beyond our control, we would be grateful if the deadline could be extended by two weeks.', 'This phrasing uses formal, precise language (''owing to circumstances beyond our control'', ''we would be grateful'') appropriate for a sensitive contractual request. ''We need more time, things came up'' is vague and too casual. ''Sorry, we''re behind schedule, can we get an extension?'' is too informal for this register despite being polite. ''Give us two more weeks or we''re done'' is unprofessional and confrontational.'),
  ('grammar_vocab', 'A1', 'mcq', 'collocations', 'I need to _____ some research before the meeting.', to_jsonb(ARRAY['do','make','have','take']::text[]), 'do', '''Do research'' is the correct fixed collocation in English. ''Make research'' is a common error and is not correct. ''Have research'' and ''take research'' are not standard collocations either.'),
  ('grammar_vocab', 'A2', 'mcq', 'collocations', 'Everyone _____ mistakes sometimes, so don''t worry about it.', to_jsonb(ARRAY['makes','does','takes','has']::text[]), 'makes', '''Make a mistake'' is the correct fixed collocation. ''Does mistakes'' is incorrect; the correct verb is ''make'', not ''do''. ''Takes mistakes'' is not a standard collocation. ''Has mistakes'' is not idiomatic English.'),
  ('grammar_vocab', 'B1', 'mcq', 'collocations', 'Could we _____ a quick word before you leave for the airport?', to_jsonb(ARRAY['have','make','do','take']::text[]), 'have', '''Have a word'' (meaning a brief conversation) is the correct fixed collocation. ''Make a word'' and ''do a word'' are not valid collocations. ''Take a word'' is not a standard expression with this meaning.'),
  ('grammar_vocab', 'B2', 'mcq', 'collocations', 'The two sides finally managed to _____ a deal after months of tough negotiation.', to_jsonb(ARRAY['strike','hit','beat','win']::text[]), 'strike', '''Strike a deal'' is the correct fixed collocation meaning to reach an agreement. ''Hit a deal'' and ''beat a deal'' are not standard English collocations. ''Win a deal'' is not idiomatic; you ''win a contract'' or ''win a tender'', but not ''win a deal''.'),
  ('grammar_vocab', 'C1', 'mcq', 'collocations', 'Before the sale, the retailer decided to _____ stock of all unsold inventory in the warehouse.', to_jsonb(ARRAY['take','make','do','have']::text[]), 'take', '''Take stock of'' is the fixed idiom meaning to carefully review or assess something. ''Make stock of'', ''do stock of'', and ''have stock of'' are not valid English collocations.'),
  ('grammar_vocab', 'C2', 'mcq', 'collocations', 'After the presentation, the CFO stayed behind to _____ questions from concerned shareholders.', to_jsonb(ARRAY['field','catch','hold','make']::text[]), 'field', '''Field questions'' is the fixed idiom meaning to handle or respond to questions, especially difficult ones. ''Catch questions'' is not a standard collocation. ''Hold questions'' would mean to postpone them, which is the opposite of staying behind to respond. ''Make questions'' is grammatically and idiomatically incorrect.');

-- Listening (24 mcq)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation) VALUES
  ('listening', 'A1', 'mcq', 'general', 'You hear: "The bus leaves at half past eight." What time does the bus leave?', to_jsonb(ARRAY['Half past eight','Eight o''clock','Half past nine','Quarter past eight']::text[]), 'Half past eight', 'The script states the bus leaves at half past eight. ''Eight o''clock'' and ''quarter past eight'' are wrong times, and ''half past nine'' is a different hour entirely.'),
  ('listening', 'A1', 'mcq', 'general', 'You hear: "Room 12 is on the third floor." Which floor is Room 12 on?', to_jsonb(ARRAY['The third floor','The first floor','The second floor','The fourth floor']::text[]), 'The third floor', 'The script says Room 12 is on the third floor. The first, second, and fourth floors are not mentioned.'),
  ('listening', 'A1', 'mcq', 'meeting', 'You hear: "The meeting is on Friday." Which day is the meeting?', to_jsonb(ARRAY['Friday','Monday','Thursday','Saturday']::text[]), 'Friday', 'The script clearly states the meeting is on Friday. Monday, Thursday, and Saturday are not mentioned.'),
  ('listening', 'A1', 'mcq', 'general', 'You hear: "Your coffee is ready at the counter." Where is the coffee?', to_jsonb(ARRAY['At the counter','In the kitchen','At the front desk','On the table']::text[]), 'At the counter', 'The script says the coffee is ready at the counter. The kitchen, front desk, and table are not mentioned.'),
  ('listening', 'A2', 'mcq', 'call', 'You hear: "I called the supplier yesterday, and they will send the invoice tomorrow." When will the invoice be sent?', to_jsonb(ARRAY['Tomorrow','Yesterday','Today','Next week']::text[]), 'Tomorrow', 'The call happened yesterday, but the invoice will be sent tomorrow. ''Yesterday'' refers to when the call was made, not when the invoice arrives, and ''today'' and ''next week'' are not mentioned.'),
  ('listening', 'A2', 'mcq', 'general', 'You hear: "We moved the boxes to the storage room this morning." Where were the boxes moved?', to_jsonb(ARRAY['To the storage room','To the office','To the car park','To the kitchen']::text[]), 'To the storage room', 'The script states the boxes were moved to the storage room. The office, car park, and kitchen are not mentioned.'),
  ('listening', 'A2', 'mcq', 'general', 'You hear: "The manager left early because she had a dentist appointment." Why did the manager leave early?', to_jsonb(ARRAY['She had a dentist appointment','She was feeling ill','She had a family emergency','She finished her work early']::text[]), 'She had a dentist appointment', 'The script gives the dentist appointment as the reason for leaving early. Illness, a family emergency, and finishing work early are not mentioned.'),
  ('listening', 'A2', 'mcq', 'general', 'You hear: "The new employee will start on Monday next week." When will the new employee start?', to_jsonb(ARRAY['Monday next week','This Monday','Next Friday','Next Tuesday']::text[]), 'Monday next week', 'The script specifies Monday next week as the start date. ''This Monday'', ''next Friday'', and ''next Tuesday'' are all incorrect days.'),
  ('listening', 'B1', 'mcq', 'customer_service', 'You hear: "The delivery van broke down on the highway, so the packages will arrive a day late." Why will the packages arrive late?', to_jsonb(ARRAY['The delivery van broke down','The packages were lost','The warehouse was closed','The driver was sick']::text[]), 'The delivery van broke down', 'The script gives the van breaking down as the reason for the delay. Lost packages, a closed warehouse, and a sick driver are not mentioned.'),
  ('listening', 'B1', 'mcq', 'general', 'You hear: "We usually close at six, but tonight we''re staying open until eight for stocktaking." What time are they closing tonight?', to_jsonb(ARRAY['Eight o''clock','Six o''clock','Seven o''clock','Nine o''clock']::text[]), 'Eight o''clock', 'The contrast ''but tonight'' signals the exception: closing is extended to eight o''clock, not the usual six. Seven and nine are not mentioned.'),
  ('listening', 'B1', 'mcq', 'meeting', 'You hear: "The projector in the boardroom stopped working, so the presentation moved to the small meeting room." Where is the presentation now?', to_jsonb(ARRAY['In the small meeting room','In the boardroom','In the cafeteria','In the reception area']::text[]), 'In the small meeting room', 'The broken projector caused the presentation to move to the small meeting room. The boardroom is where the problem occurred, not the new location; the cafeteria and reception area are not mentioned.'),
  ('listening', 'B1', 'mcq', 'general', 'You hear: "Tickets for the conference sold out quickly, but a few seats opened up after some cancellations." What happened to the conference tickets?', to_jsonb(ARRAY['A few became available after cancellations','They were all refunded','The conference was cancelled','More tickets were printed']::text[]), 'A few became available after cancellations', 'The script says tickets sold out, but cancellations freed up a few seats. Refunds, a cancelled conference, and printing more tickets are not mentioned.'),
  ('listening', 'B2', 'mcq', 'negotiation', 'You hear: "We might be able to extend the deadline by a few days, but only if the client agrees to the revised budget first." Under what condition can the deadline be extended?', to_jsonb(ARRAY['If the client agrees to the revised budget','If the team works overtime','If the client pays in advance','If the project is reduced in scope']::text[]), 'If the client agrees to the revised budget', 'The hedge ''only if'' ties the extension to the client accepting the revised budget. Overtime, advance payment, and reduced scope are plausible-sounding but not stated.'),
  ('listening', 'B2', 'mcq', 'call', 'You hear: "I could join the call at nine, though it depends on whether my earlier meeting finishes on time." What does the person''s availability depend on?', to_jsonb(ARRAY['Whether their earlier meeting finishes on time','Whether the client confirms first','Whether the call is rescheduled','Whether they finish their report']::text[]), 'Whether their earlier meeting finishes on time', 'The hedge ''though it depends on'' ties availability to the earlier meeting ending on time. Client confirmation, rescheduling, and a report are not mentioned.'),
  ('listening', 'B2', 'mcq', 'negotiation', 'You hear: "The vendor said they''d try to match the competitor''s price, but they couldn''t guarantee it in writing." What did the vendor NOT guarantee?', to_jsonb(ARRAY['Matching the competitor''s price in writing','Delivering on time','Offering free shipping','Extending the contract']::text[]), 'Matching the competitor''s price in writing', 'The vendor would only ''try'' to match the price and explicitly couldn''t guarantee it in writing. Delivery, shipping, and contract terms are not mentioned.'),
  ('listening', 'B2', 'mcq', 'customer_service', 'You hear: "We''d normally send a technician within 24 hours, but given the holiday, it might take a bit longer this time." Why might the technician take longer than usual?', to_jsonb(ARRAY['Because of the holiday','Because of a staff shortage','Because the part is out of stock','Because the office is relocating']::text[]), 'Because of the holiday', 'The contrast ''but given the holiday'' explains the possible delay. A staff shortage, missing part, and relocation are plausible but not stated.'),
  ('listening', 'C1', 'mcq', 'general', 'You hear: "He''s been dragging his feet on the report all week, so don''t hold your breath for it by Friday." What does the speaker imply about the report?', to_jsonb(ARRAY['It probably won''t be ready by Friday','It will definitely be ready by Friday','It has already been finished','It was cancelled this week']::text[]), 'It probably won''t be ready by Friday', '''Dragging his feet'' and ''don''t hold your breath'' are idioms implying slow progress and low expectations of the Friday deadline being met, not that it''s finished or cancelled.'),
  ('listening', 'C1', 'mcq', 'negotiation', 'You hear: "She played it pretty close to the chest during the negotiation, so we still don''t know their bottom line." What does the speaker imply about the other side''s position?', to_jsonb(ARRAY['They kept their real position hidden','They revealed their lowest price','They walked away from the deal','They agreed to every demand']::text[]), 'They kept their real position hidden', '''Played it close to the chest'' means being secretive, and ''we still don''t know their bottom line'' confirms their real position was hidden, not revealed or abandoned.'),
  ('listening', 'C1', 'mcq', 'meeting', 'You hear: "I wouldn''t read too much into the CEO skipping the call — these things happen." What is the speaker suggesting?', to_jsonb(ARRAY['The CEO''s absence probably isn''t significant','The CEO is planning to resign','The call was cancelled because of the CEO','The CEO''s absence is a serious problem']::text[]), 'The CEO''s absence probably isn''t significant', '''Wouldn''t read too much into it'' downplays the significance of the absence, contradicting resignation, cancellation, or a serious problem.'),
  ('listening', 'C1', 'mcq', 'customer_service', 'You hear: "The client''s gone quiet since the proposal went out, which usually isn''t a great sign." What does the speaker imply?', to_jsonb(ARRAY['The client may not be interested in the proposal','The client has confirmed the deal','The client is on holiday','The proposal was rejected in writing']::text[]), 'The client may not be interested in the proposal', 'Going quiet after a proposal being described as ''not a great sign'' implies waning interest, not confirmation, holiday, or a written rejection.'),
  ('listening', 'C2', 'mcq', 'meeting', 'You hear: "I''m not going to sugarcoat it — the numbers this quarter are underwhelming, though it''s not all doom and gloom if the new contract lands." What is the speaker''s real message about the quarter?', to_jsonb(ARRAY['Results are weak, but a new contract could improve things','Results are excellent this quarter','The new contract has already failed','Nothing can improve the current results']::text[]), 'Results are weak, but a new contract could improve things', '''Not going to sugarcoat it'' and ''underwhelming'' signal weak results, while ''not all doom and gloom if the new contract lands'' offers a conditional path to improvement, not failure or hopelessness.'),
  ('listening', 'C2', 'mcq', 'negotiation', 'You hear: "I''ll be straight with you, the client pushed back hard on the price, but they didn''t walk away from the table." What does the speaker imply about the negotiation?', to_jsonb(ARRAY['The client objected to the price but is still willing to continue','The client accepted the price immediately','The client ended the negotiation completely','The client agreed to pay more than asked']::text[]), 'The client objected to the price but is still willing to continue', '''Pushed back hard on the price'' shows objection, while ''didn''t walk away from the table'' confirms the negotiation is still active, ruling out immediate acceptance, ending talks, or agreeing to pay more.'),
  ('listening', 'C2', 'mcq', 'negotiation', 'You hear: "It''s not that they''re being difficult on purpose, but let''s just say flexibility isn''t exactly their strong suit." What is the speaker really saying about the other party?', to_jsonb(ARRAY['They are rigid, even if not deliberately','They are deliberately sabotaging the deal','They are more flexible than expected','They have already agreed to everything']::text[]), 'They are rigid, even if not deliberately', 'The speaker explicitly rules out deliberate difficulty while the idiom ''flexibility isn''t their strong suit'' politely implies genuine rigidity, not sabotage, flexibility, or full agreement.'),
  ('listening', 'C2', 'mcq', 'meeting', 'You hear: "He danced around the question when I asked about the merger, which tells me more than a straight answer would have." What does the speaker imply the evasive answer reveals?', to_jsonb(ARRAY['The evasiveness itself suggests something is happening','There is definitely no merger planned','He gave a clear, direct answer','The merger was officially announced']::text[]), 'The evasiveness itself suggests something is happening', '''Danced around the question'' and ''tells me more than a straight answer would have'' imply the evasion itself is meaningful, contradicting a denial, a direct answer, or an official announcement.');

-- Reading (6 passages, 18 mcq questions)
WITH passage5_0 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag) VALUES
    ('Fire Drill This Afternoon', 'There will be a fire drill today at 3 p.m. Please leave your desk when you hear the alarm. Walk to the car park behind the building. Do not use the lift. The drill will take about ten minutes.', 'reading', 'A1', 'general')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('reading', 'A1', 'mcq', 'general', 'What time is the fire drill?', to_jsonb(ARRAY['3 p.m.','10 a.m.','Ten minutes','Tomorrow']::text[]), '3 p.m.', 'The notice says the drill is ''today at 3 p.m.'' ''10 a.m.'' is not mentioned. ''Ten minutes'' is how long the drill lasts, not the start time. ''Tomorrow'' is wrong because the drill is today.', (SELECT id FROM passage5_0)),
  ('reading', 'A1', 'mcq', 'general', 'Where should employees go during the drill?', to_jsonb(ARRAY['The car park behind the building','The lift','The lunch room','The front desk']::text[]), 'The car park behind the building', 'The notice tells staff to ''walk to the car park behind the building.'' The lift is specifically forbidden. The lunch room and front desk are not mentioned.', (SELECT id FROM passage5_0)),
  ('reading', 'A1', 'mcq', 'general', 'What are employees told NOT to do?', to_jsonb(ARRAY['Use the lift','Leave their desk','Walk to the car park','Wait ten minutes']::text[]), 'Use the lift', 'The notice states ''Do not use the lift.'' Leaving the desk and walking to the car park are instructions employees ARE told to follow. Waiting ten minutes is not an instruction.', (SELECT id FROM passage5_0));

WITH passage5_1 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag) VALUES
    ('New Visitor Sign-In Procedure', 'From Monday, all visitors must sign in at the front desk before entering the office. Visitors will receive a paper badge with their name and the date. They must wear this badge at all times inside the building. Staff must collect their visitors from reception; visitors cannot walk to the offices alone. At the end of the visit, staff must return the visitor to reception, and the visitor will give back the badge before leaving. This new procedure will help us to know who is in the building at all times.', 'reading', 'A2', 'general')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('reading', 'A2', 'mcq', 'general', 'When does the new sign-in procedure start?', to_jsonb(ARRAY['Monday','Friday','Today','Next month']::text[]), 'Monday', 'The text begins ''From Monday, all visitors must sign in.'' Friday, today, and next month are not mentioned as the start date.', (SELECT id FROM passage5_1)),
  ('reading', 'A2', 'mcq', 'general', 'What must visitors do at all times inside the building?', to_jsonb(ARRAY['Wear their badge','Walk alone to the offices','Sign in every hour','Collect their badge from staff']::text[]), 'Wear their badge', 'The text says visitors ''must wear this badge at all times inside the building.'' They cannot walk alone (staff must collect them), sign-in happens once at the front desk, and the badge is issued at reception, not by staff.', (SELECT id FROM passage5_1)),
  ('reading', 'A2', 'mcq', 'general', 'Who must collect visitors from reception?', to_jsonb(ARRAY['Staff','Other visitors','Security guards','No one; visitors go alone']::text[]), 'Staff', 'The text states ''Staff must collect their visitors from reception; visitors cannot walk to the offices alone.'' Other visitors and security guards are not mentioned in this role.', (SELECT id FROM passage5_1));

WITH passage5_2 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag) VALUES
    ('Dress Code Policy Update', 'Starting next month, we are relaxing our dress code. Employees can wear smart casual clothing on all days, not just Fridays. However, employees meeting clients must still wear business formal attire. This is because several clients have their own dress codes. Jeans are allowed, but they must not have rips or holes. Shorts and flip-flops are never allowed. This is for health and safety reasons in the warehouse areas. If you are not sure whether an outfit is appropriate, ask your line manager before wearing it to work. We will review this policy in six months. You can send feedback to HR at any time.', 'reading', 'B1', 'general')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('reading', 'B1', 'mcq', 'general', 'What must employees wear when meeting clients?', to_jsonb(ARRAY['Business formal attire','Smart casual clothing','Any jeans','Shorts']::text[]), 'Business formal attire', 'The policy states employees meeting clients ''must still wear business formal attire.'' Smart casual is for normal days, jeans are a separate rule about rips and holes, and shorts are never allowed.', (SELECT id FROM passage5_2)),
  ('reading', 'B1', 'mcq', 'general', 'Which item of clothing is never allowed under the new policy?', to_jsonb(ARRAY['Flip-flops','Jeans','Smart casual clothing','Business formal attire']::text[]), 'Flip-flops', 'The text says ''Shorts and flip-flops are never allowed.'' Jeans are allowed if they have no rips or holes, and smart casual and business formal wear are both allowed in certain situations.', (SELECT id FROM passage5_2)),
  ('reading', 'B1', 'mcq', 'general', 'Who should staff ask if they are unsure whether an outfit is appropriate?', to_jsonb(ARRAY['Their line manager','HR','Clients','Other staff']::text[]), 'Their line manager', 'The text says to ''ask your line manager before wearing it to work.'' HR is only mentioned for receiving feedback on the policy, not outfit approval; clients and other staff are not mentioned in this role.', (SELECT id FROM passage5_2));

WITH passage5_3 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag) VALUES
    ('Update on the Four-Day Week Trial', 'Subject: Update on the Four-Day Week Trial

Dear Team,

As you know, we began trialling a four-day working week in the Marketing department three months ago. Provided that productivity levels remain stable over the coming quarter, we intend to extend the trial to the Sales and Customer Service teams from September. However, should output fall by more than five percent during this period, the trial will be paused and reviewed before any further rollout takes place. Employees taking part are still expected to complete their usual weekly hours, spread across four days instead of five, and any unfinished tasks should not simply be carried over without discussion with your manager. We would also ask that participants complete a short survey at the end of each month, as your feedback will directly shape whether this becomes a permanent policy. Thank you for your patience as we work through this trial.

Kind regards,
Operations Team', 'reading', 'B2', 'email')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('reading', 'B2', 'mcq', 'email', 'Which department began the trial three months ago?', to_jsonb(ARRAY['Marketing','Sales','Customer Service','All departments']::text[]), 'Marketing', 'The email states ''we began trialling a four-day working week in the Marketing department three months ago.'' Sales and Customer Service are only being considered for a future extension, and it is not company-wide.', (SELECT id FROM passage5_3)),
  ('reading', 'B2', 'mcq', 'email', 'Under what condition will the trial be paused?', to_jsonb(ARRAY['If output falls by more than five percent','If productivity remains stable','If employees complete the monthly survey','If the trial reaches September']::text[]), 'If output falls by more than five percent', 'The email says ''should output fall by more than five percent during this period, the trial will be paused.'' Stable productivity leads to extension, not pausing, and completing the survey or reaching September are not pause conditions.', (SELECT id FROM passage5_3)),
  ('reading', 'B2', 'mcq', 'email', 'What are employees taking part in the trial still expected to do?', to_jsonb(ARRAY['Complete their usual weekly hours over four days','Work extra hours beyond their normal total','Reduce their total weekly hours','Skip the monthly survey']::text[]), 'Complete their usual weekly hours over four days', 'The email states employees are ''still expected to complete their usual weekly hours, spread across four days instead of five.'' It does not ask for extra hours or a reduction, and participants are explicitly asked to complete the survey, not skip it.', (SELECT id FROM passage5_3));

WITH passage5_4 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag) VALUES
    ('Transition to a New Payroll Provider', 'Subject: Transition to a New Payroll Provider

Dear Colleagues,

I am writing to inform you that, following an extensive review of our payroll arrangements, the company has decided to transition from PaySure Ltd to Meridian Payroll Services with effect from the first of next month. Although this change has been under consideration for some time, the decision was ultimately prompted by a series of processing errors that PaySure failed to resolve despite repeated requests. Employees whose bank details or tax codes have changed within the last three months are asked to submit an updated payroll form to HR by the fifteenth, since Meridian will not have access to records held solely by the previous provider. While most staff should notice no disruption to their pay dates, those who are paid via international bank transfer may experience a delay of up to five working days during the first cycle, as the new system''s international payment channels are still being tested. We appreciate your patience during this transition and will circulate a further update once the migration has been completed.

Best regards,
Finance Director', 'reading', 'C1', 'email')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('reading', 'C1', 'mcq', 'email', 'Why did the company ultimately decide to change payroll providers?', to_jsonb(ARRAY['Because PaySure failed to resolve processing errors despite repeated requests','Because Meridian offered lower fees','Because staff had requested the change','Because international payments were being delayed']::text[]), 'Because PaySure failed to resolve processing errors despite repeated requests', 'The email says the decision ''was ultimately prompted by a series of processing errors that PaySure failed to resolve despite repeated requests.'' Fees and staff requests are not mentioned, and international payment delays are a consequence of the new system, not a reason for switching.', (SELECT id FROM passage5_4)),
  ('reading', 'C1', 'mcq', 'email', 'Which employees must submit an updated payroll form to HR?', to_jsonb(ARRAY['Those whose bank details or tax codes have changed in the last three months','All employees, without exception','Only employees paid by international transfer','Employees who have never updated their details']::text[]), 'Those whose bank details or tax codes have changed in the last three months', 'The email specifies this requirement applies to ''employees whose bank details or tax codes have changed within the last three months.'' It is not required of all staff, and international-transfer employees are a separate, unrelated group mentioned later.', (SELECT id FROM passage5_4)),
  ('reading', 'C1', 'mcq', 'email', 'Who might experience a delay to their pay during the first cycle?', to_jsonb(ARRAY['Staff who are paid via international bank transfer','All staff at the company','Staff who submitted updated payroll forms','Staff previously employed by PaySure']::text[]), 'Staff who are paid via international bank transfer', 'The email states ''those who are paid via international bank transfer may experience a delay of up to five working days.'' It explicitly says ''most staff should notice no disruption,'' ruling out all staff, and the other options are not linked to delays in the text.', (SELECT id FROM passage5_4));

WITH passage5_5 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag) VALUES
    ('Memo: Analysis of Rising Staff Turnover in the Logistics Division', 'Over the past two quarters, voluntary turnover in the Logistics division has risen from 8% to 19%, a trend that stands in sharp contrast to the relatively stable 6% turnover recorded across the rest of the company during the same period. Exit interviews initially pointed to pay as the primary driver, yet a closer analysis of the data suggests otherwise: departing employees in Logistics earned, on average, 4% above the market rate for comparable roles, whereas those who remained were paid slightly less. What the data does show is a strong correlation between departures and shift pattern changes introduced in March, when the division moved from fixed to rotating shifts in order to cover extended warehouse hours. Employees who left cited unpredictable schedules and difficulty arranging childcare far more often than they cited salary. Consequently, while the original assumption was that a pay review would resolve the issue, the evidence instead points toward shift flexibility as the more decisive factor. A pilot allowing staff to opt out of rotating shifts will therefore be introduced next quarter, and turnover will be monitored closely to determine whether this, rather than a pay increase, reverses the trend.', 'reading', 'C2', 'general')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('reading', 'C2', 'mcq', 'general', 'According to the memo, why is pay unlikely to be the main cause of the turnover?', to_jsonb(ARRAY['Employees who left were paid above the market rate, while those who stayed earned less','No employees mentioned pay in their exit interviews','Logistics pay was below the market rate for the role','Pay has not changed in the division since March']::text[]), 'Employees who left were paid above the market rate, while those who stayed earned less', 'The memo states departing staff ''earned, on average, 4% above the market rate... whereas those who remained were paid slightly less,'' which undercuts pay as the cause. Exit interviews did initially cite pay, Logistics pay was above (not below) market rate, and pay changes since March are not discussed.', (SELECT id FROM passage5_5)),
  ('reading', 'C2', 'mcq', 'general', 'What change was introduced in March?', to_jsonb(ARRAY['A move from fixed to rotating shifts','A company-wide pay review','A reduction in warehouse hours','A new exit interview process']::text[]), 'A move from fixed to rotating shifts', 'The memo states the division ''moved from fixed to rotating shifts'' in March ''to cover extended warehouse hours'' — meaning hours were extended, not reduced. No pay review or new exit interview process is mentioned as occurring in March.', (SELECT id FROM passage5_5)),
  ('reading', 'C2', 'mcq', 'general', 'What solution does the memo propose for next quarter?', to_jsonb(ARRAY['A pilot allowing staff to opt out of rotating shifts','An immediate pay increase for all Logistics staff','A full return to fixed shifts for the entire division','A company-wide survey on turnover causes']::text[]), 'A pilot allowing staff to opt out of rotating shifts', 'The memo says ''a pilot allowing staff to opt out of rotating shifts will therefore be introduced next quarter.'' A pay increase is explicitly framed as the rejected original assumption (''rather than a pay increase''), and the proposal is a limited opt-out pilot, not a full reversal or a survey.', (SELECT id FROM passage5_5));

-- Writing (24 prompt)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, explanation) VALUES
  ('writing', 'A1', 'prompt', 'general', 'Booking a Meeting Room

You need a meeting room for Thursday at 10am for five people. Write a short message to the office admin. Say the day, the time, and the number of people. (30–50 words)', 'A strong response gives the day, time, and number of people clearly using simple present/future forms.'),
  ('writing', 'A1', 'prompt', 'email', 'Thank You Note

A colleague helped you finish a report yesterday. Write a short note to thank them. Say what they did and why it helped you. (30–50 words)', 'A strong response names the colleague, says what they did, and expresses genuine thanks in simple language.'),
  ('writing', 'A1', 'prompt', 'general', 'Broken Printer

The printer on your floor is not working. Write a short message to IT support. Say where the printer is and what the problem is. (30–50 words)', 'A strong response states the location and the problem clearly using simple vocabulary.'),
  ('writing', 'A1', 'prompt', 'general', 'Asking for the Wifi Password

You are working from a different office today and you do not have the wifi password. Write a short message to a colleague asking for it. (30–50 words)', 'A strong response politely asks for the information and gives a brief reason using simple present forms.'),
  ('writing', 'A2', 'prompt', 'email', 'Rescheduling a Delivery

A delivery is planned for Monday morning but your office is closed that day. Write a short email to the supplier. Explain the problem and suggest a new day. (40–60 words)', 'A strong response explains the problem and proposes a new day clearly and politely.'),
  ('writing', 'A2', 'prompt', 'email', 'Team Lunch Reminder

Your team is having lunch together on Friday at 1pm at a restaurant near the office. Write a short reminder message to the team. Include the day, time, and place. (40–60 words)', 'A strong response includes the day, time, and place using clear, simple sentences.'),
  ('writing', 'A2', 'prompt', 'email', 'Requesting a Supply Order

Your department is running low on paper and pens. Write a short email to the office manager. List what you need and say when you need it by. (40–60 words)', 'A strong response lists the needed items and states a deadline clearly.'),
  ('writing', 'A2', 'prompt', 'email', 'Note to Security About a Visitor

A visitor is arriving tomorrow at 9am to see you. Write a short message to the security desk. Give the visitor''s name, arrival time, and who they are meeting. (40–60 words)', 'A strong response gives the visitor''s name, arrival time, and who they are meeting.'),
  ('writing', 'B1', 'prompt', 'email', 'Requesting Feedback on a Draft

You have finished a first draft of a report and need a colleague''s opinion before sending it to your manager. Write an email asking them to review it. Explain what the report is about, what kind of feedback you need, and by when you need it. (60–90 words)', 'A strong response explains the report''s topic, the kind of feedback needed, and a deadline in clear, organized sentences.'),
  ('writing', 'B1', 'prompt', 'general', 'Temporary Schedule Change

Due to building maintenance, your office will open one hour later than usual next week. Write an announcement to your colleagues. Explain the reason, the new opening time, and how long the change will last. (60–90 words)', 'A strong response explains the reason, the new time, and the duration of the change using clear linking language.'),
  ('writing', 'B1', 'prompt', 'email', 'Change of Contact Person

You are going on leave and a colleague will handle your emails while you are away. Write a message to your regular contacts. Explain when you will be away, who will replace you, and how to reach that person. (60–90 words)', 'A strong response states the dates of absence, names the replacement, and explains how to reach them.'),
  ('writing', 'B1', 'prompt', 'email', 'Following Up on an Unanswered Email

You sent an email a week ago asking a supplier for a price quote, but you have not received a reply. Write a polite follow-up email. Remind them of your original request and ask when you can expect an answer. (60–90 words)', 'A strong response politely reminds the reader of the original request and asks for a response, using appropriate hedging language.'),
  ('writing', 'B2', 'prompt', 'email', 'Introducing a New Team Member to Clients

A new colleague is joining your team and will now handle some of your regular client accounts. Write an email to your main clients introducing this person. Mention their role, their experience, and reassure clients about the quality of service continuing. (80–120 words)', 'A strong response introduces the new colleague, states their role and experience, and reassures the reader with a professional, warm tone.'),
  ('writing', 'B2', 'prompt', 'email', 'Requesting Additional Budget for a Project

Your project needs more funding than originally planned because of unexpected costs. Write an email to your manager requesting extra budget. Explain why the costs increased, how much more you need, and what will happen if the request is not approved. (80–120 words)', 'A strong response explains the reason for the extra cost, states the amount needed, and outlines the consequence of non-approval clearly and diplomatically.'),
  ('writing', 'B2', 'prompt', 'email', 'Addressing a Scheduling Conflict with a Supplier

A supplier has proposed a delivery date that clashes with a company holiday. Write an email explaining the conflict tactfully and proposing two alternative dates that would work for your team. (80–120 words)', 'A strong response tactfully explains the conflict and proposes concrete alternatives using polite, professional language.'),
  ('writing', 'B2', 'prompt', 'email', 'Responding to an Internal Survey with Suggestions

Your company recently ran a staff satisfaction survey, and you were asked to share ideas for improving remote working arrangements. Write an email to HR with two or three concrete suggestions, explaining briefly why each one would help. (80–120 words)', 'A strong response offers specific, actionable suggestions with brief justifications in a professional tone.'),
  ('writing', 'C1', 'prompt', 'email', 'Explaining a Data-Security Incident to Staff

A minor security incident affected some internal files last week, and it has now been resolved. Write an email to all staff explaining what happened, what steps were taken to fix it, and what precautions employees should take going forward, without causing unnecessary alarm. (100–150 words)', 'A strong response explains the incident and the fix calmly, balancing transparency with reassurance, using appropriately formal register.'),
  ('writing', 'C1', 'prompt', 'email', 'Turning Down a Partnership Offer Diplomatically

A smaller company has proposed a business partnership that does not align with your company''s current strategy. Write an email declining the offer. Thank them for their interest, explain your reasoning tactfully, and leave the door open for future opportunities. (100–150 words)', 'A strong response thanks the sender, tactfully explains the misalignment with company strategy, and leaves the relationship open for the future.'),
  ('writing', 'C1', 'prompt', 'email', 'Managing Client Expectations After a Missed Deadline

Your team missed an important deadline for a client due to an internal staffing issue. Write an email to the client acknowledging the delay, taking appropriate responsibility, explaining the cause without making excuses, and outlining a clear revised plan to rebuild their confidence. (100–150 words)', 'A strong response acknowledges the delay, takes appropriate responsibility without over-apologizing, and outlines a credible revised plan.'),
  ('writing', 'C1', 'prompt', 'email', 'Mediating a Disagreement Between Two Departments

The marketing and finance departments disagree about how to allocate budget for an upcoming campaign, and it is affecting progress. Write an email as a project lead proposing a fair compromise, acknowledging both sides'' concerns and suggesting a way forward that keeps the project on track. (100–150 words)', 'A strong response acknowledges both departments'' concerns and proposes a fair, well-reasoned compromise that keeps the project moving.'),
  ('writing', 'C2', 'prompt', 'email', 'Persuading Leadership to Reverse a Decision

Senior management has decided to cancel a project you believe is valuable to the company''s long-term strategy. Write a persuasive email to the leadership team making the case for reconsidering the decision. Use evidence, anticipate likely objections, and maintain a respectful, professional tone throughout. (120–180 words)', 'A strong response explains what happened, the remediation taken, and practical precautions, balancing transparency with reassurance.'),
  ('writing', 'C2', 'prompt', 'general', 'Responding to a Public Review Crisis

Your company has received a wave of negative public reviews after a service failure went viral on social media. Write an official public statement addressing the criticism, acknowledging shortcomings honestly, outlining corrective action, and rebuilding trust with customers, while protecting the company''s reputation. (120–180 words)', 'A strong response persuasively makes the case using evidence, anticipates objections, and closes on partnership rather than one-off assistance.'),
  ('writing', 'C2', 'prompt', 'general', 'Announcing Organizational Changes Sensitively

Due to restructuring, several roles in your department will be eliminated next month. Write an internal announcement to the affected team informing them of the changes with honesty and compassion, explaining the support available to them, and maintaining morale among remaining staff. (120–180 words)', 'A strong response acknowledges the shortcoming honestly, outlines concrete corrective action, and rebuilds trust without sounding defensive.'),
  ('writing', 'C2', 'prompt', 'negotiation', 'Negotiating Extended Payment Terms with a Struggling Client

A long-standing client is facing financial difficulty and has asked to extend their payment terms from 30 to 90 days. Write an email proposing a compromise arrangement that protects your company''s cash flow while showing empathy and preserving the long-term business relationship. (120–180 words)', 'A strong response proposes a compromise that protects cash flow while showing empathy for the client''s situation, using diplomatic, precise language.');

-- Speaking (18 prompt)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, explanation) VALUES
  ('speaking', 'A1', 'prompt', 'interview', 'What is your favourite part of your job? Tell me about it.', 'A strong response names a specific part of the job and gives a simple reason using basic present-tense language.'),
  ('speaking', 'A1', 'prompt', 'role_play', 'It''s your colleague''s birthday today. Say happy birthday to them and ask if they are doing anything to celebrate.', 'A strong response greets the colleague warmly and asks a simple, polite question about their plans.'),
  ('speaking', 'A1', 'prompt', 'discussion', 'Do you think it is important to arrive at work a few minutes early? Why or why not?', 'A strong response states a simple opinion and gives one basic reason.'),
  ('speaking', 'A2', 'prompt', 'interview', 'What tools or equipment do you use every day at work? Tell me about them.', 'A strong response names two or three specific tools and briefly describes how they are used.'),
  ('speaking', 'A2', 'prompt', 'role_play', 'You forgot your ID badge at home. Ask the reception desk for a temporary visitor pass.', 'A strong response politely explains the situation and makes a clear, simple request.'),
  ('speaking', 'A2', 'prompt', 'discussion', 'Do you think it''s important to take a lunch break away from your desk? Why or why not?', 'A strong response states a clear preference and gives a simple supporting reason.'),
  ('speaking', 'B1', 'prompt', 'interview', 'Describe how you organize your day when you have many small tasks to complete.', 'A strong response describes a method (e.g. prioritizing, listing) using clear, linked sentences.'),
  ('speaking', 'B1', 'prompt', 'role_play', 'A colleague keeps arriving 15 minutes late to your shared morning shift, and it is affecting the handover. Talk to them about it.', 'A strong response politely raises the issue and asks a direct but courteous question.'),
  ('speaking', 'B1', 'prompt', 'discussion', 'Do you think it''s better to specialize in one skill or to have a range of different skills at work? Explain your opinion.', 'A strong response states an opinion and supports it with a relevant reason or example.'),
  ('speaking', 'B2', 'prompt', 'interview', 'Talk about a time you had to learn something new quickly for your job. How did you approach it?', 'A strong response describes the situation and the approach taken using clear past-tense narrative.'),
  ('speaking', 'B2', 'prompt', 'role_play', 'A supplier has unexpectedly increased their prices. Call them to negotiate a better rate or find a compromise.', 'A strong response opens diplomatically, proposes a compromise, and maintains a professional, persuasive tone.'),
  ('speaking', 'B2', 'prompt', 'discussion', 'Do you think employees should be required to attend team-building activities outside of work hours? What''s your view?', 'A strong response gives a clear opinion supported by reasoning that considers a possible drawback.'),
  ('speaking', 'C1', 'prompt', 'interview', 'Describe a situation where you had to manage conflicting priorities from two different stakeholders. How did you handle it?', 'A strong response describes the competing priorities and explains the resolution with well-organized reasoning.'),
  ('speaking', 'C1', 'prompt', 'role_play', 'You discover that a colleague has taken credit for your idea in front of senior management. Address the situation with them.', 'A strong response addresses the issue directly but diplomatically, balancing assertiveness with professionalism.'),
  ('speaking', 'C1', 'prompt', 'discussion', 'Should employees be paid overtime for checking work emails outside office hours? Argue your position.', 'A strong response argues a position with well-developed reasoning and acknowledges the opposing view.'),
  ('speaking', 'C2', 'prompt', 'interview', 'Describe a time you had to make an unpopular decision at work that you believed was right. How did you justify it to others?', 'A strong response narrates the situation and reflects on the justification with nuanced, well-organized language.'),
  ('speaking', 'C2', 'prompt', 'role_play', 'You need to inform your team that a major client contract has been lost, and it may affect job security. Address the team.', 'A strong response delivers the news honestly and sensitively while addressing likely concerns.'),
  ('speaking', 'C2', 'prompt', 'discussion', 'Is it ethical for companies to use personality tests and psychometric assessments in hiring decisions? Defend your view.', 'A strong response constructs a nuanced argument with sophisticated reasoning and weighs counterarguments critically.');
