-- Seed content round 2: additional listening/reading/grammar_vocab/writing/speaking items.
-- Generated content, reviewed for CEFR calibration, answer correctness, and no
-- near-duplicate scenarios vs round 1 before merging.

-- Listening (30 mcq)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation) VALUES
  ('listening', 'A1', 'mcq', 'call', 'You hear: "Flight BA245 to London is now boarding at gate 12." Which gate is the flight boarding at?', to_jsonb(ARRAY['Gate 10','Gate 12','Gate 15','Gate 21']::text[]), 'Gate 12', 'The announcement states the flight is "boarding at gate 12."'),
  ('listening', 'A1', 'mcq', 'general', 'You hear: "The train to Manchester will depart from platform 4." Which platform does the train leave from?', to_jsonb(ARRAY['Platform 2','Platform 4','Platform 6','Platform 8']::text[]), 'Platform 4', 'The announcement says the train "will depart from platform 4."'),
  ('listening', 'A1', 'mcq', 'general', 'You hear: "You have reached the office. We are open from nine to five, Monday to Friday." What time does the office open?', to_jsonb(ARRAY['At eight o''clock','At nine o''clock','At ten o''clock','At five o''clock']::text[]), 'At nine o''clock', 'The message states the office is "open from nine to five," so nine is the opening time.'),
  ('listening', 'A1', 'mcq', 'meeting', 'You hear: "The meeting today is in Room 305." Which room is the meeting in?', to_jsonb(ARRAY['Room 300','Room 305','Room 350','Room 503']::text[]), 'Room 305', 'The speaker says the meeting "is in Room 305."'),
  ('listening', 'A1', 'mcq', 'customer_service', 'You hear: "Your package will arrive on Thursday." On which day will the package arrive?', to_jsonb(ARRAY['Tuesday','Wednesday','Thursday','Friday']::text[]), 'Thursday', 'The speaker directly states the package "will arrive on Thursday."'),
  ('listening', 'A2', 'mcq', 'general', 'You hear: "Please submit your expense reports by Friday this week. Reports sent after that will be processed next month." What happens to expense reports submitted after Friday?', to_jsonb(ARRAY['They will be rejected','They will be processed next month','They will be processed the same day','They will need manager approval']::text[]), 'They will be processed next month', 'The message states late reports "will be processed next month," with no mention of rejection or approval.'),
  ('listening', 'A2', 'mcq', 'call', 'You hear: "Your IT support ticket number is 4471. A technician will call you back within two hours." What is the ticket number?', to_jsonb(ARRAY['4417','4471','4171','7441']::text[]), '4471', 'The speaker clearly states the ticket number as "4471."'),
  ('listening', 'A2', 'mcq', 'general', 'You hear: "Your shift on Wednesday has been moved to Thursday this week." Which day was the shift moved to?', to_jsonb(ARRAY['Tuesday','Wednesday','Thursday','Friday']::text[]), 'Thursday', 'The message says the Wednesday shift "has been moved to Thursday."'),
  ('listening', 'A2', 'mcq', 'general', 'You hear: "Your software license will expire on the 30th of September. Please renew it before then." When does the software license expire?', to_jsonb(ARRAY['30th of August','30th of September','13th of September','3rd of September']::text[]), '30th of September', 'The message states the license "will expire on the 30th of September."'),
  ('listening', 'A2', 'mcq', 'call', 'You hear: "Your interview has been scheduled for Monday at eleven o''clock." What time is the interview?', to_jsonb(ARRAY['Ten o''clock','Eleven o''clock','Twelve o''clock','One o''clock']::text[]), 'Eleven o''clock', 'The speaker states the interview is scheduled "for Monday at eleven o''clock."'),
  ('listening', 'B1', 'mcq', 'meeting', 'You hear: "Your performance review was scheduled for Tuesday, but it has been postponed because the manager is attending a conference. It will now take place next Monday." Why was the performance review postponed?', to_jsonb(ARRAY['The manager is attending a conference','The employee is on leave','The meeting room is unavailable','The review documents are not ready']::text[]), 'The manager is attending a conference', 'The speaker explains the postponement was "because the manager is attending a conference."'),
  ('listening', 'B1', 'mcq', 'general', 'You hear: "In case of fire, please use the stairs to leave the building and gather at the car park. Note that the usual meeting point near reception is closed for renovation this month." Where should staff gather during a fire drill this month?', to_jsonb(ARRAY['Near reception','In the car park','By the stairs','In the main lobby']::text[]), 'In the car park', 'The speaker instructs staff to "gather at the car park," while the reception point is closed and the stairs are only the exit route.'),
  ('listening', 'B1', 'mcq', 'negotiation', 'You hear: "Our supplier''s lead time has increased from two weeks to four weeks because of a shortage of raw materials. We can still offer a two-week delivery for urgent orders at an extra cost." Why has the supplier''s lead time increased?', to_jsonb(ARRAY['A shortage of raw materials','A shipping strike','New safety regulations','A factory closure']::text[]), 'A shortage of raw materials', 'The speaker states the increase is "because of a shortage of raw materials."'),
  ('listening', 'B1', 'mcq', 'customer_service', 'You hear: "I checked your invoice, and you were charged for two items, but you only ordered one. We will refund the extra charge within five working days." Why will the customer receive a refund?', to_jsonb(ARRAY['They were charged for an extra item they did not order','They cancelled their order','The item arrived damaged','The price was reduced after purchase']::text[]), 'They were charged for an extra item they did not order', 'The representative explains the customer "was charged for two items, but only ordered one."'),
  ('listening', 'B1', 'mcq', 'general', 'You hear: "Your hotel booking is confirmed for three nights, and check-in is at two p.m. Please note check-in is not possible before this time." What time can guests check in?', to_jsonb(ARRAY['Twelve p.m.','One p.m.','Two p.m.','Three p.m.']::text[]), 'Two p.m.', 'The message states "check-in is at two p.m." and confirms it is not possible earlier.'),
  ('listening', 'B2', 'mcq', 'negotiation', 'You hear: "We can approve the budget increase, but only if the marketing team reduces spending in another area to balance it out. Otherwise, we''ll have to wait until next quarter." Under what condition will the budget increase be approved?', to_jsonb(ARRAY['If marketing cuts spending elsewhere to balance it','If the finance director resigns','If the increase is postponed to next quarter','If marketing submits a new proposal']::text[]), 'If marketing cuts spending elsewhere to balance it', 'The speaker sets the condition "only if the marketing team reduces spending in another area," with next quarter being the fallback, not the condition.'),
  ('listening', 'B2', 'mcq', 'meeting', 'You hear: "The client visit will now take place at our downtown office instead of the factory, since the client wants to see the sales team as well as production data. Transport will be arranged from the hotel." Why was the venue for the client visit changed?', to_jsonb(ARRAY['The client wants to meet the sales team too','The factory is closed for maintenance','The hotel cancelled the transport','The client requested a later date']::text[]), 'The client wants to meet the sales team too', 'The speaker gives the reason as the client wanting "to see the sales team as well as production data."'),
  ('listening', 'B2', 'mcq', 'customer_service', 'You hear: "Your warranty claim is valid because the fault appeared within the twelve-month period, but you''ll need to provide the original receipt before we can process the replacement." What does the customer still need to provide?', to_jsonb(ARRAY['The original receipt','A photo of the fault','Proof of the twelve-month period','A new delivery address']::text[]), 'The original receipt', 'The representative says the customer needs to "provide the original receipt before we can process the replacement."'),
  ('listening', 'B2', 'mcq', 'negotiation', 'You hear: "You can cancel your subscription, but since you''re on the annual plan, we require thirty days'' notice before the next billing date. If you cancel today, you''ll still be charged for one more month." What will happen if the customer cancels today?', to_jsonb(ARRAY['They will be charged for one more month','They will get an immediate refund','The cancellation will be rejected','They will move to a monthly plan automatically']::text[]), 'They will be charged for one more month', 'The speaker states that cancelling today means the customer will "still be charged for one more month."'),
  ('listening', 'B2', 'mcq', 'general', 'You hear: "Before I go on leave, I''ve left the client files with Sarah, but the invoice for the Peterson account is still pending approval from finance. Please chase that up while I''m away." What task is still outstanding regarding the Peterson account?', to_jsonb(ARRAY['Approval of the invoice from finance','Sending the client files to Sarah','Scheduling a meeting with the client','Updating the client''s contact details']::text[]), 'Approval of the invoice from finance', 'The speaker says the Peterson invoice "is still pending approval from finance."'),
  ('listening', 'C1', 'mcq', 'call', 'You hear: "Hi, it''s Mark from accounts. I''m just following up on that invoice — I know you''re probably snowed under, but if you could get back to me before end of day, that''d be great." What does Mark imply about the listener''s workload?', to_jsonb(ARRAY['That they are very busy','That they have finished all their work','That they are on holiday','That they have too little to do']::text[]), 'That they are very busy', 'The idiom "snowed under" means being extremely busy with work.'),
  ('listening', 'C1', 'mcq', 'negotiation', 'You hear: "I can''t promise anything, but if you renew for three years instead of one, I might be able to swing a better rate for you. Let me have a word with my manager and see what I can do." What is the salesperson suggesting?', to_jsonb(ARRAY['A longer contract could lead to a discount','The renewal has already been discounted','The manager has refused any discount','A one-year contract gets the best price']::text[]), 'A longer contract could lead to a discount', 'The speaker links a possible better rate to renewing "for three years instead of one."'),
  ('listening', 'C1', 'mcq', 'meeting', 'You hear: "Before the new starters arrive, would you mind just double-checking that all the laptops are set up? I don''t want them sitting around on day one with nothing to work with." What is the speaker asking the listener to do?', to_jsonb(ARRAY['Check that the laptops are ready','Order new laptops for the starters','Cancel the onboarding session','Postpone the new starters'' first day']::text[]), 'Check that the laptops are ready', 'The indirect request "would you mind just double-checking that all the laptops are set up" asks the listener to verify the laptops are ready.'),
  ('listening', 'C1', 'mcq', 'customer_service', 'You hear: "I hear what you''re saying, but unfortunately this particular model falls outside our standard warranty terms. Having said that, I can offer you a discounted repair as a goodwill gesture." What does the customer service representative offer instead of a warranty repair?', to_jsonb(ARRAY['A discounted repair','A full refund','A free replacement','An extended warranty']::text[]), 'A discounted repair', 'The representative explicitly offers "a discounted repair as a goodwill gesture."'),
  ('listening', 'C1', 'mcq', 'call', 'You hear: "Something''s come up on my end, so I''m afraid I''ll have to push our interview back a couple of days — would Thursday work for you instead of Tuesday?" What does the speaker want to do?', to_jsonb(ARRAY['Move the interview to a later date','Cancel the interview permanently','Bring the interview forward','Conduct the interview by phone instead']::text[]), 'Move the interview to a later date', 'The phrase "push our interview back a couple of days" and the switch from Tuesday to Thursday mean postponing to a later date.'),
  ('listening', 'C2', 'mcq', 'negotiation', 'You hear: "Look, I''m not going to pretend the numbers are perfect, but let''s not throw the baby out with the bathwater — the project''s worth funding, even if we trim a few corners here and there." What is the speaker''s overall attitude toward the project?', to_jsonb(ARRAY['They think it should still be funded despite imperfections','They think the project should be cancelled','They think the budget should be doubled','They think the numbers are completely accurate']::text[]), 'They think it should still be funded despite imperfections', 'The idiom "don''t throw the baby out with the bathwater" plus "the project''s worth funding" show support despite flaws, contradicting the claim that the numbers are perfect.'),
  ('listening', 'C2', 'mcq', 'call', 'You hear: "Sure, I can process that cancellation for you — though I''d be doing you a disservice if I didn''t mention you''ll lose the loyalty discount you''ve had for three years." What is the representative subtly trying to do?', to_jsonb(ARRAY['Discourage the customer from cancelling','Encourage the customer to cancel immediately','Confirm the cancellation with no further comment','Offer the customer a full refund']::text[]), 'Discourage the customer from cancelling', 'Mentioning the loss of the three-year loyalty discount while agreeing to cancel is a subtle attempt to dissuade the customer.'),
  ('listening', 'C2', 'mcq', 'meeting', 'You hear: "I''ve chased legal for the Kowalski contract renewal twice already, so it''s not for lack of trying on my part — if it''s still sitting on their desk when I''m back, that''s on them, not on whoever picks this up." What is the speaker implying?', to_jsonb(ARRAY['Any further delay would not be the handover person''s fault','The handover person made a mistake with the contract','Legal has already approved the contract','The speaker forgot to contact legal']::text[]), 'Any further delay would not be the handover person''s fault', 'The speaker states that if the contract is still sitting with legal, "that''s on them, not on whoever picks this up," meaning legal, not the handover person, would be responsible.'),
  ('listening', 'C2', 'mcq', 'customer_service', 'You hear: "I take your point, and on paper you''re right, but between you and me, getting this overturned isn''t going to be straightforward given how the system''s set up — I''ll do what I can, though." What does the representative suggest about resolving the dispute?', to_jsonb(ARRAY['It will be difficult, though they will try','It will be resolved immediately','It cannot be resolved under any circumstances','The customer is mistaken about the charge']::text[]), 'It will be difficult, though they will try', 'The representative admits the customer is "right" but says the overturn "isn''t going to be straightforward," while promising to "do what I can."'),
  ('listening', 'C2', 'mcq', 'general', 'You hear: "Just a heads-up, the keynote''s running a bit behind schedule, so if you were banking on catching the ten o''clock networking session beforehand, you might want to think again." What is being implied about the ten o''clock networking session?', to_jsonb(ARRAY['Attendees may not have time to attend it as planned','The session has been cancelled entirely','The session has been moved to the afternoon','The keynote will now start earlier than planned']::text[]), 'Attendees may not have time to attend it as planned', 'The warning that the keynote is "running a bit behind schedule" implies attendees relying on catching the session beforehand should reconsider, not that it is cancelled, moved, or that the keynote starts earlier.');

-- Grammar & Vocabulary (72 mcq)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation) VALUES
  ('grammar_vocab', 'A1', 'mcq', 'tenses', 'The office _____ at 9 a.m. every day.', to_jsonb(ARRAY['opens','is opening','opened','will open']::text[]), 'opens', 'Present simple is used for routines and facts, especially with time expressions like ''every day''.'),
  ('grammar_vocab', 'A1', 'mcq', 'tenses', 'Look! The manager _____ to the new client right now.', to_jsonb(ARRAY['is talking','talks','talked','will talk']::text[]), 'is talking', 'Present continuous with ''right now'' describes an action happening at the moment of speaking.'),
  ('grammar_vocab', 'A2', 'mcq', 'tenses', 'David _____ work in the London office, but now he works from home.', to_jsonb(ARRAY['used to','uses to','is used to','use to']::text[]), 'used to', '''Used to + infinitive'' describes a past habit that is no longer true, shown by the contrast with ''but now''.'),
  ('grammar_vocab', 'A2', 'mcq', 'tenses', 'We _____ the new clients tomorrow at 3 p.m.', to_jsonb(ARRAY['are meeting','meets','met','will have met']::text[]), 'are meeting', 'Present continuous with a specific future time expresses a fixed personal arrangement.'),
  ('grammar_vocab', 'B1', 'mcq', 'tenses', 'She''s exhausted because she _____ on the report non-stop since 6 a.m.', to_jsonb(ARRAY['has been working','works','worked','is working']::text[]), 'has been working', 'Present perfect continuous is used with ''since'' to describe a continuous activity with a present result (her current exhaustion).'),
  ('grammar_vocab', 'B1', 'mcq', 'tenses', 'If the temperature exceeds 90°C, the machine automatically _____ down.', to_jsonb(ARRAY['shuts','will shut','shut','is shutting']::text[]), 'shuts', 'Zero conditional uses present simple in both clauses to describe a general, automatic fact.'),
  ('grammar_vocab', 'B2', 'mcq', 'tenses', 'She _____ a presentation when the fire alarm suddenly rang.', to_jsonb(ARRAY['was giving','gave','has given','gives']::text[]), 'was giving', 'Past continuous describes an action in progress that was interrupted by a shorter past simple action.'),
  ('grammar_vocab', 'B2', 'mcq', 'tenses', 'If I _____ the manager, I would change the shift schedule.', to_jsonb(ARRAY['were','am','have been','will be']::text[]), 'were', 'Second conditional uses the subjunctive ''were'' for all persons in the if-clause, paired with ''would + infinitive''.'),
  ('grammar_vocab', 'C1', 'mcq', 'tenses', 'The team _____ for over three hours before the CEO finally arrived.', to_jsonb(ARRAY['had been negotiating','negotiated','has negotiated','were negotiating']::text[]), 'had been negotiating', 'Past perfect continuous emphasizes the duration of an action in progress up until another past event.'),
  ('grammar_vocab', 'C1', 'mcq', 'tenses', 'The client said, ''I can approve the budget tomorrow.'' She said she _____ approve the budget the following day.', to_jsonb(ARRAY['could','can','would can','may can']::text[]), 'could', 'In reported speech, the modal ''can'' shifts to ''could'' when the reporting verb is in the past tense.'),
  ('grammar_vocab', 'C2', 'mcq', 'tenses', 'He _____ present the forecast himself, but he fell ill at the last minute.', to_jsonb(ARRAY['was going to','is going to','will','has been going to']::text[]), 'was going to', '''Was going to'' expresses a past plan or intention that was not carried out, unlike other future forms.'),
  ('grammar_vocab', 'C2', 'mcq', 'tenses', 'I wish I _____ the contract more carefully before signing it.', to_jsonb(ARRAY['had read','read','have read','would read']::text[]), 'had read', '''Wish + past perfect'' expresses regret about something in the past that cannot be changed.'),
  ('grammar_vocab', 'A1', 'mcq', 'prepositions', 'The meeting is _____ July.', to_jsonb(ARRAY['in','on','at','since']::text[]), 'in', '''In'' is the correct preposition to use with months.'),
  ('grammar_vocab', 'A1', 'mcq', 'prepositions', 'Please wait for me _____ the reception desk.', to_jsonb(ARRAY['at','in','on','since']::text[]), 'at', '''At'' is used for a specific point or location, such as a desk.'),
  ('grammar_vocab', 'A2', 'mcq', 'prepositions', 'The documents are _____ the meeting room.', to_jsonb(ARRAY['in','on','at','since']::text[]), 'in', '''In'' is used for enclosed spaces such as rooms.'),
  ('grammar_vocab', 'A2', 'mcq', 'prepositions', 'The new office is located _____ Main Street.', to_jsonb(ARRAY['on','in','at','since']::text[]), 'on', '''On'' is used with the names of streets.'),
  ('grammar_vocab', 'B1', 'mcq', 'prepositions', 'She has always been interested _____ marketing.', to_jsonb(ARRAY['in','on','at','for']::text[]), 'in', '''Interested in'' is the fixed preposition pairing with this adjective.'),
  ('grammar_vocab', 'B1', 'mcq', 'prepositions', 'He is extremely good _____ negotiating contracts.', to_jsonb(ARRAY['at','in','on','for']::text[]), 'at', '''Good at'' is the standard preposition collocation used with skills and abilities.'),
  ('grammar_vocab', 'B2', 'mcq', 'prepositions', 'As the project lead, she is responsible _____ the entire budget.', to_jsonb(ARRAY['for','of','with','to']::text[]), 'for', '''Responsible for'' is the fixed preposition pairing meaning to have duty over something.'),
  ('grammar_vocab', 'B2', 'mcq', 'prepositions', 'Our production schedule depends _____ the supplier''s delivery times.', to_jsonb(ARRAY['on','of','at','in']::text[]), 'on', '''Depend on'' is the fixed verb-preposition combination.'),
  ('grammar_vocab', 'C1', 'mcq', 'prepositions', 'All contractors must comply _____ the new safety regulations.', to_jsonb(ARRAY['with','to','of','for']::text[]), 'with', '''Comply with'' is the fixed formal preposition pairing meaning to act according to rules.'),
  ('grammar_vocab', 'C1', 'mcq', 'prepositions', 'The payment was processed _____ the terms agreed in the contract.', to_jsonb(ARRAY['in accordance with','according for','in accord to','by accordance of']::text[]), 'in accordance with', '''In accordance with'' is the standard formal phrase meaning ''in a way that follows'' agreed rules or terms.'),
  ('grammar_vocab', 'C2', 'mcq', 'prepositions', '_____ your recent enquiry, please find the updated pricing attached.', to_jsonb(ARRAY['With regard to','With regards of','Regarding to','In regard for']::text[]), 'With regard to', '''With regard to'' (singular ''regard'') is the correct formal fixed phrase for introducing a topic in business correspondence.'),
  ('grammar_vocab', 'C2', 'mcq', 'prepositions', 'The final report must be submitted _____ the board meeting on Friday.', to_jsonb(ARRAY['prior to','prior of','previous to','prior than']::text[]), 'prior to', '''Prior to'' is the correct formal preposition phrase meaning ''before''; the other forms are not standard English.'),
  ('grammar_vocab', 'A1', 'mcq', 'business_vocab', 'A person you work with in the same company is called a _____.', to_jsonb(ARRAY['colleague','customer','competitor','supplier']::text[]), 'colleague', '''Colleague'' specifically means a person you work with, unlike a customer, competitor, or supplier.'),
  ('grammar_vocab', 'A1', 'mcq', 'business_vocab', 'We need to book the _____ for tomorrow''s team discussion.', to_jsonb(ARRAY['meeting room','printer','invoice','deadline']::text[]), 'meeting room', 'A ''meeting room'' is the space booked to hold discussions.'),
  ('grammar_vocab', 'A2', 'mcq', 'business_vocab', 'The finance team sets the yearly _____ to control how much each department can spend.', to_jsonb(ARRAY['budget','agenda','colleague','invoice']::text[]), 'budget', 'A ''budget'' is a planned amount of money allocated for spending.'),
  ('grammar_vocab', 'A2', 'mcq', 'business_vocab', 'A _____ is a person or company that buys goods or services from a business.', to_jsonb(ARRAY['client','stakeholder','procurement','forecast']::text[]), 'client', '''Client'' refers to someone who purchases a company''s products or services.'),
  ('grammar_vocab', 'B1', 'mcq', 'business_vocab', 'Before the meeting starts, please check the _____ to see which topics will be discussed.', to_jsonb(ARRAY['agenda','turnover','contract','liquidity']::text[]), 'agenda', 'An ''agenda'' is the list of topics planned for a meeting.'),
  ('grammar_vocab', 'B1', 'mcq', 'business_vocab', 'Both companies signed a _____ that outlines the terms of the partnership.', to_jsonb(ARRAY['contract','forecast','overhead','merger']::text[]), 'contract', 'A ''contract'' is a legally binding written agreement between parties.'),
  ('grammar_vocab', 'B2', 'mcq', 'business_vocab', 'The company''s annual _____ rose by 15%, showing strong total sales.', to_jsonb(ARRAY['turnover','liquidity','procurement','stakeholder']::text[]), 'turnover', '''Turnover'' refers to the total amount of sales a company makes in a given period.'),
  ('grammar_vocab', 'B2', 'mcq', 'business_vocab', 'Employees, shareholders, and suppliers are all considered _____ in the company''s decisions.', to_jsonb(ARRAY['stakeholders','overheads','forecasts','mergers']::text[]), 'stakeholders', '''Stakeholders'' are people or groups with an interest in a company''s performance and decisions.'),
  ('grammar_vocab', 'C1', 'mcq', 'business_vocab', 'The _____ department is responsible for sourcing and purchasing raw materials.', to_jsonb(ARRAY['procurement','liquidity','turnover','due diligence']::text[]), 'procurement', '''Procurement'' refers to the process of obtaining goods or services for a business.'),
  ('grammar_vocab', 'C1', 'mcq', 'business_vocab', 'Based on current sales trends, the analyst prepared a _____ for next quarter''s revenue.', to_jsonb(ARRAY['forecast','overhead','merger','stakeholder']::text[]), 'forecast', 'A ''forecast'' is a prediction of future business performance based on data.'),
  ('grammar_vocab', 'C2', 'mcq', 'business_vocab', 'The company faced a cash-flow crisis because it lacked sufficient _____ to pay short-term debts.', to_jsonb(ARRAY['liquidity','turnover','procurement','forecast']::text[]), 'liquidity', '''Liquidity'' refers to how easily a company''s assets can be converted to cash to meet short-term obligations.'),
  ('grammar_vocab', 'C2', 'mcq', 'business_vocab', 'Before the acquisition, the investors conducted thorough _____ to assess the target company''s finances.', to_jsonb(ARRAY['due diligence','procurement','overheads','turnover']::text[]), 'due diligence', '''Due diligence'' is the careful investigation of a business before entering into an agreement, such as an acquisition.'),
  ('grammar_vocab', 'A1', 'mcq', 'phrasal_verbs', 'Can you help me _____ the new printer in the office?', to_jsonb(ARRAY['set up','hand in','catch up','wrap up']::text[]), 'set up', '''Set up'' means to install or prepare equipment for use.'),
  ('grammar_vocab', 'A1', 'mcq', 'phrasal_verbs', 'Please _____ your holiday request form by Friday.', to_jsonb(ARRAY['hand in','set up','sort out','catch up']::text[]), 'hand in', '''Hand in'' means to submit a document to someone.'),
  ('grammar_vocab', 'A2', 'mcq', 'phrasal_verbs', 'Let''s grab coffee sometime and _____ on each other''s news.', to_jsonb(ARRAY['catch up','hand in','roll out','take on']::text[]), 'catch up', '''Catch up'' means to share and hear the latest news after not talking for a while.'),
  ('grammar_vocab', 'A2', 'mcq', 'phrasal_verbs', 'IT will _____ the login problem this afternoon.', to_jsonb(ARRAY['sort out','hand in','wrap up','run out of']::text[]), 'sort out', '''Sort out'' means to resolve or fix a problem.'),
  ('grammar_vocab', 'B1', 'mcq', 'phrasal_verbs', 'She agreed to _____ extra responsibilities while her colleague is on leave.', to_jsonb(ARRAY['take on','run out of','bring forward','get around to']::text[]), 'take on', '''Take on'' means to accept new duties or work.'),
  ('grammar_vocab', 'B1', 'mcq', 'phrasal_verbs', 'We _____ printer paper, so someone needs to order more.', to_jsonb(ARRAY['ran out of','took on','wrapped up','brought forward']::text[]), 'ran out of', '''Run out of'' means to have no more of something left.'),
  ('grammar_vocab', 'B2', 'mcq', 'phrasal_verbs', 'Could we _____ the meeting to 10 a.m. instead of 2 p.m.?', to_jsonb(ARRAY['bring forward','wrap up','sort out','roll out']::text[]), 'bring forward', '''Bring forward'' means to move an event to an earlier time.'),
  ('grammar_vocab', 'B2', 'mcq', 'phrasal_verbs', 'Let''s _____ this discussion so everyone can get back to work.', to_jsonb(ARRAY['wrap up','take on','run out of','hand in']::text[]), 'wrap up', '''Wrap up'' means to finish or conclude something.'),
  ('grammar_vocab', 'C1', 'mcq', 'phrasal_verbs', 'The company plans to _____ the new software across all branches next month.', to_jsonb(ARRAY['roll out','get around to','iron out','phase out']::text[]), 'roll out', '''Roll out'' means to introduce a new product or system gradually across an organization.'),
  ('grammar_vocab', 'C1', 'mcq', 'phrasal_verbs', 'I''ve been meaning to reply to that email, but I haven''t _____ it yet.', to_jsonb(ARRAY['gotten around to','ironed out','phased out','rolled out']::text[]), 'gotten around to', '''Get around to'' means to finally find time to do something after a delay.'),
  ('grammar_vocab', 'C2', 'mcq', 'phrasal_verbs', 'The two teams met to _____ the remaining differences in the proposal.', to_jsonb(ARRAY['iron out','phase out','get around to','hand in']::text[]), 'iron out', '''Iron out'' means to resolve minor problems or difficulties through discussion.'),
  ('grammar_vocab', 'C2', 'mcq', 'phrasal_verbs', 'The firm will gradually _____ the outdated system over the next two years.', to_jsonb(ARRAY['phase out','iron out','roll out','catch up']::text[]), 'phase out', '''Phase out'' means to gradually stop using or discontinue something over time.'),
  ('grammar_vocab', 'A1', 'mcq', 'formal_register', 'In a formal email to a client you have never met, which greeting is correct?', to_jsonb(ARRAY['Dear Mr. Johnson','Hey Johnson','Hiya','Yo Mr. Johnson']::text[]), 'Dear Mr. Johnson', '''Dear [Title] [Surname]'' is the standard formal greeting for someone you don''t know well.'),
  ('grammar_vocab', 'A1', 'mcq', 'formal_register', 'Which closing is appropriate at the end of a formal business email?', to_jsonb(ARRAY['Best regards','Bye for now','See ya','Later']::text[]), 'Best regards', '''Best regards'' is a standard polite closing for professional emails, unlike casual phrases like ''See ya'' or ''Later''.'),
  ('grammar_vocab', 'A2', 'mcq', 'formal_register', 'Writing to thank your manager in a formal email, which phrase is more appropriate?', to_jsonb(ARRAY['Thank you very much for your help','Thanks a ton','Cheers mate','Thanks heaps']::text[]), 'Thank you very much for your help', 'Full, formal phrasing is expected in professional emails, while ''Thanks a ton/heaps'' and ''Cheers mate'' are casual spoken expressions.'),
  ('grammar_vocab', 'A2', 'mcq', 'formal_register', 'In a formal written report, which sentence uses appropriate register?', to_jsonb(ARRAY['We are going to review the figures next week','We''re gonna review the figures next week','We gon review the figures','Gonna review them next week']::text[]), 'We are going to review the figures next week', 'Formal writing avoids the spoken contraction ''gonna'' and uses the full form ''going to''.'),
  ('grammar_vocab', 'B1', 'mcq', 'formal_register', 'Emailing a supplier about unclear instructions, which is the more formal way to ask for clarification?', to_jsonb(ARRAY['Could you please clarify what you mean by this?','What do you mean?','Huh, not sure what you''re saying','Say that again?']::text[]), 'Could you please clarify what you mean by this?', 'Polite modal phrasing such as ''Could you please...'' is appropriate for formal clarification requests, unlike blunt or casual alternatives.'),
  ('grammar_vocab', 'B1', 'mcq', 'formal_register', 'In a formal email requesting to reschedule a client meeting, which sentence is appropriate?', to_jsonb(ARRAY['I would like to request that we reschedule our meeting to a later date','Can we move the meeting, sorry','Let''s just push it back','We gotta change the meeting time']::text[]), 'I would like to request that we reschedule our meeting to a later date', 'Formal requests use structures like ''I would like to request that...'' rather than casual short forms.'),
  ('grammar_vocab', 'B2', 'mcq', 'formal_register', 'Disagreeing with a client''s proposal in a formal email, which is the most diplomatic and professional phrasing?', to_jsonb(ARRAY['We have some concerns about this approach and would like to suggest an alternative','You''re wrong about this','That won''t work at all','No, that''s a bad idea']::text[]), 'We have some concerns about this approach and would like to suggest an alternative', 'Professional disagreement is expressed indirectly and constructively, not with blunt rejection.'),
  ('grammar_vocab', 'B2', 'mcq', 'formal_register', 'Formally informing your employer that you are leaving your job, which sentence is appropriate for a resignation letter?', to_jsonb(ARRAY['I am writing to formally resign from my position, effective two weeks from today','I''m quitting, see ya','I''m out of here','I don''t want this job anymore']::text[]), 'I am writing to formally resign from my position, effective two weeks from today', 'A resignation letter requires formal, precise language stating intent and effective date.'),
  ('grammar_vocab', 'C1', 'mcq', 'formal_register', 'Apologizing to a client for a billing error in a formal email, which phrasing is appropriate?', to_jsonb(ARRAY['We sincerely apologize for the error and are correcting it immediately','Oops, my bad, sorry about that','Whoops, we messed up the bill','Sorry, our fault lol']::text[]), 'We sincerely apologize for the error and are correcting it immediately', 'Formal apologies use complete, respectful phrasing rather than casual exclamations like ''oops'' or ''lol''.'),
  ('grammar_vocab', 'C1', 'mcq', 'formal_register', 'Raising a formal complaint about a supplier''s service in a written letter, which is the appropriate phrasing?', to_jsonb(ARRAY['I would like to formally raise a concern regarding the recent delays in delivery','This is so annoying, why can''t you just deliver on time','Your service is terrible, ugh','Seriously, sort this out already']::text[]), 'I would like to formally raise a concern regarding the recent delays in delivery', 'Formal complaints are phrased with measured, professional language rather than emotional or blunt statements.'),
  ('grammar_vocab', 'C2', 'mcq', 'formal_register', 'In a formal letter rejecting a job applicant, which phrase best matches the expected professional register?', to_jsonb(ARRAY['We regret to inform you that you have not been selected for this position','Sorry to say you didn''t get the job','We''re gonna have to pass on you','Bad news, you''re not in']::text[]), 'We regret to inform you that you have not been selected for this position', 'Formal rejection letters use the conventional phrase ''we regret to inform you'', which is more measured and professional than casual alternatives, even ones that are grammatically correct.'),
  ('grammar_vocab', 'C2', 'mcq', 'formal_register', 'Writing a formal cover letter to a company where the recipient''s name is unknown, which opening is correct?', to_jsonb(ARRAY['To Whom It May Concern','Hey there','Yo team','What''s up']::text[]), 'To Whom It May Concern', '''To Whom It May Concern'' is the conventional formal greeting used when the specific recipient''s name is not known.'),
  ('grammar_vocab', 'A1', 'mcq', 'collocations', 'The manager will _____ a meeting every Monday morning.', to_jsonb(ARRAY['hold','make','do','take']::text[]), 'hold', '''Hold a meeting'' is the correct fixed collocation, not ''make/do/take a meeting''.'),
  ('grammar_vocab', 'A1', 'mcq', 'collocations', 'The customer decided to _____ an order for 200 units.', to_jsonb(ARRAY['place','make','do','take']::text[]), 'place', '''Place an order'' is the standard collocation for requesting goods.'),
  ('grammar_vocab', 'A2', 'mcq', 'collocations', 'The project manager will _____ a deadline for the final report.', to_jsonb(ARRAY['set','make','do','hold']::text[]), 'set', '''Set a deadline'' is the correct collocation meaning to establish a time limit.'),
  ('grammar_vocab', 'A2', 'mcq', 'collocations', 'After the presentation, the audience was asked to _____ feedback.', to_jsonb(ARRAY['give','make','do','take']::text[]), 'give', '''Give feedback'' is the fixed collocation for offering comments or opinions.'),
  ('grammar_vocab', 'B1', 'mcq', 'collocations', 'The sales team worked hard to _____ this quarter''s target.', to_jsonb(ARRAY['meet','make','do','hold']::text[]), 'meet', '''Meet a target'' is the standard collocation meaning to achieve a set goal.'),
  ('grammar_vocab', 'B1', 'mcq', 'collocations', 'When something goes wrong, a good leader will _____ responsibility rather than blame others.', to_jsonb(ARRAY['take','make','do','hold']::text[]), 'take', '''Take responsibility'' is the fixed collocation for accepting accountability.'),
  ('grammar_vocab', 'B2', 'mcq', 'collocations', 'An employee should feel comfortable enough to _____ a concern with their manager.', to_jsonb(ARRAY['raise','make','do','take']::text[]), 'raise', '''Raise a concern'' is the fixed collocation meaning to mention a worry or issue.'),
  ('grammar_vocab', 'B2', 'mcq', 'collocations', 'After analyzing the data, the team was able to _____ a clear conclusion.', to_jsonb(ARRAY['draw','make','do','take']::text[]), 'draw', '''Draw a conclusion'' is the standard collocation meaning to form a judgment based on evidence.'),
  ('grammar_vocab', 'C1', 'mcq', 'collocations', 'The new policy tries to _____ a balance between employee wellbeing and productivity.', to_jsonb(ARRAY['strike','make','hold','take']::text[]), 'strike', '''Strike a balance'' is the fixed collocation meaning to find a satisfactory middle point between two things.'),
  ('grammar_vocab', 'C1', 'mcq', 'collocations', 'She decided to _____ the opportunity to lead the new international project.', to_jsonb(ARRAY['seize','make','hold','catch']::text[]), 'seize', '''Seize an opportunity'' is the fixed collocation meaning to take quick advantage of a chance.'),
  ('grammar_vocab', 'C2', 'mcq', 'collocations', 'The audit ensures that every department continues to _____ the company''s quality standards.', to_jsonb(ARRAY['uphold','make','take','hold']::text[]), 'uphold', '''Uphold a standard'' is the fixed collocation meaning to maintain or support an established level of quality.'),
  ('grammar_vocab', 'C2', 'mcq', 'collocations', 'The new manager was brought in to _____ the outdated approval process.', to_jsonb(ARRAY['streamline','make','hold','take']::text[]), 'streamline', '''Streamline a process'' is the fixed collocation meaning to make a procedure simpler and more efficient.');

-- Writing (12 prompt)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, explanation) VALUES
  ('writing', 'A1', 'prompt', 'email', 'Asking for a Day Off

You want next Friday off for a family event. Write a short email to your manager, Mr. Diallo. Say which day you need off and why. (30–50 words)', 'A strong response uses simple present/future forms and clearly states the date and reason.'),
  ('writing', 'A1', 'prompt', 'general', 'Welcome Note for a New Colleague

A new team member, Ana, starts on Monday. Write a short welcome note. Say hello, tell her your name, and say you are happy she is joining the team. (30–50 words)', 'A strong response greets warmly, introduces the writer, and uses simple friendly vocabulary correctly.'),
  ('writing', 'A2', 'prompt', 'email', 'Office Move Announcement

Your office is moving to a new building on 5th Street starting next month. Write a short email to staff. Give the new address, the start date, and tell them where to park. (50–80 words)', 'A strong response gives clear factual details (address, date, instructions) in simple, well-organized sentences.'),
  ('writing', 'A2', 'prompt', 'general', 'Instructions for Covering the Front Desk

Your colleague Tom is covering the front desk while you are at lunch. Write simple instructions for him: how to greet visitors, where the sign-in sheet is, and what to do if the phone rings. (50–80 words)', 'A strong response gives clear, ordered instructions using simple imperative forms.'),
  ('writing', 'B1', 'prompt', 'email', 'Replying to a Job Application Question

A candidate named Priya emailed asking whether the Marketing Assistant position is still open and when interviews will start. Write a reply confirming the role is open, giving an approximate interview date, and telling her what documents to send. (80–120 words)', 'A strong response answers all three questions clearly and uses polite, professional email phrases.'),
  ('writing', 'B1', 'prompt', 'general', 'Summarizing Meeting Notes

You attended a team meeting where it was decided to launch the new website in September, assign Marco to lead design, and hold weekly check-ins on Mondays. Write a short summary of these notes to share with a colleague who missed the meeting. (80–120 words)', 'A strong response organizes the key decisions logically and reports them accurately in past/reported forms.'),
  ('writing', 'B2', 'prompt', 'email', 'Project Status Update

Write an email to your project sponsor updating them on the CRM migration project. Explain that data migration is 70% complete, testing has revealed two minor bugs being fixed this week, and the go-live date remains on track for August 15th. (120–160 words)', 'A strong response structures the update logically (progress, issues, timeline) with appropriate business vocabulary and reasoning.'),
  ('writing', 'B2', 'prompt', 'customer_service', 'Handling a Subscription Cancellation Request

A customer, Mr. Hendricks, emails asking to cancel his premium subscription because he feels it is too expensive. Reply confirming you can process the cancellation, explain what happens to his data and access, and mention a lower-cost plan he might consider instead. (120–160 words)', 'A strong response balances customer service tone with clear procedural explanation and a tactful alternative offer.'),
  ('writing', 'C1', 'prompt', 'email', 'Explaining a Policy Change

Your company is changing its remote-work policy so employees must now be in the office three days a week instead of two, starting next quarter. Write an email to your team explaining the reasoning behind the change, acknowledging it may be unwelcome, and outlining how flexibility will still be offered. (150–200 words)', 'A strong response explains reasoning persuasively, shows empathy for a negative reaction, and maintains a measured professional tone.'),
  ('writing', 'C1', 'prompt', 'general', 'Declining a Meeting Invitation Politely

A senior colleague, Ms. Okafor, has invited you to a strategy meeting that clashes with an existing client commitment you cannot move. Write a message declining the invitation, explaining the conflict without sounding dismissive, and proposing a way to stay informed or contribute asynchronously. (150–200 words)', 'A strong response declines gracefully while preserving the relationship, using hedging language and a constructive alternative.'),
  ('writing', 'C2', 'prompt', 'negotiation', 'Negotiating a Vendor Price Increase

Your long-standing office supplies vendor has notified you of a 15% price increase, citing rising raw material costs. Write an email negotiating this increase: acknowledge their cost pressures, present your case for a smaller increase or phased implementation based on your multi-year relationship, and propose next steps for discussion. (180–250 words)', 'A strong response demonstrates sophisticated negotiation tactics, balancing firmness and diplomacy while building a reasoned counter-argument.'),
  ('writing', 'C2', 'prompt', 'general', 'Following Up After a Networking Event

You met Dr. Elena Vasquez, a potential industry partner, at a conference last week and had a promising conversation about a possible collaboration. Write a follow-up message that reestablishes rapport, subtly reminds her of the specifics you discussed, and proposes a concrete next step without appearing overly eager. (180–250 words)', 'A strong response demonstrates nuanced relationship-building, calibrated tone, and persuasive yet understated professional writing.');

-- Speaking (18 prompt)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, explanation) VALUES
  ('speaking', 'A1', 'prompt', 'interview', 'What time do you start work every day?', 'A strong response states a simple time using basic present-tense language.'),
  ('speaking', 'A2', 'prompt', 'interview', 'Describe your ideal work environment. What does it look like?', 'A strong response gives two or three simple concrete details about a workspace using familiar vocabulary.'),
  ('speaking', 'B1', 'prompt', 'interview', 'Talk about a skill you are currently developing at work. Why did you choose it?', 'A strong response names a skill and gives a clear reason using linked sentences.'),
  ('speaking', 'B2', 'prompt', 'interview', 'Describe how you prioritize your tasks when you have several deadlines at once.', 'A strong response explains a clear method with examples and appropriate sequencing language.'),
  ('speaking', 'C1', 'prompt', 'interview', 'Talk about a piece of feedback you received that changed how you work. How did you respond to it at the time, and how do you view it now?', 'A strong response reflects on past and present perspectives with nuanced, well-organized language.'),
  ('speaking', 'C2', 'prompt', 'interview', 'Describe a time you helped a colleague through a difficult professional situation. What did that experience teach you about leadership?', 'A strong response weaves narrative and abstract reflection with precise, sophisticated vocabulary.'),
  ('speaking', 'A1', 'prompt', 'role_play', 'You need a stapler from a colleague''s desk. Ask them if you can borrow it.', 'A strong response uses a simple, polite request with basic vocabulary.'),
  ('speaking', 'A2', 'prompt', 'role_play', 'You need one more day to finish a report. Ask your manager for a short extension.', 'A strong response makes a clear, polite request and gives a simple reason.'),
  ('speaking', 'B1', 'prompt', 'role_play', 'A customer calls, upset that their order arrived damaged. Respond to them on the phone and explain what you will do next.', 'A strong response acknowledges the problem calmly and explains a next step with appropriate phrasing.'),
  ('speaking', 'B2', 'prompt', 'role_play', 'You are meeting a new client for the first time. Introduce yourself, your company, and explain how you can help them.', 'A strong response is professional and well-structured, balancing warmth with clear information.'),
  ('speaking', 'C1', 'prompt', 'role_play', 'Two colleagues have accidentally booked the same meeting room at the same time and both need it urgently. Mediate the conversation and propose a solution.', 'A strong response manages competing interests diplomatically and proposes a fair, well-reasoned compromise.'),
  ('speaking', 'C2', 'prompt', 'role_play', 'You must give a junior colleague constructive feedback on a mistake that affected a client relationship, without damaging their confidence. Have that conversation.', 'A strong response balances honesty and tact, using sophisticated, carefully calibrated language throughout.'),
  ('speaking', 'A1', 'prompt', 'discussion', 'Do you like working in an office or at home? Why?', 'A strong response states a simple preference with a basic reason.'),
  ('speaking', 'A2', 'prompt', 'discussion', 'Do you prefer open-plan offices or private offices? Why?', 'A strong response states a clear preference and supports it with one or two simple reasons.'),
  ('speaking', 'B1', 'prompt', 'discussion', 'Do you think multitasking makes people more productive at work? Why or why not?', 'A strong response states an opinion and supports it with a relevant reason or example.'),
  ('speaking', 'B2', 'prompt', 'discussion', 'Should companies offer unlimited vacation days to employees? What do you think?', 'A strong response gives a clear opinion supported by reasoning that considers a possible drawback.'),
  ('speaking', 'C1', 'prompt', 'discussion', 'Is video-call fatigue a real problem for modern workplaces, or is it exaggerated? Argue your position.', 'A strong response argues a position with well-developed reasoning and acknowledges the opposing view.'),
  ('speaking', 'C2', 'prompt', 'discussion', 'Should managers always be promoted from within a company, or is it better to hire externally? Defend your view.', 'A strong response constructs a nuanced argument with sophisticated reasoning and weighs counterarguments critically.');

-- Reading (12 passages, 36 mcq questions)
WITH passage2_0 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag) VALUES
    ('Internal Vacancy: Front Desk Assistant', 'We need a new Front Desk Assistant. The job starts on August 1. You will work from 9 am to 5 pm, Monday to Friday. You will answer phones and greet visitors. Please send your CV to Mr. Diallo by July 28. Only staff can apply.', 'reading', 'A1', 'general')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('reading', 'A1', 'mcq', 'general', 'What is the job title advertised?', to_jsonb(ARRAY['Front Desk Assistant','Sales Assistant','Office Manager','IT Support']::text[]), 'Front Desk Assistant', 'The notice says "We need a new Front Desk Assistant."', (SELECT id FROM passage2_0)),
  ('reading', 'A1', 'mcq', 'general', 'When does the job start?', to_jsonb(ARRAY['August 1','July 28','September 1','August 15']::text[]), 'August 1', 'The notice states "The job starts on August 1"; July 28 is only the application deadline.', (SELECT id FROM passage2_0)),
  ('reading', 'A1', 'mcq', 'general', 'Who should applicants send their CV to?', to_jsonb(ARRAY['Mr. Diallo','Ms. Diallo','the HR department','the front desk']::text[]), 'Mr. Diallo', 'The notice says "Please send your CV to Mr. Diallo by July 28."', (SELECT id FROM passage2_0));

WITH passage2_1 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag) VALUES
    ('New Excel Training', 'Subject: New Excel Training
Dear Team,
We have a new Excel course. It starts on Monday, June 2. Classes are from 2 pm to 3 pm every Tuesday and Thursday. The training room is Room 5. Please tell Anna if you want to join. There are only 10 places.
Best,
Karim', 'reading', 'A1', 'email')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('reading', 'A1', 'mcq', 'email', 'What course is being offered?', to_jsonb(ARRAY['Excel','Word','PowerPoint','Accounting']::text[]), 'Excel', 'The email says "We have a new Excel course."', (SELECT id FROM passage2_1)),
  ('reading', 'A1', 'mcq', 'email', 'Which room is the training in?', to_jsonb(ARRAY['Room 5','Room 2','Room 10','Room 3']::text[]), 'Room 5', 'The email states "The training room is Room 5."', (SELECT id FROM passage2_1)),
  ('reading', 'A1', 'mcq', 'email', 'Who should staff contact to join the course?', to_jsonb(ARRAY['Anna','Karim','HR','the manager']::text[]), 'Anna', 'The email says "Please tell Anna if you want to join"; Karim only signed the email.', (SELECT id FROM passage2_1));

WITH passage2_2 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag) VALUES
    ('Expense Policy Update', 'Expense Policy Update
From July 1, all staff must submit expense claims within 14 days of the purchase. Claims made after this time will not be paid. You must attach a receipt for any amount over €20. Claims under €20 do not need a receipt. Send your claim form to the finance team by email. If you have questions, contact Sophie in Finance before you submit your claim.', 'reading', 'A2', 'general')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('reading', 'A2', 'mcq', 'general', 'How many days do staff have to submit an expense claim?', to_jsonb(ARRAY['14 days','20 days','7 days','30 days']::text[]), '14 days', 'The policy says staff must submit claims "within 14 days of the purchase."', (SELECT id FROM passage2_2)),
  ('reading', 'A2', 'mcq', 'general', 'When is a receipt required?', to_jsonb(ARRAY['For amounts over €20','For all claims','For amounts under €20','Only for travel claims']::text[]), 'For amounts over €20', 'The policy states a receipt is needed "for any amount over €20" and that claims under €20 do not need one.', (SELECT id FROM passage2_2)),
  ('reading', 'A2', 'mcq', 'general', 'Who should staff contact if they have questions about their claim?', to_jsonb(ARRAY['Sophie in Finance','the HR manager','the finance team''s general email','the office manager']::text[]), 'Sophie in Finance', 'The policy says "If you have questions, contact Sophie in Finance before you submit your claim."', (SELECT id FROM passage2_2));

WITH passage2_3 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag) VALUES
    ('IT Security Notice', 'IT Security Notice
Please change your computer password every 60 days. Your new password must have at least 8 characters and one number. Do not write your password on paper. Do not share your password with other staff. If you forget your password, call the IT Help Desk at extension 204. Report any strange emails to IT immediately. This policy starts on Monday.', 'reading', 'A2', 'general')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('reading', 'A2', 'mcq', 'general', 'How often must staff change their password?', to_jsonb(ARRAY['Every 60 days','Every 30 days','Every 8 days','Every year']::text[]), 'Every 60 days', 'The notice says "Please change your computer password every 60 days."', (SELECT id FROM passage2_3)),
  ('reading', 'A2', 'mcq', 'general', 'What should staff do if they forget their password?', to_jsonb(ARRAY['Call the IT Help Desk','Write it on paper','Ask another staff member','Send an email to IT']::text[]), 'Call the IT Help Desk', 'The notice says "call the IT Help Desk at extension 204," while it says not to write passwords down or share them.', (SELECT id FROM passage2_3)),
  ('reading', 'A2', 'mcq', 'general', 'What is the minimum number of characters for a new password?', to_jsonb(ARRAY['8','6','10','60']::text[]), '8', 'The notice states the password "must have at least 8 characters."', (SELECT id FROM passage2_3));

WITH passage2_4 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag) VALUES
    ('Product Recall Notice: Model KX-200 Kettle', 'We have found a safety problem with the KX-200 electric kettle sold between March and May this year. The handle may become loose during use, which could cause the kettle to fall. If you own this model, please stop using it immediately. Check the bottom of your kettle for the model number. Customers can return the kettle to any store for a full refund, or contact our support line to arrange a free replacement part. This recall does not affect the KX-100 or KX-300 models. We apologise for any inconvenience and thank customers for their patience while we correct this issue.', 'reading', 'B1', 'general')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('reading', 'B1', 'mcq', 'general', 'What is the problem with the KX-200 kettle?', to_jsonb(ARRAY['The handle may become loose','The kettle may overheat','The power cord is damaged','The lid does not close']::text[]), 'The handle may become loose', 'The notice says "The handle may become loose during use, which could cause the kettle to fall."', (SELECT id FROM passage2_4)),
  ('reading', 'B1', 'mcq', 'general', 'What can customers do to get a full refund?', to_jsonb(ARRAY['Return the kettle to any store','Call the factory','Send the kettle by post','Visit the website']::text[]), 'Return the kettle to any store', 'The notice states customers "can return the kettle to any store for a full refund."', (SELECT id FROM passage2_4)),
  ('reading', 'B1', 'mcq', 'general', 'Which models are NOT affected by this recall?', to_jsonb(ARRAY['KX-100 and KX-300','KX-200 and KX-300','Only KX-100','All kettle models']::text[]), 'KX-100 and KX-300', 'The notice says "This recall does not affect the KX-100 or KX-300 models"; the KX-200 is the affected model.', (SELECT id FROM passage2_4));

WITH passage2_5 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag) VALUES
    ('Welcome as a New Supplier', 'Subject: Welcome as a New Supplier
Dear Mr. Osei,
Thank you for agreeing to supply packaging materials to our company. Before we can place our first order, we need three documents from you: a copy of your business licence, your bank details for payment, and proof of insurance. Please send these to our procurement team within five working days. Once we receive them, we will set up your account in our system, which usually takes two to three days. Our standard payment terms are 30 days from the invoice date. If you have any questions about this process, please contact our procurement manager, Ms. Lund, directly.
Regards,
Procurement Team', 'reading', 'B1', 'email')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('reading', 'B1', 'mcq', 'email', 'How many documents does the supplier need to send?', to_jsonb(ARRAY['Three','Two','Five','Four']::text[]), 'Three', 'The email says "we need three documents from you: a copy of your business licence, your bank details for payment, and proof of insurance."', (SELECT id FROM passage2_5)),
  ('reading', 'B1', 'mcq', 'email', 'What are the company''s standard payment terms?', to_jsonb(ARRAY['30 days from the invoice date','30 days from the order date','14 days from delivery','Payment in advance']::text[]), '30 days from the invoice date', 'The email states "Our standard payment terms are 30 days from the invoice date."', (SELECT id FROM passage2_5)),
  ('reading', 'B1', 'mcq', 'email', 'Who should the supplier contact with questions about the process?', to_jsonb(ARRAY['Ms. Lund','Mr. Osei','the procurement team''s general email','the finance department']::text[]), 'Ms. Lund', 'The email says to "contact our procurement manager, Ms. Lund, directly"; Mr. Osei is the supplier receiving the email, not the contact.', (SELECT id FROM passage2_5));

WITH passage2_6 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag) VALUES
    ('Launch of the Employee Wellness Programme', 'Memo: Launch of the Employee Wellness Programme
Starting next month, the company will introduce a wellness programme aimed at supporting staff physical and mental health. The programme includes free weekly yoga sessions in the third-floor meeting room, a subsidised gym membership covering 50% of monthly fees at partner gyms, and access to a confidential counselling helpline available 24 hours a day. Employees who wish to join the yoga sessions should register with the HR team, as places are limited to twenty participants per session. The gym subsidy will be applied automatically to payslips once employees submit proof of membership to HR. Managers are encouraged to remind their teams that taking short breaks during the day is also part of maintaining wellbeing, though this is not a formal element of the programme. We hope these initiatives will make a genuine difference to how supported staff feel at work.', 'reading', 'B2', 'general')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('reading', 'B2', 'mcq', 'general', 'What percentage of gym fees does the company subsidise?', to_jsonb(ARRAY['50%','100%','25%','75%']::text[]), '50%', 'The memo mentions "a subsidised gym membership covering 50% of monthly fees at partner gyms."', (SELECT id FROM passage2_6)),
  ('reading', 'B2', 'mcq', 'general', 'How should employees join the yoga sessions?', to_jsonb(ARRAY['Register with the HR team','Sign up at the gym','Call the counselling helpline','Speak to their manager']::text[]), 'Register with the HR team', 'The memo says employees "should register with the HR team" to join the yoga sessions.', (SELECT id FROM passage2_6)),
  ('reading', 'B2', 'mcq', 'general', 'What does the memo say about taking short breaks during the day?', to_jsonb(ARRAY['It is encouraged by managers but is not a formal part of the programme','It is a required daily activity','It replaces the yoga sessions','It is only available to managers']::text[]), 'It is encouraged by managers but is not a formal part of the programme', 'The memo states this is "encouraged" by managers but "is not a formal element of the programme."', (SELECT id FROM passage2_6));

WITH passage2_7 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag) VALUES
    ('Registration Confirmed – Annual Sales Conference', 'Subject: Registration Confirmed – Annual Sales Conference
Dear Ms. Fabre,
Thank you for registering for the Annual Sales Conference, taking place on 14–15 September at the Riverside Convention Centre. Your registration includes access to all keynote sessions, two workshops of your choice, and lunch on both days. Please note that workshop places are allocated on a first-come, first-served basis, so we recommend selecting your preferred sessions through the online portal before 1 September. Your conference badge and materials will be available for collection from the registration desk from 8 am on the first day. If you require a certificate of attendance, this can be requested at the registration desk, but it will only be issued to delegates who attend both days in full. Should your plans change, cancellations made before 1 September are fully refundable; after that date, no refunds can be given, although substitute delegates are welcome at no extra charge.
Kind regards,
Conference Team', 'reading', 'B2', 'email')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('reading', 'B2', 'mcq', 'email', 'What happens to workshop places if delegates wait too long to select them?', to_jsonb(ARRAY['Places may already be taken because they are allocated first-come, first-served','Extra workshops will be added automatically','Places are guaranteed regardless of registration date','Workshops will be cancelled']::text[]), 'Places may already be taken because they are allocated first-come, first-served', 'The email states "workshop places are allocated on a first-come, first-served basis."', (SELECT id FROM passage2_7)),
  ('reading', 'B2', 'mcq', 'email', 'Who can receive a certificate of attendance?', to_jsonb(ARRAY['Only delegates who attend both days in full','Any delegate who requests one','Only keynote speakers','Delegates who attend at least one day']::text[]), 'Only delegates who attend both days in full', 'The email says the certificate "will only be issued to delegates who attend both days in full."', (SELECT id FROM passage2_7)),
  ('reading', 'B2', 'mcq', 'email', 'What happens if a delegate cancels after 1 September?', to_jsonb(ARRAY['No refund is given, but a substitute delegate may attend free of charge','A full refund is given automatically','A 50% refund is given','The delegate loses their badge but gets a refund']::text[]), 'No refund is given, but a substitute delegate may attend free of charge', 'The email states that after 1 September "no refunds can be given, although substitute delegates are welcome at no extra charge."', (SELECT id FROM passage2_7));

WITH passage2_8 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag) VALUES
    ('Company-wide Rollout of the New Expense Management System', 'Following a successful pilot in the finance department, the new expense management system, ExpensePro, will be rolled out to all departments over the coming month. Staff will be migrated in three phases, beginning with Sales and Marketing next week, followed by Operations two weeks later, and finally Customer Support and HR in the final phase. Each department will receive a 45-minute training session prior to go-live, and a dedicated support channel will be available on the intranet throughout the transition period. Employees are asked to submit any expense claims currently in progress through the existing system before their department''s cut-off date, as claims cannot be transferred between systems once migration is complete. Early feedback from the pilot group has been largely positive, with users particularly welcoming the mobile receipt-scanning feature, although several noted that the approval workflow for claims over £500 still requires a manual signature, a limitation the IT team is working to address in a future update. Managers should encourage their teams to complete the mandatory training before their go-live date, as access to the new system will not be granted otherwise.', 'reading', 'C1', 'general')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('reading', 'C1', 'mcq', 'general', 'Which department will be migrated to ExpensePro first, according to the rollout schedule?', to_jsonb(ARRAY['Sales and Marketing','Operations','Finance','Customer Support and HR']::text[]), 'Sales and Marketing', 'The text says migration begins "with Sales and Marketing next week"; Finance was already using the system as the pilot department.', (SELECT id FROM passage2_8)),
  ('reading', 'C1', 'mcq', 'general', 'According to early feedback, what limitation of the system have some users noted?', to_jsonb(ARRAY['Claims over £500 still require a manual signature','The mobile app cannot scan receipts','The system does not work on the intranet','Training sessions are too short']::text[]), 'Claims over £500 still require a manual signature', 'The text notes users found "the approval workflow for claims over £500 still requires a manual signature."', (SELECT id FROM passage2_8)),
  ('reading', 'C1', 'mcq', 'general', 'What must employees do before their department''s cut-off date?', to_jsonb(ARRAY['Submit any in-progress expense claims through the existing system','Complete their mandatory training','Download the ExpensePro mobile app','Request manager approval for all claims']::text[]), 'Submit any in-progress expense claims through the existing system', 'The text says employees must submit in-progress claims "before their department''s cut-off date, as claims cannot be transferred between systems once migration is complete."', (SELECT id FROM passage2_8));

WITH passage2_9 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag) VALUES
    ('Understanding the New Performance Review Cycle', 'This year, the company is moving from a single annual performance review to a continuous feedback model, in which employees and managers hold shorter, more frequent check-ins every quarter. The change follows staff survey findings suggesting that annual reviews often felt disconnected from day-to-day work and left little room to address concerns before they became significant. Under the new model, each quarterly check-in focuses on progress toward goals set at the start of the year, with formal ratings still assigned only once, at the year-end review. This means that while feedback will be ongoing, the rating that determines eligibility for bonuses and promotions is not finalised until December. Employees are encouraged to keep a running record of achievements throughout the year, as managers will draw on notes from all four check-ins when preparing the year-end assessment, rather than relying solely on their most recent impression. HR has also introduced an optional peer-feedback component, allowing colleagues to contribute observations that managers may include in the review, though this input is advisory only and does not itself affect the final rating.', 'reading', 'C1', 'general')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('reading', 'C1', 'mcq', 'general', 'When is the formal performance rating assigned?', to_jsonb(ARRAY['Once, at the year-end review','At each quarterly check-in','Only if HR requests it','At the start of the year when goals are set']::text[]), 'Once, at the year-end review', 'The text says "formal ratings still assigned only once, at the year-end review."', (SELECT id FROM passage2_9)),
  ('reading', 'C1', 'mcq', 'general', 'Why did the company change its review process?', to_jsonb(ARRAY['Because annual reviews often felt disconnected from daily work and delayed addressing concerns','Because managers requested more paperwork','Because bonuses were being paid too often','Because peer feedback was made compulsory']::text[]), 'Because annual reviews often felt disconnected from daily work and delayed addressing concerns', 'The text states the change follows findings that annual reviews "often felt disconnected from day-to-day work and left little room to address concerns before they became significant."', (SELECT id FROM passage2_9)),
  ('reading', 'C1', 'mcq', 'general', 'What effect does peer feedback have on an employee''s final rating?', to_jsonb(ARRAY['It is advisory only and does not itself affect the final rating','It automatically determines 50% of the final rating','It replaces the manager''s assessment','It is used only for promotions, not ratings']::text[]), 'It is advisory only and does not itself affect the final rating', 'The text says peer feedback input "is advisory only and does not itself affect the final rating."', (SELECT id FROM passage2_9));

WITH passage2_10 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag) VALUES
    ('From the CEO''s Desk: Reflections on a Turbulent Quarter', 'It would be disingenuous to pretend this quarter unfolded as smoothly as we''d hoped. The supply chain disruptions that dogged us through April forced several difficult calls, not least the temporary pause on our Nordic expansion, a decision I know landed poorly with the regional team who had spent months laying the groundwork. And yet, viewed against the wider picture, there is genuine cause for optimism. Revenue held broadly steady despite the headwinds, a testament less to any single masterstroke than to the quiet, unglamorous discipline shown across procurement and logistics, teams whose contributions rarely make it into these updates but without whom the quarter would have looked very different indeed. Looking ahead, the board has approved renewed investment in the Nordic plans, though timelines remain deliberately loose given how quickly circumstances have shifted this year. I would rather under-promise here than repeat the overconfidence that, if I am honest, coloured some of our earlier communications. What I can promise is candour: when things go well, we will say so, and when they do not, you will hear that too, plainly and without spin. Thank you, as ever, for the resilience you have shown these past months.', 'reading', 'C2', 'general')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('reading', 'C2', 'mcq', 'general', 'What does the CEO imply about the company''s past communications?', to_jsonb(ARRAY['They were sometimes overconfident','They were always accurate','They deliberately hid all problems','They were written by the board, not the CEO']::text[]), 'They were sometimes overconfident', 'The CEO admits wanting to avoid repeating "the overconfidence that... coloured some of our earlier communications."', (SELECT id FROM passage2_10)),
  ('reading', 'C2', 'mcq', 'general', 'What has happened to the Nordic expansion?', to_jsonb(ARRAY['It was paused and has now had renewed investment approved, though with loose timelines','It has been permanently cancelled','It was never affected by the supply chain disruptions','It was completed ahead of schedule']::text[]), 'It was paused and has now had renewed investment approved, though with loose timelines', 'The letter mentions "the temporary pause on our Nordic expansion" and that "the board has approved renewed investment in the Nordic plans, though timelines remain deliberately loose."', (SELECT id FROM passage2_10)),
  ('reading', 'C2', 'mcq', 'general', 'According to the CEO, what mainly explains the steady revenue this quarter?', to_jsonb(ARRAY['The consistent efforts of the procurement and logistics teams','A single major strategic decision by the board','The success of the Nordic expansion','Reduced spending on communications']::text[]), 'The consistent efforts of the procurement and logistics teams', 'The CEO credits steady revenue to "the quiet, unglamorous discipline shown across procurement and logistics," not "any single masterstroke."', (SELECT id FROM passage2_10));

WITH passage2_11 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag) VALUES
    ('Customer Satisfaction Survey: Q2 Results Summary', 'This quarter''s survey drew a healthy response rate of 62%, up from 48% in Q1, though it''s worth noting that the increase coincided with a prize-draw incentive we hadn''t previously offered, so some caution is warranted before reading too much into the improved engagement alone. Overall satisfaction scores rose modestly to 7.8 out of 10, continuing a gradual upward trend since the service-desk restructuring in January. The most striking shift, however, was in the free-text comments: complaints about response times, which dominated Q1 feedback, fell sharply, while a new theme emerged around the clarity of billing statements, an area that had barely registered as an issue before. This suggests the January changes succeeded in addressing their intended target but may have inadvertently drawn attention to a problem that was previously overshadowed by more pressing concerns rather than genuinely worsening. Notably, satisfaction among customers who contacted support more than twice was markedly lower than among first-time contacts, hinting that our resolution process may still struggle with more complex or recurring issues even as it handles routine queries well. We recommend the billing team review statement design before Q3, while the support team should investigate repeat-contact cases specifically rather than treating overall satisfaction as the only relevant metric.', 'reading', 'C2', 'customer_service')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('reading', 'C2', 'mcq', 'customer_service', 'Why does the report urge caution about the higher survey response rate?', to_jsonb(ARRAY['Because it may be linked to a new prize-draw incentive rather than genuinely greater engagement','Because the response rate actually fell','Because the survey was conducted differently in Q2','Because too few customers responded to be meaningful']::text[]), 'Because it may be linked to a new prize-draw incentive rather than genuinely greater engagement', 'The report notes the increase "coincided with a prize-draw incentive we hadn''t previously offered, so some caution is warranted."', (SELECT id FROM passage2_11)),
  ('reading', 'C2', 'mcq', 'customer_service', 'What does the report suggest about the new complaints regarding billing statement clarity?', to_jsonb(ARRAY['The issue likely existed before but was overshadowed by bigger concerns like response times','Billing statements were changed in January and became worse','Billing complaints have always been the top concern','The billing team caused the increase in response times']::text[]), 'The issue likely existed before but was overshadowed by bigger concerns like response times', 'The report says the billing issue was "previously overshadowed by more pressing concerns rather than genuinely worsening."', (SELECT id FROM passage2_11)),
  ('reading', 'C2', 'mcq', 'customer_service', 'What does the report say about customers who contacted support more than twice?', to_jsonb(ARRAY['Their satisfaction was markedly lower than first-time contacts, suggesting the process struggles with complex or recurring issues','They were the most satisfied group overall','They were excluded from the survey','Their satisfaction matched first-time contacts exactly']::text[]), 'Their satisfaction was markedly lower than first-time contacts, suggesting the process struggles with complex or recurring issues', 'The report states satisfaction among repeat contacts "was markedly lower than among first-time contacts, hinting that our resolution process may still struggle with more complex or recurring issues."', (SELECT id FROM passage2_11));
