-- Seed content round 3: listening + reading only (grammar_vocab/writing/speaking
-- deliberately skipped this round per user direction).
-- Generated content, reviewed for CEFR calibration, answer correctness, and no
-- near-duplicate scenarios vs rounds 1-2 before merging.

-- Listening (42 mcq)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation) VALUES
  ('listening', 'A1', 'mcq', 'general', 'You hear: "Your badge doesn''t work at the front door. Please use the side entrance." Which entrance should you use?', to_jsonb(ARRAY['The side entrance','The front door','The back door','The main gate']::text[]), 'The side entrance', 'The speaker says to "use the side entrance" because the badge doesn''t work at the front door.'),
  ('listening', 'A1', 'mcq', 'general', 'You hear: "The elevator is out of order today. Please use the stairs." What is out of order today?', to_jsonb(ARRAY['The elevator','The stairs','The front door','The printer']::text[]), 'The elevator', 'The script states "The elevator is out of order," so people must use the stairs instead.'),
  ('listening', 'A1', 'mcq', 'general', 'You hear: "The office is closed today because of snow." Why is the office closed today?', to_jsonb(ARRAY['Because of snow','Because of rain','Because of a holiday','Because of a fire']::text[]), 'Because of snow', 'The speaker gives the reason directly: "closed today because of snow."'),
  ('listening', 'A1', 'mcq', 'customer_service', 'You hear: "The printer has no toner. New toner arrives tomorrow." When does new toner arrive?', to_jsonb(ARRAY['Tomorrow','Today','Next week','On Friday']::text[]), 'Tomorrow', 'The script says "New toner arrives tomorrow."'),
  ('listening', 'A1', 'mcq', 'call', 'You hear: "Please submit your timesheet by Friday." When is the timesheet due?', to_jsonb(ARRAY['By Friday','By Monday','By Wednesday','By Sunday']::text[]), 'By Friday', 'The instruction states the timesheet is due "by Friday."'),
  ('listening', 'A1', 'mcq', 'general', 'You hear: "The canteen has pasta today, not pizza." What food does the canteen have today?', to_jsonb(ARRAY['Pasta','Pizza','Soup','Salad']::text[]), 'Pasta', 'The speaker says the canteen has "pasta today, not pizza," ruling out pizza.'),
  ('listening', 'A1', 'mcq', 'meeting', 'You hear: "There is a fire alarm test at 10 a.m. today." What time is the fire alarm test?', to_jsonb(ARRAY['10 a.m.','11 a.m.','9 a.m.','2 p.m.']::text[]), '10 a.m.', 'The script directly states the test is "at 10 a.m. today."'),
  ('listening', 'A2', 'mcq', 'customer_service', 'You hear: "The courier needs a signature for your package. He will come back at 3 p.m. if no one is here now." What time will the courier come back?', to_jsonb(ARRAY['3 p.m.','2 p.m.','4 p.m.','1 p.m.']::text[]), '3 p.m.', 'The script says the courier "will come back at 3 p.m." if no one answers.'),
  ('listening', 'A2', 'mcq', 'call', 'You hear: "The VPN stopped working this morning. IT expects to fix it by 2 p.m." When does IT expect to fix the VPN?', to_jsonb(ARRAY['By 2 p.m.','By 5 p.m.','Tomorrow','By noon']::text[]), 'By 2 p.m.', 'The speaker states IT "expects to fix it by 2 p.m."'),
  ('listening', 'A2', 'mcq', 'meeting', 'You hear: "We booked the off-site for next Thursday, not Wednesday." Which day is the off-site now booked for?', to_jsonb(ARRAY['Thursday','Wednesday','Friday','Tuesday']::text[]), 'Thursday', 'The speaker corrects the day, saying "Thursday, not Wednesday."'),
  ('listening', 'A2', 'mcq', 'meeting', 'You hear: "The product launch moved from June to August." When is the new launch date?', to_jsonb(ARRAY['August','June','July','September']::text[]), 'August', 'The script says the launch "moved from June to August," so August is the new date.'),
  ('listening', 'A2', 'mcq', 'general', 'You hear: "You can book desk 12 for tomorrow. Desk 5 is already taken." Which desk is available for tomorrow?', to_jsonb(ARRAY['Desk 12','Desk 5','Desk 3','Desk 8']::text[]), 'Desk 12', 'The speaker says desk 12 can be booked, while desk 5 "is already taken."'),
  ('listening', 'A2', 'mcq', 'general', 'You hear: "The pool car is booked until 4 p.m. Please return it by then." By what time should the pool car be returned?', to_jsonb(ARRAY['4 p.m.','3 p.m.','5 p.m.','6 p.m.']::text[]), '4 p.m.', 'The script instructs to "return it by" 4 p.m., the time the booking ends.'),
  ('listening', 'A2', 'mcq', 'customer_service', 'You hear: "Your package arrived. Please collect it from the mail room before 6 p.m." Where should you collect the package?', to_jsonb(ARRAY['The mail room','Reception','The main office','The warehouse']::text[]), 'The mail room', 'The speaker says to collect the package "from the mail room."'),
  ('listening', 'B1', 'mcq', 'call', 'You hear: "The conference call starts at 9, but the dial-in code changed because the old line was full. Use code 4521 instead of 3390." Which code should you use for the call?', to_jsonb(ARRAY['4521','3390','9','2521']::text[]), '4521', 'The speaker says to "use code 4521 instead of 3390," the old code.'),
  ('listening', 'B1', 'mcq', 'general', 'You hear: "Backups usually run at midnight, but this week they moved to 2 a.m. because of system maintenance." When do the backups run this week?', to_jsonb(ARRAY['2 a.m.','Midnight','6 a.m.','Noon']::text[]), '2 a.m.', 'The script says backups "moved to 2 a.m." this week due to maintenance, unlike the usual midnight slot.'),
  ('listening', 'B1', 'mcq', 'meeting', 'You hear: "The farewell party was going to be in the café, but it moved to the rooftop because more people signed up than expected." Where is the farewell party now being held?', to_jsonb(ARRAY['The rooftop','The café','The canteen','The garden']::text[]), 'The rooftop', 'The speaker explains the party "moved to the rooftop" because of higher-than-expected sign-ups.'),
  ('listening', 'B1', 'mcq', 'meeting', 'You hear: "Salary reviews normally happen in January, but this year they were pushed to March after the budget was finalized late." When are salary reviews happening this year?', to_jsonb(ARRAY['March','January','February','April']::text[]), 'March', 'The script states reviews "were pushed to March" this year because of the late budget.'),
  ('listening', 'B1', 'mcq', 'general', 'You hear: "New starters usually get a buddy on day one, but Sam''s buddy is on leave, so he will meet his buddy on day three instead." When will Sam meet his buddy?', to_jsonb(ARRAY['On day three','On day one','On day two','On day five']::text[]), 'On day three', 'Because the buddy is on leave, Sam "will meet his buddy on day three instead" of day one.'),
  ('listening', 'B1', 'mcq', 'call', 'You hear: "James left the company last week, so his badge was deactivated, but his email account stays active for one more month for handover." What happened to James''s badge?', to_jsonb(ARRAY['It was deactivated','It stays active for a month','It was upgraded','It was never active']::text[]), 'It was deactivated', 'The script clearly states "his badge was deactivated" after he left, while only the email stays active.'),
  ('listening', 'B1', 'mcq', 'negotiation', 'You hear: "The agency sent a temp for two weeks, but we need cover for a month, so they are sending a second temp next week." How long do they actually need cover for?', to_jsonb(ARRAY['A month','Two weeks','One week','Three months']::text[]), 'A month', 'The speaker says "we need cover for a month," which is why a second temp is being sent.'),
  ('listening', 'B2', 'mcq', 'customer_service', 'You hear: "We received your insurance claim, but it''s missing the incident report, so we can''t process it until that''s submitted. Once we have it, processing usually takes five working days." Why can''t the claim be processed yet?', to_jsonb(ARRAY['The incident report is missing','The signature is missing','The claim date is wrong','The claim is too old']::text[]), 'The incident report is missing', 'The speaker says the claim "is missing the incident report," which is blocking processing.'),
  ('listening', 'B2', 'mcq', 'meeting', 'You hear: "Exit interviews are usually held on the last day, but since Maria''s last day falls on a public holiday, hers has been brought forward to the Friday before." When is Maria''s exit interview?', to_jsonb(ARRAY['The Friday before her last day','On her last day','The Monday after her last day','Two weeks before her last day']::text[]), 'The Friday before her last day', 'Because her last day is a public holiday, the interview "has been brought forward to the Friday before."'),
  ('listening', 'B2', 'mcq', 'negotiation', 'You hear: "The NDA needs to be signed before the project kickoff, and since the kickoff was moved up to accommodate the client, the deadline is now this Wednesday rather than next Monday." When is the NDA deadline now?', to_jsonb(ARRAY['This Wednesday','Next Monday','Next Wednesday','This Friday']::text[]), 'This Wednesday', 'The speaker states the deadline "is now this Wednesday rather than next Monday" because the kickoff moved earlier.'),
  ('listening', 'B2', 'mcq', 'negotiation', 'You hear: "The invoice was quoted in dollars, but because the exchange rate shifted sharply last week, the euro total ended up higher than the client expected." Why is the euro total higher than the client expected?', to_jsonb(ARRAY['The exchange rate shifted','The quantity increased','The payment was late','Tax rates increased']::text[]), 'The exchange rate shifted', 'The script attributes the higher euro total to the fact that "the exchange rate shifted sharply last week."'),
  ('listening', 'B2', 'mcq', 'call', 'You hear: "The safety inspector was due next Tuesday, but she asked to move it forward since she''ll be in the area this Thursday anyway." When will the inspection now happen?', to_jsonb(ARRAY['This Thursday','Next Tuesday','Next Thursday','This Tuesday']::text[]), 'This Thursday', 'The inspector asked to move the visit forward to "this Thursday," replacing the original next-Tuesday date.'),
  ('listening', 'B2', 'mcq', 'general', 'You hear: "Spaces on the first-aid course filled up fast, so a second session was added, though it''s only open to people who missed the first one." Who can join the second first-aid session?', to_jsonb(ARRAY['People who missed the first session','Anyone who wants to join','Managers only','New starters only']::text[]), 'People who missed the first session', 'The speaker specifies the second session "is only open to people who missed the first one."'),
  ('listening', 'B2', 'mcq', 'customer_service', 'You hear: "Gym membership reimbursement claims are normally capped at 30 euros a month, but since your invoice covers a full year paid upfront, it will be processed as a single larger claim." How will the gym membership claim be processed?', to_jsonb(ARRAY['As one larger claim','As monthly claims of 30 euros','It will not be processed','Split into two claims']::text[]), 'As one larger claim', 'Because the invoice covers a full year upfront, the script says it "will be processed as a single larger claim" instead of the usual monthly cap.'),
  ('listening', 'C1', 'mcq', 'call', 'You hear: "I know it''s a bit of an ask, but could we push the call to 8 your time? Otherwise our New York folks will be dialing in before sunrise." Why does the speaker want to change the call time?', to_jsonb(ARRAY['So the New York colleagues don''t have to join too early','Because the speaker is on holiday','Because the client cancelled the call','Because of a system outage']::text[]), 'So the New York colleagues don''t have to join too early', 'The speaker explains that otherwise "New York folks will be dialing in before sunrise," so the time needs to change for their benefit.'),
  ('listening', 'C1', 'mcq', 'meeting', 'You hear: "She''s not making a big deal of it, but juggling the handover with only two weeks'' notice is going to be tight." What does the speaker imply about the handover?', to_jsonb(ARRAY['It will be difficult to complete in the time available','The leave request was denied','No handover is necessary','Two weeks is more time than needed']::text[]), 'It will be difficult to complete in the time available', 'Describing the handover as "going to be tight" with only two weeks'' notice implies it will be difficult, not easy.'),
  ('listening', 'C1', 'mcq', 'negotiation', 'You hear: "Honestly, swapping the caterer this close to the retreat is cutting it fine, but they promised the new menu by Friday." What does the phrase cutting it fine suggest about the timing?', to_jsonb(ARRAY['There is very little time left before the retreat','The caterer refused the job','The menu is too expensive','The retreat has been cancelled']::text[]), 'There is very little time left before the retreat', 'Cutting it fine is an idiom meaning there is barely enough time, matching "this close to the retreat."'),
  ('listening', 'C1', 'mcq', 'meeting', 'You hear: "We''d assumed the client would bring their own interpreter, but it turns out we''re on the hook for booking one now." Who is now responsible for booking the interpreter?', to_jsonb(ARRAY['The company','The client','Nobody','The venue']::text[]), 'The company', '"We''re on the hook for booking one now" means the responsibility has shifted to the speaker''s own company.'),
  ('listening', 'C1', 'mcq', 'general', 'You hear: "The restaurant can just about squeeze us in at one, but if anyone''s running late, we might lose the table." What is implied about the one o''clock reservation?', to_jsonb(ARRAY['It is not guaranteed if people arrive late','It has already been cancelled','It is at a different restaurant now','It is confirmed no matter what time people arrive']::text[]), 'It is not guaranteed if people arrive late', 'The warning "if anyone''s running late, we might lose the table" implies the reservation could be lost, so it isn''t guaranteed.'),
  ('listening', 'C1', 'mcq', 'meeting', 'You hear: "The count came up short again, and between you and me, it''s the third time this quarter, so someone upstairs is bound to ask questions." What does the speaker suggest?', to_jsonb(ARRAY['Management will likely investigate the repeated shortages','The count was accurate this time','This is the first time it has happened','The warehouse is closing down']::text[]), 'Management will likely investigate the repeated shortages', '"Someone upstairs is bound to ask questions" implies management attention is coming because of the repeated shortfall, "the third time this quarter."'),
  ('listening', 'C1', 'mcq', 'general', 'You hear: "We were going to keep it low-key, but word got out, so half the building''s expecting an invite now." What happened to the retirement gathering plan?', to_jsonb(ARRAY['More people than planned now expect to be invited','The event was cancelled entirely','It was moved to an online event','Nobody wants to attend anymore']::text[]), 'More people than planned now expect to be invited', '"Word got out" and now "half the building''s expecting an invite," showing the guest list grew beyond the original low-key plan.'),
  ('listening', 'C2', 'mcq', 'general', 'You hear: "Honestly, we could keep pushing the deadline back, but at some point we''re just kicking the can down the road, so I''d rather we bite the bullet and finish it this week." What does the speaker want to do?', to_jsonb(ARRAY['Finish the task this week instead of delaying it further','Push the deadline back again','Cancel the task altogether','Wait for someone else to decide']::text[]), 'Finish the task this week instead of delaying it further', 'The speaker says they would "rather we bite the bullet and finish it this week" instead of continuing to delay.'),
  ('listening', 'C2', 'mcq', 'meeting', 'You hear: "Nobody''s said anything officially, but three meetings got moved to the top floor this week, and that''s usually not a good sign." What does the speaker imply?', to_jsonb(ARRAY['Something significant may be happening, even though nothing has been confirmed','The company has officially announced restructuring','The meetings were all cancelled','The top floor is being renovated']::text[]), 'Something significant may be happening, even though nothing has been confirmed', 'The speaker notes "nobody''s said anything officially" yet still reads the moved meetings as "usually not a good sign," implying suspicion without confirmation.'),
  ('listening', 'C2', 'mcq', 'call', 'You hear: "Priya''s off sick for the rest of the week, so I''ve asked Tom to cover her calls, but he can only do mornings because he''s got his own deadline in the afternoons." When can Tom cover Priya''s calls?', to_jsonb(ARRAY['Mornings only','Afternoons only','All day','Only on Friday']::text[]), 'Mornings only', 'The speaker states Tom "can only do mornings" due to his own afternoon deadline.'),
  ('listening', 'C2', 'mcq', 'customer_service', 'You hear: "Because of the security review, your badge access has been paused, not cancelled, so you''ll need to sign in at reception until it''s reinstated, hopefully by Monday." What does the speaker clarify about the badge?', to_jsonb(ARRAY['It is paused temporarily, not cancelled','It has been permanently cancelled','It was never active','It still works everywhere except reception']::text[]), 'It is paused temporarily, not cancelled', 'The speaker explicitly distinguishes that access "has been paused, not cancelled," expecting reinstatement by Monday.'),
  ('listening', 'C2', 'mcq', 'negotiation', 'You hear: "They said they''d have a think about it, which, knowing this client, usually means we won''t hear back unless we chase them." What does the speaker suggest about the client''s response?', to_jsonb(ARRAY['The client is unlikely to respond unless followed up with','The client agreed to the deal immediately','The client rejected the offer outright','The client will call back within the hour']::text[]), 'The client is unlikely to respond unless followed up with', 'The speaker''s experience is that this phrase "usually means we won''t hear back unless we chase them," implying follow-up will be needed.'),
  ('listening', 'C2', 'mcq', 'meeting', 'You hear: "Turns out both teams booked Room B for two, and since the client''s already in there, I think the internal review''s just going to have to shift to Room D." Which meeting will move to a different room?', to_jsonb(ARRAY['The internal review','The client meeting','Neither meeting is affected','Both meetings move to Room D']::text[]), 'The internal review', 'Since "the client''s already in there," it is "the internal review" that has to "shift to Room D," not the client meeting.'),
  ('listening', 'C2', 'mcq', 'general', 'You hear: "Feedback on the new system''s been mixed: some people love not having to double-enter data, others reckon it''s slower for anything outside the basics." What is one criticism of the new system mentioned?', to_jsonb(ARRAY['It is slower for tasks beyond the basics','It requires double data entry','Nobody likes the new system','No feedback has been given yet']::text[]), 'It is slower for tasks beyond the basics', 'Critics say the system "is slower for anything outside the basics," while others actually praise it for removing "double-enter data," ruling out that option.');

-- Reading (18 passages, 54 mcq questions)
WITH passage3_0 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag) VALUES
    ('Recycling Bins in the Office', 'We have new recycling bins in the kitchen. Blue bins are for paper. Green bins are for plastic bottles. Please put food waste in the brown bin. Do not put food in the blue or green bins. The bins are next to the coffee machine. Thank you for helping us recycle.', 'reading', 'A1', 'general')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('reading', 'A1', 'mcq', 'general', 'What color bin is for paper?', to_jsonb(ARRAY['Blue','Green','Brown','Red']::text[]), 'Blue', 'The passage says "Blue bins are for paper."', (SELECT id FROM passage3_0)),
  ('reading', 'A1', 'mcq', 'general', 'Where are the new bins?', to_jsonb(ARRAY['Next to the coffee machine','In the meeting room','Near the front door','In the car park']::text[]), 'Next to the coffee machine', 'The passage says "The bins are next to the coffee machine."', (SELECT id FROM passage3_0)),
  ('reading', 'A1', 'mcq', 'general', 'What should you not put in the blue or green bins?', to_jsonb(ARRAY['Food waste','Paper','Plastic bottles','Coffee cups']::text[]), 'Food waste', 'The passage says "Do not put food in the blue or green bins," while paper and plastic bottles are the correct items for those bins.', (SELECT id FROM passage3_0));

WITH passage3_1 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag) VALUES
    ('New Employee Orientation Day', 'New employees start on Monday. The orientation is in Meeting Room 2. It starts at 9 a.m. First, HR will talk about the company. Then, at 11 a.m., there is a tour of the building. Lunch is at 12:30 p.m. In the afternoon, you will meet your team. The day ends at 4 p.m.', 'reading', 'A1', 'general')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('reading', 'A1', 'mcq', 'general', 'Where is the orientation?', to_jsonb(ARRAY['Meeting Room 2','Meeting Room 1','The cafeteria','The HR office']::text[]), 'Meeting Room 2', 'The passage says "The orientation is in Meeting Room 2."', (SELECT id FROM passage3_1)),
  ('reading', 'A1', 'mcq', 'general', 'What time does the tour start?', to_jsonb(ARRAY['11 a.m.','9 a.m.','12:30 p.m.','4 p.m.']::text[]), '11 a.m.', 'The passage says "at 11 a.m., there is a tour of the building."', (SELECT id FROM passage3_1)),
  ('reading', 'A1', 'mcq', 'general', 'What happens after lunch?', to_jsonb(ARRAY['You meet your team','You have a tour','HR talks about the company','The day starts']::text[]), 'You meet your team', 'The passage says "In the afternoon, you will meet your team," which comes after lunch at 12:30 p.m.', (SELECT id FROM passage3_1));

WITH passage3_2 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag) VALUES
    ('Charity Bake Sale This Friday', 'Hi team, On Friday, we are having a bake sale for charity. It starts at 10 a.m. in the lobby. Cakes cost 2 euros. All the money goes to a children''s hospital. Please bring cash. Everyone is welcome! Best, Sara', 'reading', 'A1', 'email')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('reading', 'A1', 'mcq', 'email', 'When is the bake sale?', to_jsonb(ARRAY['Friday','Monday','Saturday','Thursday']::text[]), 'Friday', 'The passage says "On Friday, we are having a bake sale for charity."', (SELECT id FROM passage3_2)),
  ('reading', 'A1', 'mcq', 'email', 'Where is the bake sale?', to_jsonb(ARRAY['In the lobby','In the kitchen','In Meeting Room 2','Outside']::text[]), 'In the lobby', 'The passage says "It starts at 10 a.m. in the lobby."', (SELECT id FROM passage3_2)),
  ('reading', 'A1', 'mcq', 'email', 'Who gets the money?', to_jsonb(ARRAY['A children''s hospital','The office team','Sara','A school']::text[]), 'A children''s hospital', 'The passage says "All the money goes to a children''s hospital."', (SELECT id FROM passage3_2));

WITH passage3_3 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag) VALUES
    ('New Referral Bonus Programme', 'Dear Staff, From next month, you can earn a bonus when you recommend a friend for a job here. If we hire the person you recommend, you will receive 200 euros. The new employee must stay for three months before you get the money. To recommend someone, send their CV to HR. This offer will run for six months. If you have questions, contact the HR team. Regards, Recruitment Team', 'reading', 'A2', 'email')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('reading', 'A2', 'mcq', 'email', 'How much is the bonus?', to_jsonb(ARRAY['200 euros','100 euros','300 euros','250 euros']::text[]), '200 euros', 'The passage says "you will receive 200 euros."', (SELECT id FROM passage3_3)),
  ('reading', 'A2', 'mcq', 'email', 'How long must the new employee stay before you get paid?', to_jsonb(ARRAY['Three months','One month','Six months','One year']::text[]), 'Three months', 'The passage says "The new employee must stay for three months before you get the money."', (SELECT id FROM passage3_3)),
  ('reading', 'A2', 'mcq', 'email', 'How do you recommend someone?', to_jsonb(ARRAY['Send their CV to HR','Call HR','Email the manager','Fill in a form']::text[]), 'Send their CV to HR', 'The passage says "To recommend someone, send their CV to HR."', (SELECT id FROM passage3_3));

WITH passage3_4 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag) VALUES
    ('Flexible Benefits: Time to Choose', 'Every year, staff can choose their benefits for the next twelve months. This year, enrolment opens on 1 September and closes on 15 September. You can choose extra holiday days, private health insurance, or a gym membership. You must make your choice online. If you do not choose anything, you will keep the same benefits as last year. Late requests will not be accepted.', 'reading', 'A2', 'general')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('reading', 'A2', 'mcq', 'general', 'When does enrolment close?', to_jsonb(ARRAY['15 September','1 September','30 September','15 October']::text[]), '15 September', 'The passage says "enrolment opens on 1 September and closes on 15 September."', (SELECT id FROM passage3_4)),
  ('reading', 'A2', 'mcq', 'general', 'Where must you make your choice?', to_jsonb(ARRAY['Online','By phone','In the HR office','By email']::text[]), 'Online', 'The passage says "You must make your choice online."', (SELECT id FROM passage3_4)),
  ('reading', 'A2', 'mcq', 'general', 'What happens if you do not choose anything?', to_jsonb(ARRAY['You keep the same benefits as last year','You lose all benefits','You get extra holiday days automatically','Enrolment is extended']::text[]), 'You keep the same benefits as last year', 'The passage says "If you do not choose anything, you will keep the same benefits as last year."', (SELECT id FROM passage3_4));

WITH passage3_5 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag) VALUES
    ('We Are Changing Our Delivery Company', 'Dear Customer, From 1 June, we will use a new delivery company called FastGo for all orders. Your orders may arrive one day earlier than before. You will still receive a tracking link by email. If your order does not arrive on time, please contact our customer service team. We are sorry for any confusion during this change. Thank you for your patience. Customer Service Team', 'reading', 'A2', 'customer_service')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('reading', 'A2', 'mcq', 'customer_service', 'What is the name of the new delivery company?', to_jsonb(ARRAY['FastGo','QuickShip','SpeedyBox','RapidCourier']::text[]), 'FastGo', 'The passage says "we will use a new delivery company called FastGo."', (SELECT id FROM passage3_5)),
  ('reading', 'A2', 'mcq', 'customer_service', 'From when will the new company be used?', to_jsonb(ARRAY['1 June','1 July','15 June','1 May']::text[]), '1 June', 'The passage says "From 1 June, we will use a new delivery company."', (SELECT id FROM passage3_5)),
  ('reading', 'A2', 'mcq', 'customer_service', 'How will customers still track their orders?', to_jsonb(ARRAY['By email','By text message','By phone call','Through an app']::text[]), 'By email', 'The passage says "You will still receive a tracking link by email."', (SELECT id FROM passage3_5));

WITH passage3_6 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag) VALUES
    ('Carrying Over Unused Annual Leave', 'As the year comes to an end, many employees still have unused holiday days. From this year, you may carry over a maximum of five days into the next year, as long as you use them before 31 March. Any days above this limit will be lost, unless you were unable to take leave due to illness or an approved project deadline. To carry over days, you must submit a request through the HR portal before 15 December. Managers will review requests within one week. If you have more than five unused days and no valid reason, we strongly recommend booking time off now, since the extra days cannot be paid out in cash.', 'reading', 'B1', 'general')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('reading', 'B1', 'mcq', 'general', 'What is the maximum number of days that can be carried over?', to_jsonb(ARRAY['Five','Three','Ten','Unlimited']::text[]), 'Five', 'The passage says "you may carry over a maximum of five days."', (SELECT id FROM passage3_6)),
  ('reading', 'B1', 'mcq', 'general', 'By when must carried-over days be used?', to_jsonb(ARRAY['31 March','31 December','15 December','1 January']::text[]), '31 March', 'The passage says the days can be carried over "as long as you use them before 31 March."', (SELECT id FROM passage3_6)),
  ('reading', 'B1', 'mcq', 'general', 'What must employees do to carry over days?', to_jsonb(ARRAY['Submit a request through the HR portal','Email their manager directly','Call HR','Wait for automatic approval']::text[]), 'Submit a request through the HR portal', 'The passage says "you must submit a request through the HR portal before 15 December."', (SELECT id FROM passage3_6));

WITH passage3_7 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag) VALUES
    ('Equipment for Home Working', 'Dear Team, Since many of you now work from home part of the week, we want to make sure you have the right equipment. The company will provide a laptop, a monitor, and a keyboard for each remote worker. If you need a chair or a desk, you can request one through the facilities form, and the company will cover costs up to 150 euros. Please note that all equipment remains company property and must be returned if you leave the company. Requests submitted before the 20th of each month will usually be processed within two weeks. If you already have suitable equipment at home, you do not need to request anything new. Best regards, Facilities Team', 'reading', 'B1', 'email')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('reading', 'B1', 'mcq', 'email', 'What three items will the company provide automatically?', to_jsonb(ARRAY['A laptop, a monitor, and a keyboard','A desk, a chair, and a laptop','A phone, a laptop, and a monitor','A chair, a keyboard, and a phone']::text[]), 'A laptop, a monitor, and a keyboard', 'The passage says "The company will provide a laptop, a monitor, and a keyboard for each remote worker."', (SELECT id FROM passage3_7)),
  ('reading', 'B1', 'mcq', 'email', 'What is the maximum amount the company will cover for a chair or desk?', to_jsonb(ARRAY['150 euros','100 euros','200 euros','250 euros']::text[]), '150 euros', 'The passage says "the company will cover costs up to 150 euros."', (SELECT id FROM passage3_7)),
  ('reading', 'B1', 'mcq', 'email', 'What must happen to the equipment if an employee leaves the company?', to_jsonb(ARRAY['It must be returned','It can be kept','It must be sold back','It becomes the employee''s property']::text[]), 'It must be returned', 'The passage says the equipment "remains company property and must be returned if you leave the company."', (SELECT id FROM passage3_7));

WITH passage3_8 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag) VALUES
    ('Your Mentorship Programme Match', 'Hi Daniela, We are pleased to let you know that you have been paired with a mentor for our new mentorship programme. Your mentor is Marcus Webb, who works in the finance department and has been with the company for eight years. We recommend that you contact Marcus this week to arrange your first meeting, which should take place before the end of the month. Over the next six months, you will meet at least once a month to discuss your career goals and any challenges you are facing. Please complete a short feedback form after each meeting so we can improve the programme in the future. Good luck, and we hope you find the experience valuable. HR Team', 'reading', 'B1', 'email')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('reading', 'B1', 'mcq', 'email', 'Which department does Marcus work in?', to_jsonb(ARRAY['Finance','HR','Marketing','IT']::text[]), 'Finance', 'The passage says "Marcus Webb, who works in the finance department."', (SELECT id FROM passage3_8)),
  ('reading', 'B1', 'mcq', 'email', 'How often should Daniela and Marcus meet over six months?', to_jsonb(ARRAY['At least once a month','Once a week','Once every two months','Only once']::text[]), 'At least once a month', 'The passage says "you will meet at least once a month."', (SELECT id FROM passage3_8)),
  ('reading', 'B1', 'mcq', 'email', 'What should Daniela do after each meeting?', to_jsonb(ARRAY['Complete a short feedback form','Send Marcus a gift','Report to her manager','Write a full report']::text[]), 'Complete a short feedback form', 'The passage says "Please complete a short feedback form after each meeting."', (SELECT id FROM passage3_8));

WITH passage3_9 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag) VALUES
    ('Guidelines for Business Travel Expenses', 'Employees travelling for business purposes should book flights and hotels at least two weeks in advance through the approved travel portal, as last-minute bookings are rarely cost-effective and require additional manager approval. Economy class is standard for flights under five hours; for longer flights, premium economy may be booked with prior authorisation. Hotel accommodation should not exceed 150 euros per night in most cities, though exceptions apply in higher-cost locations such as London or Paris, where the limit rises to 200 euros. Meals during travel are reimbursed up to 40 euros per day, but alcohol is not covered under any circumstances. All receipts must be submitted within ten working days of returning from the trip; claims submitted later than this may be delayed or, in some cases, rejected entirely. Employees are encouraged to use the mobile app to photograph receipts as soon as they are received, rather than keeping paper copies until the end of the trip.', 'reading', 'B2', 'general')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('reading', 'B2', 'mcq', 'general', 'What is the standard hotel limit in London?', to_jsonb(ARRAY['200 euros','150 euros','100 euros','250 euros']::text[]), '200 euros', 'The passage says in London or Paris "the limit rises to 200 euros."', (SELECT id FROM passage3_9)),
  ('reading', 'B2', 'mcq', 'general', 'Within how many working days must receipts be submitted?', to_jsonb(ARRAY['Ten','Five','Fifteen','Thirty']::text[]), 'Ten', 'The passage says "receipts must be submitted within ten working days of returning from the trip."', (SELECT id FROM passage3_9)),
  ('reading', 'B2', 'mcq', 'general', 'What is never reimbursed during business travel?', to_jsonb(ARRAY['Alcohol','Meals','Hotel accommodation','Economy flights']::text[]), 'Alcohol', 'The passage says "alcohol is not covered under any circumstances."', (SELECT id FROM passage3_9));

WITH passage3_10 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag) VALUES
    ('Protecting Yourself from Phishing Emails', 'Dear Colleagues, Over the past month, our IT department has noticed a sharp increase in phishing emails targeting staff accounts, several of which have successfully tricked employees into revealing their login details. These emails often appear to come from senior managers or trusted suppliers and typically create a sense of urgency, asking you to click a link or transfer money immediately. Please remember that IT will never ask for your password by email under any circumstances. Before clicking any link, hover over it to check the actual web address, and if anything looks suspicious, forward the email to security@company.com rather than replying to it directly. We will be running a mandatory training session next week to help everyone recognise these threats more easily. Anyone who accidentally clicks a suspicious link should report it immediately rather than staying silent, as early reporting allows IT to limit any potential damage. Thank you for your vigilance. IT Security Team', 'reading', 'B2', 'email')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('reading', 'B2', 'mcq', 'email', 'What should you do if an email looks suspicious?', to_jsonb(ARRAY['Forward it to security@company.com','Reply asking for confirmation','Delete it immediately','Click the link to check it']::text[]), 'Forward it to security@company.com', 'The passage says "forward the email to security@company.com rather than replying to it directly."', (SELECT id FROM passage3_10)),
  ('reading', 'B2', 'mcq', 'email', 'What will IT never do by email?', to_jsonb(ARRAY['Ask for your password','Send training invitations','Contact senior managers','Report suspicious activity']::text[]), 'Ask for your password', 'The passage says "IT will never ask for your password by email under any circumstances."', (SELECT id FROM passage3_10)),
  ('reading', 'B2', 'mcq', 'email', 'What should an employee do after accidentally clicking a suspicious link?', to_jsonb(ARRAY['Report it immediately','Stay silent to avoid trouble','Change their email address','Wait for IT to notice']::text[]), 'Report it immediately', 'The passage says the employee "should report it immediately rather than staying silent."', (SELECT id FROM passage3_10));

WITH passage3_11 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag) VALUES
    ('Notice of Updated Pricing', 'Dear Valued Client, After careful review of our production and material costs, which have risen significantly over the past year, we must inform you that our price list will be updated from 1 September. Most products will see an increase of between three and five percent, though our premium range will remain unchanged as part of our commitment to long-term partners like yourselves. We understand this news may affect your budgeting, so we are offering existing clients the option to lock in current prices for orders placed and confirmed before 15 August. We value our relationship greatly and would welcome the opportunity to discuss these changes directly, including possible volume discounts for larger annual commitments. Please contact your account manager if you would like to arrange a call. We remain fully committed to providing the quality and service you have come to expect. Sincerely, Sales Department', 'reading', 'B2', 'negotiation')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('reading', 'B2', 'mcq', 'negotiation', 'By when must orders be confirmed to keep current prices?', to_jsonb(ARRAY['15 August','1 September','1 August','15 September']::text[]), '15 August', 'The passage says clients can lock in current prices "for orders placed and confirmed before 15 August."', (SELECT id FROM passage3_11)),
  ('reading', 'B2', 'mcq', 'negotiation', 'What will NOT increase in price?', to_jsonb(ARRAY['The premium range','Most products','All products','Standard items']::text[]), 'The premium range', 'The passage says "our premium range will remain unchanged."', (SELECT id FROM passage3_11)),
  ('reading', 'B2', 'mcq', 'negotiation', 'Who should clients contact to discuss the changes?', to_jsonb(ARRAY['Their account manager','The production team','Customer service','The finance department']::text[]), 'Their account manager', 'The passage says "Please contact your account manager if you would like to arrange a call."', (SELECT id FROM passage3_11));

WITH passage3_12 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag) VALUES
    ('Findings from the Annual Software Licence Audit', 'Following the completion of this year''s software licence audit, the IT governance team has identified several areas requiring attention before our next renewal cycle. Most notably, we discovered that the design department has been running 34 active seats of a specialist editing suite, despite only 22 licences having been formally purchased, exposing the company to potential compliance penalties if left unaddressed. Conversely, the finance division holds 40 licences for a reporting tool but usage logs indicate that fewer than half have been accessed in the last six months, suggesting a considerable opportunity for cost reduction at the next renewal. We are also aware that several teams have independently subscribed to cloud-based tools outside the centrally managed procurement process, which complicates both budgeting and security oversight. Department heads are asked to review their current allocations against actual usage and submit any adjustment requests by the end of the month. Where over-licensing is identified, we would rather quietly true up the numbers now than face an uncomfortable conversation with the vendor''s compliance team later. A full summary will be presented at next month''s leadership meeting.', 'reading', 'C1', 'general')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('reading', 'C1', 'mcq', 'general', 'What compliance risk did the audit find in the design department?', to_jsonb(ARRAY['More seats are active than licences purchased','Too many unused licences','Unauthorised cloud subscriptions','Expired licences']::text[]), 'More seats are active than licences purchased', 'The passage says the design department runs "34 active seats... despite only 22 licences having been formally purchased."', (SELECT id FROM passage3_12)),
  ('reading', 'C1', 'mcq', 'general', 'What does the finance division''s usage data suggest?', to_jsonb(ARRAY['An opportunity to reduce costs at renewal','A need to buy more licences','A serious security breach','Full compliance with no issues']::text[]), 'An opportunity to reduce costs at renewal', 'The passage says fewer than half the licences have been used recently, "suggesting a considerable opportunity for cost reduction at the next renewal."', (SELECT id FROM passage3_12)),
  ('reading', 'C1', 'mcq', 'general', 'What are department heads asked to do by the end of the month?', to_jsonb(ARRAY['Review allocations and submit adjustment requests','Cancel all software subscriptions','Attend the leadership meeting','Purchase additional licences']::text[]), 'Review allocations and submit adjustment requests', 'The passage says department heads are asked to "review their current allocations against actual usage and submit any adjustment requests by the end of the month."', (SELECT id FROM passage3_12));

WITH passage3_13 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag) VALUES
    ('Launching Our Diversity and Inclusion Initiative', 'Dear All, I am pleased to announce the launch of our company-wide Diversity and Inclusion initiative, a programme that reflects our belief that varied perspectives ultimately make us a stronger and more innovative organisation. Over the coming year, this will include unconscious bias training for all managers, the formation of employee resource groups for underrepresented staff, and a review of our recruitment process to ensure job descriptions and interview panels do not inadvertently disadvantage any candidates. We recognise that meaningful change takes sustained effort rather than a single announcement, which is why progress will be measured through an annual survey and reported transparently to all staff, including areas where we have fallen short. Employees interested in joining or starting an employee resource group should contact the D&I committee directly; no prior experience is necessary, only genuine interest. We are also introducing a mentorship strand specifically for employees from underrepresented backgrounds, separate from our existing general mentorship programme. This is only the beginning, and we welcome your feedback as we shape the initiative further. With thanks, People & Culture Team', 'reading', 'C1', 'email')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('reading', 'C1', 'mcq', 'email', 'How will progress on the initiative be measured?', to_jsonb(ARRAY['Through an annual survey','Through quarterly manager reports','Through exit interviews','Through recruitment statistics only']::text[]), 'Through an annual survey', 'The passage says "progress will be measured through an annual survey."', (SELECT id FROM passage3_13)),
  ('reading', 'C1', 'mcq', 'email', 'What is required to join an employee resource group?', to_jsonb(ARRAY['Genuine interest, no prior experience necessary','Manager approval','At least two years at the company','Completion of bias training']::text[]), 'Genuine interest, no prior experience necessary', 'The passage says "no prior experience is necessary, only genuine interest."', (SELECT id FROM passage3_13)),
  ('reading', 'C1', 'mcq', 'email', 'How does the new mentorship strand relate to the existing programme?', to_jsonb(ARRAY['It is separate from the existing general mentorship programme','It replaces the existing programme','It is identical to the existing programme','It is only open to managers']::text[]), 'It is separate from the existing general mentorship programme', 'The passage describes the new strand as "separate from our existing general mentorship programme."', (SELECT id FROM passage3_13));

WITH passage3_14 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag) VALUES
    ('Rollout of Company Expense Cards', 'Dear Team, As part of our effort to simplify expense management, we are rolling out company expense cards to all employees who travel or make purchases on behalf of the business at least once a month. Unlike the previous system, where you paid out of pocket and waited for reimbursement, purchases on the new card will be charged directly to the company, though you will still need to upload a receipt and a brief note within 48 hours through the finance app. Cards will be issued in phases over the next two months, starting with the sales and operations teams, whose travel volume makes them the priority group; other departments will follow shortly after. Please note that the card is intended strictly for approved business expenses, and any personal use, even if reimbursed later, will be treated as a policy violation. Employees who leave the qualifying criteria, for instance moving to a role with minimal travel, may have their card withdrawn at the next review. If you believe you qualify but have not been contacted, please reach out to the finance team. Regards, Finance Team', 'reading', 'C1', 'email')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('reading', 'C1', 'mcq', 'email', 'Why are sales and operations teams receiving cards first?', to_jsonb(ARRAY['Their travel volume makes them the priority group','They asked for cards first','They have the most complaints','They are the largest departments']::text[]), 'Their travel volume makes them the priority group', 'The passage says the rollout starts with sales and operations "whose travel volume makes them the priority group."', (SELECT id FROM passage3_14)),
  ('reading', 'C1', 'mcq', 'email', 'Within how many hours must a receipt and note be uploaded?', to_jsonb(ARRAY['48 hours','24 hours','72 hours','One week']::text[]), '48 hours', 'The passage says employees must "upload a receipt and a brief note within 48 hours."', (SELECT id FROM passage3_14)),
  ('reading', 'C1', 'mcq', 'email', 'What is considered a policy violation?', to_jsonb(ARRAY['Personal use of the card, even if reimbursed','Uploading receipts late','Requesting a card','Working in a non-qualifying role']::text[]), 'Personal use of the card, even if reimbursed', 'The passage says "any personal use, even if reimbursed later, will be treated as a policy violation."', (SELECT id FROM passage3_14));

WITH passage3_15 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag) VALUES
    ('Update to Our Whistleblowing Policy', 'Following consultation with staff representatives and external legal counsel, we are updating our whistleblowing policy to reinforce, in both letter and spirit, our commitment to a culture in which concerns can be raised without fear of reprisal. The revised policy broadens the definition of protected disclosures to include not only financial irregularities and legal breaches but also concerns about workplace culture, such as bullying that management has repeatedly failed to address. A new, independently operated reporting hotline will allow employees to raise concerns anonymously, and reports may no longer be routed through an employee''s direct line manager by default, a change prompted by feedback that this arrangement had, in practice, discouraged some staff from coming forward. Investigations will be led by a designated compliance officer who sits outside the reporting employee''s department, and interim updates will be shared with the discloser at each stage, even where no wrongdoing is ultimately found. We want to be candid that trust in this process has been dented in the past, and rebuilding it will take consistent, demonstrated action rather than a single policy revision. Employees with questions about the new process should consult the updated handbook or contact the compliance office directly.', 'reading', 'C2', 'general')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('reading', 'C2', 'mcq', 'general', 'Why was the default routing through a direct line manager removed?', to_jsonb(ARRAY['Feedback suggested it had discouraged some staff from coming forward','Line managers requested it be removed','It was too slow','Legal counsel found it illegal']::text[]), 'Feedback suggested it had discouraged some staff from coming forward', 'The passage says the change was "prompted by feedback that this arrangement had, in practice, discouraged some staff from coming forward."', (SELECT id FROM passage3_15)),
  ('reading', 'C2', 'mcq', 'general', 'What does the passage imply about trust in the whistleblowing process?', to_jsonb(ARRAY['It has been damaged and will take time to rebuild','It has never been questioned','It was fully restored by this policy alone','It is not something the company is concerned about']::text[]), 'It has been damaged and will take time to rebuild', 'The passage says "trust in this process has been dented in the past, and rebuilding it will take consistent, demonstrated action."', (SELECT id FROM passage3_15)),
  ('reading', 'C2', 'mcq', 'general', 'Who leads investigations under the new policy?', to_jsonb(ARRAY['A designated compliance officer outside the employee''s department','The employee''s direct line manager','An external law firm','A senior executive committee']::text[]), 'A designated compliance officer outside the employee''s department', 'The passage says "Investigations will be led by a designated compliance officer who sits outside the reporting employee''s department."', (SELECT id FROM passage3_15));

WITH passage3_16 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag) VALUES
    ('Summary of Internal Audit Findings: Procurement', 'The internal audit team''s review of procurement practices across three regional offices has surfaced a pattern that, while not indicative of deliberate wrongdoing, warrants closer scrutiny than it has so far received. In each office, a small number of suppliers accounted for a disproportionate share of spend, and in two cases, contracts had been renewed without the competitive tender process our policy requires, apparently because the relevant approvals were treated as a formality rather than a genuine checkpoint. None of the individual transactions reviewed exceeded authorisation limits, which is likely why the pattern had gone unnoticed until data from all three offices was compared side by side. The audit team stops short of recommending disciplinary action, noting that the breakdown appears procedural rather than intentional, but recommends that any tender renewal above a set spending threshold require a documented second sign-off from someone outside the originating office, since regional managers'' proximity to long-standing suppliers may have made objectivity difficult in practice. Given the reputational sensitivity of procurement irregularities, however measured, the audit committee has asked that this summary not be circulated beyond department heads until the response plan is finalised.', 'reading', 'C2', 'general')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('reading', 'C2', 'mcq', 'general', 'Why did the spending pattern go unnoticed for so long?', to_jsonb(ARRAY['No individual transaction exceeded authorisation limits, so comparison across offices was needed to spot it','The suppliers hid their invoices','The audit team was not given access to the data','Regional managers deliberately concealed the pattern']::text[]), 'No individual transaction exceeded authorisation limits, so comparison across offices was needed to spot it', 'The passage says none of the transactions exceeded limits, "which is likely why the pattern had gone unnoticed until data from all three offices was compared side by side."', (SELECT id FROM passage3_16)),
  ('reading', 'C2', 'mcq', 'general', 'Does the audit team recommend disciplinary action?', to_jsonb(ARRAY['No, it describes the breakdown as procedural rather than intentional','Yes, against all three regional managers','Yes, but only in one office','The passage does not mention disciplinary action']::text[]), 'No, it describes the breakdown as procedural rather than intentional', 'The passage says "the audit team stops short of recommending disciplinary action, noting that the breakdown appears procedural rather than intentional."', (SELECT id FROM passage3_16)),
  ('reading', 'C2', 'mcq', 'general', 'Who has the audit committee asked NOT to receive this summary for now?', to_jsonb(ARRAY['Anyone beyond department heads','Regional managers only','Suppliers','The audit team itself']::text[]), 'Anyone beyond department heads', 'The passage says the committee "asked that this summary not be circulated beyond department heads until the response plan is finalised."', (SELECT id FROM passage3_16));

WITH passage3_17 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag) VALUES
    ('Quarterly Analysis of Client Complaint Trends', 'This quarter''s review of client complaints reveals a trend that, on the surface, looks concerning but merits a more nuanced reading than the raw numbers suggest. Total complaint volume rose by 18 percent compared with the previous quarter, yet this increase coincides almost exactly with the rollout of our new billing system, and nearly two-thirds of new complaints relate specifically to invoice formatting rather than to service quality, pricing, or delivery, none of which saw a meaningful increase. Once billing-related complaints are set aside, underlying satisfaction indicators, including repeat business and unprompted positive feedback, have in fact held steady or improved slightly. This suggests the headline figure reflects a transitional issue with a specific system rather than a broader decline in service, though it would be premature to dismiss it entirely, since prolonged billing confusion can itself erode trust if left unresolved. The customer service team recommends a targeted communication to affected clients explaining the new invoice format, alongside a temporary rollback of the most confusing layout elements while a permanent fix is developed. We do not recommend a full system reversal, as the underlying billing engine has already delivered measurable processing efficiencies elsewhere. A follow-up review is planned for next quarter.', 'reading', 'C2', 'customer_service')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('reading', 'C2', 'mcq', 'customer_service', 'What does most of the complaint increase relate to?', to_jsonb(ARRAY['Invoice formatting from the new billing system','Poor service quality','Late deliveries','Pricing changes']::text[]), 'Invoice formatting from the new billing system', 'The passage says "nearly two-thirds of new complaints relate specifically to invoice formatting" tied to the new billing system''s rollout.', (SELECT id FROM passage3_17)),
  ('reading', 'C2', 'mcq', 'customer_service', 'What does the report say about underlying satisfaction indicators once billing complaints are set aside?', to_jsonb(ARRAY['They have held steady or improved slightly','They have declined sharply','They cannot be measured','They have doubled']::text[]), 'They have held steady or improved slightly', 'The passage says these indicators "have in fact held steady or improved slightly."', (SELECT id FROM passage3_17)),
  ('reading', 'C2', 'mcq', 'customer_service', 'What does the customer service team recommend instead of a full system reversal?', to_jsonb(ARRAY['A targeted communication and temporary rollback of confusing layout elements','Immediate cancellation of the billing system','No action at all','A full refund to all affected clients']::text[]), 'A targeted communication and temporary rollback of confusing layout elements', 'The passage says the team recommends "a targeted communication to affected clients... alongside a temporary rollback of the most confusing layout elements" rather than a full system reversal.', (SELECT id FROM passage3_17));
