-- B2 reading round 2. C1 and C2 each got both a patch (rewriting the
-- weakest existing question per passage) AND a dedicated round of new
-- inference-first passages. B2 had the identical fact-lookup problem
-- (fixed via patch in 20260802112000) but never got the round-2
-- treatment, leaving it asymmetric with C1/C2. Closes that gap: 3 new
-- B2 passages, 9 questions, 2 of 3 per passage requiring inference/
-- synthesis rather than lookup, matching the C1/C2 round-2 pattern.

WITH b2rp2_passage_0 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag)
    VALUES ('Switching Office Cleaning Contractors', 'After several complaints about missed bins and dusty desks, the office manager has decided to switch cleaning contractors from CleanCo to SparkleServices, starting next Monday. The new contractor will visit every weekday evening instead of three times a week, which should reduce the kind of build-up that led to recent complaints. Staff are asked to clear their desks of personal items each evening so the new team can clean properly, something the previous contractor never required. The office manager acknowledged that some staff may find the daily desk-clearing routine an extra step, but said the trade-off was worth it given how many complaints had piled up under the old schedule. Any issues with the new contractor should be reported directly to the office manager rather than left for the next cleaning visit, so that problems can be raised with SparkleServices quickly rather than accumulating unnoticed.', 'reading', 'B2', 'general')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('reading', 'B2', 'mcq', 'general', 'How often will the new contractor clean the office?', to_jsonb(ARRAY['Every weekday evening','Three times a week','Once a week','Every morning']::text[]), 'Every weekday evening', 'The passage says the new contractor "will visit every weekday evening instead of three times a week."', (SELECT id FROM b2rp2_passage_0)),
  ('reading', 'B2', 'mcq', 'general', 'What does the office manager''s comment about the desk-clearing routine suggest about their view of the trade-off?', to_jsonb(ARRAY['They accept the minor inconvenience because it should fix the underlying complaints','They believe the new routine is not worth the switch','They think staff exaggerated their complaints','They plan to remove the desk-clearing requirement soon']::text[]), 'They accept the minor inconvenience because it should fix the underlying complaints', 'The manager "acknowledged that some staff may find the daily desk-clearing routine an extra step, but said the trade-off was worth it given how many complaints had piled up" -- weighing a small cost against a bigger gain, not dismissing complaints or planning to reverse the policy.', (SELECT id FROM b2rp2_passage_0)),
  ('reading', 'B2', 'mcq', 'general', 'Why does the office manager ask staff to report issues directly rather than waiting for the next visit?', to_jsonb(ARRAY['To prevent problems from building up unnoticed, the way they did under the previous contractor','To give staff extra work responsibilities','To reduce the number of cleaning visits further','To transfer complaints to HR instead of the office manager']::text[]), 'To prevent problems from building up unnoticed, the way they did under the previous contractor', 'The passage states this is "so that problems can be raised with SparkleServices quickly rather than accumulating unnoticed" -- directly echoing the original complaint pattern the switch was meant to fix.', (SELECT id FROM b2rp2_passage_0));

WITH b2rp2_passage_1 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag)
    VALUES ('A Change to Expense Approval Limits', 'Starting next month, department heads will be able to approve expenses up to €2,000 without needing sign-off from finance, up from the current limit of €500. The change follows feedback that the old process was creating unnecessary delays for routine purchases like software licences and travel bookings, which rarely caused problems even when they exceeded €500. Finance will still review all expenses retrospectively each quarter, and any department showing an unusual pattern of spending will be flagged for closer monitoring going forward. Department heads are reminded that the higher limit is a matter of trust rather than reduced accountability, and that repeated errors or unclear justifications could see the limit lowered again for that department specifically. The finance team will run a short briefing next week for anyone who wants to understand the new retrospective review process in more detail.', 'reading', 'B2', 'general')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('reading', 'B2', 'mcq', 'general', 'What is the new expense approval limit for department heads?', to_jsonb(ARRAY['€2,000','€500','€1,000','€5,000']::text[]), '€2,000', 'The passage states department heads "will be able to approve expenses up to €2,000... up from the current limit of €500."', (SELECT id FROM b2rp2_passage_1)),
  ('reading', 'B2', 'mcq', 'general', 'Why does the passage describe the higher limit as "a matter of trust rather than reduced accountability"?', to_jsonb(ARRAY['Because spending is still reviewed afterward, and the limit can be lowered again if problems arise','Because department heads no longer need to justify any expenses','Because finance has stopped monitoring spending altogether','Because the €2,000 limit applies only to software purchases']::text[]), 'Because spending is still reviewed afterward, and the limit can be lowered again if problems arise', 'The passage says "Finance will still review all expenses retrospectively each quarter" and that "repeated errors or unclear justifications could see the limit lowered again" -- accountability is retained through review, just applied afterward instead of blocking approval upfront.', (SELECT id FROM b2rp2_passage_1)),
  ('reading', 'B2', 'mcq', 'general', 'What does the option to lower the limit again "for that department specifically" suggest about how the policy will be applied?', to_jsonb(ARRAY['The new limit is not a fixed, company-wide rule but can be adjusted per department based on behaviour','All departments will automatically lose the higher limit after one quarter','Only the finance department can ever have its limit changed','The limit will increase further for departments that spend more']::text[]), 'The new limit is not a fixed, company-wide rule but can be adjusted per department based on behaviour', 'Specifying the limit could be lowered "for that department" (not company-wide) shows the policy is applied and adjusted per department, not as a single fixed rule for everyone.', (SELECT id FROM b2rp2_passage_1));

WITH b2rp2_passage_2 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag)
    VALUES ('Feedback on the New Booking System', 'Two months after switching to the new meeting room booking system, initial feedback has been mixed. Most staff say the app itself is easier to use than the old spreadsheet, and double-bookings have dropped significantly since the switch. However, several people have raised a specific complaint: the system does not send a reminder when a booked room goes unused, so rooms are sometimes held for meetings that were cancelled informally and never released. IT is investigating whether an automatic release feature can be added for rooms unused fifteen minutes past the booking start time, though this would require a minor update to the underlying software licence. In the meantime, staff are asked to manually cancel bookings as soon as they know a meeting won''t go ahead, rather than assuming the system will notice on its own. The facilities team plans to review usage data again in another two months to see whether the manual cancellation reminder has been enough to reduce the problem without needing the software update.', 'reading', 'B2', 'general')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('reading', 'B2', 'mcq', 'general', 'What has dropped significantly since the new booking system was introduced?', to_jsonb(ARRAY['Double-bookings','The number of meeting rooms','Staff complaints about the app','The length of meetings']::text[]), 'Double-bookings', 'The passage says "double-bookings have dropped significantly since the switch."', (SELECT id FROM b2rp2_passage_2)),
  ('reading', 'B2', 'mcq', 'general', 'Why are staff being asked to manually cancel bookings in the meantime?', to_jsonb(ARRAY['Because the system cannot currently detect or release unused rooms on its own','Because IT has disabled the booking app temporarily','Because manual cancellation is now required for all future bookings permanently','Because the facilities team wants to reduce the total number of bookings']::text[]), 'Because the system cannot currently detect or release unused rooms on its own', 'The passage explains the system "does not send a reminder when a booked room goes unused," so staff must cancel manually until IT''s automatic release feature (if built) fixes this gap.', (SELECT id FROM b2rp2_passage_2)),
  ('reading', 'B2', 'mcq', 'general', 'What does the facilities team''s plan to review usage data again in two months suggest about their approach to the unused-room problem?', to_jsonb(ARRAY['They want to see if the manual-cancellation request alone fixes the issue before committing to the more complex software update','They have already decided the software update is unnecessary','They plan to abandon the new booking system entirely','They believe the problem is not worth investigating further']::text[]), 'They want to see if the manual-cancellation request alone fixes the issue before committing to the more complex software update', 'The passage frames the review as checking "whether the manual cancellation reminder has been enough to reduce the problem without needing the software update" -- a wait-and-see step before committing to the update IT is separately investigating.', (SELECT id FROM b2rp2_passage_2));
