-- Seed content round 4: listening + reading only (same skip-pattern as round 3).
-- Generated content, reviewed for CEFR calibration, answer correctness, and no
-- near-duplicate scenarios vs rounds 1-3 before merging.

-- Listening (42 mcq)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation) VALUES
  ('listening', 'A1', 'mcq', 'general', 'You hear: "A black umbrella was found at reception this morning." What was found at reception?', to_jsonb(ARRAY['A black umbrella','A black bag','A red umbrella','A black jacket']::text[]), 'A black umbrella', 'The script says a "black umbrella" was found, not a bag, a red umbrella, or a jacket.'),
  ('listening', 'A1', 'mcq', 'call', 'You hear: "Please return the laptop by Friday." When must the laptop be returned?', to_jsonb(ARRAY['By Friday','By Monday','By Thursday','By Wednesday']::text[]), 'By Friday', 'The message states the laptop must be returned "by Friday."'),
  ('listening', 'A1', 'mcq', 'general', 'You hear: "New parking permits start on the first of May." When do the new parking permits start?', to_jsonb(ARRAY['On the first of May','On the first of June','On the fifteenth of May','On the first of April']::text[]), 'On the first of May', 'The script gives the exact start date as "the first of May."'),
  ('listening', 'A1', 'mcq', 'call', 'You hear: "Your password was reset this morning." When was the password reset?', to_jsonb(ARRAY['This morning','Yesterday','Tomorrow','This afternoon']::text[]), 'This morning', 'The script says the password was reset "this morning," not yesterday, tomorrow, or this afternoon.'),
  ('listening', 'A1', 'mcq', 'meeting', 'You hear: "The team lunch is now in the garden, not the cafeteria." Where is the team lunch now?', to_jsonb(ARRAY['In the garden','In the cafeteria','In the office','In the car park']::text[]), 'In the garden', 'The script directly says the lunch is now in the garden and explicitly rules out the cafeteria.'),
  ('listening', 'A1', 'mcq', 'general', 'You hear: "The company car has a small scratch on the door." What is wrong with the car?', to_jsonb(ARRAY['It has a scratch','It has a flat tyre','It is missing','The engine is broken']::text[]), 'It has a scratch', 'The script names a "scratch on the door," not a flat tyre, a missing car, or an engine problem.'),
  ('listening', 'A1', 'mcq', 'general', 'You hear: "A visitor is waiting at the front desk." Where is the visitor waiting?', to_jsonb(ARRAY['At the front desk','In the meeting room','In the car park','At the lift']::text[]), 'At the front desk', 'The script states the visitor is waiting "at the front desk."'),
  ('listening', 'A2', 'mcq', 'customer_service', 'You hear: "The client complained about the delay, so the call was transferred to the manager." Why was the call transferred to the manager?', to_jsonb(ARRAY['Because the client complained','Because the line was busy','Because the manager called first','Because the client cancelled the order']::text[]), 'Because the client complained', 'The script says the call was transferred because the client "complained about the delay."'),
  ('listening', 'A2', 'mcq', 'general', 'You hear: "The company will announce big news next Monday, but nobody knows what it is yet." When will the company make the announcement?', to_jsonb(ARRAY['Next Monday','Next Friday','Tomorrow','Next Tuesday']::text[]), 'Next Monday', 'The script gives the announcement date as "next Monday."'),
  ('listening', 'A2', 'mcq', 'negotiation', 'You hear: "The current price list expires on the 15th, so orders after that will cost more." What happens to orders placed after the 15th?', to_jsonb(ARRAY['They will cost more','They will be free','They will be cancelled','They will arrive late']::text[]), 'They will cost more', 'The script says orders placed after the 15th "will cost more," with no mention of being free, cancelled, or late.'),
  ('listening', 'A2', 'mcq', 'general', 'You hear: "Sarah is moving from Sales to Marketing next month." Which department is Sarah moving to?', to_jsonb(ARRAY['Marketing','Sales','Finance','IT']::text[]), 'Marketing', 'The script says Sarah is moving "to Marketing," and names Sales as the department she is leaving.'),
  ('listening', 'A2', 'mcq', 'meeting', 'You hear: "After his three-month probation, Tom passed his review and got a permanent contract." What did Tom get after his review?', to_jsonb(ARRAY['A permanent contract','A promotion','A pay cut','A new office']::text[]), 'A permanent contract', 'The script states Tom "got a permanent contract" after passing his review; no promotion, pay cut, or office change is mentioned.'),
  ('listening', 'A2', 'mcq', 'call', 'You hear: "The company credit card was blocked after two failed payments." Why was the credit card blocked?', to_jsonb(ARRAY['Because of two failed payments','Because it was lost','Because it expired','Because of one late payment']::text[]), 'Because of two failed payments', 'The script gives the exact reason as "two failed payments," not a lost card, expiry, or a single late payment.'),
  ('listening', 'A2', 'mcq', 'general', 'You hear: "The parts shipment is three days late, so production will start on Thursday instead of Monday." When will production now start?', to_jsonb(ARRAY['Thursday','Monday','Wednesday','Friday']::text[]), 'Thursday', 'The script says production will start on "Thursday instead of Monday," so Monday is explicitly ruled out.'),
  ('listening', 'B1', 'mcq', 'general', 'You hear: "James''s laptop was stolen from his car last night, but luckily he had backed up all his files that morning." What had James done before the laptop was stolen?', to_jsonb(ARRAY['He had backed up his files','He had reported it to the police','He had left the car unlocked','He had insured the laptop']::text[]), 'He had backed up his files', 'The script says he "had backed up all his files that morning," with no mention of the police, an unlocked car, or insurance.'),
  ('listening', 'B1', 'mcq', 'call', 'You hear: "The translated contract was supposed to arrive on Tuesday, but the translator emailed to say it will now come on Thursday." When will the translated contract now arrive?', to_jsonb(ARRAY['Thursday','Tuesday','Wednesday','Friday']::text[]), 'Thursday', 'The script says the contract "will now come on Thursday," replacing the original Tuesday date.'),
  ('listening', 'B1', 'mcq', 'general', 'You hear: "The lease has been signed by the landlord, but it still needs the tenant''s signature before it is valid." Whose signature is still missing?', to_jsonb(ARRAY['The tenant''s','The landlord''s','The lawyer''s','The manager''s']::text[]), 'The tenant''s', 'The script confirms the landlord already signed and says it "still needs the tenant''s signature."'),
  ('listening', 'B1', 'mcq', 'meeting', 'You hear: "The new hire''s start date was pushed back because her background check hasn''t come through yet." Why was the start date pushed back?', to_jsonb(ARRAY['Because the background check isn''t finished','Because she asked for more time','Because the office is full','Because of a public holiday']::text[]), 'Because the background check isn''t finished', 'The script gives the reason as the background check "hasn''t come through yet," not a personal request, space issue, or holiday.'),
  ('listening', 'B1', 'mcq', 'general', 'You hear: "My expense claim was rejected because I forgot to attach the receipt, so I have to resubmit it by Friday." Why was the expense claim rejected?', to_jsonb(ARRAY['The receipt was missing','The amount was too high','It was submitted late','It was the wrong form']::text[]), 'The receipt was missing', 'The script states the claim was rejected because the speaker "forgot to attach the receipt."'),
  ('listening', 'B1', 'mcq', 'general', 'You hear: "An employee slipped in the warehouse yesterday, and the incident report must be filed by end of day today." When must the incident report be filed?', to_jsonb(ARRAY['By the end of today','By the end of yesterday','By tomorrow','By next week']::text[]), 'By the end of today', 'The script says the report is due "by end of day today," while the accident itself happened yesterday.'),
  ('listening', 'B1', 'mcq', 'customer_service', 'You hear: "The phone lines will be down for maintenance this afternoon, so customers should email instead of calling." What should customers do instead of calling this afternoon?', to_jsonb(ARRAY['Email instead','Visit in person','Wait until tomorrow','Use the mobile app']::text[]), 'Email instead', 'The script instructs customers to "email instead of calling" during the maintenance window.'),
  ('listening', 'B2', 'mcq', 'negotiation', 'You hear: "The landlord offered a five-year lease renewal, but only if we commit before the end of the quarter, otherwise the rent goes up ten percent." What happens if the company doesn''t commit before the end of the quarter?', to_jsonb(ARRAY['The rent will increase by ten percent','The lease will be extended for free','The office will close','The landlord will lower the rent']::text[]), 'The rent will increase by ten percent', 'The script says that otherwise "the rent goes up ten percent," tying the increase directly to missing the deadline.'),
  ('listening', 'B2', 'mcq', 'customer_service', 'You hear: "The client''s payment bounced twice this week, so finance has put a hold on their account until the invoice is cleared." Why has finance put a hold on the client''s account?', to_jsonb(ARRAY['Because the payment bounced twice','Because the invoice was overpaid','Because the client cancelled the order','Because of a system error']::text[]), 'Because the payment bounced twice', 'The script states the hold followed the payment bouncing "twice this week," not overpayment, cancellation, or a system error.'),
  ('listening', 'B2', 'mcq', 'general', 'You hear: "The booth contractor is running two hours behind, so the banners won''t be up before the doors open, although the stand itself will be ready." What will NOT be ready before the doors open?', to_jsonb(ARRAY['The banners','The stand','The contractor','The doors']::text[]), 'The banners', 'The script explicitly says the banners "won''t be up before the doors open," while confirming the stand will be ready.'),
  ('listening', 'B2', 'mcq', 'meeting', 'You hear: "Priya was promoted to team lead, although the announcement won''t be made official until her replacement has been hired." Why hasn''t the promotion been announced officially yet?', to_jsonb(ARRAY['Because a replacement hasn''t been hired yet','Because Priya declined the role','Because HR rejected it','Because the budget wasn''t approved']::text[]), 'Because a replacement hasn''t been hired yet', 'The script says the announcement waits "until her replacement has been hired," not on Priya''s decision, HR, or budget.'),
  ('listening', 'B2', 'mcq', 'general', 'You hear: "HR sent a reminder that the whistleblower hotline is anonymous and available around the clock, though most staff still don''t know it exists." What did HR remind staff about?', to_jsonb(ARRAY['The whistleblower hotline','A new pay policy','The dress code','A training session']::text[]), 'The whistleblower hotline', 'The script says HR''s reminder was specifically about "the whistleblower hotline," not pay, dress code, or training.'),
  ('listening', 'B2', 'mcq', 'general', 'You hear: "The alarm went off this morning, but it turned out to be a false alarm caused by burnt toast in the kitchen, not an actual fire." What caused the alarm to go off?', to_jsonb(ARRAY['Burnt toast in the kitchen','An actual fire','A test drill','An electrical fault']::text[]), 'Burnt toast in the kitchen', 'The script names "burnt toast in the kitchen" as the cause and explicitly rules out an actual fire.'),
  ('listening', 'B2', 'mcq', 'meeting', 'You hear: "The client meeting was switched to video call after their flight got cancelled, although the agenda stays exactly the same." Why was the meeting switched to a video call?', to_jsonb(ARRAY['Because the client''s flight was cancelled','Because of a room booking conflict','Because the client requested it weeks ago','Because of a technical issue']::text[]), 'Because the client''s flight was cancelled', 'The script gives the cause as the client''s "flight got cancelled," not a room conflict, prior request, or technical issue.'),
  ('listening', 'C1', 'mcq', 'general', 'You hear: "I probably shouldn''t say too much, but there''s something big coming down the pipeline next week, and management''s been very tight-lipped about it." What does the speaker suggest about the upcoming announcement?', to_jsonb(ARRAY['Management is keeping it secret for now','The announcement has been cancelled','Everyone already knows the details','It was announced last week']::text[]), 'Management is keeping it secret for now', 'Calling management "tight-lipped" and saying "something big" is coming next week implies details are being withheld, not that it''s cancelled, known, or already happened.'),
  ('listening', 'C1', 'mcq', 'customer_service', 'You hear: "I hate to be the bearer of bad news, but the client''s gone over my head and asked to speak directly to the director." What has the client done?', to_jsonb(ARRAY['Asked to speak to the director directly','Cancelled the contract','Filed a formal complaint in writing','Asked for a refund']::text[]), 'Asked to speak to the director directly', '"Gone over my head and asked to speak directly to the director" states plainly what the client did, with no mention of cancelling, a written complaint, or a refund.'),
  ('listening', 'C1', 'mcq', 'negotiation', 'You hear: "Look, I''m not going to pretend the dent wasn''t there before you took it, but let''s not make a big deal out of it, just get it fixed and send me the receipt." What does the speaker ask the listener to do?', to_jsonb(ARRAY['Get the car fixed and send the receipt','Pay for the damage immediately','Report the incident to insurance','Return the car unfixed']::text[]), 'Get the car fixed and send the receipt', 'The speaker directly instructs "get it fixed and send me the receipt," not to pay immediately, involve insurance, or leave it unfixed.'),
  ('listening', 'C1', 'mcq', 'meeting', 'You hear: "Between you and me, the client wasn''t thrilled with the mock-up, so we''re scrapping it and starting the design over from scratch." What is happening to the design?', to_jsonb(ARRAY['It is being redone from the beginning','It has been approved with minor changes','It has been sent to a different client','It is being delayed by two weeks']::text[]), 'It is being redone from the beginning', '"Scrapping it and starting over from scratch" means the design is being redone from the beginning, not approved, reassigned, or merely delayed.'),
  ('listening', 'C1', 'mcq', 'general', 'You hear: "IT''s pulling an all-nighter to get the intranet back up, so fingers crossed it''s sorted before everyone logs on tomorrow." What is IT trying to do?', to_jsonb(ARRAY['Fix the intranet before tomorrow','Replace the intranet permanently','Shut down the intranet for good','Delay the fix until next week']::text[]), 'Fix the intranet before tomorrow', '"Pulling an all-nighter to get the intranet back up" before people "log on tomorrow" means IT is racing to fix it by then, not replace, permanently shut down, or delay it.'),
  ('listening', 'C1', 'mcq', 'meeting', 'You hear: "I don''t want to jump the gun, but word is the whole project''s on ice until legal gives it the green light." What does the speaker suggest about the project?', to_jsonb(ARRAY['It is paused pending legal approval','It has been cancelled for good','It has just been approved','It was never affected by legal review']::text[]), 'It is paused pending legal approval', '"On ice until legal gives it the green light" means paused pending approval, not cancelled for good, already approved, or unaffected.'),
  ('listening', 'C1', 'mcq', 'meeting', 'You hear: "We were caught a bit off guard when the HR manager called in sick, so the finance director''s stepping in at the eleventh hour." When is the finance director stepping in?', to_jsonb(ARRAY['At the last minute','Several weeks in advance','Next month','Before the HR manager called in sick']::text[]), 'At the last minute', '"Stepping in at the eleventh hour" means at the last minute, which contradicts stepping in weeks in advance, next month, or before the HR manager called in sick.'),
  ('listening', 'C2', 'mcq', 'general', 'You hear: "I''ll be honest, the figures aren''t as bad as the rumour mill would have you believe, but they''re not exactly rosy either, so let''s not sugar-coat it in the report." How does the speaker want the figures presented in the report?', to_jsonb(ARRAY['Honestly, without exaggeration in either direction','As better than they actually are','As worse than they actually are','Left out of the report entirely']::text[]), 'Honestly, without exaggeration in either direction', '"Not as bad as the rumour mill" but "not exactly rosy" and "let''s not sugar-coat it" together signal an honest, unembellished presentation, ruling out the other options.'),
  ('listening', 'C2', 'mcq', 'meeting', 'You hear: "I''m not here to point fingers, but the report was late because someone sat on the data for three days before passing it along." According to the speaker, why was the report late?', to_jsonb(ARRAY['Someone delayed passing on the data','The speaker refused to write the report','The deadline was moved without notice','The data was never received']::text[]), 'Someone delayed passing on the data', 'The script states someone "sat on the data for three days before passing it along," not that the speaker refused, the deadline moved, or data was never received.'),
  ('listening', 'C2', 'mcq', 'negotiation', 'You hear: "It''s not that Dan dropped the ball exactly, but the account''s been going nowhere for months, so it''s being handed over to someone with a fresh pair of eyes." Why is the account being reassigned?', to_jsonb(ARRAY['It hasn''t been progressing and needs a new approach','Dan requested to be removed from it','The client demanded a new account manager','The account has been closed entirely']::text[]), 'It hasn''t been progressing and needs a new approach', '"Going nowhere for months" and needing "a fresh pair of eyes" explains the reassignment, with no mention of Dan requesting it, client demand, or closure.'),
  ('listening', 'C2', 'mcq', 'meeting', 'You hear: "Finance hasn''t come out and banned new hires, but every request''s been sitting on someone''s desk for weeks, so read into that what you will." What does the speaker imply about hiring?', to_jsonb(ARRAY['New hires are effectively being blocked without an official announcement','Finance has approved all pending hiring requests','Hiring has been officially banned in writing','There is no delay in the hiring process']::text[]), 'New hires are effectively being blocked without an official announcement', 'Requests "sitting on someone''s desk for weeks" despite no official ban implies an unofficial block, ruling out approval, a formal ban, or no delay.'),
  ('listening', 'C2', 'mcq', 'general', 'You hear: "They''ve booked out the top-floor room for the whole afternoon and asked reception to hold all calls, which tells you this isn''t your average catch-up." What does the speaker imply about the meeting?', to_jsonb(ARRAY['The meeting is likely more serious than a routine catch-up','The meeting has been cancelled','The meeting is open to all staff','The meeting was scheduled weeks in advance']::text[]), 'The meeting is likely more serious than a routine catch-up', '"This isn''t your average catch-up," combined with holding all calls and booking the room all afternoon, implies unusual significance, not cancellation, openness, or advance scheduling.'),
  ('listening', 'C2', 'mcq', 'general', 'You hear: "She hasn''t handed in anything on paper yet, but she''s already cleared her desk, so make of that what you will." What does the speaker imply about the colleague?', to_jsonb(ARRAY['She is likely leaving even though nothing has been formalized','She has officially resigned in writing','She is just tidying her desk for spring cleaning','She has been promoted to a new desk']::text[]), 'She is likely leaving even though nothing has been formalized', 'Clearing her desk before submitting anything "on paper" implies she''s likely leaving informally, contradicting a formal resignation, spring cleaning, or a promotion.'),
  ('listening', 'C2', 'mcq', 'negotiation', 'You hear: "They''re not threatening to walk away outright, but every email''s got a bit more terse, and that''s usually a sign they''re not happy with where the numbers landed." What does the speaker infer from the supplier''s emails?', to_jsonb(ARRAY['The supplier is likely dissatisfied with the current terms','The supplier has confirmed they will end the contract','The supplier is fully satisfied with the deal','The emails show no change in tone']::text[]), 'The supplier is likely dissatisfied with the current terms', 'Terser emails as "a sign they''re not happy with where the numbers landed" implies dissatisfaction, not confirmed contract termination, satisfaction, or unchanged tone.');

-- Reading (18 passages, 54 mcq questions)
WITH passage4_0 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag) VALUES
    ('Lost Property Notice', 'Lost Property box is in the reception area. Last week, someone found a black umbrella, a blue water bottle, and a pair of glasses near the lift. If these items are yours, please ask Maria at reception. She works there from 9 am to 5 pm. Unclaimed items go to a charity shop after two weeks.', 'reading', 'A1', 'general')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('reading', 'A1', 'mcq', 'general', 'Where is the Lost Property box?', to_jsonb(ARRAY['In the reception area','Near the lift','In the charity shop','In the meeting room']::text[]), 'In the reception area', 'The passage says "Lost Property box is in the reception area."', (SELECT id FROM passage4_0)),
  ('reading', 'A1', 'mcq', 'general', 'Who should you ask about a lost item?', to_jsonb(ARRAY['Maria','The manager','Security','John']::text[]), 'Maria', 'The passage says to "please ask Maria at reception."', (SELECT id FROM passage4_0)),
  ('reading', 'A1', 'mcq', 'general', 'What happens to unclaimed items after two weeks?', to_jsonb(ARRAY['They go to a charity shop','They stay in the box','They are thrown away','They go back to reception']::text[]), 'They go to a charity shop', 'The passage states "Unclaimed items go to a charity shop after two weeks."', (SELECT id FROM passage4_0));

WITH passage4_1 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag) VALUES
    ('First-Aid Kit Locations', 'First-aid kits are now in three places. There is one in the kitchen, one near the lift on the second floor, and one at reception. Each kit has plasters, bandages, and pain tablets. If you use anything from a kit, please tell your manager.', 'reading', 'A1', 'general')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('reading', 'A1', 'mcq', 'general', 'How many first-aid kits are there?', to_jsonb(ARRAY['Three','Two','One','Four']::text[]), 'Three', 'The passage says "First-aid kits are now in three places."', (SELECT id FROM passage4_1)),
  ('reading', 'A1', 'mcq', 'general', 'On which floor is a kit located near the lift?', to_jsonb(ARRAY['The second floor','The first floor','The third floor','The ground floor']::text[]), 'The second floor', 'The passage says a kit is "near the lift on the second floor."', (SELECT id FROM passage4_1)),
  ('reading', 'A1', 'mcq', 'general', 'What should you do if you use something from a kit?', to_jsonb(ARRAY['Tell your manager','Call reception','Buy a new one','Do nothing']::text[]), 'Tell your manager', 'The passage says "please tell your manager" if you use anything from a kit.', (SELECT id FROM passage4_1));

WITH passage4_2 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag) VALUES
    ('10 Years Party!', 'Subject: 10 Years Party! Dear team, Our company is 10 years old this month! We will have a small party on Friday at 4 pm in the main office. There will be cake and drinks. Please come and celebrate with us. No need to bring anything. See you there! Best, Sam', 'reading', 'A1', 'email')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('reading', 'A1', 'mcq', 'email', 'How old is the company this month?', to_jsonb(ARRAY['10 years','5 years','20 years','1 year']::text[]), '10 years', 'The email says "Our company is 10 years old this month!"', (SELECT id FROM passage4_2)),
  ('reading', 'A1', 'mcq', 'email', 'When is the party?', to_jsonb(ARRAY['Friday at 4 pm','Monday at 4 pm','Friday at 9 am','Friday morning']::text[]), 'Friday at 4 pm', 'The email says the party is "on Friday at 4 pm."', (SELECT id FROM passage4_2)),
  ('reading', 'A1', 'mcq', 'email', 'Do employees need to bring anything?', to_jsonb(ARRAY['No, nothing','Yes, cake','Yes, drinks','Yes, a gift']::text[]), 'No, nothing', 'The email says "No need to bring anything."', (SELECT id FROM passage4_2));

WITH passage4_3 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag) VALUES
    ('Borrowing Office Equipment', 'Staff can now borrow office equipment for home use. This includes laptops, monitors, and headsets. To borrow an item, complete the loan form at reception and show your staff ID. Loans last for three months, but you can ask for one extra month if needed. All equipment must be returned in good condition. Lost or damaged items must be reported to IT immediately.', 'reading', 'A2', 'general')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('reading', 'A2', 'mcq', 'general', 'What must you show to borrow equipment?', to_jsonb(ARRAY['Your staff ID','Your passport','A manager''s signature','A receipt']::text[]), 'Your staff ID', 'The passage says to "show your staff ID" when borrowing an item.', (SELECT id FROM passage4_3)),
  ('reading', 'A2', 'mcq', 'general', 'How long do loans normally last?', to_jsonb(ARRAY['Three months','One month','Six months','One year']::text[]), 'Three months', 'The passage says "Loans last for three months."', (SELECT id FROM passage4_3)),
  ('reading', 'A2', 'mcq', 'general', 'What must you do if an item is damaged?', to_jsonb(ARRAY['Report it to IT immediately','Pay a fine','Return it early','Tell reception']::text[]), 'Report it to IT immediately', 'The passage says damaged items "must be reported to IT immediately," not to reception.', (SELECT id FROM passage4_3));

WITH passage4_4 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag) VALUES
    ('Important: Card Security Alert', 'Subject: Important: Card Security Alert. Dear staff, We recently found unusual charges on some company credit cards. If you have a company card, please check your last five transactions today. Report anything strange to Finance at finance@company.com. Do not use your card online until we send further instructions. We are sorry for the inconvenience and will update you soon. Thank you, Finance Team', 'reading', 'A2', 'email')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('reading', 'A2', 'mcq', 'email', 'What should cardholders check today?', to_jsonb(ARRAY['Their last five transactions','Their last ten transactions','Their card PIN','Their bank statement']::text[]), 'Their last five transactions', 'The email says to "check your last five transactions today."', (SELECT id FROM passage4_4)),
  ('reading', 'A2', 'mcq', 'email', 'Who should strange charges be reported to?', to_jsonb(ARRAY['Finance','IT','Their manager','Security']::text[]), 'Finance', 'The email says "Report anything strange to Finance."', (SELECT id FROM passage4_4)),
  ('reading', 'A2', 'mcq', 'email', 'What should staff avoid doing until further notice?', to_jsonb(ARRAY['Using the card online','Cancelling the card','Calling the bank','Using the card at all']::text[]), 'Using the card online', 'The email says "Do not use your card online until we send further instructions," not to stop using it entirely.', (SELECT id FROM passage4_4));

WITH passage4_5 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag) VALUES
    ('New Security Badges', 'From next Monday, the office will use new security badges. The old paper badges will stop working. New badges use a small chip and open doors automatically. You can collect your new badge from the security desk this week. Bring your old badge and a photo ID. The upgrade will make the building safer and entry quicker for everyone.', 'reading', 'A2', 'general')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('reading', 'A2', 'mcq', 'general', 'When do the old badges stop working?', to_jsonb(ARRAY['Next Monday','Next Friday','Today','Next month']::text[]), 'Next Monday', 'The passage says "From next Monday... the old paper badges will stop working."', (SELECT id FROM passage4_5)),
  ('reading', 'A2', 'mcq', 'general', 'What must you bring to collect a new badge?', to_jsonb(ARRAY['Old badge and photo ID','Just a photo ID','A manager''s approval','Payment']::text[]), 'Old badge and photo ID', 'The passage says to "Bring your old badge and a photo ID."', (SELECT id FROM passage4_5)),
  ('reading', 'A2', 'mcq', 'general', 'Why is the company upgrading the badges?', to_jsonb(ARRAY['To make entry safer and quicker','To save money','Because badges were lost','To reduce staff numbers']::text[]), 'To make entry safer and quicker', 'The passage says the upgrade "will make the building safer and entry quicker for everyone."', (SELECT id FROM passage4_5));

WITH passage4_6 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag) VALUES
    ('New Hybrid Working Policy', 'Starting next month, the company is introducing a hybrid working policy. Employees will be expected to work from the office at least three days a week, with Tuesday and Thursday fixed as core office days for the whole team. The other office day can be chosen freely, based on personal or team needs. Employees who wish to work from the office fewer than three days must get approval from their line manager. Desks will no longer be assigned to individuals; instead, staff will book a desk each morning using the new booking app. Managers will review how the policy is working after three months and may adjust the required number of office days.', 'reading', 'B1', 'general')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('reading', 'B1', 'mcq', 'general', 'What is the minimum number of office days per week?', to_jsonb(ARRAY['Three days','Two days','Four days','Five days']::text[]), 'Three days', 'The passage says employees "will be expected to work from the office at least three days a week."', (SELECT id FROM passage4_6)),
  ('reading', 'B1', 'mcq', 'general', 'Which days are fixed as core office days for the whole team?', to_jsonb(ARRAY['Tuesday and Thursday','Monday and Friday','Wednesday and Friday','Monday and Wednesday']::text[]), 'Tuesday and Thursday', 'The passage names "Tuesday and Thursday fixed as core office days for the whole team."', (SELECT id FROM passage4_6)),
  ('reading', 'B1', 'mcq', 'general', 'How will staff get a desk under the new system?', to_jsonb(ARRAY['By booking a desk each morning via the app','By keeping their assigned desk','By asking their manager each day','By arriving early to claim a desk']::text[]), 'By booking a desk each morning via the app', 'The passage says desks are no longer assigned and "staff will book a desk each morning using the new booking app."', (SELECT id FROM passage4_6));

WITH passage4_7 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag) VALUES
    ('Updated Parental Leave Policy', 'The company has updated its parental leave policy for all employees. Mothers are now entitled to 16 weeks of fully paid maternity leave, an increase from 12 weeks. Fathers and partners can take up to 4 weeks of paid paternity leave, which must be used within six months of the birth. Employees adopting a child receive the same leave as birth parents. All staff must inform HR at least eight weeks before their expected leave date so that cover can be arranged. Employees returning from leave may request flexible hours for their first three months back at work.', 'reading', 'B1', 'general')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('reading', 'B1', 'mcq', 'general', 'How many weeks of paid maternity leave are mothers now entitled to?', to_jsonb(ARRAY['16 weeks','12 weeks','4 weeks','20 weeks']::text[]), '16 weeks', 'The passage says mothers "are now entitled to 16 weeks of fully paid maternity leave."', (SELECT id FROM passage4_7)),
  ('reading', 'B1', 'mcq', 'general', 'Within what time must paternity leave be used?', to_jsonb(ARRAY['Six months of the birth','Three months of the birth','One year of the birth','Eight weeks of the birth']::text[]), 'Six months of the birth', 'The passage says paternity leave "must be used within six months of the birth."', (SELECT id FROM passage4_7)),
  ('reading', 'B1', 'mcq', 'general', 'How far in advance must staff inform HR of their leave date?', to_jsonb(ARRAY['At least eight weeks','At least four weeks','At least six months','At least two weeks']::text[]), 'At least eight weeks', 'The passage says staff "must inform HR at least eight weeks before their expected leave date."', (SELECT id FROM passage4_7));

WITH passage4_8 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag) VALUES
    ('Internal Transfer Process', 'Employees who want to move to a different department can now apply through the internal transfer process. First, discuss your interest with your current manager before applying, so they are not surprised later. Next, submit an internal transfer form to HR, along with an updated CV. Applications are reviewed once a month by a small panel. If successful, employees usually start in the new role within six weeks, though this can be longer for specialist positions. Employees must stay in their current role for at least one year before applying for another transfer.', 'reading', 'B1', 'general')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('reading', 'B1', 'mcq', 'general', 'What is the first step in the transfer process?', to_jsonb(ARRAY['Discuss it with their current manager','Submit a form to HR','Wait six weeks','Talk to the new department']::text[]), 'Discuss it with their current manager', 'The passage says "First, discuss your interest with your current manager before applying."', (SELECT id FROM passage4_8)),
  ('reading', 'B1', 'mcq', 'general', 'How often are applications reviewed?', to_jsonb(ARRAY['Once a month','Once a week','Once a year','Twice a month']::text[]), 'Once a month', 'The passage says "Applications are reviewed once a month by a small panel."', (SELECT id FROM passage4_8)),
  ('reading', 'B1', 'mcq', 'general', 'How long must employees wait before applying for another transfer?', to_jsonb(ARRAY['At least one year','At least six months','At least six weeks','There is no waiting period']::text[]), 'At least one year', 'The passage says employees "must stay in their current role for at least one year before applying for another transfer."', (SELECT id FROM passage4_8));

WITH passage4_9 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag) VALUES
    ('Choosing Your Health Insurance Plan', 'Subject: Choosing Your Health Insurance Plan for Next Year. Dear colleagues, Open enrolment for health insurance begins next week, and this year we are offering three plans instead of two. The Standard Plan keeps your current monthly premium and coverage unchanged. The Enhanced Plan costs an extra €25 per month but adds dental and vision coverage, along with a lower deductible. The Family Plan, available to those with dependants, costs more overall but covers a spouse and children under one policy rather than requiring separate enrolment for each. Employees who do not actively choose a plan by the deadline will automatically be kept on their current plan for another year. We strongly encourage everyone to compare the options carefully, as the Enhanced Plan may suit employees with ongoing dental or vision needs better than the Standard Plan. A comparison table is attached. Regards, Benefits Team', 'reading', 'B2', 'email')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('reading', 'B2', 'mcq', 'email', 'How many insurance plans are offered this year?', to_jsonb(ARRAY['Three','Two','Four','One']::text[]), 'Three', 'The email says "this year we are offering three plans instead of two."', (SELECT id FROM passage4_9)),
  ('reading', 'B2', 'mcq', 'email', 'What does the Enhanced Plan add compared to the Standard Plan?', to_jsonb(ARRAY['Dental and vision coverage','Only dental coverage','A higher premium only','Travel insurance']::text[]), 'Dental and vision coverage', 'The email says the Enhanced Plan "adds dental and vision coverage, along with a lower deductible."', (SELECT id FROM passage4_9)),
  ('reading', 'B2', 'mcq', 'email', 'What happens if an employee does not choose a plan by the deadline?', to_jsonb(ARRAY['They stay on their current plan','They lose coverage','They are enrolled in the Family Plan','They must pay a penalty']::text[]), 'They stay on their current plan', 'The email says such employees "will automatically be kept on their current plan for another year."', (SELECT id FROM passage4_9));

WITH passage4_10 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag) VALUES
    ('Introducing Our New Rewards Programme', 'Subject: Introducing Our New Rewards Programme. Dear valued customer, We are excited to launch our new loyalty programme, starting this Friday. For every €10 you spend, you will earn one point, and points can be redeemed for discounts on future purchases once you reach 50 points. Members also receive early access to sales events, 48 hours before they open to the public. Signing up is free and takes less than two minutes online. Existing customers will automatically receive credit for purchases made in the last three months once they register, so there is no need to worry about missing out on early points. Please note that points expire twelve months after they are earned if unused. We hope this programme rewards your continued loyalty. Warm regards, Customer Relations', 'reading', 'B2', 'customer_service')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('reading', 'B2', 'mcq', 'customer_service', 'How many points does a customer need before they can redeem a discount?', to_jsonb(ARRAY['50 points','10 points','100 points','25 points']::text[]), '50 points', 'The email says points "can be redeemed for discounts on future purchases once you reach 50 points."', (SELECT id FROM passage4_10)),
  ('reading', 'B2', 'mcq', 'customer_service', 'How much early access do members get before public sales events?', to_jsonb(ARRAY['48 hours','24 hours','One week','None, access is the same as the public']::text[]), '48 hours', 'The email says members receive early access "48 hours before they open to the public."', (SELECT id FROM passage4_10)),
  ('reading', 'B2', 'mcq', 'customer_service', 'What happens to unused points after twelve months?', to_jsonb(ARRAY['They expire','They double','They convert to cash','They are transferred to a friend']::text[]), 'They expire', 'The email says "points expire twelve months after they are earned if unused."', (SELECT id FROM passage4_10));

WITH passage4_11 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag) VALUES
    ('Open-Plan Office Noise Survey Results', 'Last month, the facilities team surveyed 200 employees about noise levels in the open-plan office. Sixty percent said phone calls from nearby colleagues were the most distracting noise, more than any other source mentioned, including printers and general conversation. Only 15 percent said they were rarely bothered by noise at all. In response, the company will install four soundproof phone booths on the third floor by the end of next month, and quiet zones will be introduced where phone calls are not permitted. Employees who need to make frequent calls will be encouraged to book a booth in advance through the facilities app. The survey also found that younger employees were more likely to use headphones to block out noise than employees who had worked at the company for over ten years. A follow-up survey is planned for six months after the changes are made.', 'reading', 'B2', 'general')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('reading', 'B2', 'mcq', 'general', 'What was the most common source of distracting noise?', to_jsonb(ARRAY['Phone calls from nearby colleagues','Printers','General conversation','Air conditioning noise']::text[]), 'Phone calls from nearby colleagues', 'The passage says "Sixty percent said phone calls from nearby colleagues were the most distracting noise."', (SELECT id FROM passage4_11)),
  ('reading', 'B2', 'mcq', 'general', 'How many phone booths will be installed?', to_jsonb(ARRAY['Four','Two','Six','Ten']::text[]), 'Four', 'The passage says the company "will install four soundproof phone booths."', (SELECT id FROM passage4_11)),
  ('reading', 'B2', 'mcq', 'general', 'Where will the phone booths be located?', to_jsonb(ARRAY['The third floor','The ground floor','Every floor','The second floor']::text[]), 'The third floor', 'The passage says the booths will be installed "on the third floor."', (SELECT id FROM passage4_11));

WITH passage4_12 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag) VALUES
    ('Supplier Onboarding Checklist', 'Supplier Onboarding Checklist: Before a new supplier can be added to our procurement system, several steps must be completed in sequence. First, the supplier must submit proof of insurance and, where applicable, relevant industry certifications; incomplete documentation is the most common cause of onboarding delays. Second, our finance team conducts a credit check, which typically takes three to five working days, though this can extend to two weeks for suppliers based overseas due to additional verification requirements. Third, a sample order is placed to assess quality and delivery reliability before any long-term contract is signed; this step is skipped only for suppliers already approved under a group-wide framework agreement. Finally, the supplier is issued a unique vendor code, which must be quoted on all future invoices. Departments are reminded that onboarding should begin at least six weeks before a supplier is expected to deliver its first order, since rushing the process increases the risk of contractual or compliance issues later on.', 'reading', 'C1', 'general')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('reading', 'C1', 'mcq', 'general', 'What is described as the most common cause of onboarding delays?', to_jsonb(ARRAY['Incomplete documentation','Slow credit checks','Late vendor codes','Poor sample quality']::text[]), 'Incomplete documentation', 'The passage states "incomplete documentation is the most common cause of onboarding delays."', (SELECT id FROM passage4_12)),
  ('reading', 'C1', 'mcq', 'general', 'When is the sample order step skipped?', to_jsonb(ARRAY['When the supplier is already approved under a group-wide framework agreement','When the supplier is based overseas','When the credit check is fast','It is never skipped']::text[]), 'When the supplier is already approved under a group-wide framework agreement', 'The passage says this step "is skipped only for suppliers already approved under a group-wide framework agreement."', (SELECT id FROM passage4_12)),
  ('reading', 'C1', 'mcq', 'general', 'How far in advance should onboarding begin before a supplier''s first delivery?', to_jsonb(ARRAY['At least six weeks','At least two weeks','At least three months','There is no recommended timeframe']::text[]), 'At least six weeks', 'The passage says onboarding "should begin at least six weeks before a supplier is expected to deliver its first order."', (SELECT id FROM passage4_12));

WITH passage4_13 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag) VALUES
    ('Invitation to Speak at Our Annual Industry Summit', 'Subject: Invitation to Speak at Our Annual Industry Summit. Dear Dr. Chen, On behalf of the organising committee, I would like to invite you to speak at this year''s Industry Summit, taking place on 14 November in Manchester. Given your recent published research on supply chain resilience, we believe your perspective would be particularly valuable to our audience of over 300 delegates, most of whom are senior operations professionals. We are proposing a 30-minute keynote, followed by a 15-minute question-and-answer session, though we are happy to adjust the format if you would prefer a panel discussion instead. Speakers receive complimentary accommodation for two nights and reimbursement of standard travel costs, though we regret that we are unable to offer a speaking fee this year due to budget constraints. Should you accept, we would need your presentation title and a short biography by 1 October at the latest, as the programme goes to print shortly afterwards. We very much hope you will consider joining us. Kind regards, Summit Organising Committee', 'reading', 'C1', 'email')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('reading', 'C1', 'mcq', 'email', 'Why was Dr. Chen specifically invited to speak?', to_jsonb(ARRAY['Her recent published research on supply chain resilience','Her role as committee chair','Her attendance last year','Her large social media following']::text[]), 'Her recent published research on supply chain resilience', 'The email says "Given your recent published research on supply chain resilience, we believe your perspective would be particularly valuable."', (SELECT id FROM passage4_13)),
  ('reading', 'C1', 'mcq', 'email', 'What will speakers NOT receive this year?', to_jsonb(ARRAY['A speaking fee','Accommodation','Travel cost reimbursement','An invitation to the summit']::text[]), 'A speaking fee', 'The email says "we are unable to offer a speaking fee this year due to budget constraints."', (SELECT id FROM passage4_13)),
  ('reading', 'C1', 'mcq', 'email', 'By when must the presentation title and biography be sent?', to_jsonb(ARRAY['1 October','14 November','Two nights before the summit','The day of the summit']::text[]), '1 October', 'The email says these are needed "by 1 October at the latest."', (SELECT id FROM passage4_13));

WITH passage4_14 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag) VALUES
    ('Our New Head Office', 'Subject: Our New Head Office. Dear colleagues, After eighteen months of planning, I am pleased to confirm that we will relocate to our new head office in the Riverside Business Park on 3 March. The new building offers considerably more collaborative space than our current site, including four dedicated project rooms and a rooftop terrace, though individual desk space will be slightly reduced compared to what many of you are used to. Parking on-site will be limited to 40 spaces, reserved primarily for those with mobility needs or long commutes from areas with poor public transport links; other staff are encouraged to use the new tram stop, a two-minute walk from the entrance. The IT team will migrate all systems over the final weekend of February, so please back up any local files before leaving the current office on Friday 27 February. A dedicated moving guide will be circulated next week with further details, including how to request a locker in the new building. Thank you for your patience during this transition. Best regards, Operations Director', 'reading', 'C1', 'email')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('reading', 'C1', 'mcq', 'email', 'When will the company move to the new office?', to_jsonb(ARRAY['3 March','27 February','Eighteen months from now','Next week']::text[]), '3 March', 'The email says "we will relocate to our new head office... on 3 March."', (SELECT id FROM passage4_14)),
  ('reading', 'C1', 'mcq', 'email', 'Who will on-site parking spaces primarily be reserved for?', to_jsonb(ARRAY['Staff with mobility needs or poor public transport access','Senior managers only','Staff who arrive earliest','All staff equally']::text[]), 'Staff with mobility needs or poor public transport access', 'The email says parking is "reserved primarily for those with mobility needs or long commutes from areas with poor public transport links."', (SELECT id FROM passage4_14)),
  ('reading', 'C1', 'mcq', 'email', 'By when should staff back up their local files?', to_jsonb(ARRAY['Before leaving the office on Friday 27 February','Before 3 March','After the move','By the end of March']::text[]), 'Before leaving the office on Friday 27 February', 'The email says to "back up any local files before leaving the current office on Friday 27 February."', (SELECT id FROM passage4_14));

WITH passage4_15 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag) VALUES
    ('Post-Incident Review: Intranet Outage', 'Post-Incident Review: Intranet Outage, 12 July. On the morning of 12 July, the company intranet became unavailable for approximately four hours, disrupting access to internal documents, the leave-booking system, and the staff directory. The root cause was traced to a failed software update applied overnight, which corrupted a configuration file on the primary server; a secondary server that should have taken over automatically failed to do so because of a misconfigured failover setting that had gone unnoticed since the servers were last upgraded. IT restored service by manually redirecting traffic to a backup server shortly before midday, though some users continued to experience intermittent errors for a further hour as caches refreshed. Notably, the incident revealed that our monitoring alerts, which are meant to notify the on-call engineer within minutes of an outage, had not been triggered at all; the fault was instead first reported by an employee in Finance. Going forward, the failover configuration will be tested quarterly rather than left unverified between upgrades, and monitoring alerts will be reviewed to close this gap. A fuller technical report will follow once the alerting issue has been diagnosed.', 'reading', 'C2', 'general')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('reading', 'C2', 'mcq', 'general', 'What was the root cause of the outage?', to_jsonb(ARRAY['A failed software update that corrupted a configuration file','A power cut at the data centre','A cyberattack','Scheduled maintenance that overran']::text[]), 'A failed software update that corrupted a configuration file', 'The report states "The root cause was traced to a failed software update applied overnight, which corrupted a configuration file."', (SELECT id FROM passage4_15)),
  ('reading', 'C2', 'mcq', 'general', 'How was the outage first identified?', to_jsonb(ARRAY['It was reported by an employee in Finance','It was flagged automatically by monitoring alerts','The on-call engineer noticed it immediately','A customer complained']::text[]), 'It was reported by an employee in Finance', 'The report says the monitoring alerts "had not been triggered at all; the fault was instead first reported by an employee in Finance."', (SELECT id FROM passage4_15)),
  ('reading', 'C2', 'mcq', 'general', 'What change will now happen quarterly?', to_jsonb(ARRAY['Testing of the failover configuration','Replacement of the primary server','Staff training on outages','Review of the leave-booking system']::text[]), 'Testing of the failover configuration', 'The report says "the failover configuration will be tested quarterly rather than left unverified between upgrades."', (SELECT id FROM passage4_15));

WITH passage4_16 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag) VALUES
    ('Case Study: How Bramwell Logistics Cut Delivery Delays', 'Case Study: How Bramwell Logistics Cut Delivery Delays by 30 Percent. When Bramwell Logistics first approached us, their central challenge was not a lack of data but an inability to act on it: dispatch decisions were still being made manually each morning based on the previous day''s figures, leaving little room to respond to real-time disruptions such as traffic or weather. Within the first three months of implementing our routing platform, Bramwell''s average delivery delay fell by 30 percent, a result the company''s operations director attributes less to the software''s routing algorithm itself than to the shift in decision-making culture it enabled, since dispatchers could finally intervene during the day rather than only planning the night before. Interestingly, the most resistant team during rollout was not, as expected, the longest-serving dispatchers, but a group of newer hires who had been trained entirely on the old manual system and had no prior exposure to automated tools. Full adoption took five months rather than the ten weeks originally projected, largely because of this unexpected training gap. Bramwell has since extended the platform to two additional regional depots.', 'reading', 'C2', 'customer_service')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('reading', 'C2', 'mcq', 'customer_service', 'By how much did Bramwell''s average delivery delay fall?', to_jsonb(ARRAY['30 percent','10 percent','50 percent','3 percent']::text[]), '30 percent', 'The case study title and text state delivery delay "fell by 30 percent."', (SELECT id FROM passage4_16)),
  ('reading', 'C2', 'mcq', 'customer_service', 'According to the operations director, what mainly drove the improvement?', to_jsonb(ARRAY['The shift in decision-making culture','The routing algorithm alone','A reduction in staff','Lower fuel costs']::text[]), 'The shift in decision-making culture', 'The text says the director attributes the result "less to the software''s routing algorithm itself than to the shift in decision-making culture it enabled."', (SELECT id FROM passage4_16)),
  ('reading', 'C2', 'mcq', 'customer_service', 'Which group was most resistant during rollout?', to_jsonb(ARRAY['Newer hires trained only on the old manual system','The longest-serving dispatchers','Senior management','Drivers']::text[]), 'Newer hires trained only on the old manual system', 'The text says the most resistant team was "not... the longest-serving dispatchers, but a group of newer hires who had been trained entirely on the old manual system."', (SELECT id FROM passage4_16));

WITH passage4_17 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag) VALUES
    ('Extract from Our First Sustainability Report', 'Extract from Our First Sustainability Report. This year marks the publication of our first formal sustainability report, and we have chosen to be candid about where our progress has fallen short of our ambitions as well as where it has exceeded them. Our carbon emissions per employee fell by 18 percent, comfortably surpassing the 10 percent target we set two years ago, largely due to the switch to renewable electricity at our two largest sites. However, our target to eliminate single-use plastics from office kitchens by this year was not met; roughly a third of sites still use plastic cutlery, mainly because suitable compostable alternatives were not available from our supplier in time. We have also, for the first time, begun measuring emissions from staff commuting, which account for a larger share of our footprint than we had assumed, and this will now become a formal target area next year. We recognise that a report of this kind carries little value if it simply restates good news, and we would rather set out an honest baseline now than present a more flattering picture that later proves difficult to sustain.', 'reading', 'C2', 'general')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('reading', 'C2', 'mcq', 'general', 'By how much did carbon emissions per employee fall?', to_jsonb(ARRAY['18 percent','10 percent','30 percent','8 percent']::text[]), '18 percent', 'The report says "Our carbon emissions per employee fell by 18 percent."', (SELECT id FROM passage4_17)),
  ('reading', 'C2', 'mcq', 'general', 'Why was the single-use plastics target missed?', to_jsonb(ARRAY['Suitable compostable alternatives were not available from the supplier in time','Staff refused to change','It was too expensive','It was not a priority for the company']::text[]), 'Suitable compostable alternatives were not available from the supplier in time', 'The report says this was "mainly because suitable compostable alternatives were not available from our supplier in time."', (SELECT id FROM passage4_17)),
  ('reading', 'C2', 'mcq', 'general', 'What did the report find about staff commuting emissions?', to_jsonb(ARRAY['They account for a larger share of the footprint than assumed','They account for a smaller share of the footprint than assumed','They were not measured','They fell by 18 percent']::text[]), 'They account for a larger share of the footprint than assumed', 'The report says commuting emissions "account for a larger share of our footprint than we had assumed."', (SELECT id FROM passage4_17));
