-- Phase 2 content round: text-reconstruction items across all 6
-- grammar_vocab sub-topics, 1 per CEFR level per sub-topic (36 total).
-- options = chunks in canonical order (scrambled client-side at render
-- time); correct_answer = the canonical joined sentence, used for
-- exact-match grading against the learner's assembled chunk order.

INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation) VALUES
  ('grammar_vocab', 'A1', 'reconstruction', 'tenses', 'Put the words in the correct order.', to_jsonb(ARRAY['He','checks','his emails','every morning.']::text[]), 'He checks his emails every morning.', 'Simple present tense (''checks'') describes a habitual action, and the time marker ''every morning'' goes at the end, following the fixed Subject-Verb-Object-Time word order.'),
  ('grammar_vocab', 'A2', 'reconstruction', 'tenses', 'Put the words in the correct order.', to_jsonb(ARRAY['We','are going to meet','the client','tomorrow.']::text[]), 'We are going to meet the client tomorrow.', '''Be going to'' + base verb expresses a planned future action (''are going to meet''), with the time expression ''tomorrow'' placed at the end of the sentence.'),
  ('grammar_vocab', 'B1', 'reconstruction', 'tenses', 'Put the words in the correct order.', to_jsonb(ARRAY['After','she finishes the training,','she will start','her new role.']::text[]), 'After she finishes the training, she will start her new role.', 'In a future time clause with ''after'', the verb stays in the present simple (''finishes'') even though it refers to the future, while the main clause uses ''will'' + base verb (''will start'') for the resulting future action.'),
  ('grammar_vocab', 'B2', 'reconstruction', 'tenses', 'Put the words in the correct order.', to_jsonb(ARRAY['She was reviewing','the budget report','when','her manager','suddenly walked','into the office.']::text[]), 'She was reviewing the budget report when her manager suddenly walked into the office.', 'The past continuous (''was reviewing'') sets the background action in progress, and ''when'' introduces the shorter simple past action (''walked'') that interrupts it.'),
  ('grammar_vocab', 'C1', 'reconstruction', 'tenses', 'Put the words in the correct order.', to_jsonb(ARRAY['She','had been managing','the account','for two years','when she was offered','a promotion.']::text[]), 'She had been managing the account for two years when she was offered a promotion.', 'The past perfect continuous (''had been managing'') stresses the duration of an ongoing past action (''for two years'') that was happening before another past event (''was offered''), introduced by ''when''.'),
  ('grammar_vocab', 'C2', 'reconstruction', 'tenses', 'Put the words in the correct order.', to_jsonb(ARRAY['Were the audit','to reveal any discrepancies','before the deadline,','the board','would immediately launch','a full investigation.']::text[]), 'Were the audit to reveal any discrepancies before the deadline, the board would immediately launch a full investigation.', '''Were...to'' inversion is a formal alternative to ''If the audit were to reveal...'', typical of C2 register; the main clause uses ''would'' + adverb + base verb (''would immediately launch'') for the hypothetical result.'),
  ('grammar_vocab', 'A1', 'reconstruction', 'prepositions', 'Put the words in the correct order.', to_jsonb(ARRAY['The train','leaves','at six o''clock.']::text[]), 'The train leaves at six o''clock.', 'We use "at" with clock times to say exactly when something happens: "at six o''clock."'),
  ('grammar_vocab', 'A2', 'reconstruction', 'prepositions', 'Put the words in the correct order.', to_jsonb(ARRAY['My colleague','travels by bicycle','every day.']::text[]), 'My colleague travels by bicycle every day.', '"By" is used before a means of transport with no article: "by bicycle" (like "by bus" or "by train").'),
  ('grammar_vocab', 'B1', 'reconstruction', 'prepositions', 'Put the words in the correct order.', to_jsonb(ARRAY['Our manager','seems worried about','the deadline.']::text[]), 'Our manager seems worried about the deadline.', 'The adjective "worried" is always followed by "about" when it introduces the cause of the worry.'),
  ('grammar_vocab', 'B2', 'reconstruction', 'prepositions', 'Put the words in the correct order.', to_jsonb(ARRAY['The board','will vote on','the merger','next week.']::text[]), 'The board will vote on the merger next week.', 'The fixed business collocation is "vote on" something (a proposal, a merger), not "vote for" or "vote about".'),
  ('grammar_vocab', 'C1', 'reconstruction', 'prepositions', 'Put the words in the correct order.', to_jsonb(ARRAY['The proposal','was drafted','in consultation with','all department heads.']::text[]), 'The proposal was drafted in consultation with all department heads.', '"In consultation with" is a fixed formal expression meaning "while discussing it with"; the three words always stay together in this order.'),
  ('grammar_vocab', 'C2', 'reconstruction', 'prepositions', 'Put the words in the correct order.', to_jsonb(ARRAY['Sales rose','sharply','on the back of','a successful marketing campaign.']::text[]), 'Sales rose sharply on the back of a successful marketing campaign.', '"On the back of" is an idiomatic fixed expression meaning "as a direct result of"; it functions as a single unit and cannot be split or reordered.'),
  ('grammar_vocab', 'A1', 'reconstruction', 'business_vocab', 'Put the words in the correct order.', to_jsonb(ARRAY['The customer','wants to speak','to the manager.']::text[]), 'The customer wants to speak to the manager.', 'A ''customer'' is a person who buys goods or services from a business. The sentence follows the fixed pattern subject + verb phrase + ''to'' + person, so ''to the manager'' must stay at the end, right after ''wants to speak''.'),
  ('grammar_vocab', 'A2', 'reconstruction', 'business_vocab', 'Put the words in the correct order.', to_jsonb(ARRAY['The delivery','contained','fifty printer cartridges.']::text[]), 'The delivery contained fifty printer cartridges.', 'A ''delivery'' is a shipment of goods sent to a workplace. The sentence is a simple subject + verb + object sentence, so ''fifty printer cartridges'' (the thing delivered) must come directly after the verb ''contained'' as its object.'),
  ('grammar_vocab', 'B1', 'reconstruction', 'business_vocab', 'Put the words in the correct order.', to_jsonb(ARRAY['The company','advertised','a vacancy','for a sales assistant.']::text[]), 'The company advertised a vacancy for a sales assistant.', 'A ''vacancy'' is an open job position that needs to be filled. ''For a sales assistant'' describes exactly which vacancy, so it must stay attached right after ''a vacancy'' — it cannot be moved elsewhere in the sentence.'),
  ('grammar_vocab', 'B2', 'reconstruction', 'business_vocab', 'Put the words in the correct order.', to_jsonb(ARRAY['The tech giant','announced','the acquisition','of a rival.']::text[]), 'The tech giant announced the acquisition of a rival.', 'An ''acquisition'' is when one company buys and takes control of another. ''Of a rival'' identifies what was acquired, so it must directly follow ''the acquisition'' — the two form a single unit that cannot be split apart.'),
  ('grammar_vocab', 'C1', 'reconstruction', 'business_vocab', 'Put the words in the correct order.', to_jsonb(ARRAY['The account','manager','will liaise closely','with the client.']::text[]), 'The account manager will liaise closely with the client.', 'To ''liaise'' (with someone) means to communicate and cooperate regularly with them to coordinate work. ''Liaise'' always requires the preposition ''with'', so ''with the client'' must immediately follow ''will liaise closely''.'),
  ('grammar_vocab', 'C2', 'reconstruction', 'business_vocab', 'Put the words in the correct order.', to_jsonb(ARRAY['The hedge','fund','profited from','currency arbitrage.']::text[]), 'The hedge fund profited from currency arbitrage.', '''Arbitrage'' is the practice of profiting from price differences for the same asset in different markets. ''Profited from'' requires an object, so ''currency arbitrage'' must follow it directly, completing the subject-verb-object spine of the sentence.'),
  ('grammar_vocab', 'A1', 'reconstruction', 'phrasal_verbs', 'Put the words in the correct order.', to_jsonb(ARRAY['He','will come back','from lunch','soon.']::text[]), 'He will come back from lunch soon.', 'The phrasal verb ''come back'' (return) stays together as one unit. Subject comes first, then the verb phrase, then the place (''from lunch''), with the time word ''soon'' at the very end. Using the pronoun ''He'' (rather than a noun like ''the manager'') blocks ''from lunch'' from being misread as a modifier of the subject, since pronouns can''t take that kind of postmodifying phrase.'),
  ('grammar_vocab', 'A2', 'reconstruction', 'phrasal_verbs', 'Put the words in the correct order.', to_jsonb(ARRAY['Please','fill in','this form','before your interview.']::text[]), 'Please fill in this form before your interview.', 'This is a polite imperative: ''Please'' starts the request, followed by the phrasal verb ''fill in'' (complete a document), its object ''this form'', and the time clause ''before your interview'' at the end.'),
  ('grammar_vocab', 'B1', 'reconstruction', 'phrasal_verbs', 'Put the words in the correct order.', to_jsonb(ARRAY['She promised','to get back to','the client','this afternoon.']::text[]), 'She promised to get back to the client this afternoon.', '''Get back to'' (reply/contact again) is a fixed prepositional phrasal verb, so it must be followed immediately by its object ''the client''; the time expression ''this afternoon'' naturally closes the sentence.'),
  ('grammar_vocab', 'B2', 'reconstruction', 'phrasal_verbs', 'Put the words in the correct order.', to_jsonb(ARRAY['The board decided','to bring forward','the meeting','to Thursday.']::text[]), 'The board decided to bring forward the meeting to Thursday.', '''Bring forward'' (move to an earlier time) is kept whole; because the object ''the meeting'' is a full noun phrase, it follows the complete phrasal verb, and the new date ''to Thursday'' ends the sentence.'),
  ('grammar_vocab', 'C1', 'reconstruction', 'phrasal_verbs', 'Put the words in the correct order.', to_jsonb(ARRAY['The board needs','to weigh up','the risks','before approving the investment.']::text[]), 'The board needs to weigh up the risks before approving the investment.', '''Weigh up'' (consider carefully) stays together, followed by its object ''the risks''; the reason clause ''before approving the investment'' must come last since it depends on the whole preceding clause.'),
  ('grammar_vocab', 'C2', 'reconstruction', 'phrasal_verbs', 'Put the words in the correct order.', to_jsonb(ARRAY['The consultant advised','the team','not to dwell on','past mistakes.']::text[]), 'The consultant advised the team not to dwell on past mistakes.', '''Advise'' takes a direct object (''the team'') before its infinitive complement; the idiomatic phrasal verb ''dwell on'' (think too much about) stays intact and is immediately followed by its object ''past mistakes''.'),
  ('grammar_vocab', 'A1', 'reconstruction', 'formal_register', 'Put the words in the correct order.', to_jsonb(ARRAY['Could you please','confirm','receipt','of this email?']::text[]), 'Could you please confirm receipt of this email?', 'This is a polite, formal question using the fixed pattern ''Could you please + verb...?'' for workplace requests. The modal phrase ''Could you please'' must open the question, and ''of this email'' stays locked to ''receipt'' as one noun phrase, so no other word order is grammatically correct.'),
  ('grammar_vocab', 'A2', 'reconstruction', 'formal_register', 'Put the words in the correct order.', to_jsonb(ARRAY['I look forward','to hearing','from you.']::text[]), 'I look forward to hearing from you.', 'This is a standard fixed formula used to close formal business emails politely. ''Look forward to'' must be followed by the gerund ''hearing'', and ''from you'' completes it, so this fixed expression has only one possible order.'),
  ('grammar_vocab', 'B1', 'reconstruction', 'formal_register', 'Put the words in the correct order.', to_jsonb(ARRAY['We must insist','on immediate payment','of this invoice.']::text[]), 'We must insist on immediate payment of this invoice.', '''Insist on'' is a formal fixed verb pattern for firm business requests, and ''of this invoice'' is locked to ''payment'' as a single noun phrase, so it cannot be moved elsewhere in the sentence.'),
  ('grammar_vocab', 'B2', 'reconstruction', 'formal_register', 'Put the words in the correct order.', to_jsonb(ARRAY['Unfortunately, we','are unable','to accommodate','your request.']::text[]), 'Unfortunately, we are unable to accommodate your request.', 'This is a polite, formal way to decline a request in business correspondence. ''Unfortunately'' is fused to the subject and modal verb as a single fixed opening block, and ''unable to accommodate'' is a set formal verb pattern that must be followed directly by its object ''your request'', so no other word order produces a grammatical sentence.'),
  ('grammar_vocab', 'C1', 'reconstruction', 'formal_register', 'Put the words in the correct order.', to_jsonb(ARRAY['Please find','enclosed','a copy','of the invoice.']::text[]), 'Please find enclosed a copy of the invoice.', '''Please find enclosed'' is a fixed formal business email formula used when including a document. ''Of the invoice'' belongs to the noun phrase ''a copy of the invoice'' and cannot be separated or repositioned.'),
  ('grammar_vocab', 'C2', 'reconstruction', 'formal_register', 'Put the words in the correct order.', to_jsonb(ARRAY['We regret','to inform you','that the position','has been filled.']::text[]), 'We regret to inform you that the position has been filled.', 'This is a diplomatic, formal way to deliver unwelcome news in business correspondence. ''We regret to inform you'' is a fixed formal opener, followed by the fixed complement clause ''that the position has been filled'', giving only one natural word order.'),
  ('grammar_vocab', 'A1', 'reconstruction', 'collocations', 'Put the words in the correct order.', to_jsonb(ARRAY['You can','ask a question','during the training.']::text[]), 'You can ask a question during the training.', '''Ask a question'' is a fixed verb+noun collocation. The subject and modal ''You can'' must open the sentence, and the time phrase ''during the training'' closes it, so only one order is grammatical.'),
  ('grammar_vocab', 'A2', 'reconstruction', 'collocations', 'Put the words in the correct order.', to_jsonb(ARRAY['Can you','make a copy','of this document','for me?']::text[]), 'Can you make a copy of this document for me?', '''Make a copy'' is a common workplace collocation. The question word order requires the modal ''Can you'' first, followed by the verb phrase, then the object and beneficiary phrase ''of this document for me?''.'),
  ('grammar_vocab', 'B1', 'reconstruction', 'collocations', 'Put the words in the correct order.', to_jsonb(ARRAY['The company needs','to renew a contract','before the end','of the month.']::text[]), 'The company needs to renew a contract before the end of the month.', '''Renew a contract'' is a business collocation. ''Needs'' takes the infinitive ''to renew a contract'', and the deadline phrase ''before the end of the month'' naturally follows at the end.'),
  ('grammar_vocab', 'B2', 'reconstruction', 'collocations', 'Put the words in the correct order.', to_jsonb(ARRAY['The new','product','exceeded all expectations','within the first month.']::text[]), 'The new product exceeded all expectations within the first month.', '''Exceed expectations'' is a business collocation meaning to perform better than hoped. The subject leads, the verb phrase follows, and the time frame ''within the first month'' closes the sentence.'),
  ('grammar_vocab', 'C1', 'reconstruction', 'collocations', 'Put the words in the correct order.', to_jsonb(ARRAY['Cybersecurity breaches','pose a serious threat','to client','confidentiality.']::text[]), 'Cybersecurity breaches pose a serious threat to client confidentiality.', '''Pose a threat'' is a formal collocation used to describe a risk or danger. The subject ''Cybersecurity breaches'' opens the sentence, and the prepositional phrase ''to client confidentiality'' specifies what is threatened.'),
  ('grammar_vocab', 'C2', 'reconstruction', 'collocations', 'Put the words in the correct order.', to_jsonb(ARRAY['Shareholders were left','to foot the bill','after the failed','merger negotiations.']::text[]), 'Shareholders were left to foot the bill after the failed merger negotiations.', '''Foot the bill'' is an idiomatic collocation meaning to pay for something, often reluctantly. ''Were left to foot the bill'' is the fixed passive construction, followed by the reason clause ''after the failed merger negotiations''.');
