-- Phase 3 content round: word-bank passages, 3 per CEFR level (18 total),
-- ~108 blanks. One shared word pool per passage (blank answers + 3
-- distractors); questions.ordinal maps each {{n}} token in the passage
-- body back to its row. Pool order is independently shuffled per passage
-- (not authored in answer order) as defense in depth on top of the
-- client-side shuffle() applied at render time.

WITH wb_passage_0 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag, word_bank)
    VALUES ('A Busy Day at the Office', 'Every day, Anna {{1}} to work at eight o''clock. Yesterday, she {{2}} to work early for a meeting. Right now, she is {{3}} her email. Tomorrow, she will {{4}} a report.', 'grammar_vocab', 'A1', 'tenses', to_jsonb(ARRAY['went','go','write','checks','goes','checking','written']::text[]))
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, correct_answer, explanation, passage_id, ordinal) VALUES
  ('grammar_vocab', 'A1', 'word_bank', 'tenses', 'Blank 1 of A Busy Day at the Office', 'goes', 'Present simple with the -s ending is used with ''every day'' to describe a daily habit with the third-person singular subject ''Anna''.', (SELECT id FROM wb_passage_0), 1),
  ('grammar_vocab', 'A1', 'word_bank', 'tenses', 'Blank 2 of A Busy Day at the Office', 'went', 'Past simple form of ''go'' is needed because ''Yesterday'' signals a completed action in the past.', (SELECT id FROM wb_passage_0), 2),
  ('grammar_vocab', 'A1', 'word_bank', 'tenses', 'Blank 3 of A Busy Day at the Office', 'checking', 'After ''is'' and with ''Right now'' pointing to an action in progress, the present continuous form (verb + -ing) is required.', (SELECT id FROM wb_passage_0), 3),
  ('grammar_vocab', 'A1', 'word_bank', 'tenses', 'Blank 4 of A Busy Day at the Office', 'write', 'After the modal ''will'', the verb stays in its base form, used here for a future action signaled by ''Tomorrow''.', (SELECT id FROM wb_passage_0), 4);

WITH wb_passage_1 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag, word_bank)
    VALUES ('At the Shop', 'Tom always keeps the shop''s spare keys {{1}} a small locked box behind the counter. He starts work {{2}} nine o''clock every morning. He writes today''s specials {{3}} a small whiteboard by the door. Customers can pay {{4}} a credit card.', 'grammar_vocab', 'A1', 'prepositions', to_jsonb(ARRAY['with','into','in','under','at','on','of']::text[]))
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, correct_answer, explanation, passage_id, ordinal) VALUES
  ('grammar_vocab', 'A1', 'word_bank', 'prepositions', 'Blank 1 of At the Shop', 'in', 'The preposition ''in'' shows physical containment inside an enclosed object, like a locked box; ''at a locked box'' is ungrammatical, unlike the workplace sense of ''at'' used elsewhere.', (SELECT id FROM wb_passage_1), 1),
  ('grammar_vocab', 'A1', 'word_bank', 'prepositions', 'Blank 2 of At the Shop', 'at', 'The preposition ''at'' is the fixed choice before a clock time, such as ''at nine o''clock''.', (SELECT id FROM wb_passage_1), 2),
  ('grammar_vocab', 'A1', 'word_bank', 'prepositions', 'Blank 3 of At the Shop', 'on', 'Written content appears ''on'' a surface like a whiteboard; a person''s own position while writing might use ''at'', but where the specials themselves end up requires ''on''.', (SELECT id FROM wb_passage_1), 3),
  ('grammar_vocab', 'A1', 'word_bank', 'prepositions', 'Blank 4 of At the Shop', 'with', 'The preposition ''with'' shows the means of payment, as in the fixed phrase ''pay with a credit card''.', (SELECT id FROM wb_passage_1), 4);

WITH wb_passage_2 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag, word_bank)
    VALUES ('A Job Interview', 'Maria has a job {{1}} tomorrow morning. She wants to work for a big {{2}} with offices in many countries. The job pays a good {{3}} of 2,500 euros every month. Her new {{4}} is very kind and helpful.', 'grammar_vocab', 'A1', 'business_vocab', to_jsonb(ARRAY['company','weather','shoe','interview','weekend','salary','manager']::text[]))
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, correct_answer, explanation, passage_id, ordinal) VALUES
  ('grammar_vocab', 'A1', 'word_bank', 'business_vocab', 'Blank 1 of A Job Interview', 'interview', 'An ''interview'' is the meeting where an employer asks a candidate questions before deciding to hire them.', (SELECT id FROM wb_passage_2), 1),
  ('grammar_vocab', 'A1', 'word_bank', 'business_vocab', 'Blank 2 of A Job Interview', 'company', 'A ''company'' is a business organization that can have ''offices in many countries'', matching ''work for a big ___''.', (SELECT id FROM wb_passage_2), 2),
  ('grammar_vocab', 'A1', 'word_bank', 'business_vocab', 'Blank 3 of A Job Interview', 'salary', 'A ''salary'' is the regular money paid for a job, matching the phrase ''a good ___ of 2,500 euros every month''.', (SELECT id FROM wb_passage_2), 3),
  ('grammar_vocab', 'A1', 'word_bank', 'business_vocab', 'Blank 4 of A Job Interview', 'manager', 'A ''manager'' is the person who leads employees at work, fitting the description ''kind and helpful'' toward Maria.', (SELECT id FROM wb_passage_2), 4);

WITH wb_passage_3 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag, word_bank)
    VALUES ('The Delivery Schedule', 'The new boxes are going to arrive {{1}} Monday morning. Please put them {{2}} the storage room, next to the shelves. The driver usually arrives {{3}} 9 and 10 o''clock. If you are not {{4}} your desk, call Sam and he will sign for the delivery.', 'grammar_vocab', 'A2', 'prepositions', to_jsonb(ARRAY['at','to','on','under','in','between','since']::text[]))
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, correct_answer, explanation, passage_id, ordinal) VALUES
  ('grammar_vocab', 'A2', 'word_bank', 'prepositions', 'Blank 1 of The Delivery Schedule', 'on', 'We use "on" with specific days, so "on Monday morning" is correct.', (SELECT id FROM wb_passage_3), 1),
  ('grammar_vocab', 'A2', 'word_bank', 'prepositions', 'Blank 2 of The Delivery Schedule', 'in', '"In" shows position inside an enclosed space, like a room, so the boxes go "in the storage room".', (SELECT id FROM wb_passage_3), 2),
  ('grammar_vocab', 'A2', 'word_bank', 'prepositions', 'Blank 3 of The Delivery Schedule', 'between', '"Between" is used with two times or points to show a range, matching "9 and 10 o''clock".', (SELECT id FROM wb_passage_3), 3),
  ('grammar_vocab', 'A2', 'word_bank', 'prepositions', 'Blank 4 of The Delivery Schedule', 'at', '"At" is used for a specific point/place a person can be, so we say someone is "at your desk" (not, for example, "in your desk", which would mean physically inside it).', (SELECT id FROM wb_passage_3), 4);

WITH wb_passage_4 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag, word_bank)
    VALUES ('A New Task at Work', 'Our {{1}} wants the sales numbers by Friday. She sent an email about the new {{2}} — everyone must meet it by Friday. I need to finish writing my {{3}} before lunch. Then we have a short {{4}} to talk about the next steps.', 'grammar_vocab', 'A2', 'business_vocab', to_jsonb(ARRAY['kitchen','elevator','deadline','printer','manager','meeting','report']::text[]))
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, correct_answer, explanation, passage_id, ordinal) VALUES
  ('grammar_vocab', 'A2', 'word_bank', 'business_vocab', 'Blank 1 of A New Task at Work', 'manager', 'The person who asks for the sales numbers and gives instructions is the "manager", the boss in the office.', (SELECT id FROM wb_passage_4), 1),
  ('grammar_vocab', 'A2', 'word_bank', 'business_vocab', 'Blank 2 of A New Task at Work', 'deadline', '"Deadline" means the date by which something must be finished — you "meet a deadline", which fits "everyone must meet it by Friday".', (SELECT id FROM wb_passage_4), 2),
  ('grammar_vocab', 'A2', 'word_bank', 'business_vocab', 'Blank 3 of A New Task at Work', 'report', 'A "report" is a document with information (like sales numbers) that you write — "finish writing my report" fits, unlike the other pool words.', (SELECT id FROM wb_passage_4), 3),
  ('grammar_vocab', 'A2', 'word_bank', 'business_vocab', 'Blank 4 of A New Task at Work', 'meeting', 'A short event where people "talk about the next steps" is called a "meeting".', (SELECT id FROM wb_passage_4), 4);

WITH wb_passage_5 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag, word_bank)
    VALUES ('Starting the Work Day', 'First, I {{1}} my computer, wait for it to start up, and check my emails. Then I need to {{2}} the blank spaces on the form for the new project. After that, I {{3}} the file I need for the meeting, since I can''t remember where I put it. At the end of the day, I {{4}} my completed time sheet to my manager for approval.', 'grammar_vocab', 'A2', 'phrasal_verbs', to_jsonb(ARRAY['fill in','hand in','sit down','turn on','come from','look for','give up']::text[]))
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, correct_answer, explanation, passage_id, ordinal) VALUES
  ('grammar_vocab', 'A2', 'word_bank', 'phrasal_verbs', 'Blank 1 of Starting the Work Day', 'turn on', '"Turn on" is the phrasal verb for switching on a device — fitting with "wait for it to start up", which doesn''t make sense if you''re still searching for the computer.', (SELECT id FROM wb_passage_5), 1),
  ('grammar_vocab', 'A2', 'word_bank', 'phrasal_verbs', 'Blank 2 of Starting the Work Day', 'fill in', '"Fill in" means to complete a form by writing information in its blank spaces.', (SELECT id FROM wb_passage_5), 2),
  ('grammar_vocab', 'A2', 'word_bank', 'phrasal_verbs', 'Blank 3 of Starting the Work Day', 'look for', '"Look for" means to search for something you need — "since I can''t remember where I put it" only makes sense if you''re searching, not handing something in or giving it up.', (SELECT id FROM wb_passage_5), 3),
  ('grammar_vocab', 'A2', 'word_bank', 'phrasal_verbs', 'Blank 4 of Starting the Work Day', 'hand in', '"Hand in" means to submit a document, like a completed time sheet, to someone in charge.', (SELECT id FROM wb_passage_5), 4);

WITH wb_passage_6 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag, word_bank)
    VALUES ('Quarterly Sales Update', 'Our sales team has {{1}} a new strategy this quarter because the previous approach was not working well. Last month, we managed to {{2}} three new clients, which increased our overall revenue. However, we still need to {{3}} our costs if we want to hit our profit target, since revenue growth alone won''t cover rising expenses. When the finance director reviewed the {{4}}, she said they were better than expected. We have also decided to {{5}} a new marketing campaign to reach more customers next month. If the campaign is successful, the company will {{6}} its market share significantly, overtaking its main rival.', 'grammar_vocab', 'B1', 'business_vocab', to_jsonb(ARRAY['reduce','holiday','sign','resign','increase','complain','implemented','figures','launch']::text[]))
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, correct_answer, explanation, passage_id, ordinal) VALUES
  ('grammar_vocab', 'B1', 'word_bank', 'business_vocab', 'Blank 1 of Quarterly Sales Update', 'implemented', 'Present perfect (''has implemented'') is used because the action was recently completed and is still relevant now; ''implement a strategy'' is a standard business collocation.', (SELECT id FROM wb_passage_6), 1),
  ('grammar_vocab', 'B1', 'word_bank', 'business_vocab', 'Blank 2 of Quarterly Sales Update', 'sign', '''Sign a client'' is common business vocabulary meaning to get a client to agree to work with your company, fitting after ''managed to''.', (SELECT id FROM wb_passage_6), 2),
  ('grammar_vocab', 'B1', 'word_bank', 'business_vocab', 'Blank 3 of Quarterly Sales Update', 'reduce', '''Reduce costs'' is a fixed business collocation; the clause ''since revenue growth alone won''t cover rising expenses'' only makes sense if costs need to go down, not up.', (SELECT id FROM wb_passage_6), 3),
  ('grammar_vocab', 'B1', 'word_bank', 'business_vocab', 'Blank 4 of Quarterly Sales Update', 'figures', '''Figures'' (plural) is the natural object for a finance director to ''review'' — the following pronoun ''they'' requires a plural noun, which rules out the other, singular pool words.', (SELECT id FROM wb_passage_6), 4),
  ('grammar_vocab', 'B1', 'word_bank', 'business_vocab', 'Blank 5 of Quarterly Sales Update', 'launch', '''Launch a campaign'' is a standard collocation for starting a new marketing activity, matching ''decided to ___''.', (SELECT id FROM wb_passage_6), 5),
  ('grammar_vocab', 'B1', 'word_bank', 'business_vocab', 'Blank 6 of Quarterly Sales Update', 'increase', '''Increase market share'' is a common business expression; ''overtaking its main rival'' only follows logically from growth, not a reduction.', (SELECT id FROM wb_passage_6), 6);

WITH wb_passage_7 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag, word_bank)
    VALUES ('A Busy Monday at the Office', 'When I arrived at work this morning, I learned that a major client had complained about a late delivery. I immediately decided to {{1}} why the delivery had been delayed, before responding to the client. Not long after, I had to {{2}} the client''s lawyer three times before he finally answered his phone, so I could explain what had happened. Because we were short-staffed, I also had to {{3}} a tall stack of shipping receipts, one by one, to find the mistake. When a colleague fell ill, I offered to {{4}} the morning shift at reception for the rest of the day. I also managed to {{5}} the confusing mess of duplicate delivery addresses that had caused the whole problem. By the end of the day, I had finally managed to {{6}} with my manager about the whole situation.', 'grammar_vocab', 'B1', 'phrasal_verbs', to_jsonb(ARRAY['take over','sort out','look into','get through to','turn down','catch up','show off','go through','hang out']::text[]))
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, correct_answer, explanation, passage_id, ordinal) VALUES
  ('grammar_vocab', 'B1', 'word_bank', 'phrasal_verbs', 'Blank 1 of A Busy Monday at the Office', 'look into', '''Look into'' means to investigate an unknown cause; a ''why''-clause object only grammatically follows an investigation verb, not the other pool verbs.', (SELECT id FROM wb_passage_7), 1),
  ('grammar_vocab', 'B1', 'word_bank', 'phrasal_verbs', 'Blank 2 of A Busy Monday at the Office', 'get through to', '''Get through to someone'' means to succeed in reaching them, especially by phone after difficulty — matching ''three times before he finally answered his phone''.', (SELECT id FROM wb_passage_7), 2),
  ('grammar_vocab', 'B1', 'word_bank', 'phrasal_verbs', 'Blank 3 of A Busy Monday at the Office', 'go through', '''Go through'' means to review items one at a time, such as a stack of receipts — matching ''one by one'' in the sentence.', (SELECT id FROM wb_passage_7), 3),
  ('grammar_vocab', 'B1', 'word_bank', 'phrasal_verbs', 'Blank 4 of A Busy Monday at the Office', 'take over', '''Take over'' means to assume responsibility for a role or task, such as covering a colleague''s shift.', (SELECT id FROM wb_passage_7), 4),
  ('grammar_vocab', 'B1', 'word_bank', 'phrasal_verbs', 'Blank 5 of A Busy Monday at the Office', 'sort out', '''Sort out'' means to untangle a mess or confusion, such as a mix-up with duplicate addresses.', (SELECT id FROM wb_passage_7), 5),
  ('grammar_vocab', 'B1', 'word_bank', 'phrasal_verbs', 'Blank 6 of A Busy Monday at the Office', 'catch up', '''Catch up with someone'' means to update them after being busy; the fixed preposition ''with'' only follows ''catch up'' among the pool words.', (SELECT id FROM wb_passage_7), 6);

WITH wb_passage_8 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag, word_bank)
    VALUES ('Meeting Recap: Project Timeline', 'Dear Team, I am writing to {{1}} you of the outcome of yesterday''s meeting regarding the new website project. We have {{2}} to postpone the launch date unilaterally, without waiting to hear back from the client. Furthermore, the client has {{3}} several changes to the homepage, which we must complete before we continue. If everyone agrees, we would like to {{4}} a new deadline of the 15th. Please let us know as soon as possible if you have any concerns, so that we can {{5}} them properly. We {{6}} for any inconvenience this delay may cause and thank you for your patience.', 'grammar_vocab', 'B1', 'formal_register', to_jsonb(ARRAY['borrow','ignore','address','requested','celebrate','decided','propose','inform','apologise']::text[]))
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, correct_answer, explanation, passage_id, ordinal) VALUES
  ('grammar_vocab', 'B1', 'word_bank', 'formal_register', 'Blank 1 of Meeting Recap: Project Timeline', 'inform', '''Inform someone of something'' is a formal fixed pattern for giving official information, more appropriate in a business email than an informal word like ''tell''.', (SELECT id FROM wb_passage_8), 1),
  ('grammar_vocab', 'B1', 'word_bank', 'formal_register', 'Blank 2 of Meeting Recap: Project Timeline', 'decided', '''Decided...unilaterally, without waiting to hear back'' shows the team acted alone; ''requested...unilaterally'' is self-contradictory, since a request by definition involves asking someone else.', (SELECT id FROM wb_passage_8), 2),
  ('grammar_vocab', 'B1', 'word_bank', 'formal_register', 'Blank 3 of Meeting Recap: Project Timeline', 'requested', '''Requested'' is the formal register choice for asking for something, fitting ''the client has ___ several changes'' better than a casual verb like ''asked''.', (SELECT id FROM wb_passage_8), 3),
  ('grammar_vocab', 'B1', 'word_bank', 'formal_register', 'Blank 4 of Meeting Recap: Project Timeline', 'propose', '''Would like to propose'' is a standard formal way of suggesting something in business correspondence, matching the polite conditional ''if everyone agrees''.', (SELECT id FROM wb_passage_8), 4),
  ('grammar_vocab', 'B1', 'word_bank', 'formal_register', 'Blank 5 of Meeting Recap: Project Timeline', 'address', '''Address a concern'' is the formal expression for dealing with it properly, more appropriate here than an informal verb like ''fix''.', (SELECT id FROM wb_passage_8), 5),
  ('grammar_vocab', 'B1', 'word_bank', 'formal_register', 'Blank 6 of Meeting Recap: Project Timeline', 'apologise', '''Apologise for'' is the standard formal closing phrase for expressing regret about inconvenience in business writing.', (SELECT id FROM wb_passage_8), 6);

WITH wb_passage_9 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag, word_bank)
    VALUES ('Renegotiating the Supply Contract', 'The negotiations had been dragging on for weeks before both sides finally agreed to sit {{1}} and go through the figures once more. Although the initial offer was rejected outright, the supplier''s team decided not to give {{2}} hope of reaching an agreement, and a revised schedule was proposed instead. As a result, the finance director asked her assistant to set {{3}} to clarify the new terms in a formal memo before the next meeting. Despite mounting pressure from head office, the manager refused to give {{4}} to demands that she considered unreasonable. When a last-minute clause was added, the legal team had to go {{5}} the entire document once more to check for inconsistencies. By Friday afternoon, an agreement had finally been reached, and both directors signed {{6}} on the deal.', 'grammar_vocab', 'B2', 'phrasal_verbs', to_jsonb(ARRAY['in','down','along','out','away','off','about','over','up']::text[]))
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, correct_answer, explanation, passage_id, ordinal) VALUES
  ('grammar_vocab', 'B2', 'word_bank', 'phrasal_verbs', 'Blank 1 of Renegotiating the Supply Contract', 'down', '"Sit down" is the standard phrasal verb for settling in to begin a serious, focused discussion, which matches the two sides preparing to review the figures.', (SELECT id FROM wb_passage_9), 1),
  ('grammar_vocab', 'B2', 'word_bank', 'phrasal_verbs', 'Blank 2 of Renegotiating the Supply Contract', 'up', '"Give up hope" is a fixed idiom; "give in hope" is ungrammatical, since "give in" doesn''t take "hope" as a direct object.', (SELECT id FROM wb_passage_9), 2),
  ('grammar_vocab', 'B2', 'word_bank', 'phrasal_verbs', 'Blank 3 of Renegotiating the Supply Contract', 'out', '"Set out to clarify" (intend/begin to clarify) is idiomatic; "set down to clarify" is not a standard English pattern.', (SELECT id FROM wb_passage_9), 3),
  ('grammar_vocab', 'B2', 'word_bank', 'phrasal_verbs', 'Blank 4 of Renegotiating the Supply Contract', 'in', '"Give in" means to yield or submit to pressure, matching the manager''s resistance to demands she found unreasonable.', (SELECT id FROM wb_passage_9), 4),
  ('grammar_vocab', 'B2', 'word_bank', 'phrasal_verbs', 'Blank 5 of Renegotiating the Supply Contract', 'over', '"Go over" means to examine or review something carefully again, matching the legal team rechecking the document for inconsistencies.', (SELECT id FROM wb_passage_9), 5),
  ('grammar_vocab', 'B2', 'word_bank', 'phrasal_verbs', 'Blank 6 of Renegotiating the Supply Contract', 'off', '"Sign off (on)" means to give final formal approval, fitting the conclusion of a successfully completed negotiation.', (SELECT id FROM wb_passage_9), 6);

WITH wb_passage_10 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag, word_bank)
    VALUES ('Formal Performance Review Feedback', 'Dear Ms. Owusu, I am writing {{1}} your request for feedback on the quarterly performance review. The report has been reviewed carefully by the panel, and, {{2}} having several minor concerns, your overall contribution was judged to be highly satisfactory. {{3}} to the meeting, please review the attached figures so that you are fully prepared to discuss them. Furthermore, you are expected to {{4}} to improve turnaround times on client deliverables over the coming quarter. {{5}}, your collaborative approach with the marketing team has been particularly commendable and should be maintained. Should any queries arise, do not hesitate to contact HR, who will {{6}} respond within two working days.', 'grammar_vocab', 'B2', 'formal_register', to_jsonb(ARRAY['thereby','downtime','promptly','regarding','Nonetheless','endeavour','hereby','Prior','despite']::text[]))
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, correct_answer, explanation, passage_id, ordinal) VALUES
  ('grammar_vocab', 'B2', 'word_bank', 'formal_register', 'Blank 1 of Formal Performance Review Feedback', 'regarding', '"Regarding" is the formal equivalent of "about," appropriate for opening a professional letter and introducing its subject.', (SELECT id FROM wb_passage_10), 1),
  ('grammar_vocab', 'B2', 'word_bank', 'formal_register', 'Blank 2 of Formal Performance Review Feedback', 'despite', '"Despite having several minor concerns" is grammatical; "regarding having several minor concerns" is not a natural pattern, since "regarding" doesn''t combine with a gerund this way.', (SELECT id FROM wb_passage_10), 2),
  ('grammar_vocab', 'B2', 'word_bank', 'formal_register', 'Blank 3 of Formal Performance Review Feedback', 'Prior', '"Prior to" is a formal, written alternative to "before," commonly used in professional correspondence to sequence events.', (SELECT id FROM wb_passage_10), 3),
  ('grammar_vocab', 'B2', 'word_bank', 'formal_register', 'Blank 4 of Formal Performance Review Feedback', 'endeavour', '"Endeavour" is a formal verb meaning "to try," more suitable in official feedback than the informal "try."', (SELECT id FROM wb_passage_10), 4),
  ('grammar_vocab', 'B2', 'word_bank', 'formal_register', 'Blank 5 of Formal Performance Review Feedback', 'Nonetheless', '"Nonetheless" is a formal connector meaning "despite this," used here to pivot from areas for improvement to genuine praise.', (SELECT id FROM wb_passage_10), 5),
  ('grammar_vocab', 'B2', 'word_bank', 'formal_register', 'Blank 6 of Formal Performance Review Feedback', 'promptly', '"Promptly" is a formal adverb meaning "without delay," matching the professional tone of an HR service commitment.', (SELECT id FROM wb_passage_10), 6);

WITH wb_passage_11 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag, word_bank)
    VALUES ('A Difficult Strategic Decision', 'After months of deliberation, the board finally had to {{1}} up its mind about whether to expand into the Asian market. Although the initial data was promising, several analysts {{2}} concerns about the volatility of currency exchange rates. As a result, the CEO asked the strategy team to {{3}} further research before any commitment was made. Once the findings had been presented, the directors were able to {{4}} a consensus on a phased rollout instead of a full launch. Despite the tight schedule, the operations manager was confident that the team could {{5}} the requirements set by the investors. In the end, the board agreed to {{6}} the risks carefully before finalising the budget for next year.', 'grammar_vocab', 'B2', 'collocations', to_jsonb(ARRAY['conduct','weigh','feedback','raised','meet','outcome','revenue','make','reach']::text[]))
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, correct_answer, explanation, passage_id, ordinal) VALUES
  ('grammar_vocab', 'B2', 'word_bank', 'collocations', 'Blank 1 of A Difficult Strategic Decision', 'make', '"Make up its mind" is a fixed idiom; "reach up its mind" is ungrammatical, since "reach" doesn''t combine with "up... mind" this way.', (SELECT id FROM wb_passage_11), 1),
  ('grammar_vocab', 'B2', 'word_bank', 'collocations', 'Blank 2 of A Difficult Strategic Decision', 'raised', '"Raise concerns" is the fixed collocation meaning to formally voice worries, matching the analysts'' role in flagging currency risk.', (SELECT id FROM wb_passage_11), 2),
  ('grammar_vocab', 'B2', 'word_bank', 'collocations', 'Blank 3 of A Difficult Strategic Decision', 'conduct', '"Conduct research" is the standard formal collocation for carrying out a structured investigation before a decision is made.', (SELECT id FROM wb_passage_11), 3),
  ('grammar_vocab', 'B2', 'word_bank', 'collocations', 'Blank 4 of A Difficult Strategic Decision', 'reach', '"Reach a consensus" is the fixed collocation meaning to arrive at general agreement after discussion among the directors.', (SELECT id FROM wb_passage_11), 4),
  ('grammar_vocab', 'B2', 'word_bank', 'collocations', 'Blank 5 of A Difficult Strategic Decision', 'meet', '"Meet the requirements" is the standard collocation; "make the requirements" doesn''t fit, since the requirements were already set by the investors, not created by the team.', (SELECT id FROM wb_passage_11), 5),
  ('grammar_vocab', 'B2', 'word_bank', 'collocations', 'Blank 6 of A Difficult Strategic Decision', 'weigh', '"Weigh the risks" is the standard collocation meaning to carefully consider potential downsides before finalising a decision.', (SELECT id FROM wb_passage_11), 6);

WITH wb_passage_12 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag, word_bank)
    VALUES ('Board Ratification of Executive Restructuring', 'At its quarterly meeting, the board of directors {{1}} to approve a sweeping restructuring of the senior management team. Notwithstanding vocal opposition from a minority of shareholders, the resolution was carried by an overwhelming majority. The chairman was at pains to stress that the decision had not been reached {{2}}, but only after protracted consultation with external counsel. In light of the group''s declining profitability, the directors judged it {{3}} to merge three divisions into a single operating unit. Employees affected by the changes will be treated {{4}} with the redundancy policy agreed with the works council last year. The board further resolved that a full audit of the group''s governance arrangements be {{5}} before the end of the fiscal year. Directors reiterated their {{6}} commitment to transparency, regardless of the cost, whereby all material resolutions will henceforth be published within five working days of adoption. Should any dispute {{7}} regarding the implementation of these measures, the audit committee has been empowered to intervene forthwith. The minutes of the meeting will be circulated to shareholders {{8}} the close of business on Friday.', 'grammar_vocab', 'C1', 'formal_register', to_jsonb(ARRAY['voted','loophole','arise','lightly','conducted','unwavering','shortfall','in accordance','prudent','prior to','downturn']::text[]))
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, correct_answer, explanation, passage_id, ordinal) VALUES
  ('grammar_vocab', 'C1', 'word_bank', 'formal_register', 'Blank 1 of Board Ratification of Executive Restructuring', 'voted', '"Voted" is the standard formal verb for a board''s collective decision, appropriate to the register of corporate governance reporting rather than a plainer verb like "chose".', (SELECT id FROM wb_passage_12), 1),
  ('grammar_vocab', 'C1', 'word_bank', 'formal_register', 'Blank 2 of Board Ratification of Executive Restructuring', 'lightly', '"Not reached lightly" is a fixed formal collocation signalling that a decision was made seriously and only after careful deliberation, a common hedge in formal minutes.', (SELECT id FROM wb_passage_12), 2),
  ('grammar_vocab', 'C1', 'word_bank', 'formal_register', 'Blank 3 of Board Ratification of Executive Restructuring', 'prudent', '"Judged it prudent" is an elevated, formal way of expressing that the directors considered a course of action wise, fitting the register of board resolutions.', (SELECT id FROM wb_passage_12), 3),
  ('grammar_vocab', 'C1', 'word_bank', 'formal_register', 'Blank 4 of Board Ratification of Executive Restructuring', 'in accordance', '"In accordance with" is a formal two-word connector meaning "following the terms of", standard in legal and HR-related corporate language.', (SELECT id FROM wb_passage_12), 4),
  ('grammar_vocab', 'C1', 'word_bank', 'formal_register', 'Blank 5 of Board Ratification of Executive Restructuring', 'conducted', '"Conducted" is the formal verb that collocates with "audit" in the passive construction "be conducted", typical of formal governance prose.', (SELECT id FROM wb_passage_12), 5),
  ('grammar_vocab', 'C1', 'word_bank', 'formal_register', 'Blank 6 of Board Ratification of Executive Restructuring', 'unwavering', '"Unwavering commitment... regardless of the cost" is coherent (steadfast despite cost); "prudent commitment... regardless of the cost" is self-contradictory, since prudence means weighing costs carefully.', (SELECT id FROM wb_passage_12), 6),
  ('grammar_vocab', 'C1', 'word_bank', 'formal_register', 'Blank 7 of Board Ratification of Executive Restructuring', 'arise', '"Should any dispute arise" is a formal inverted conditional (omitting "if"), and "arise" is the verb that formally collocates with "dispute".', (SELECT id FROM wb_passage_12), 7),
  ('grammar_vocab', 'C1', 'word_bank', 'formal_register', 'Blank 8 of Board Ratification of Executive Restructuring', 'prior to', '"Prior to" is a formal, elevated alternative to "before", typical of official correspondence and corporate documents.', (SELECT id FROM wb_passage_12), 8);

WITH wb_passage_13 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag, word_bank)
    VALUES ('Internal Compliance Review Following a Data Breach', 'Shortly after the data breach first came to {{1}}, following an anonymous tip to the hotline, the compliance department launched a thorough investigation into the circumstances surrounding the incident. Preliminary findings suggest that the breach may have {{2}} a significant risk to the personal data of over ten thousand clients. The legal team was instructed to take {{3}} account the possibility of regulatory sanctions before drafting its response to the data protection authority. Several employees raised {{4}} about the adequacy of the existing cybersecurity protocols during the internal review. Management has since resolved to conduct a full {{5}} audit of all third-party vendors with access to sensitive systems. The board has also agreed to bear in {{6}} the recommendations put forward by the external auditors when revising the company''s data-handling policy. Following extensive deliberation, the committee finally reached a {{7}} on the measures required to prevent a recurrence. It was widely acknowledged that failure to act promptly could constitute a serious breach {{8}} the company''s contractual obligations to its clients.', 'grammar_vocab', 'C1', 'collocations', to_jsonb(ARRAY['posed','of','concerns','mind','outcome','consensus','security','backlog','light','into','footnote']::text[]))
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, correct_answer, explanation, passage_id, ordinal) VALUES
  ('grammar_vocab', 'C1', 'word_bank', 'collocations', 'Blank 1 of Internal Compliance Review Following a Data Breach', 'light', '"Came to light" is a fixed idiomatic collocation meaning "became known"; "following an anonymous tip" only makes sense with something becoming known, not "coming to mind".', (SELECT id FROM wb_passage_13), 1),
  ('grammar_vocab', 'C1', 'word_bank', 'collocations', 'Blank 2 of Internal Compliance Review Following a Data Breach', 'posed', '"Pose a risk" is the standard collocation for creating a danger or threat; the modal perfect "may have posed" also marks speculation about the past.', (SELECT id FROM wb_passage_13), 2),
  ('grammar_vocab', 'C1', 'word_bank', 'collocations', 'Blank 3 of Internal Compliance Review Following a Data Breach', 'into', '"Take into account" is a fixed three-word collocation meaning to consider something; "into" is the only preposition that completes the idiom.', (SELECT id FROM wb_passage_13), 3),
  ('grammar_vocab', 'C1', 'word_bank', 'collocations', 'Blank 4 of Internal Compliance Review Following a Data Breach', 'concerns', '"Raise concerns" is the fixed collocation meaning to formally voice worries; no other noun in the pool pairs naturally with "raise" in this idiomatic sense.', (SELECT id FROM wb_passage_13), 4),
  ('grammar_vocab', 'C1', 'word_bank', 'collocations', 'Blank 5 of Internal Compliance Review Following a Data Breach', 'security', '"Security audit" is the fixed collocation for a systematic review of cybersecurity practices, distinct from a financial or logistical audit.', (SELECT id FROM wb_passage_13), 5),
  ('grammar_vocab', 'C1', 'word_bank', 'collocations', 'Blank 6 of Internal Compliance Review Following a Data Breach', 'mind', '"Bear in mind" is a fixed idiomatic collocation meaning to keep something in consideration; no other noun completes this expression.', (SELECT id FROM wb_passage_13), 6),
  ('grammar_vocab', 'C1', 'word_bank', 'collocations', 'Blank 7 of Internal Compliance Review Following a Data Breach', 'consensus', '"Reach a consensus" is the standard collocation for arriving at general agreement after deliberation, apt for describing a committee''s conclusion.', (SELECT id FROM wb_passage_13), 7),
  ('grammar_vocab', 'C1', 'word_bank', 'collocations', 'Blank 8 of Internal Compliance Review Following a Data Breach', 'of', '"Breach of" is the fixed legal collocation used before contractual or legal obligations (as in "breach of contract"), and "of" is the obligatory preposition.', (SELECT id FROM wb_passage_13), 8);

WITH wb_passage_14 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag, word_bank)
    VALUES ('A Decade of Strategic Transformation', 'By the time the new CEO took office in 2019, the company {{1}} already lost almost a third of its market share to overseas competitors. Since then, the leadership team {{2}} been working tirelessly to reverse the decline, restructuring entire divisions and renegotiating key supplier contracts, and continues to do so today. Analysts insist that, had the previous board acted sooner, the crisis {{3}} likely have been averted altogether. Over the past eighteen months, revenues {{4}} so far risen steadily, climbing by nearly twelve per cent year on year. By the end of next quarter, there is no doubt that the finance department {{5}} have completed its migration to the new reporting system, three months ahead of the original schedule. While the restructuring {{6}} still taking place, several senior executives chose to resign rather than adapt to the new structure. Employee representatives {{7}} not consulted by the board at any stage, a fact the board later admitted was a serious oversight. Critics maintain that the board {{8}} clearly have consulted them before announcing the redundancies so abruptly.', 'grammar_vocab', 'C1', 'tenses', to_jsonb(ARRAY['were','have','am','has','would','did','was','had','will','should','does']::text[]))
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, correct_answer, explanation, passage_id, ordinal) VALUES
  ('grammar_vocab', 'C1', 'word_bank', 'tenses', 'Blank 1 of A Decade of Strategic Transformation', 'had', 'The past perfect ("had already lost") is needed to show an action completed before another past reference point, here the CEO''s arrival in 2019.', (SELECT id FROM wb_passage_14), 1),
  ('grammar_vocab', 'C1', 'word_bank', 'tenses', 'Blank 2 of A Decade of Strategic Transformation', 'has', 'The present perfect continuous ("has been working... and continues to do so today") expresses an action that began in the past and continues now; "had" would clash with "continues... today".', (SELECT id FROM wb_passage_14), 2),
  ('grammar_vocab', 'C1', 'word_bank', 'tenses', 'Blank 3 of A Decade of Strategic Transformation', 'would', 'The conditional perfect ("would likely have been averted") is required in the result clause of a third conditional, pairing with the past perfect "had acted" in the if-clause.', (SELECT id FROM wb_passage_14), 3),
  ('grammar_vocab', 'C1', 'word_bank', 'tenses', 'Blank 4 of A Decade of Strategic Transformation', 'have', 'Present perfect simple ("have so far risen") with "over the past eighteen months" describes change continuing up to now; the plural subject "revenues" requires "have" rather than "has".', (SELECT id FROM wb_passage_14), 4),
  ('grammar_vocab', 'C1', 'word_bank', 'tenses', 'Blank 5 of A Decade of Strategic Transformation', 'will', 'The future perfect ("will have completed") describes an action expected to be finished before a specified future point; "there is no doubt that" states a plain certainty, which clashes with the hedged, expectation-flavored "should".', (SELECT id FROM wb_passage_14), 5),
  ('grammar_vocab', 'C1', 'word_bank', 'tenses', 'Blank 6 of A Decade of Strategic Transformation', 'was', 'The past continuous ("was still taking place") provides ongoing background to the simple past event that follows ("executives chose to resign").', (SELECT id FROM wb_passage_14), 6),
  ('grammar_vocab', 'C1', 'word_bank', 'tenses', 'Blank 7 of A Decade of Strategic Transformation', 'were', 'The passive past simple ("were not consulted by the board") is required because the subject, the employee representatives, receives the action rather than performing it.', (SELECT id FROM wb_passage_14), 7),
  ('grammar_vocab', 'C1', 'word_bank', 'tenses', 'Blank 8 of A Decade of Strategic Transformation', 'should', 'The modal perfect "should clearly have consulted" expresses retrospective criticism of an action that did not happen, a hallmark C1 structure for hypothetical regret.', (SELECT id FROM wb_passage_14), 8);

WITH wb_passage_15 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag, word_bank)
    VALUES ('Sealing the Merger', 'After eighteen months of painstaking negotiation, the board finally reached a {{1}} agreement that would reshape the industry landscape. The chief executive was adamant that the deal be handled with the utmost {{2}}, so that nobody outside the negotiating room would ever learn what had been discussed. Analysts had long speculated that the two firms would eventually {{3}} forces, pooling their complementary strengths to weather an increasingly volatile market. Yet the negotiations very nearly {{4}} down over disagreements about executive compensation, with each side accusing the other of moving the goalposts. It was only when the lead negotiator proposed a compromise on severance packages that talks were able to {{5}} traction once more. The resulting agreement, hammered out in the small hours, struck a delicate {{6}} between shareholder value and workforce stability. Employees, understandably anxious about redundancies, were reassured that due {{7}} would be exercised throughout the integration process. In the end, the merger was widely hailed as a textbook case of two rivals turning {{8}} into a mutually beneficial partnership.', 'grammar_vocab', 'C2', 'collocations', to_jsonb(ARRAY['broke','levity','gain','balance','discretion','diligence','adversity','join','attrition','landmark','fluency']::text[]))
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, correct_answer, explanation, passage_id, ordinal) VALUES
  ('grammar_vocab', 'C2', 'word_bank', 'collocations', 'Blank 1 of Sealing the Merger', 'landmark', '"Landmark agreement" is the fixed collocation for a highly significant, precedent-setting deal; it carries far more idiomatic weight than a generic near-miss like "important agreement".', (SELECT id FROM wb_passage_15), 1),
  ('grammar_vocab', 'C2', 'word_bank', 'collocations', 'Blank 2 of Sealing the Merger', 'discretion', '"Utmost discretion" (confidentiality) is what causes nobody outside the room to learn what was discussed; "diligence" (thoroughness/care in one''s work) doesn''t causally produce secrecy the way discretion does.', (SELECT id FROM wb_passage_15), 2),
  ('grammar_vocab', 'C2', 'word_bank', 'collocations', 'Blank 3 of Sealing the Merger', 'join', '"Join forces" is the fixed collocation meaning to combine efforts; "combine forces" is a common but less idiomatic near-miss in this exact phrase.', (SELECT id FROM wb_passage_15), 3),
  ('grammar_vocab', 'C2', 'word_bank', 'collocations', 'Blank 4 of Sealing the Merger', 'broke', '"Broke down" is the fixed phrasal collocation for negotiations collapsing mid-process, distinct from "fell through", which describes a deal failing to materialise at all.', (SELECT id FROM wb_passage_15), 4),
  ('grammar_vocab', 'C2', 'word_bank', 'collocations', 'Blank 5 of Sealing the Merger', 'gain', '"Gain traction" is the fixed collocation for building fresh momentum; "regain" would wrongly imply the talks previously had momentum before stalling.', (SELECT id FROM wb_passage_15), 5),
  ('grammar_vocab', 'C2', 'word_bank', 'collocations', 'Blank 6 of Sealing the Merger', 'balance', '"Strike a balance" is the fixed idiom for finding a satisfactory middle ground between competing interests, here shareholder value and workforce stability.', (SELECT id FROM wb_passage_15), 6),
  ('grammar_vocab', 'C2', 'word_bank', 'collocations', 'Blank 7 of Sealing the Merger', 'diligence', '"Due diligence" is the standard business/legal collocation for the careful, systematic scrutiny applied before and during a deal; "due discretion" is not the fixed professional term used in this context.', (SELECT id FROM wb_passage_15), 7),
  ('grammar_vocab', 'C2', 'word_bank', 'collocations', 'Blank 8 of Sealing the Merger', 'adversity', 'This echoes the idiom "turn adversity into opportunity", here adapted to the partnership outcome, conveying that a difficult rivalry was transformed into something mutually beneficial.', (SELECT id FROM wb_passage_15), 8);

WITH wb_passage_16 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag, word_bank)
    VALUES ('Containing the Fallout', 'No sooner had the breach been detected than the incident-response team {{1}} into action, activating protocols that had been rehearsed only weeks earlier. By the time the regulator''s inquiry landed on the general counsel''s desk, the company {{2}} already notified every affected client, a fact that would later prove pivotal in mitigating reputational damage. Had the communications director not insisted on transparency from the outset, the narrative {{3}} have spiralled out of control within hours. Since the crisis broke, the firm {{4}} worked around the clock, and morale, remarkably, has held. By this time next week, the taskforce {{5}} have compiled a full forensic report for the board''s review. While the technical team was still patching the vulnerability, the general counsel {{6}} already drafting contingency statements for every conceivable media scenario. It is often said that a crisis reveals character; rarely, if ever, {{7}} a leadership team demonstrate such composure during that single, gruelling week. Looking back, few would deny that the response, though imperfect, {{8}} the company''s reputation from far graver harm.', 'grammar_vocab', 'C2', 'tenses', to_jsonb(ARRAY['were','spared','was','did','had','having','has','would','sprang','will','is']::text[]))
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, correct_answer, explanation, passage_id, ordinal) VALUES
  ('grammar_vocab', 'C2', 'word_bank', 'tenses', 'Blank 1 of Containing the Fallout', 'sprang', 'The inversion "No sooner had X happened than Y..." pairs a past perfect first clause with a simple past second clause, so "sprang" is required rather than "had sprung", which would wrongly duplicate the past perfect.', (SELECT id FROM wb_passage_16), 1),
  ('grammar_vocab', 'C2', 'word_bank', 'tenses', 'Blank 2 of Containing the Fallout', 'had', '"By the time" plus a simple-past clause signals a prior completed action, which requires the past perfect auxiliary "had", not the present perfect "has" or a bare simple past.', (SELECT id FROM wb_passage_16), 2),
  ('grammar_vocab', 'C2', 'word_bank', 'tenses', 'Blank 3 of Containing the Fallout', 'would', 'The inverted third-conditional clause "Had X not insisted..." requires the modal perfect "would have + past participle" in the result clause to express an unrealised hypothetical past outcome.', (SELECT id FROM wb_passage_16), 3),
  ('grammar_vocab', 'C2', 'word_bank', 'tenses', 'Blank 4 of Containing the Fallout', 'has', '"Since the crisis broke" pairs with the present perfect "has worked" to show an action beginning in the past and continuing into the present, unlike the future "will" or simple past "was".', (SELECT id FROM wb_passage_16), 4),
  ('grammar_vocab', 'C2', 'word_bank', 'tenses', 'Blank 5 of Containing the Fallout', 'will', '"By this time next week" is a future time marker requiring the future perfect "will have compiled" for an action to be completed before that specified future point.', (SELECT id FROM wb_passage_16), 5),
  ('grammar_vocab', 'C2', 'word_bank', 'tenses', 'Blank 6 of Containing the Fallout', 'was', 'The singular subject "the general counsel" (one person, not a collective like "the department") requires the singular "was", not "were", to match the parallel past continuous "was still patching".', (SELECT id FROM wb_passage_16), 6),
  ('grammar_vocab', 'C2', 'word_bank', 'tenses', 'Blank 7 of Containing the Fallout', 'did', 'Fronting the negative-frequency adverb "rarely" triggers subject-auxiliary inversion with do-support, so "did" plus the bare infinitive "demonstrate" is required; "that single, gruelling week" anchors to one specific past event, which clashes with "would"''s habitual/repeated-pattern reading.', (SELECT id FROM wb_passage_16), 7),
  ('grammar_vocab', 'C2', 'word_bank', 'tenses', 'Blank 8 of Containing the Fallout', 'spared', 'The retrospective frame "Looking back...that the response..." states a single completed past fact, so the simple past "spared" is required rather than a perfect or continuous form.', (SELECT id FROM wb_passage_16), 8);

WITH wb_passage_17 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag, word_bank)
    VALUES ('The Boardroom Standoff', 'The two delegations faced each other from {{1}} the polished mahogany table, each side acutely aware that the slightest miscalculation could scupper months of preparation. The chief negotiator, renowned {{2}} her unflappable composure, opened with a proposal calculated to test the other party''s resolve. Beneath the veneer of cordiality, both sides remained deeply suspicious {{3}} one another''s true intentions, each convinced the other was bluffing. The rival CEO visibly baulked {{4}} the proposed valuation, before anyone had even finished presenting it. It gradually became apparent that the impasse hinged {{5}} a single clause buried deep within the indemnity schedule. Rather than capitulate, the lead counsel argued {{6}} any further concessions to the other side, much to the visible irritation of the opposing team. After nearly nine hours, the two sides finally came {{7}} a compromise after painstaking, deliberate negotiation that preserved the deal despite satisfying neither party outright. Looking back on the ordeal, most observers agreed that the outcome had come about largely {{8}} sheer attritional stamina rather than any flash of strategic brilliance.', 'grammar_vocab', 'C2', 'prepositions', to_jsonb(ARRAY['by','with','for','across','into','at','of','on','under','to','against']::text[]))
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, correct_answer, explanation, passage_id, ordinal) VALUES
  ('grammar_vocab', 'C2', 'word_bank', 'prepositions', 'Blank 1 of The Boardroom Standoff', 'across', '"Faced each other from across the table" is the standard collocation for two parties on opposite sides of a table; "from at the table" is ungrammatical, since "from" cannot combine with "at" this way.', (SELECT id FROM wb_passage_17), 1),
  ('grammar_vocab', 'C2', 'word_bank', 'prepositions', 'Blank 2 of The Boardroom Standoff', 'for', '"Renowned for" is the fixed prepositional pairing indicating the basis of a reputation.', (SELECT id FROM wb_passage_17), 2),
  ('grammar_vocab', 'C2', 'word_bank', 'prepositions', 'Blank 3 of The Boardroom Standoff', 'of', '"Suspicious of" is the standard prepositional collocation when the object is a person''s motives or intentions.', (SELECT id FROM wb_passage_17), 3),
  ('grammar_vocab', 'C2', 'word_bank', 'prepositions', 'Blank 4 of The Boardroom Standoff', 'at', '"Balk/baulk at" is the fixed phrasal verb for an immediate reaction of hesitation; "before anyone had even finished presenting it" rules out "balk on", which implies backing out of a prior commitment that doesn''t yet exist here.', (SELECT id FROM wb_passage_17), 4),
  ('grammar_vocab', 'C2', 'word_bank', 'prepositions', 'Blank 5 of The Boardroom Standoff', 'on', '"Hinge on" is the fixed collocation meaning to depend entirely on a single deciding factor.', (SELECT id FROM wb_passage_17), 5),
  ('grammar_vocab', 'C2', 'word_bank', 'prepositions', 'Blank 6 of The Boardroom Standoff', 'against', '"Argue against... concessions to the other side" opposes giving the other side more, consistent with "rather than capitulate"; "argue for concessions to the other side" would itself be a form of capitulating, contradicting the sentence''s own premise.', (SELECT id FROM wb_passage_17), 6),
  ('grammar_vocab', 'C2', 'word_bank', 'prepositions', 'Blank 7 of The Boardroom Standoff', 'to', '"Come to a compromise" is the fixed idiom for reaching a negotiated resolution; "after painstaking, deliberate negotiation" contradicts "came across" (an accidental discovery).', (SELECT id FROM wb_passage_17), 7),
  ('grammar_vocab', 'C2', 'word_bank', 'prepositions', 'Blank 8 of The Boardroom Standoff', 'by', '"Come about by" identifies the means or cause behind an outcome; "by sheer stamina" names the causal agent precisely, as required by this fixed pattern.', (SELECT id FROM wb_passage_17), 8);
