-- Writing volume round 2: 24 new prompts (4 per CEFR level), expanding
-- the pool from 8 to 12 prompts per level. Scenarios are distinct from
-- the existing 48 prompts and cover varied context_tags.

INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, explanation) VALUES
('writing', 'A1', 'prompt', 'meeting', 'Ask about a meeting time

You are new at a company. You need to know what time the weekly team meeting starts. Write a short message to a colleague to ask about the meeting time and place. (30–50 words)', 'A strong response uses simple, polite language to ask about the meeting time and location. It includes a greeting, a clear question, and a simple closing.'),
('writing', 'A1', 'prompt', 'call', 'Write a note about a missed call

A customer called while your colleague was away from their desk. Write a short note for your colleague with the caller''s name (Mr. Park), phone number (555-0192), and reason for the call (delivery question). (30–50 words)', 'A strong response includes all three pieces of information clearly: the caller''s name, phone number, and reason for calling. It uses simple, direct language.'),
('writing', 'A1', 'prompt', 'customer_service', 'Greet a visitor at reception

You work at the front desk of a company. A visitor has arrived for a meeting with your manager. Write a short welcome message to the visitor. Ask them to wait and offer a drink. (30–50 words)', 'A strong response is friendly and polite. It greets the visitor, asks them to take a seat, and offers a hot or cold drink using simple vocabulary and short sentences.'),
('writing', 'A1', 'prompt', 'negotiation', 'Accept a delivery date

A supplier has offered to deliver your order on March 15. You are happy with this date. Write a short reply to accept the delivery date and say thank you. (30–50 words)', 'A strong response clearly confirms acceptance of the proposed date, expresses thanks, and uses simple polite language. A greeting and closing are included.'),
('writing', 'A2', 'prompt', 'meeting', 'Write a short meeting agenda

You are organizing a 30-minute team meeting for Friday morning. Write a short email to your team with the agenda. Include at least three items to discuss and the time and place of the meeting. (50–80 words)', 'A strong response includes a clear subject, a greeting, the meeting time and location, at least three agenda items in a logical order, and a polite closing. The tone is professional but friendly.'),
('writing', 'A2', 'prompt', 'call', 'Follow up after a phone call

You just had a phone call with a client, Ms. Rivera. She asked about the price of your company''s training package. Write a short email to follow up. Include the price ($500 per person) and offer to answer more questions. (50–80 words)', 'A strong response references the phone call, provides the requested pricing information clearly, and offers further assistance. It uses polite, professional language with correct past tense for the call and present tense for the offer.'),
('writing', 'A2', 'prompt', 'negotiation', 'Request a lower price

You are buying 200 office chairs from a furniture company. The price is $85 per chair. Write a short email to the sales representative to ask for a discount because you are ordering a large quantity. (50–80 words)', 'A strong response politely states the current price, mentions the large order quantity as a reason for the discount request, and asks if a better price is available. It maintains a respectful, professional tone.'),
('writing', 'A2', 'prompt', 'customer_service', 'Process a product exchange

A customer, Mr. Chen, bought a medium-sized company polo shirt but needs a large size instead. Write a short email to confirm the exchange and explain what he should do to return the medium shirt. (50–80 words)', 'A strong response confirms the exchange, clearly explains the return process in simple steps, and uses polite, helpful language. It addresses the customer by name and includes a friendly closing.'),
('writing', 'B1', 'prompt', 'customer_service', 'Apologize for a billing error

A long-time customer, Ms. Thompson, was charged twice for the same invoice. She sent an email to complain. Write a professional response apologizing for the mistake, explaining what happened, and describing the steps your company will take to correct the error and prevent it from happening again. (80–120 words)', 'A strong response acknowledges the error with a sincere apology, provides a brief explanation of the cause, outlines specific corrective actions such as issuing a refund and reviewing billing procedures, and thanks the customer for their patience. The tone is professional and empathetic.'),
('writing', 'B1', 'prompt', 'call', 'Summarize a conference call

You participated in a conference call with a client about a new marketing project. Write an email to your manager summarizing the key points discussed, including the project timeline (launch in June), the budget ($15,000), and the next steps (send a proposal by Friday). (80–120 words)', 'A strong response organizes information clearly, covers all key discussion points, and uses appropriate reporting language such as "We agreed that..." or "The client confirmed...". It includes a logical structure with an opening reference to the call and a clear summary of next steps.'),
('writing', 'B1', 'prompt', 'negotiation', 'Propose a payment plan

Your company provides IT services to a small business client, GreenLeaf Ltd. They are having cash flow problems and cannot pay their $12,000 invoice in full. Write an email proposing a three-month payment plan. Explain how the plan would work and why it benefits both sides. (80–120 words)', 'A strong response shows understanding of the client''s situation, clearly outlines the proposed payment schedule, and presents mutual benefits. It uses professional language with conditional structures and maintains a collaborative tone.'),
('writing', 'B1', 'prompt', 'meeting', 'Cancel a meeting and propose alternatives

You need to cancel a project review meeting scheduled for Thursday because two key team members are unavailable. Write an email to all attendees explaining the cancellation, giving a brief reason, and suggesting two alternative dates. Ask attendees to confirm their availability. (80–120 words)', 'A strong response clearly states the cancellation and reason, proposes specific alternative dates, and asks for confirmation. It uses polite, professional language and shows consideration for the attendees'' schedules.'),
('writing', 'B2', 'prompt', 'meeting', 'Write a post-meeting action plan

You chaired a cross-functional meeting about improving employee retention. Several ideas were discussed, including flexible work options, mentoring programs, and salary benchmarking. Write a follow-up email to all participants summarizing the decisions made, assigning specific action items to team members, and setting deadlines. Include a note about the next review meeting. (120–160 words)', 'A strong response demonstrates the ability to synthesize meeting content into clear, organized action items. It assigns responsibilities with specific deadlines, uses professional language, and provides a logical structure that makes it easy for recipients to identify their tasks.'),
('writing', 'B2', 'prompt', 'call', 'Follow up on a difficult client call

You had a phone call with a frustrated client who is unhappy about repeated delays in a software development project. The client threatened to cancel the contract. Write a follow-up email to the client acknowledging their frustration, explaining the steps your team will take to get back on track, and proposing a weekly progress call to rebuild trust. (120–160 words)', 'A strong response balances empathy with accountability. It acknowledges the client''s concerns without being defensive, presents a concrete recovery plan with timelines, and proposes a clear mechanism for ongoing communication. The tone is professional, reassuring, and solution-oriented.'),
('writing', 'B2', 'prompt', 'customer_service', 'Respond to a service-level agreement breach

Your company''s cloud hosting service experienced 14 hours of downtime last month, exceeding the guaranteed 99.5% uptime in the service-level agreement with a client. Write a formal email to the client acknowledging the breach, explaining the cause, detailing the compensation you are offering such as a service credit, and outlining preventive measures. (120–160 words)', 'A strong response takes responsibility, provides a transparent explanation, offers appropriate compensation, and details specific technical or procedural improvements. It uses formal register with measured, confident language and avoids excessive apology or vague promises.'),
('writing', 'B2', 'prompt', 'negotiation', 'Counter a proposed contract change

A business partner has proposed shortening the payment terms in your contract from 60 days to 15 days. This would create cash flow challenges for your company. Write a professional email presenting a counter-proposal of 30 days, explaining your reasoning, acknowledging the partner''s perspective, and suggesting a compromise that benefits both parties. (120–160 words)', 'A strong response demonstrates balanced argumentation by acknowledging the partner''s needs while advocating for the writer''s position. It uses persuasive but respectful language, provides logical justification for the counter-proposal, and frames the compromise as a win-win solution.'),
('writing', 'C1', 'prompt', 'meeting', 'Write a pre-meeting briefing for executives

Your company is about to enter negotiations with a potential acquisition target, NovaTech Solutions. You have been asked to prepare a short briefing document for the executive team ahead of the first meeting. Cover NovaTech''s strengths and weaknesses, potential synergies, key risks including cultural integration and regulatory concerns, and recommended talking points for the meeting. The briefing should be concise yet thorough enough to prepare the executives for a productive discussion. (150–200 words)', 'A strong response demonstrates strategic thinking and the ability to synthesize complex information for a senior audience. It uses hedging language appropriately, balances optimism about synergies with honest risk assessment, and provides actionable talking points. The tone is authoritative yet measured.'),
('writing', 'C1', 'prompt', 'call', 'Prepare talking points for a restructuring announcement

Your company is closing a regional office and relocating 40 employees to the headquarters. As the HR director, write talking points for a phone call you will make to the regional office manager to inform them of this decision before the wider announcement. Address the business rationale, the impact on staff, the relocation support package being offered, and how to handle questions from the team. The tone should be empathetic but clear. (150–200 words)', 'A strong response navigates the sensitivity of the situation by balancing directness with empathy. It provides a clear business rationale without being cold, outlines concrete support measures, and anticipates likely questions. The language demonstrates diplomacy and emotional intelligence while maintaining professional clarity.'),
('writing', 'C1', 'prompt', 'customer_service', 'Respond to a high-profile client escalation

The CEO of one of your company''s top three clients has written directly to your CEO expressing deep dissatisfaction with recent service quality, citing three specific incidents over the past quarter. Your CEO has asked you to draft a response. Acknowledge each incident, take accountability without revealing confidential internal details, outline immediate corrective actions, and propose a quarterly review process to ensure ongoing service excellence. (150–200 words)', 'A strong response handles the escalation with the gravity it deserves while maintaining the company''s credibility. It addresses each incident specifically, demonstrates accountability without over-sharing, and proposes forward-looking measures. The register is highly formal and carefully calibrated for a CEO-to-CEO communication.'),
('writing', 'C1', 'prompt', 'negotiation', 'Renegotiate terms after a market shift

Your company supplies raw materials to a major manufacturer. Due to a significant increase in global shipping costs (up 35%), your current contract pricing is no longer sustainable. Write an email to the client''s procurement director proposing a price adjustment. Acknowledge the long-standing relationship, present data to justify the increase, offer flexible options such as longer contract commitments in exchange for smaller increases, and express your commitment to the partnership. (150–200 words)', 'A strong response demonstrates sophisticated negotiation skills by grounding the request in objective market data while preserving the relationship. It uses hedging and concessive language effectively, offers creative solutions rather than ultimatums, and frames the adjustment as a mutual investment in the partnership''s future.'),
('writing', 'C2', 'prompt', 'meeting', 'Draft a board presentation summary on market entry

The board of directors has asked for a written summary to accompany your presentation on entering a new Southeast Asian market. Address market opportunity and competitive landscape, regulatory and political risks, the proposed entry strategy (joint venture versus wholly owned subsidiary), resource requirements, and a three-year financial projection narrative. Acknowledge dissenting views from the preliminary strategy committee regarding the joint venture approach and explain why your recommendation still holds. The summary must be persuasive yet balanced, suitable for board members with varying levels of familiarity with the region. (200–250 words)', 'A strong response demonstrates executive-level communication by presenting a complex strategic recommendation with supporting evidence while addressing counterarguments. It uses sophisticated argumentation, implicit persuasion, and layered analysis. The writing is concise yet comprehensive, with a tone that conveys confidence without dismissing legitimate concerns.'),
('writing', 'C2', 'prompt', 'call', 'Write a debrief memo after a crisis conference call

Following a two-hour emergency conference call about a data breach affecting 50,000 customer records, write a confidential debrief memo for the senior leadership team. Cover the known facts, immediate containment actions taken, legal and regulatory obligations including notification timelines, reputational risk assessment, and recommended next steps across IT security, legal, communications, and customer relations. Flag areas of uncertainty and decisions still pending. The memo should serve as both a record of decisions made and a roadmap for the next 72 hours. (200–250 words)', 'A strong response demonstrates the ability to synthesize high-stakes, fast-moving information into a clear, actionable document. It distinguishes between confirmed facts and uncertainties, assigns clear ownership for next steps, and maintains a tone of controlled urgency. The writing is precise, avoiding both panic and complacency, and shows awareness of multiple stakeholder perspectives.'),
('writing', 'C2', 'prompt', 'negotiation', 'Draft a multi-stakeholder negotiation position paper

Your company is negotiating a five-year public-private partnership with a city government to develop a smart transportation system. Multiple stakeholders have competing interests: the city wants to minimize costs and maximize public benefit, your company seeks a reasonable return on investment, and privacy advocacy groups have raised concerns about data collection. Write a position paper that proposes a framework for balancing these interests, including data governance principles, a revenue-sharing model, and accountability mechanisms. Address each stakeholder group''s primary concern and explain how your proposed framework creates alignment. (200–250 words)', 'A strong response demonstrates mastery of multi-stakeholder communication by addressing divergent interests with a coherent, unifying framework. It uses sophisticated argumentative structures, anticipates objections from each party, and proposes specific mechanisms rather than vague principles. The writing shows the ability to create alignment through logical analysis and diplomatic language.'),
('writing', 'C2', 'prompt', 'email', 'Recommend an ethics policy for AI deployment

Your company is preparing to deploy an AI-powered hiring screening tool. As the head of corporate responsibility, write an internal recommendation to the executive committee. Address the ethical risks (algorithmic bias, transparency, candidate consent), the legal landscape including existing and emerging regulations, competitive implications of both deploying and not deploying, and your recommended governance framework. Acknowledge the tension between innovation speed and responsible deployment, and propose a phased rollout with specific safeguards at each stage. (200–250 words)', 'A strong response demonstrates the ability to navigate complex ethical territory with nuance and pragmatism. It presents a balanced analysis that neither dismisses innovation concerns nor minimizes ethical risks. The governance framework is specific and actionable, with clear criteria for progressing between phases. The writing uses sophisticated hedging, concessive structures, and implicit persuasion appropriate for influencing senior decision-makers.');
