-- First listening-passage content round: 18 passages (3 per CEFR
-- level), 54 linked mcq questions. Closes the audit-flagged gap where
-- every listening item was a single decontextualized sentence.
-- passages.audio_url is left NULL here (falls back to browser TTS
-- reading passages.body aloud) -- real audio is generated afterward
-- via the admin panel's 'Generate passage audio' button.

WITH lp_passage_0 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag)
    VALUES ('Tom Calls In Sick', 'Tom calls his manager, Mrs. Green, in the morning. He says, ''Hello, this is Tom. I am sick today. I have a headache.'' Mrs. Green says, ''I am sorry to hear that. Please rest at home.'' Tom says, ''Thank you. I will come back to work tomorrow.'' Mrs. Green says, ''Okay, feel better soon.''', 'listening', 'A1', 'call')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('listening', 'A1', 'mcq', 'call', 'Who does Tom call?', to_jsonb(ARRAY['His doctor','His manager, Mrs. Green','His colleague','His wife']::text[]), 'His manager, Mrs. Green', 'The passage says ''Tom calls his manager, Mrs. Green, in the morning,'' so he calls his manager, not a doctor, colleague, or his wife.', (SELECT id FROM lp_passage_0)),
  ('listening', 'A1', 'mcq', 'call', 'Why does Tom stay home?', to_jsonb(ARRAY['He is on vacation','He is sick, he has a headache','His car is broken','He has a meeting']::text[]), 'He is sick, he has a headache', 'Tom says, ''I am sick today. I have a headache,'' which is the reason he stays home, not vacation, car trouble, or a meeting.', (SELECT id FROM lp_passage_0)),
  ('listening', 'A1', 'mcq', 'call', 'When will Tom come back to work?', to_jsonb(ARRAY['Tomorrow','Next week','Today','Never']::text[]), 'Tomorrow', 'Tom says, ''I will come back to work tomorrow,'' so ''today,'' ''next week,'' and ''never'' are all incorrect.', (SELECT id FROM lp_passage_0));

WITH lp_passage_1 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag)
    VALUES ('New Report Deadline', 'Every Monday, the team has a meeting at ten o''clock. Today, the manager says, ''The report is not for Monday now. The report is for Friday.'' One worker asks, ''Can I send it by email?'' The manager says, ''Yes. Please send it to my email before five o''clock.''', 'listening', 'A1', 'meeting')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('listening', 'A1', 'mcq', 'meeting', 'What day does the team usually meet?', to_jsonb(ARRAY['Monday','Friday','Tuesday','Wednesday']::text[]), 'Monday', 'The passage begins, ''Every Monday, the team has a meeting,'' so Monday is their usual meeting day.', (SELECT id FROM lp_passage_1)),
  ('listening', 'A1', 'mcq', 'meeting', 'When is the report now?', to_jsonb(ARRAY['Next Monday','Friday','Today','Ten o''clock']::text[]), 'Friday', 'The manager says, ''The report is not for Monday now. The report is for Friday,'' so Friday is correct and Monday is explicitly ruled out.', (SELECT id FROM lp_passage_1)),
  ('listening', 'A1', 'mcq', 'meeting', 'How should the worker send the report?', to_jsonb(ARRAY['By fax','By phone','By email','In person']::text[]), 'By email', 'The worker asks, ''Can I send it by email?'' and the manager agrees, saying ''please send it to my email,'' so email is the correct method.', (SELECT id FROM lp_passage_1));

WITH lp_passage_2 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag)
    VALUES ('Returning a Jacket', 'A customer walks into the shop with a black jacket. She says to the worker, ''I bought this jacket yesterday, but it is too small. Can I return it?'' The worker says, ''Yes, do you have the receipt?'' The customer says, ''Yes, here it is.'' The worker says, ''Thank you. I will give you your money back now.''', 'listening', 'A1', 'customer_service')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('listening', 'A1', 'mcq', 'customer_service', 'What does the customer want to do?', to_jsonb(ARRAY['Buy a new jacket','Return the jacket','Exchange the jacket for a shirt','Complain about the worker']::text[]), 'Return the jacket', 'The customer asks, ''Can I return it?'' referring to the jacket, so she wants to return it, not buy, exchange, or complain.', (SELECT id FROM lp_passage_2)),
  ('listening', 'A1', 'mcq', 'customer_service', 'Why does the customer want to return the jacket?', to_jsonb(ARRAY['It is the wrong color','It is too expensive','It is too small','It is dirty']::text[]), 'It is too small', 'The customer says the jacket ''is too small,'' which is the stated reason, not color, price, or cleanliness.', (SELECT id FROM lp_passage_2)),
  ('listening', 'A1', 'mcq', 'customer_service', 'What does the worker ask for?', to_jsonb(ARRAY['Her name','The receipt','Her phone number','Her ID']::text[]), 'The receipt', 'The worker asks, ''do you have the receipt?'' and the customer provides it, so the receipt is what is requested.', (SELECT id FROM lp_passage_2));

WITH lp_passage_3 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag)
    VALUES ('The Wrong Delivery', 'Tom works at a small office. This morning, a delivery driver arrives with three boxes of paper. Tom checks the order and sees a problem. He says, "We ordered two boxes of pens, not paper." The driver looks at his sheet and says, "Sorry, this delivery is for the office next door." Tom calls the driver''s company. A woman answers and says, "Don''t worry, we will collect the paper this afternoon and bring your pens tomorrow morning." Tom thanks her and puts the boxes near the front door.', 'listening', 'A2', 'customer_service')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('listening', 'A2', 'mcq', 'customer_service', 'What did Tom''s office actually order?', to_jsonb(ARRAY['Three boxes of paper','Two boxes of pens','Two boxes of paper','Three boxes of pens']::text[]), 'Two boxes of pens', 'Tom says, "We ordered two boxes of pens, not paper." The three boxes of paper were delivered by mistake.', (SELECT id FROM lp_passage_3)),
  ('listening', 'A2', 'mcq', 'customer_service', 'Why did the delivery driver bring the wrong boxes?', to_jsonb(ARRAY['He forgot the order','The delivery was meant for the office next door','Tom changed the order that morning','The company sent the wrong company''s address']::text[]), 'The delivery was meant for the office next door', 'The driver checks his sheet and says, "Sorry, this delivery is for the office next door," showing it was delivered to the wrong place.', (SELECT id FROM lp_passage_3)),
  ('listening', 'A2', 'mcq', 'customer_service', 'When will Tom receive his pens?', to_jsonb(ARRAY['This afternoon','Tomorrow morning','Later this morning','Next week']::text[]), 'Tomorrow morning', 'The woman on the phone says they will "collect the paper this afternoon and bring your pens tomorrow morning."', (SELECT id FROM lp_passage_3));

WITH lp_passage_4 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag)
    VALUES ('Changing the Meeting Time', 'Sophie calls her colleague Marc to change their meeting. She says, "Hi Marc, can we move our meeting from Tuesday to Wednesday? I have a training course on Tuesday morning." Marc checks his calendar and says, "Wednesday is fine, but not before eleven o''clock. I have a call with a client at ten." Sophie suggests, "Let''s meet at two in the afternoon, in the small meeting room on the third floor." Marc agrees and says he will send a new invitation before the end of the day.', 'listening', 'A2', 'meeting')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('listening', 'A2', 'mcq', 'meeting', 'Why does Sophie want to change the meeting day?', to_jsonb(ARRAY['She is on holiday on Tuesday','She has a training course on Tuesday morning','Marc is busy on Tuesday','The meeting room is not free on Tuesday']::text[]), 'She has a training course on Tuesday morning', 'Sophie says, "I have a training course on Tuesday morning," which is why she wants to move the meeting to Wednesday.', (SELECT id FROM lp_passage_4)),
  ('listening', 'A2', 'mcq', 'meeting', 'Why can''t Marc meet before eleven o''clock on Wednesday?', to_jsonb(ARRAY['He starts work late','He has a call with a client at ten','He has another meeting at eleven','He is picking up a colleague']::text[]), 'He has a call with a client at ten', 'Marc explains, "not before eleven o''clock, I have a call with a client at ten," so the earlier hours are taken.', (SELECT id FROM lp_passage_4)),
  ('listening', 'A2', 'mcq', 'meeting', 'Where will Sophie and Marc meet?', to_jsonb(ARRAY['In Marc''s office','In the small meeting room on the third floor','At a client''s office','In the kitchen on the second floor']::text[]), 'In the small meeting room on the third floor', 'Sophie suggests meeting "in the small meeting room on the third floor," and Marc agrees to this plan.', (SELECT id FROM lp_passage_4));

WITH lp_passage_5 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag)
    VALUES ('Office Announcement', 'The office manager makes an announcement at the start of the day. She says, "Good morning everyone. First, the coffee machine on the second floor is broken, so please use the one in the kitchen. Second, the car park will close for cleaning tomorrow from nine until midday. Please park on the street instead. Finally, don''t forget the team lunch on Friday at one o''clock in the café downstairs." Everyone listens carefully and a few people write notes about the car park.', 'listening', 'A2', 'general')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('listening', 'A2', 'mcq', 'general', 'Why should employees use the coffee machine in the kitchen?', to_jsonb(ARRAY['The kitchen machine makes better coffee','The second floor coffee machine is broken','The second floor is closed for cleaning','There is no coffee machine on their floor']::text[]), 'The second floor coffee machine is broken', 'The manager says, "the coffee machine on the second floor is broken, so please use the one in the kitchen."', (SELECT id FROM lp_passage_5)),
  ('listening', 'A2', 'mcq', 'general', 'When will the car park be closed?', to_jsonb(ARRAY['Today from nine until midday','Tomorrow from nine until midday','Friday at one o''clock','All week for cleaning']::text[]), 'Tomorrow from nine until midday', 'She announces, "the car park will close for cleaning tomorrow from nine until midday."', (SELECT id FROM lp_passage_5)),
  ('listening', 'A2', 'mcq', 'general', 'What time is the team lunch on Friday?', to_jsonb(ARRAY['Nine o''clock','Midday','One o''clock','Two o''clock']::text[]), 'One o''clock', 'The manager reminds staff about "the team lunch on Friday at one o''clock in the café downstairs."', (SELECT id FROM lp_passage_5));

WITH lp_passage_6 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag)
    VALUES ('A Late Shipment', 'A warehouse manager calls a supplier about a delayed delivery. She says, ''We were expecting the shipment on Monday, but it still hasn''t arrived, and our production line is waiting for those parts.'' The supplier apologises and explains that a problem at their loading dock delayed the order by two days. He offers to send the shipment by express courier at no extra cost, and promises it will arrive by Thursday morning at the latest. The manager thanks him but asks him to email a written confirmation of the new delivery date, so she can update her production schedule and inform her team before the end of the day.', 'listening', 'B1', 'call')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('listening', 'B1', 'mcq', 'call', 'Why was the original shipment delayed?', to_jsonb(ARRAY['A problem at the supplier''s loading dock','The courier company went on strike','The manager cancelled the first order','Bad weather blocked the roads']::text[]), 'A problem at the supplier''s loading dock', 'The supplier explains that ''a problem at their loading dock delayed the order by two days.''', (SELECT id FROM lp_passage_6)),
  ('listening', 'B1', 'mcq', 'call', 'What does the manager ask the supplier to do before the end of the day?', to_jsonb(ARRAY['Send a written confirmation of the new delivery date','Cancel the express courier','Call the production team directly','Refund part of the order']::text[]), 'Send a written confirmation of the new delivery date', 'The manager asks him to ''email a written confirmation of the new delivery date'' so she can update her schedule before the end of the day.', (SELECT id FROM lp_passage_6)),
  ('listening', 'B1', 'mcq', 'call', 'Why does the manager want written confirmation rather than just accepting the phone call?', to_jsonb(ARRAY['She needs a reliable record so she can update her production schedule and inform her team','She does not trust the supplier''s spoken promises at all','Company policy forbids phone agreements of any kind','She plans to complain to the supplier''s manager later']::text[]), 'She needs a reliable record so she can update her production schedule and inform her team', 'The passage links her request directly to a practical purpose: she wants the confirmation ''so she can update her production schedule and inform her team,'' not because of distrust or policy, which are never mentioned.', (SELECT id FROM lp_passage_6));

WITH lp_passage_7 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag)
    VALUES ('Rescheduling the Budget Meeting', 'During a Monday morning meeting, the finance team discusses next quarter''s budget. The team leader announces that the meeting originally planned for Friday afternoon has been moved to Thursday morning instead, because two key managers will be travelling to a conference on Friday. She explains that the main goal of the new meeting will be to decide how much to allocate to the marketing campaign that has been proposed for the autumn launch. One colleague mentions that she has been reviewing last year''s figures all week and has found that marketing spending was underused by almost fifteen percent. The team leader asks her to present these findings at the rescheduled meeting.', 'listening', 'B1', 'meeting')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('listening', 'B1', 'mcq', 'meeting', 'Why was the meeting moved from Friday to Thursday?', to_jsonb(ARRAY['Two key managers will be at a conference on Friday','The finance team wanted an earlier start to the week','The marketing campaign was cancelled','The meeting room was double-booked']::text[]), 'Two key managers will be at a conference on Friday', 'The team leader explains the change happened ''because two key managers will be travelling to a conference on Friday.''', (SELECT id FROM lp_passage_7)),
  ('listening', 'B1', 'mcq', 'meeting', 'What is the main purpose of the rescheduled meeting?', to_jsonb(ARRAY['To decide how much to allocate to the marketing campaign','To review employee performance for the quarter','To plan the conference travel arrangements','To hire a new marketing manager']::text[]), 'To decide how much to allocate to the marketing campaign', 'The passage states the ''main goal of the new meeting will be to decide how much to allocate to the marketing campaign'' for the autumn launch.', (SELECT id FROM lp_passage_7)),
  ('listening', 'B1', 'mcq', 'meeting', 'What can be concluded about why the colleague was asked to present her findings?', to_jsonb(ARRAY['Her research on underused marketing spending is directly relevant to the budget decision being made','She is the most senior person on the finance team','She originally proposed the autumn marketing campaign','The team leader wants her to replace the absent managers']::text[]), 'Her research on underused marketing spending is directly relevant to the budget decision being made', 'This requires connecting two facts: the meeting will decide marketing budget allocation, and the colleague found marketing spending was underused by fifteen percent last year — data directly useful to that decision, which is why the leader asks her to present it.', (SELECT id FROM lp_passage_7));

WITH lp_passage_8 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag)
    VALUES ('A Complaint About a Faulty Printer', 'A customer calls a company''s support line to complain about a printer she bought two weeks ago. She explains that it worked fine for the first few days, but it has been jamming constantly since last weekend, and she has already lost several important documents because of it. The support agent listens carefully and apologises for the inconvenience. He checks her order number and confirms that the printer is still under warranty, so she will not have to pay for a repair or a replacement. He offers her a choice: she can send the printer back for a full refund, or the company can send a replacement unit within three working days. She decides to ask for the replacement, since she needs a working printer for her home office.', 'listening', 'B1', 'customer_service')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('listening', 'B1', 'mcq', 'customer_service', 'What problem has the customer been experiencing with the printer?', to_jsonb(ARRAY['It has been jamming constantly since last weekend','It stopped turning on completely','It prints in the wrong colours','It makes a loud noise when printing']::text[]), 'It has been jamming constantly since last weekend', 'The customer explains that the printer ''has been jamming constantly since last weekend.''', (SELECT id FROM lp_passage_8)),
  ('listening', 'B1', 'mcq', 'customer_service', 'What does the customer choose to do?', to_jsonb(ARRAY['Ask for a replacement printer','Ask for a full refund','Ask to speak to a manager','Ask for a partial refund and keep the printer']::text[]), 'Ask for a replacement printer', 'The passage states she ''decides to ask for the replacement, since she needs a working printer for her home office.''', (SELECT id FROM lp_passage_8)),
  ('listening', 'B1', 'mcq', 'customer_service', 'Why does the customer not have to pay anything for the repair or replacement?', to_jsonb(ARRAY['The printer is still covered by its warranty','The company has a general no-cost policy for all complaints','She purchased additional insurance for the printer','The agent is offering her a personal discount']::text[]), 'The printer is still covered by its warranty', 'The agent ''confirms that the printer is still under warranty, so she will not have to pay for a repair or a replacement'' — the cost-free outcome follows directly from the warranty status, not a general policy or insurance, which are never mentioned.', (SELECT id FROM lp_passage_8));

WITH lp_passage_9 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag)
    VALUES ('Choosing Between Two Candidates', 'Following the final interview round, the hiring manager called her colleague on the panel to compare notes on the two finalists. She admitted that the first candidate''s technical skills were clearly stronger, but confessed she''d left the interview feeling slightly uneasy about how dismissively he''d spoken about a previous team''s process failures. Her colleague pointed out that the second candidate, while less experienced technically, had asked several thoughtful questions about how the team collaborates under pressure, which he took as a good sign. The hiring manager agreed, adding that technical gaps could be closed through training, but attitude was harder to change. After a short pause, she said she''d rather bring on someone slightly underqualified who fit well than risk a repeat of the friction they''d had with a difficult hire two years earlier. They agreed to recommend the second candidate to leadership, with a note suggesting additional technical mentoring during the first few months.', 'listening', 'B2', 'general')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('listening', 'B2', 'mcq', 'general', 'Which candidate did the hiring manager and her colleague ultimately decide to recommend?', to_jsonb(ARRAY['The first candidate, despite the attitude concern','The second candidate, despite weaker technical skills','Neither candidate — the search will continue','Both candidates, for a trial period']::text[]), 'The second candidate, despite weaker technical skills', 'The passage states ''they agreed to recommend the second candidate to leadership, with a note suggesting additional technical mentoring,'' directly ruling out the other outcomes.', (SELECT id FROM lp_passage_9)),
  ('listening', 'B2', 'mcq', 'general', 'Why did the hiring manager feel uneasy about the first candidate?', to_jsonb(ARRAY['He spoke dismissively about a previous team''s process failures','He was late to the interview','He asked no questions about the role','He had no relevant experience']::text[]), 'He spoke dismissively about a previous team''s process failures', 'She ''confessed she''d left the interview feeling slightly uneasy about how dismissively he''d spoken about a previous team''s process failures,'' which is the stated reason.', (SELECT id FROM lp_passage_9)),
  ('listening', 'B2', 'mcq', 'general', 'What can you infer motivated the hiring manager''s final decision, beyond what she stated about training versus attitude?', to_jsonb(ARRAY['A past experience with a difficult hire is influencing her to prioritize attitude and fit over technical strength','She personally dislikes the first candidate for unrelated reasons','Company policy requires hiring the less experienced candidate','She was pressured by her colleague to agree against her own judgment']::text[]), 'A past experience with a difficult hire is influencing her to prioritize attitude and fit over technical strength', 'Her comment that she''d rather avoid ''a repeat of the friction they''d had with a difficult hire two years earlier'' reveals a past experience shaping her present risk calculus toward valuing fit over raw skill — this isn''t offered as an explicit single-sentence reason for the final choice, it has to be connected from her aside about the earlier hire to her stated preference for attitude over trainable skills.', (SELECT id FROM lp_passage_9));

WITH lp_passage_10 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag)
    VALUES ('Negotiating the Contract Renewal', 'During the supplier negotiation, Tom opened by proposing a two-year contract at current rates, hoping to lock in stability for both sides. The supplier''s representative pushed back, insisting that rising material costs meant a five percent increase was non-negotiable if the contract were to run beyond twelve months. Tom countered by suggesting a one-year term with a built-in review clause, allowing prices to be revisited once costs became clearer. There was a long silence before the representative admitted that a shorter term with flexibility actually suited her company too, since she''d been hesitant to commit to two years given how unpredictable the market currently was. They ultimately agreed on a twelve-month contract with a quarterly pricing review, and Tom left the meeting relieved that he hadn''t given in to the initial demand for a blanket increase.', 'listening', 'B2', 'negotiation')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('listening', 'B2', 'mcq', 'negotiation', 'Why did the supplier''s representative initially want a price increase?', to_jsonb(ARRAY['Rising material costs','New government taxes','Increased shipping distances','A change in company ownership']::text[]), 'Rising material costs', 'The passage states she insisted a five percent increase was necessary because of ''rising material costs,'' which is explicitly given as her reason.', (SELECT id FROM lp_passage_10)),
  ('listening', 'B2', 'mcq', 'negotiation', 'What can you infer about the representative''s true feelings toward a long-term contract?', to_jsonb(ARRAY['She strongly preferred a two-year deal but hid it','She was secretly relieved to avoid a long commitment','She had no opinion either way','She wanted an even longer contract than two years']::text[]), 'She was secretly relieved to avoid a long commitment', 'She ''admitted that a shorter term with flexibility actually suited her company too, since she''d been hesitant to commit to two years given how unpredictable the market currently was.'' This reveals that, despite pushing for a price increase on a longer deal, she privately preferred not to be locked in long-term, contradicting the idea that she wanted two years.', (SELECT id FROM lp_passage_10)),
  ('listening', 'B2', 'mcq', 'negotiation', 'What was the final outcome of the negotiation?', to_jsonb(ARRAY['A two-year contract at increased rates','A twelve-month contract with quarterly pricing reviews','No agreement was reached','A six-month trial contract']::text[]), 'A twelve-month contract with quarterly pricing reviews', 'The passage concludes that ''they ultimately agreed on a twelve-month contract with a quarterly pricing review,'' which directly states the outcome and rules out the other options.', (SELECT id FROM lp_passage_10));

WITH lp_passage_11 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag)
    VALUES ('Feedback After the Product Launch', 'After the product launch, Elena called James into her office to discuss how the project had gone. She began by praising the creativity of his marketing campaign, noting that engagement numbers had exceeded expectations. However, she then mentioned, somewhat carefully, that the launch timeline had slipped by nearly two weeks, which had put pressure on the sales team to catch up before quarter-end. James explained that a last-minute change in design requirements had forced the delay, though he admitted he probably should have flagged the risk earlier instead of trying to absorb it quietly. Elena nodded and said she valued his honesty, adding that next time she''d rather hear about problems early, even if it meant an uncomfortable conversation, than discover them once it was too late to adjust. She ended by saying she still wanted him leading the next launch.', 'listening', 'B2', 'meeting')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('listening', 'B2', 'mcq', 'meeting', 'What was the primary reason for the delay in the launch timeline?', to_jsonb(ARRAY['A shortage of marketing budget','A last-minute change in design requirements','The sales team''s unavailability','A problem with the engagement metrics']::text[]), 'A last-minute change in design requirements', 'James ''explained that a last-minute change in design requirements had forced the delay,'' which directly identifies the cause and rules out the other listed reasons.', (SELECT id FROM lp_passage_11)),
  ('listening', 'B2', 'mcq', 'meeting', 'How would you best describe Elena''s overall attitude in this meeting?', to_jsonb(ARRAY['Angry and dismissive of James''s efforts','Balanced, offering both praise and constructive criticism','Indifferent to the outcome of the launch','Entirely focused on blaming the sales team']::text[]), 'Balanced, offering both praise and constructive criticism', 'Elena first ''praised the creativity of his marketing campaign'' and later raised the timeline issue ''somewhat carefully,'' then ended by saying she valued his honesty and still wanted him leading the next launch. This mix of genuine praise and calm, constructive feedback, rather than anger or blame, shows a balanced approach, ruling out the other options.', (SELECT id FROM lp_passage_11)),
  ('listening', 'B2', 'mcq', 'meeting', 'What does Elena say she would prefer James do differently in the future?', to_jsonb(ARRAY['Avoid taking on risky projects','Delegate more tasks to his team','Flag problems early rather than trying to handle them quietly','Focus more on engagement metrics than deadlines']::text[]), 'Flag problems early rather than trying to handle them quietly', 'Elena states she''d ''rather hear about problems early, even if it meant an uncomfortable conversation, than discover them once it was too late to adjust,'' which matches this option directly and is not supported by the other choices.', (SELECT id FROM lp_passage_11));

WITH lp_passage_12 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag)
    VALUES ('Renegotiating the Supplier Contract', 'During a quarterly review call, a procurement manager named Elena raised the subject of the annual contract renewal with a long-standing supplier. She began by acknowledging that the partnership had been valuable over the past three years, praising the supplier''s reliability during the previous winter''s shortages. However, she then noted that market conditions had shifted considerably, and that two competing vendors had recently submitted quotes that were, in her words, ''meaningfully more attractive.'' She stopped short of naming any figures, instead suggesting that if the current terms could not be revisited, procurement would be obliged to open the contract to broader tender when it expired in September. The supplier''s representative pushed back gently, arguing that the quality guarantees embedded in the existing agreement justified the premium, and proposed a compromise: a modest reduction in the per-unit rate in exchange for extending the contract term to five years. Elena thanked him for the flexibility but said she would need to consult her director before committing to anything beyond the current cycle, and the call closed with both parties agreeing to reconvene the following week.', 'listening', 'C1', 'negotiation')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('listening', 'C1', 'mcq', 'negotiation', 'What compromise did the supplier''s representative propose?', to_jsonb(ARRAY['A modest reduction in the per-unit rate in exchange for a five-year contract extension','An immediate switch to a lower-quality product line to cut costs','A full price match with the competing vendors'' quotes','A one-year trial period before renegotiating terms']::text[]), 'A modest reduction in the per-unit rate in exchange for a five-year contract extension', 'The passage states this directly: the representative ''proposed a compromise: a modest reduction in the per-unit rate in exchange for extending the contract term to five years.'' The other options describe changes (product downgrade, full price match, one-year trial) that are never mentioned.', (SELECT id FROM lp_passage_12)),
  ('listening', 'C1', 'mcq', 'negotiation', 'What does Elena most likely intend by mentioning the competing vendors'' quotes without naming figures?', to_jsonb(ARRAY['To pressure the supplier into better terms while keeping her negotiating position flexible','To formally announce that the contract will not be renewed','To request that the supplier match the exact prices of the competitors','To end the business relationship immediately']::text[]), 'To pressure the supplier into better terms while keeping her negotiating position flexible', 'Elena praises the supplier''s past reliability, avoids stating exact figures, and only raises the possibility of open tender as a consequence ''if'' terms aren''t revisited — this is leverage, not a decision already made. This rules out ''formally announce non-renewal'' and ''end the relationship immediately,'' since the tone and hedged conditional language show she is still open to negotiating. ''Match the exact prices'' is not stated — she never discloses figures, so an exact match cannot have been requested.', (SELECT id FROM lp_passage_12)),
  ('listening', 'C1', 'mcq', 'negotiation', 'What does Elena''s need to consult her director, voiced right after she thanks the supplier for his flexibility, suggest about the balance of power in this negotiation?', to_jsonb(ARRAY['Despite appearing to negotiate from a position of strength, Elena does not have unilateral authority and the supplier may still have room to hold firm on other terms','Elena has more authority than the supplier''s representative and is simply being polite','The supplier''s representative also lacks authority and must consult his own superiors','Elena is stalling because she has already decided to reject the compromise']::text[]), 'Despite appearing to negotiate from a position of strength, Elena does not have unilateral authority and the supplier may still have room to hold firm on other terms', 'Although Elena leads the conversation with leverage (competing quotes, potential open tender), her admission that she ''would need to consult her director before committing to anything beyond the current cycle'' — voiced right after praising the supplier''s flexibility — reveals her authority is not absolute, tempering the apparent one-sidedness of the negotiation. This isn''t stated as a direct assessment of the power balance; it must be inferred by weighing her leverage-based rhetoric against this authority limitation. The passage gives no indication the supplier lacks authority (he negotiates and proposes his own compromise freely), and her tone (thanking him ''for the flexibility'') contradicts pretextual stalling.', (SELECT id FROM lp_passage_12));

WITH lp_passage_13 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag)
    VALUES ('Briefing the Team on the Department Merger', 'At a hastily convened team meeting, a department head named Marcus informed his staff that the customer support and technical support functions would be merged into a single unit by the end of the quarter, as part of a wider efficiency drive across the company. He emphasised that the decision had been made at a senior level and that his role was simply to ensure the transition went smoothly. When asked directly whether this would mean job losses, Marcus said only that ''headcount decisions are still being finalised'' and that he ''couldn''t get ahead of a process that wasn''t yet complete,'' though he added that anyone with concerns about their role was welcome to speak with him privately. He then spent several minutes outlining the new reporting lines and the timeline for combining the two ticketing systems, striking a notably more confident tone once the conversation moved away from staffing. He closed by thanking the team for their patience during what he called ''a period of understandable uncertainty,'' and promised a further update within two weeks.', 'listening', 'C1', 'meeting')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('listening', 'C1', 'mcq', 'meeting', 'Which two functions are being merged into a single unit?', to_jsonb(ARRAY['Customer support and technical support','Sales and marketing','Finance and procurement','Technical support and product development']::text[]), 'Customer support and technical support', 'This is stated explicitly: ''the customer support and technical support functions would be merged into a single unit.'' None of the other departments are mentioned in the passage.', (SELECT id FROM lp_passage_13)),
  ('listening', 'C1', 'mcq', 'meeting', 'What does Marcus''s answer about job losses most strongly suggest?', to_jsonb(ARRAY['That staffing cuts are a real possibility that has not yet been officially decided or announced','That he has personally guaranteed no one will lose their job','That all affected staff have already been individually notified of layoffs','That the question is irrelevant because the merger will not affect staffing at all']::text[]), 'That staffing cuts are a real possibility that has not yet been officially decided or announced', 'Marcus avoids a direct denial, saying only that ''headcount decisions are still being finalised'' — a hedge that would be unnecessary if there were no risk of cuts. This rules out a guarantee of no job losses (he offers none) and rules out cuts already being confirmed and communicated (he explicitly says the process ''wasn''t yet complete''). Saying staffing is unaffected contradicts his own evasive phrasing.', (SELECT id FROM lp_passage_13)),
  ('listening', 'C1', 'mcq', 'meeting', 'What does the shift in Marcus''s tone once he moves on to reporting lines and systems imply?', to_jsonb(ARRAY['He is more comfortable discussing operational logistics than addressing the sensitive question of job security','He was poorly prepared for the entire meeting and only became confident by chance','He disagrees with the merger decision and is signalling his objection through tone','He considers the staffing question to be less important than the technical details']::text[]), 'He is more comfortable discussing operational logistics than addressing the sensitive question of job security', 'The passage notes he becomes ''notably more confident'' specifically ''once the conversation moved away from staffing,'' directly linking the tonal shift to avoidance of the sensitive topic rather than random unpreparedness or a substantive view on importance. There is no evidence in the passage that he disagrees with the decision, he presents it as coming from senior leadership and his job as ensuring smooth execution.', (SELECT id FROM lp_passage_13));

WITH lp_passage_14 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag)
    VALUES ('Debriefing After a Client Escalation', 'After resolving a formal complaint from one of the firm''s largest retail clients, a customer service manager named Priya debriefed her team on how the case had been handled. The client had experienced repeated delivery failures over a six-week period and had threatened to move the account to a competitor. Priya explained that although a full refund and a goodwill credit had ultimately been issued, the client''s tone during the final call had remained noticeably reserved, and he had declined an invitation to renew the service contract early, saying he would ''wait and see how the next quarter goes.'' Priya cautioned the team against treating the case as closed, noting that the compensation had addressed the financial loss but might not have restored the client''s confidence in the service. She asked the account team to schedule a proactive check-in call within the next fortnight, rather than waiting for the client to raise further issues himself, and stressed that the account should be flagged internally as at risk until renewal was confirmed.', 'listening', 'C1', 'customer_service')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('listening', 'C1', 'mcq', 'customer_service', 'What compensation was issued to the client?', to_jsonb(ARRAY['A full refund and a goodwill credit','A discount on the client''s next three orders','A formal written apology only, with no financial compensation','An early contract renewal at a reduced rate']::text[]), 'A full refund and a goodwill credit', 'The passage states directly that ''a full refund and a goodwill credit had ultimately been issued.'' A discount on future orders, a written-apology-only response, and an early renewal at reduced rate are never mentioned as part of the resolution.', (SELECT id FROM lp_passage_14)),
  ('listening', 'C1', 'mcq', 'customer_service', 'What does the client''s decision to decline early renewal most likely suggest?', to_jsonb(ARRAY['His trust in the service has not been fully restored despite the compensation','He is fully satisfied and simply prefers standard renewal timing for administrative reasons','He has already decided to switch to a competitor','He was not offered the option to renew early']::text[]), 'His trust in the service has not been fully restored despite the compensation', 'The passage links his ''noticeably reserved'' tone and his wait-and-see comment directly to the decision to decline early renewal, and Priya explicitly reasons that compensation addressed the financial loss but ''might not have restored the client''s confidence.'' This rules out simple administrative preference. It also rules out an already-decided switch, since he is waiting to observe performance rather than leaving outright, and rules out no offer being made, since the passage says he ''declined an invitation.''', (SELECT id FROM lp_passage_14)),
  ('listening', 'C1', 'mcq', 'customer_service', 'Why does Priya ask for a proactive check-in call rather than waiting for the client to raise further issues?', to_jsonb(ARRAY['She believes the relationship is still fragile and at risk despite the case being formally resolved','Company policy requires a check-in call after every complaint regardless of outcome','She wants to upsell the client on additional services before the quarter ends','The client explicitly requested a follow-up call during the final conversation']::text[]), 'She believes the relationship is still fragile and at risk despite the case being formally resolved', 'Priya ''cautioned the team against treating the case as closed'' and asked for the account to be ''flagged internally as at risk until renewal was confirmed'' — this reasoning, tied to the client''s reserved tone and declined early renewal, is why she wants a proactive touchpoint. No general company policy is mentioned, there is no mention of upselling, and the passage says the client declined an invitation to renew, not that he requested a follow-up call.', (SELECT id FROM lp_passage_14));

WITH lp_passage_15 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag)
    VALUES ('The Boardroom Standoff Over Q3 Numbers', 'The finance director cleared her throat before sliding the revised forecast across the table, conceding that the third quarter numbers were, in her words, a little softer than the market would like, though she was quick to add that softer was hardly the same as soft. The chief executive raised an eyebrow and asked whether a twelve percent shortfall against guidance still counted as merely soft. She replied that context mattered enormously, and that once you stripped out the currency swing and the delayed Rotterdam shipment, the underlying trend was, if anything, encouraging. The operations lead, who had said nothing for the first ten minutes, finally observed that they seemed to be discovering a remarkable number of one-off explanations lately, and wondered aloud whether the board might eventually start asking why these one-offs kept recurring with such regularity. A brief, uncomfortable silence followed. The chief executive then suggested, with the faintest trace of a smile, that perhaps it was time to stop calling them one-offs altogether, since investors would inevitably call them something else entirely: a pattern. The finance director promised a fuller variance analysis by Friday, and the meeting moved on, a little stiffly, to the next item on the agenda.', 'listening', 'C2', 'meeting')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('listening', 'C2', 'mcq', 'meeting', 'What does the finance director''s distinction between the numbers being ''softer'' rather than ''soft'' suggest about her communication style?', to_jsonb(ARRAY['She is using deliberately imprecise, euphemistic language to downplay bad news','She is being maximally precise and technically accurate','She has misunderstood the underlying financial data','She is fully agreeing with the CEO''s assessment']::text[]), 'She is using deliberately imprecise, euphemistic language to downplay bad news', 'The passage explicitly frames this as a distinction she insists on (''softer was hardly the same as soft'') immediately after admitting a real shortfall exists. Drawing a fine semantic line to blunt the force of bad news is a classic hedging tactic, not precision (a genuinely precise account would just state the twelve percent figure plainly), misunderstanding (she clearly knows the numbers), or agreement (the CEO is the one pressing her, not the reverse).', (SELECT id FROM lp_passage_15)),
  ('listening', 'C2', 'mcq', 'meeting', 'What is implied by the operations lead''s remark about discovering ''a remarkable number of one-off explanations lately''?', to_jsonb(ARRAY['He fully accepts each explanation as legitimate and unrelated to the others','He is subtly suggesting that a recurring problem is being mislabeled as a series of isolated incidents','He is proposing that the finance director be dismissed','He agrees the Q3 trend is genuinely encouraging']::text[]), 'He is subtly suggesting that a recurring problem is being mislabeled as a series of isolated incidents', 'He notes the frequency (''remarkable number... lately'') and then explicitly wonders why ''one-offs'' keep ''recurring'', a direct logical tension, since something recurring cannot truly be a one-off. This rules out full acceptance and agreement with her optimistic framing; nothing in the passage suggests he calls for anyone''s removal, only that he questions the pattern of explanations.', (SELECT id FROM lp_passage_15)),
  ('listening', 'C2', 'mcq', 'meeting', 'What does the CEO''s closing comment about investors eventually calling the one-offs ''a pattern'' imply?', to_jsonb(ARRAY['He is satisfied with the finance director''s explanation and considers the matter closed','He is tacitly siding with the operations lead''s skepticism and warning that the euphemism will not hold up externally','He is defending the finance director against the operations lead''s criticism','He is asking to postpone the Friday variance analysis indefinitely']::text[]), 'He is tacitly siding with the operations lead''s skepticism and warning that the euphemism will not hold up externally', 'The CEO''s remark comes ''with the faintest trace of a smile'' directly after the operations lead''s skeptical comment and explicitly picks up the same word (''pattern''), extending the challenge rather than dismissing it, he predicts investors will use that very word. This rules out satisfaction and defense of the finance director, and the passage states she still promises the analysis ''by Friday'', contradicting postponement.', (SELECT id FROM lp_passage_15));

WITH lp_passage_16 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag)
    VALUES ('Renegotiating Terms After the Due-Diligence Discovery', 'During the follow-up call on the acquisition terms, the lead negotiator for the buying side opened by saying she wanted to be upfront: the discovery of pending litigation in Brazil had, unsurprisingly, given her team pause. The seller''s representative countered that the litigation was, in his estimation, more nuisance than threat, and that folding it into the valuation discussion risked conflating a minor legal formality with a genuinely material business risk. She replied, diplomatically, that she wasn''t suggesting bad faith on anyone''s part, merely that thorough due diligence required her to treat every disclosed liability as material until proven otherwise, and that the current offer would need to reflect that caution. He asked, somewhat pointedly, whether this meant the price was simply being renegotiated outright. She said she would rather frame it as recalibrating the risk allocation, perhaps through an escrow holdback tied to the litigation''s resolution, rather than a straightforward reduction in the headline price. There was a pause on the line before he admitted that an escrow arrangement, while not his first preference, was at least a structure his board could live with, provided the release conditions were clearly defined. She agreed to circulate draft terms by the end of the week, and the call closed on notably warmer footing than it had begun.', 'listening', 'C2', 'negotiation')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('listening', 'C2', 'mcq', 'negotiation', 'What is the function of the buyer''s negotiator opening the call by saying she ''wanted to be upfront''?', to_jsonb(ARRAY['It is a formal apology for a mistake her own team made','It diplomatically softens the introduction of a serious concern before she raises it','It signals that negotiations are being terminated','It is a compliment intended to flatter the seller''s representative']::text[]), 'It diplomatically softens the introduction of a serious concern before she raises it', 'The phrase immediately precedes the disclosure that the litigation ''had... given her team pause'', a courteous framing device used to cushion unwelcome news, not an apology (nothing suggests her team erred), a termination (the call proceeds constructively and ends ''on warmer footing''), or flattery (there is no complimentary content).', (SELECT id FROM lp_passage_16)),
  ('listening', 'C2', 'mcq', 'negotiation', 'Why does the buyer''s negotiator prefer the phrase ''recalibrating the risk allocation'' to describe her proposal rather than calling it a price cut?', to_jsonb(ARRAY['Because the escrow holdback has no real connection to the purchase price','Because she is using diplomatic language to propose what is functionally a price reduction while avoiding direct confrontation over the headline figure','Because she made an error and is trying to disguise it','Because the seller''s representative specifically instructed her to use that wording']::text[]), 'Because she is using diplomatic language to propose what is functionally a price reduction while avoiding direct confrontation over the headline figure', 'She proposes the escrow specifically ''rather than a straightforward reduction in the headline price'', meaning it achieves a similar financial effect (money withheld pending litigation outcome) while letting both sides avoid saying ''price cut'' directly, which is why the seller''s representative had asked ''somewhat pointedly'' if renegotiation was underway. This rules out no connection to price; nothing indicates an error or that the seller dictated her wording, he in fact calls it ''not his first preference''.', (SELECT id FROM lp_passage_16)),
  ('listening', 'C2', 'mcq', 'negotiation', 'What does the seller''s representative''s reaction to the escrow proposal reveal about his actual position?', to_jsonb(ARRAY['He enthusiastically welcomes the escrow structure as his preferred outcome','He reluctantly accepts it as a workable compromise rather than an ideal solution, conditional on clearly defined terms','He rejects the proposal outright and ends the call','He demands the litigation be removed from the deal entirely']::text[]), 'He reluctantly accepts it as a workable compromise rather than an ideal solution, conditional on clearly defined terms', 'He states the arrangement is ''not his first preference'' yet something his board ''could live with'', and adds a condition (''provided the release conditions were clearly defined''), language of grudging, qualified acceptance, not enthusiasm or rejection (the call ends warmly with terms to follow). No demand to drop the litigation issue appears anywhere.', (SELECT id FROM lp_passage_16));

WITH lp_passage_17 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag)
    VALUES ('Deciding How to Disclose the Data Incident', 'When the security team confirmed that a limited set of customer email addresses had been exposed during a routine software update, the general counsel convened an urgent call with the head of communications to decide how, and when, to inform affected customers. The general counsel argued that regulation gave the company a reasonable window to complete a full technical assessment before any public statement, and that rushing out a notice before the scope was fully understood risked causing needless alarm, or worse, having to issue a confusing correction later. The communications head countered, somewhat carefully, that customers tended to be far less forgiving of a delayed disclosure than an imperfect one, and that if the story broke first through a journalist rather than the company itself, the reputational cost would dwarf any embarrassment from an early, incomplete statement. There was a pause before the general counsel conceded that she wasn''t disputing the communications logic, only flagging that legal exposure was a real cost too, not merely a theoretical one. They ultimately agreed on a compromise: a brief holding statement within forty-eight hours acknowledging an incident under investigation, followed by full details once the technical review concluded, with legal reviewing every word of the initial statement before it went out.', 'listening', 'C2', 'meeting')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('listening', 'C2', 'mcq', 'meeting', 'What was exposed during the software update?', to_jsonb(ARRAY['A limited set of customer email addresses','Customer payment card details','Employee salary records','The company''s source code']::text[]), 'A limited set of customer email addresses', 'The passage states directly that ''a limited set of customer email addresses had been exposed during a routine software update.'' None of the other data types are mentioned.', (SELECT id FROM lp_passage_17)),
  ('listening', 'C2', 'mcq', 'meeting', 'What does the general counsel''s statement that she ''wasn''t disputing the communications logic, only flagging that legal exposure was a real cost too'' reveal about the negotiation dynamic between the two executives?', to_jsonb(ARRAY['She is conceding the argument on its merits while still trying to protect her own department''s concerns from being dismissed','She fully agrees with delaying disclosure and rejects the communications head''s view entirely','She is threatening to escalate the disagreement to the CEO','She believes the communications head is acting in bad faith']::text[]), 'She is conceding the argument on its merits while still trying to protect her own department''s concerns from being dismissed', 'By explicitly saying she isn''t disputing the logic, she acknowledges the communications head''s point has force — a genuine concession — but she simultaneously insists her own concern (legal exposure) not be waved away as merely theoretical. This is a diplomatic move to avoid losing the argument entirely while still asserting her department''s stake, not a full concession (she still flags her cost as ''real''), and not rejection, escalation, or an accusation of bad faith, none of which appear in the passage.', (SELECT id FROM lp_passage_17)),
  ('listening', 'C2', 'mcq', 'meeting', 'What does the final compromise — a brief holding statement followed by full details later, with legal reviewing every word — suggest about how the two competing concerns were resolved?', to_jsonb(ARRAY['Both concerns were partially addressed by combining prompt acknowledgment with legal oversight, rather than one side fully winning','The general counsel''s view prevailed completely and disclosure was delayed indefinitely','The communications head''s view prevailed completely and legal was excluded from the process','The company decided not to disclose the incident to customers at all']::text[]), 'Both concerns were partially addressed by combining prompt acknowledgment with legal oversight, rather than one side fully winning', 'The compromise gives the communications head her prompt acknowledgment (addressing the fear of being scooped by a journalist) while giving the general counsel continued legal review of the wording (addressing her exposure concern) — neither position is adopted wholesale. The passage never states this as a summary; it must be inferred by connecting the compromise''s two features back to each executive''s earlier stated worry.', (SELECT id FROM lp_passage_17));
