-- Reading round 2: new C1/C2 passages, built inference-first. The
-- earlier fix (20260802094500) retrofitted one inference question into
-- each existing passage; this adds genuinely new content in the same
-- spirit as the listening passage round, with 2 of 3 questions per
-- passage requiring inference/synthesis/tone from the outset rather than
-- text-location lookup. 3 new C1 passages + 3 new C2 passages, 9
-- questions each level (18 total).

WITH rp2_passage_0 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag)
    VALUES ('A Delayed Product Launch', 'The product team had originally planned to launch the new inventory management tool on 1 October, but a critical bug discovered during final testing last week has pushed the release back by three weeks. The bug caused stock counts to display incorrectly under specific conditions, a fault the team considered too risky to ship given how central accurate stock data is to the tool''s whole purpose. Marketing had already scheduled a customer webinar for the original launch date, and rather than cancel it outright, the team has decided to run it as planned but reframe it as a ''sneak preview'' session, showing the interface without opening access to new customers yet. The support team has been briefed to expect a wave of migration questions once existing customers hear about the new version, even though it isn''t available to them yet. The engineering lead noted that although the delay is frustrating, shipping a tool with unreliable stock counts would have done far more damage to trust than a three-week wait ever could.', 'reading', 'C1', 'general')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('reading', 'C1', 'mcq', 'general', 'Why was the launch delayed?', to_jsonb(ARRAY['A bug that caused stock counts to display incorrectly','Marketing was not ready in time','The engineering team ran out of budget','A key team member resigned']::text[]), 'A bug that caused stock counts to display incorrectly', 'The passage states "a critical bug... caused stock counts to display incorrectly under specific conditions" was the reason for the delay; budget and staffing issues are never mentioned.', (SELECT id FROM rp2_passage_0)),
  ('reading', 'C1', 'mcq', 'general', 'Why did the team decide to still run the webinar as a "sneak preview" rather than cancel it outright?', to_jsonb(ARRAY['It let them use the already-planned event to build anticipation without promising access before the tool was ready','Marketing refused to communicate with customers about the delay at all','The bug had already been fully fixed by the time the webinar was scheduled','The company decided to launch immediately despite the bug']::text[]), 'It let them use the already-planned event to build anticipation without promising access before the tool was ready', 'This isn''t stated directly, but the passage shows the webinar was already scheduled, was kept rather than cancelled, and was reframed to show the interface "without opening access to new customers yet" -- reasoning that lets the event go ahead without overpromising, which is the opposite of refusing to communicate or launching immediately.', (SELECT id FROM rp2_passage_0)),
  ('reading', 'C1', 'mcq', 'general', 'What does the engineering lead''s comment suggest about the team''s priorities?', to_jsonb(ARRAY['They value long-term customer trust over meeting the original deadline','They believe speed of release matters more than reliability','They think customers will not notice minor bugs','They regret delaying and wish they had launched anyway']::text[]), 'They value long-term customer trust over meeting the original deadline', 'The lead says "shipping a tool with unreliable stock counts would have done far more damage to trust than a three-week wait ever could" -- explicitly ranking trust above the deadline, not expressing regret or downplaying the bug.', (SELECT id FROM rp2_passage_0));

WITH rp2_passage_1 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag)
    VALUES ('Handling a Vendor Data Breach Notification', 'Yesterday afternoon, one of our third-party vendors, a payroll processing company, notified us that a subset of their systems had been affected by unauthorised access over the weekend. According to their initial report, the exposed data may include employee names and bank account details for a limited number of staff, though the vendor has not yet confirmed exactly how many of our employees are affected or which records were accessed. Legal has advised against notifying all staff immediately, since an overly broad alert before the scope is confirmed could cause unnecessary alarm among employees who were never actually affected, and could also complicate the vendor''s own investigation if employees start contacting them directly with questions the vendor cannot yet answer. Instead, HR will prepare a holding message for all staff acknowledging that an incident has occurred at a vendor, without specifying details, while a smaller, targeted notification goes out once the vendor confirms exactly whose records were exposed. The vendor has committed to a full report within five working days, and our own security team will independently verify their findings before we consider the matter closed.', 'reading', 'C1', 'general')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('reading', 'C1', 'mcq', 'general', 'What kind of company is the vendor involved in the breach?', to_jsonb(ARRAY['A payroll processing company','A software testing firm','A recruitment agency','An insurance provider']::text[]), 'A payroll processing company', 'The passage identifies the vendor as "a payroll processing company" in the first sentence.', (SELECT id FROM rp2_passage_1)),
  ('reading', 'C1', 'mcq', 'general', 'What does the two-stage communication plan (a general holding message, then a targeted notification) suggest about the company''s approach to this incident?', to_jsonb(ARRAY['It aims to balance transparency with accuracy, avoiding premature or overly broad claims before facts are confirmed','It aims to delay informing anyone for as long as possible','It shows the company does not trust its own security team','It means only senior staff will ever be informed']::text[]), 'It aims to balance transparency with accuracy, avoiding premature or overly broad claims before facts are confirmed', 'The plan acknowledges the incident to everyone immediately (not full delay) while withholding specifics until confirmed and following up with a targeted notice -- a middle path between silence and premature over-alerting, not a trust issue with the security team, who are in fact independently verifying the vendor''s report.', (SELECT id FROM rp2_passage_1)),
  ('reading', 'C1', 'mcq', 'general', 'What does the company''s decision to independently verify the vendor''s findings suggest?', to_jsonb(ARRAY['The company is not simply taking the vendor''s report at face value','The company doubts that a breach happened at all','The company plans to terminate the vendor contract immediately','The vendor has refused to cooperate with the investigation']::text[]), 'The company is not simply taking the vendor''s report at face value', 'The passage says the security team "will independently verify their findings before we consider the matter closed" -- a due-diligence step, not evidence of doubting the breach occurred, ending the contract, or any refusal to cooperate, none of which are mentioned.', (SELECT id FROM rp2_passage_1));

WITH rp2_passage_2 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag)
    VALUES ('Piloting a New Onboarding Process', 'Following complaints from several recent hires that their first two weeks felt disorganised, HR piloted a revised onboarding process with the last cohort of eight new starters. Instead of a single, dense orientation day covering everything from IT setup to company history, the new process spreads the same content across the first two weeks, with each day focused on a single theme and a short check-in with a manager at the end of each week. Feedback from the pilot cohort was notably more positive than previous groups, particularly around feeling less overwhelmed in the first few days, though two participants noted that spreading things out made it harder to remember who to ask about administrative issues like expense claims, since that session happened on day three and wasn''t repeated. HR is treating this as a genuine trade-off rather than a flaw to eliminate entirely, and is considering adding a simple one-page reference sheet covering key contacts, distributed on day one, rather than reworking the schedule again. The revised process will now be extended to all new starters from next month, with the reference sheet included from the outset.', 'reading', 'C1', 'general')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('reading', 'C1', 'mcq', 'general', 'How many new starters were in the pilot cohort?', to_jsonb(ARRAY['Eight','Two','Twelve','Five']::text[]), 'Eight', 'The passage states HR "piloted a revised onboarding process with the last cohort of eight new starters."', (SELECT id FROM rp2_passage_2)),
  ('reading', 'C1', 'mcq', 'general', 'What does HR''s response to the administrative-contact issue suggest about their approach to the pilot''s results?', to_jsonb(ARRAY['They prefer a small, targeted fix over abandoning or overhauling a process that is otherwise working well','They plan to scrap the new onboarding process entirely','They believe the feedback was not worth acting on','They will repeat the administrative session every day going forward']::text[]), 'They prefer a small, targeted fix over abandoning or overhauling a process that is otherwise working well', 'HR is "treating this as a genuine trade-off rather than a flaw to eliminate entirely, and is considering adding a simple one-page reference sheet... rather than reworking the schedule again" -- a minimal, targeted response, not abandonment, dismissal of the feedback, or a bigger schedule change.', (SELECT id FROM rp2_passage_2)),
  ('reading', 'C1', 'mcq', 'general', 'What is the main change introduced by the new onboarding process?', to_jsonb(ARRAY['Spreading orientation content across two weeks with themed days and weekly check-ins, instead of one dense day','Removing manager check-ins from onboarding entirely','Reducing onboarding to a single half-day session','Replacing all onboarding with self-guided online modules']::text[]), 'Spreading orientation content across two weeks with themed days and weekly check-ins, instead of one dense day', 'The passage describes replacing "a single, dense orientation day" with content "spread... across the first two weeks, with each day focused on a single theme and a short check-in with a manager at the end of each week."', (SELECT id FROM rp2_passage_2));

WITH rp2_passage_3 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag)
    VALUES ('Debrief After Losing a Key Account', 'The account lead opened the debrief by acknowledging what everyone in the room already knew: after four years, Halden Manufacturing had confirmed they would not be renewing, moving their business to a competitor offering a marginally lower rate. She was careful not to frame this purely as a pricing loss, however, noting that the account team''s own quarterly check-ins had grown noticeably shorter and more transactional over the past year, and that Halden''s procurement contact had mentioned, almost in passing during the final call, that they''d stopped hearing from anyone beyond the invoicing team. The operations director pushed back gently, arguing that client relationships naturally cool once an account becomes stable and low-maintenance, and that constant hand-holding on a mature account isn''t always a good use of billable time. The account lead conceded the point in principle, but noted that ''stable'' and ''forgotten'' can look identical from the outside until a competitor calls with a lower number, at which point the absence of any real relationship leaves nothing to counter the price argument with. The team agreed to introduce a standing quarterly relationship review for all accounts above a certain size, regardless of how settled they appear.', 'reading', 'C2', 'general')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('reading', 'C2', 'mcq', 'general', 'What does the account lead ultimately suggest was the deeper cause of losing Halden''s business, beyond the competitor''s price?', to_jsonb(ARRAY['The relationship had quietly thinned out to the point where the company had nothing left to offer beyond price','Halden''s procurement contact left the company','The invoicing team made repeated billing errors','The competitor offered a dramatically lower price that could never have been matched']::text[]), 'The relationship had quietly thinned out to the point where the company had nothing left to offer beyond price', 'This connects several details: check-ins had grown "shorter and more transactional," the contact had "stopped hearing from anyone beyond the invoicing team," and the account lead''s closing point that "stable and forgotten can look identical... until a competitor calls with a lower number." The competitor''s price was only "marginally lower," not dramatic, and no billing errors or contact departure are mentioned.', (SELECT id FROM rp2_passage_3)),
  ('reading', 'C2', 'mcq', 'general', 'What is the function of the operations director''s comment about "constant hand-holding on a mature account"?', to_jsonb(ARRAY['It offers a reasonable counter-argument that some relationship cooling is normal and not inherently a mistake','It fully blames the account lead for losing the client','It proves that pricing was the only real factor in the loss','It recommends immediately increasing check-in frequency on every account']::text[]), 'It offers a reasonable counter-argument that some relationship cooling is normal and not inherently a mistake', 'The director "pushed back gently, arguing that client relationships naturally cool once an account becomes stable" -- a genuine counterpoint, not blame, not proof pricing was the sole factor, and the actual policy response (quarterly reviews) comes later from the team as a whole, not from this comment.', (SELECT id FROM rp2_passage_3)),
  ('reading', 'C2', 'mcq', 'general', 'What does the new quarterly relationship review policy suggest the team ultimately concluded?', to_jsonb(ARRAY['That relationship maintenance shouldn''t be assumed unnecessary just because an account seems settled','That all client relationships should be reviewed weekly instead of quarterly','That pricing is the only factor worth monitoring going forward','That the operations director''s view was rejected entirely']::text[]), 'That relationship maintenance shouldn''t be assumed unnecessary just because an account seems settled', 'The account lead "conceded the point in principle" (that cooling can be normal) while the team still adopted a policy guarding against relationships going unnoticed on "accounts above a certain size, regardless of how settled they appear" -- a synthesis of both views, not a rejection of either or a call for weekly reviews.', (SELECT id FROM rp2_passage_3));

WITH rp2_passage_4 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag)
    VALUES ('Reviewing a Failed Product Trial', 'The results from the six-month trial of the subscription pricing model were, in the product lead''s words, ''inconclusive in the way that matters most.'' Conversion rates among trial users were statistically indistinguishable from the control group, which on its own might suggest the new model made no difference either way. Dig into the segment data, though, and a clearer picture starts to form: among users who had cancelled a subscription with the company at least once before, the new model performed twenty percent better than the old one, while among first-time subscribers, it performed slightly worse. The product lead''s read is that the new model''s flexibility, easier pausing, prorated refunds, appeals more to users who have already been burned by rigid subscription terms elsewhere, while first-time subscribers, who have no such prior frustration to react against, find the same flexibility mildly confusing rather than reassuring. Rather than abandon the model or roll it out universally, the team is now proposing to show it only to returning users who previously cancelled, keeping the simpler original model as the default for everyone else. The finance lead noted that this segmented approach would be more complex to maintain long-term, but agreed the trial data didn''t support a one-size-fits-all conclusion either way.', 'reading', 'C2', 'general')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('reading', 'C2', 'mcq', 'general', 'What does the product lead''s phrase "inconclusive in the way that matters most" most likely mean, given what follows?', to_jsonb(ARRAY['The headline result hid a real effect that only became visible once the data was broken down by user segment','The trial produced no usable data of any kind','The trial proved the new pricing model was a complete failure','The trial proved the new pricing model should replace the old one for everyone']::text[]), 'The headline result hid a real effect that only became visible once the data was broken down by user segment', 'The overall conversion rate looked like a tie, but the segment breakdown that follows shows a real, opposite-direction effect for returning vs. first-time users -- exactly the kind of result a flat headline number obscures, not proof of total failure, universal success, or a lack of data.', (SELECT id FROM rp2_passage_4)),
  ('reading', 'C2', 'mcq', 'general', 'Why does the product lead believe the new model appeals more to previously-cancelled users than to first-time subscribers?', to_jsonb(ARRAY['Returning users have prior frustration with rigid terms that the new model''s flexibility directly answers, while first-time users have no such frustration to react against','First-time subscribers are unaware that a new pricing model exists','Returning users are offered a lower price than first-time subscribers','The new model is only technically available to returning users']::text[]), 'Returning users have prior frustration with rigid terms that the new model''s flexibility directly answers, while first-time users have no such frustration to react against', 'The passage states flexibility "appeals more to users who have already been burned by rigid subscription terms elsewhere, while first-time subscribers, who have no such prior frustration to react against, find the same flexibility mildly confusing rather than reassuring."', (SELECT id FROM rp2_passage_4)),
  ('reading', 'C2', 'mcq', 'general', 'What does the finance lead''s comment suggest about their view of the proposed segmented rollout?', to_jsonb(ARRAY['A qualified acceptance -- acknowledging added complexity while agreeing the data justifies a segmented approach over a single universal rule','Outright rejection of the segmented approach in favour of a universal rollout','Enthusiastic support for the new model over the old one in general','A demand for a second six-month trial before any decision is made']::text[]), 'A qualified acceptance -- acknowledging added complexity while agreeing the data justifies a segmented approach over a single universal rule', 'The finance lead "noted that this segmented approach would be more complex to maintain long-term, but agreed the trial data didn''t support a one-size-fits-all conclusion" -- a concern paired with agreement, not rejection, blanket enthusiasm, or a request to re-run the trial.', (SELECT id FROM rp2_passage_4));

WITH rp2_passage_5 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag)
    VALUES ('Notes From a Difficult Reference Call', 'When Priya called the listed reference for a candidate under consideration for the operations manager role, the conversation was, technically, entirely positive: competent, reliable, good with detail, nothing negative said outright. And yet she came away from the call less confident than before she''d made it, a reaction she found difficult to justify on paper. Replaying it afterward, she noticed the reference had answered every question with specific examples except one: asked directly how the candidate handled disagreement with a manager, the reference paused, said ''she''s very professional about it,'' and moved straight on to a different topic without being redirected. Every other answer had included at least one concrete anecdote; that one hadn''t. Priya raised this with the hiring panel, fully aware that she was arguing for caution based on an absence rather than a presence, a single unfilled gap in an otherwise glowing account. One panel member pointed out that not every question yields a good anecdote and that reading too much into a single hesitant answer risked penalising the candidate for the reference''s conversational style rather than anything real. Priya agreed this was a fair risk, but proposed a second, informal call with a different former colleague before making a final decision, reasoning that a genuine pattern would likely surface twice, while an isolated conversational quirk would not.', 'reading', 'C2', 'general')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('reading', 'C2', 'mcq', 'general', 'Why did Priya feel less confident after a call that was "technically, entirely positive"?', to_jsonb(ARRAY['One question about handling disagreement got a vague, example-free answer, unlike every other question in the call','The reference openly criticised the candidate''s performance','The reference refused to answer most of the questions','The reference contradicted information on the candidate''s CV']::text[]), 'One question about handling disagreement got a vague, example-free answer, unlike every other question in the call', 'The passage says every other answer "included at least one concrete anecdote; that one hadn''t" -- the single unfilled gap, not open criticism, refusal to answer, or any CV contradiction, none of which occurred.', (SELECT id FROM rp2_passage_5)),
  ('reading', 'C2', 'mcq', 'general', 'What is the function of the panel member''s objection to Priya''s concern?', to_jsonb(ARRAY['It raises a legitimate risk that Priya is over-interpreting a single vague answer rather than a real pattern','It confirms that the candidate should be rejected immediately','It proves the reference was lying throughout the call','It shows the panel member has already decided to hire the candidate']::text[]), 'It raises a legitimate risk that Priya is over-interpreting a single vague answer rather than a real pattern', 'The panel member warns against "reading too much into a single hesitant answer," which "risked penalising the candidate for the reference''s conversational style rather than anything real" -- a fair caution, not a rejection or endorsement decision, and nothing suggests the reference lied.', (SELECT id FROM rp2_passage_5)),
  ('reading', 'C2', 'mcq', 'general', 'What does Priya''s proposal to make a second call reveal about her reasoning?', to_jsonb(ARRAY['She wants to distinguish a genuine pattern from an isolated quirk before treating her concern as significant','She has already decided not to hire the candidate regardless of a second call','She believes the first reference lied about everything','She wants to replace the entire reference-checking process going forward']::text[]), 'She wants to distinguish a genuine pattern from an isolated quirk before treating her concern as significant', 'Priya reasons "that a genuine pattern would likely surface twice, while an isolated conversational quirk would not" -- she is testing her hypothesis, not pre-judging the outcome, accusing the reference of lying, or proposing a broader process change.', (SELECT id FROM rp2_passage_5));
