-- Seed content: first content round for listening/reading/grammar_vocab/writing/speaking.
-- Generated content, reviewed for CEFR calibration and answer correctness before merging.

-- Listening (30 mcq)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation) VALUES
  ('listening', 'A1', 'mcq', 'call', 'You hear: "Please call me back at three o''clock." What time should the person call back?', to_jsonb(ARRAY['At two o''clock','At three o''clock','At four o''clock','At one o''clock']::text[]), 'At three o''clock', 'The speaker says "call me back at three o''clock," directly stating the time.'),
  ('listening', 'A1', 'mcq', 'meeting', 'You hear: "The meeting starts at nine o''clock in room two." Where is the meeting?', to_jsonb(ARRAY['Room one','Room two','Room three','Room four']::text[]), 'Room two', 'The script states the meeting is "in room two."'),
  ('listening', 'A1', 'mcq', 'customer_service', 'You hear: "Your order number is one two three." What is the order number?', to_jsonb(ARRAY['123','132','213','321']::text[]), '123', 'The digits are given in order as "one two three," which is 123.'),
  ('listening', 'A1', 'mcq', 'general', 'You hear: "The office is closed on Monday." Which day is the office closed?', to_jsonb(ARRAY['Monday','Tuesday','Wednesday','Friday']::text[]), 'Monday', 'The script directly names "Monday" as the closed day.'),
  ('listening', 'A1', 'mcq', 'negotiation', 'You hear: "We can offer a ten percent discount." What discount can they offer?', to_jsonb(ARRAY['Five percent','Ten percent','Fifteen percent','Twenty percent']::text[]), 'Ten percent', 'The speaker states "a ten percent discount" exactly.'),
  ('listening', 'A2', 'mcq', 'call', 'You hear: "Hi, this is Mark from the IT department. I''m calling to say the system will be down tomorrow morning." When will the system be down?', to_jsonb(ARRAY['Tomorrow morning','Tomorrow afternoon','Today morning','Next week']::text[]), 'Tomorrow morning', 'Mark says the system "will be down tomorrow morning," ruling out the other time options.'),
  ('listening', 'A2', 'mcq', 'meeting', 'You hear: "The training session was moved from Tuesday to Thursday." Which day is the training now?', to_jsonb(ARRAY['Tuesday','Wednesday','Thursday','Friday']::text[]), 'Thursday', 'The session was "moved from Tuesday to Thursday," so Thursday is the new date; Tuesday is the old date.'),
  ('listening', 'A2', 'mcq', 'customer_service', 'You hear: "Thank you for calling. Your package will arrive in three days." How many days until the package arrives?', to_jsonb(ARRAY['Two','Three','Four','Five']::text[]), 'Three', 'The agent states the package "will arrive in three days."'),
  ('listening', 'A2', 'mcq', 'negotiation', 'You hear: "We usually ask for fifty euros, but we can offer it for forty euros today." What is today''s price?', to_jsonb(ARRAY['Fifty euros','Forty euros','Thirty euros','Sixty euros']::text[]), 'Forty euros', 'The word "but" signals the special today''s price of "forty euros," as opposed to the usual fifty.'),
  ('listening', 'A2', 'mcq', 'general', 'You hear: "The new printer is on the second floor, next to the kitchen." Where is the new printer?', to_jsonb(ARRAY['First floor near the kitchen','Second floor next to the kitchen','Third floor near the elevator','Second floor near reception']::text[]), 'Second floor next to the kitchen', 'The script places the printer "on the second floor, next to the kitchen," matching both details.'),
  ('listening', 'B1', 'mcq', 'call', 'You hear: "I tried calling you this morning, but the line was busy. Can you call me back before five o''clock?" What does the caller want?', to_jsonb(ARRAY['To be called back before five o''clock','To be called back after five o''clock','To receive an email instead','To visit the office in person']::text[]), 'To be called back before five o''clock', 'The caller explicitly asks, "Can you call me back before five o''clock?"'),
  ('listening', 'B1', 'mcq', 'meeting', 'You hear: "The weekly meeting usually happens on Monday, but this week it''s on Wednesday because the manager is traveling." Why is the meeting on Wednesday this week?', to_jsonb(ARRAY['Because the manager is traveling','Because the room is booked','Because it''s a holiday','Because of a client visit']::text[]), 'Because the manager is traveling', 'The connector "because" links the Wednesday change directly to the manager traveling.'),
  ('listening', 'B1', 'mcq', 'customer_service', 'You hear: "I understand you ordered a blue jacket, but unfortunately we only have it in black and grey now." What color jacket did the customer originally order?', to_jsonb(ARRAY['Blue','Black','Grey','Red']::text[]), 'Blue', 'The agent says "you ordered a blue jacket," while black and grey are only the currently available colors.'),
  ('listening', 'B1', 'mcq', 'negotiation', 'You hear: "We can reduce the price by ten percent if you sign the contract today, but only five percent if you decide next week." What discount applies if the client signs today?', to_jsonb(ARRAY['Five percent','Ten percent','Fifteen percent','No discount']::text[]), 'Ten percent', 'The script ties "ten percent" specifically to signing "today," while five percent applies to next week.'),
  ('listening', 'B1', 'mcq', 'general', 'You hear: "The office will close early on Friday for the staff party, but it opens as normal on Monday." When does the office close early?', to_jsonb(ARRAY['Friday','Monday','Saturday','Thursday']::text[]), 'Friday', 'The office closes early "on Friday," while Monday is explicitly described as normal.'),
  ('listening', 'B2', 'mcq', 'call', 'You hear: "I''m sorry, Mr. Dubois is in a meeting until three, but he asked me to let you know that he''ll call you as soon as he''s free." When will Mr. Dubois likely call back?', to_jsonb(ARRAY['Before three o''clock','Sometime after three o''clock','Tomorrow','He won''t call back']::text[]), 'Sometime after three o''clock', 'Since he is in a meeting "until three" and will call "as soon as he''s free," the call must come after three.'),
  ('listening', 'B2', 'mcq', 'meeting', 'You hear: "The quarterly review has been pushed back a week because two of the regional managers can''t attend, and we need everyone present for the budget discussion." Why was the meeting postponed?', to_jsonb(ARRAY['Because two regional managers are unavailable','Because the budget wasn''t ready','Because of a venue problem','Because it was cancelled']::text[]), 'Because two regional managers are unavailable', 'The script gives the reason directly: "two of the regional managers can''t attend."'),
  ('listening', 'B2', 'mcq', 'customer_service', 'You hear: "I can see your refund was processed on Monday, but it can take up to five business days to appear in your account, so please check again by the end of this week." By when should the customer expect to see the refund?', to_jsonb(ARRAY['By the end of this week','Immediately','Next month','On Monday']::text[]), 'By the end of this week', 'The agent directly instructs the customer to "check again by the end of this week," not on Monday, when it was only processed.'),
  ('listening', 'B2', 'mcq', 'negotiation', 'You hear: "If you commit to a twelve-month contract, we can lower the monthly fee, but a six-month contract stays at the standard rate." What is required to get a lower monthly fee?', to_jsonb(ARRAY['Signing a twelve-month contract','Signing a six-month contract','Paying upfront','Increasing order volume']::text[]), 'Signing a twelve-month contract', 'The lower fee is tied to the "twelve-month contract," while the six-month option explicitly stays at the standard rate.'),
  ('listening', 'B2', 'mcq', 'general', 'You hear: "Since the parking garage is being repaired this week, staff are asked to use the public lot across the street, though visitors can still use the main entrance." Where should staff park this week?', to_jsonb(ARRAY['The public lot across the street','The parking garage','The main entrance','There is no parking available']::text[]), 'The public lot across the street', 'Staff are directed to "the public lot across the street" because the garage is under repair; the main entrance is only for visitors.'),
  ('listening', 'C1', 'mcq', 'call', 'You hear: "Look, I don''t want to put you on the spot, but is there any chance you could squeeze in a call with the client before Friday? I know it''s short notice." What is the caller asking the listener to do?', to_jsonb(ARRAY['Arrange a call with the client before Friday','Cancel the call with the client','Wait until after Friday','Reschedule for next month']::text[]), 'Arrange a call with the client before Friday', 'The indirect request "could you squeeze in a call... before Friday" means fitting the call in before that deadline.'),
  ('listening', 'C1', 'mcq', 'meeting', 'You hear: "To be honest, I think we should hold off on finalizing the roadmap until marketing weighs in, even if that means pushing the deadline." What does the speaker suggest?', to_jsonb(ARRAY['Delaying the roadmap decision until marketing gives input','Finalizing the roadmap immediately','Cancelling the roadmap entirely','Asking marketing to leave the meeting']::text[]), 'Delaying the roadmap decision until marketing gives input', '"Hold off on finalizing... until marketing weighs in" means waiting for marketing''s input before deciding.'),
  ('listening', 'C1', 'mcq', 'customer_service', 'You hear: "I hear what you''re saying about the delay, and while I can''t promise a same-day fix, I''ll make sure this gets bumped up the priority list." What does the representative commit to?', to_jsonb(ARRAY['Giving the issue higher priority','Fixing it the same day','Refusing to help further','Transferring the call elsewhere']::text[]), 'Giving the issue higher priority', '"Bumped up the priority list" is the commitment made, while a same-day fix is explicitly ruled out.'),
  ('listening', 'C1', 'mcq', 'negotiation', 'You hear: "We''re not miles apart on price, but if you could meet us halfway on the delivery timeline, I think we''d have a deal." What does the speaker want the other side to compromise on?', to_jsonb(ARRAY['The delivery timeline','The price','The payment method','The contract length']::text[]), 'The delivery timeline', 'The speaker says price is already close ("not miles apart") and asks for compromise "on the delivery timeline."'),
  ('listening', 'C1', 'mcq', 'general', 'You hear: "It''s not that the new system is bad, exactly, it''s just that nobody''s had time to get up to speed, so teething problems are bound to happen." What does the speaker imply is causing the problems?', to_jsonb(ARRAY['Lack of time to learn the new system','The system being fundamentally broken','Staff refusing to use the system','A lack of budget']::text[]), 'Lack of time to learn the new system', '"Nobody''s had time to get up to speed" points to unfamiliarity, not a faulty system, which the speaker explicitly denies.'),
  ('listening', 'C2', 'mcq', 'call', 'You hear: "Honestly, I''d love to say the numbers are looking rosy, but between you and me, we''re cutting it fine this quarter." What is the speaker really saying about the quarter''s numbers?', to_jsonb(ARRAY['They are close to missing targets','They are excellent','They are guaranteed to succeed','They have already failed']::text[]), 'They are close to missing targets', '"Cutting it fine" means a narrow margin of success; the "but" after "rosy" signals the opposite of a positive picture.'),
  ('listening', 'C2', 'mcq', 'meeting', 'You hear: "I''m not saying it''s a done deal, but let''s just say the client didn''t exactly slam the door on the proposal." What can be inferred about the client''s reaction?', to_jsonb(ARRAY['The client showed some openness to the proposal','The client rejected the proposal outright','The client had no reaction at all','The client already signed the deal']::text[]), 'The client showed some openness to the proposal', '"Didn''t exactly slam the door" is a litotes meaning the client did not reject it, while "not a done deal" rules out a signed agreement.'),
  ('listening', 'C2', 'mcq', 'customer_service', 'You hear: "I won''t pretend this hasn''t been a headache for you, and while I can''t wave a magic wand, I can get you a replacement out by tomorrow." What can the representative actually do?', to_jsonb(ARRAY['Send a replacement by tomorrow','Solve the problem instantly','Refuse to help further','Do nothing at all']::text[]), 'Send a replacement by tomorrow', '"Can''t wave a magic wand" rules out an instant fix, but the concrete commitment is a replacement "by tomorrow."'),
  ('listening', 'C2', 'mcq', 'negotiation', 'You hear: "Let''s not beat around the bush: your last offer was a bit of a non-starter for us, but this new figure is definitely in the right ballpark." How does the speaker feel about the new figure compared to the last offer?', to_jsonb(ARRAY['The new figure is much closer to acceptable','The new figure is equally unacceptable','The new figure is still a non-starter','The new figure is too high to consider']::text[]), 'The new figure is much closer to acceptable', '"In the right ballpark" contrasts with the earlier "non-starter," showing the new figure is now near acceptable.'),
  ('listening', 'C2', 'mcq', 'general', 'You hear: "Between the lines, management''s ''restructuring'' announcement this morning sounded a lot like layoffs are coming, even if nobody used that word." What does the speaker suggest management''s announcement really means?', to_jsonb(ARRAY['Job cuts are likely coming','The company is expanding','Nothing will change','Management explicitly announced layoffs']::text[]), 'Job cuts are likely coming', '"Sounded a lot like layoffs" is the implied meaning, though the script states "nobody used that word," ruling out an explicit announcement.');

-- Grammar & Vocabulary (72 mcq)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation) VALUES
  ('grammar_vocab', 'A1', 'mcq', 'tenses', 'She _____ a manager at this company.', to_jsonb(ARRAY['is','are','am','be']::text[]), 'is', 'The verb ''to be'' takes the form ''is'' with third-person singular subjects like ''she''.'),
  ('grammar_vocab', 'A1', 'mcq', 'tenses', 'I _____ from Paris.', to_jsonb(ARRAY['am','is','are','be']::text[]), 'am', 'The verb ''to be'' takes the form ''am'' with the first-person singular subject ''I''.'),
  ('grammar_vocab', 'A2', 'mcq', 'tenses', 'Yesterday, we _____ a meeting at 9 a.m.', to_jsonb(ARRAY['had','have','has','having']::text[]), 'had', '''Yesterday'' signals a completed past action, so the past simple form ''had'' is required.'),
  ('grammar_vocab', 'A2', 'mcq', 'tenses', 'I _____ to finish the report tomorrow.', to_jsonb(ARRAY['am going','go','went','will going']::text[]), 'am going', '''Going to'' expresses a planned future action, formed with ''am/is/are + going to + verb''.'),
  ('grammar_vocab', 'B1', 'mcq', 'tenses', 'She _____ the report already.', to_jsonb(ARRAY['has finished','finished since','is finishing since','have finished']::text[]), 'has finished', '''Already'' with a third-person singular subject requires the present perfect ''has finished''.'),
  ('grammar_vocab', 'B1', 'mcq', 'tenses', 'If it _____ tomorrow, we will cancel the outdoor meeting.', to_jsonb(ARRAY['rains','will rain','rained','is raining']::text[]), 'rains', 'In the first conditional, the ''if'' clause uses present simple even though it refers to the future.'),
  ('grammar_vocab', 'B2', 'mcq', 'tenses', 'By the time the client arrived, the team _____ the presentation.', to_jsonb(ARRAY['had finished','finished','has finished','was finishing']::text[]), 'had finished', 'Past perfect (''had finished'') shows an action completed before another past action (''arrived'').'),
  ('grammar_vocab', 'B2', 'mcq', 'tenses', 'The contract _____ by the legal department last week.', to_jsonb(ARRAY['was reviewed','reviewed','has reviewed','is reviewing']::text[]), 'was reviewed', 'The passive voice (''was reviewed'') is needed because the contract receives the action, and ''last week'' requires past simple.'),
  ('grammar_vocab', 'C1', 'mcq', 'tenses', 'If we _____ the deadline sooner, we wouldn''t have lost the client.', to_jsonb(ARRAY['had known','knew','have known','would know']::text[]), 'had known', 'The third conditional uses past perfect in the ''if'' clause to describe a hypothetical past situation.'),
  ('grammar_vocab', 'C1', 'mcq', 'tenses', 'The manager said, ''The project is delayed.'' Report this: ''The manager said that the project _____ delayed.''', to_jsonb(ARRAY['was','is','had been','would be']::text[]), 'was', 'In reported speech, present simple (''is'') backshifts to past simple (''was'') after a past reporting verb.'),
  ('grammar_vocab', 'C2', 'mcq', 'tenses', 'If she _____ harder at university, she would be running her own company by now.', to_jsonb(ARRAY['had worked','worked','has worked','would have worked']::text[]), 'had worked', 'This mixed conditional uses past perfect for the completed past condition (university) with a present result clause.'),
  ('grammar_vocab', 'C2', 'mcq', 'tenses', 'By next year, she _____ at the firm for two decades.', to_jsonb(ARRAY['will have been working','will be working','has been working','will work']::text[]), 'will have been working', 'Future perfect continuous emphasizes the duration of an action that continues up to a specific point in the future.'),
  ('grammar_vocab', 'A1', 'mcq', 'prepositions', 'The meeting is _____ Monday.', to_jsonb(ARRAY['on','in','at','for']::text[]), 'on', '''On'' is used with days of the week.'),
  ('grammar_vocab', 'A1', 'mcq', 'prepositions', 'Our office is _____ the third floor.', to_jsonb(ARRAY['on','in','at','by']::text[]), 'on', '''On'' is the correct preposition for floors of a building.'),
  ('grammar_vocab', 'A2', 'mcq', 'prepositions', 'I usually arrive at work _____ 9 a.m.', to_jsonb(ARRAY['at','on','in','for']::text[]), 'at', '''At'' is used with precise clock times.'),
  ('grammar_vocab', 'A2', 'mcq', 'prepositions', 'She has worked here _____ 2019.', to_jsonb(ARRAY['since','for','from','at']::text[]), 'since', '''Since'' is used with a specific starting point in time alongside the present perfect.'),
  ('grammar_vocab', 'B1', 'mcq', 'prepositions', 'We have been waiting _____ two hours.', to_jsonb(ARRAY['for','since','during','at']::text[]), 'for', '''For'' is used with a period of duration, unlike ''since'', which marks a starting point.'),
  ('grammar_vocab', 'B1', 'mcq', 'prepositions', 'Please send the report _____ Friday.', to_jsonb(ARRAY['by','until','till','at']::text[]), 'by', '''By'' marks a deadline for a single completed action, while ''until'' describes an ongoing action continuing up to that point.'),
  ('grammar_vocab', 'B2', 'mcq', 'prepositions', 'The proposal was rejected _____ the board due to budget concerns.', to_jsonb(ARRAY['by','from','with','of']::text[]), 'by', '''By'' introduces the agent performing the action in a passive sentence.'),
  ('grammar_vocab', 'B2', 'mcq', 'prepositions', 'He apologized _____ the delay in the shipment.', to_jsonb(ARRAY['for','about','of','with']::text[]), 'for', '''Apologize'' is followed by ''for'' when referring to the reason for the apology.'),
  ('grammar_vocab', 'C1', 'mcq', 'prepositions', 'The company is committed _____ reducing its carbon footprint.', to_jsonb(ARRAY['to','for','in','with']::text[]), 'to', '''Committed to'' is the fixed collocation, followed by a noun or gerund.'),
  ('grammar_vocab', 'C1', 'mcq', 'prepositions', '_____ several setbacks, the team met the deadline.', to_jsonb(ARRAY['Despite','Despite of','In spite','Although of']::text[]), 'Despite', '''Despite'' is followed directly by a noun phrase with no ''of'', unlike ''in spite of''.'),
  ('grammar_vocab', 'C2', 'mcq', 'prepositions', 'The negotiations broke down _____ a disagreement over pricing.', to_jsonb(ARRAY['over','about','for','at']::text[]), 'over', '''Break down over'' is the natural collocation linking a failure to its underlying cause.'),
  ('grammar_vocab', 'C2', 'mcq', 'prepositions', 'She was praised _____ her meticulous attention to detail.', to_jsonb(ARRAY['for','of','about','with']::text[]), 'for', '''Praised for'' introduces the reason someone is commended.'),
  ('grammar_vocab', 'A1', 'mcq', 'business_vocab', 'Please put the documents on my _____.', to_jsonb(ARRAY['desk','floor','window','road']::text[]), 'desk', '''Desk'' is the everyday office noun for a piece of furniture where documents are placed.'),
  ('grammar_vocab', 'A1', 'mcq', 'business_vocab', 'The _____ starts the weekly meeting every Monday.', to_jsonb(ARRAY['manager','driver','dentist','chef']::text[]), 'manager', '''Manager'' is the office role responsible for leading team meetings.'),
  ('grammar_vocab', 'A2', 'mcq', 'business_vocab', 'We need to order more paper for the _____.', to_jsonb(ARRAY['printer','oven','garden','bicycle']::text[]), 'printer', '''Printer'' is the office machine that requires paper to function.'),
  ('grammar_vocab', 'A2', 'mcq', 'business_vocab', 'Can you check my _____? I haven''t read my messages today.', to_jsonb(ARRAY['email','recipe','passport','menu']::text[]), 'email', '''Email'' is the workplace tool used for sending and reading messages.'),
  ('grammar_vocab', 'B1', 'mcq', 'business_vocab', 'The client hasn''t paid the _____ yet.', to_jsonb(ARRAY['invoice','napkin','umbrella','ticket']::text[]), 'invoice', 'An ''invoice'' is the document requesting payment for goods or services.'),
  ('grammar_vocab', 'B1', 'mcq', 'business_vocab', 'I need to finish this before the _____ on Friday.', to_jsonb(ARRAY['deadline','holiday','breakfast','weather']::text[]), 'deadline', '''Deadline'' refers to the latest time by which a task must be completed.'),
  ('grammar_vocab', 'B2', 'mcq', 'business_vocab', 'Our _____ increased by 15% this quarter.', to_jsonb(ARRAY['revenue','recipe','rainfall','traffic']::text[]), 'revenue', '''Revenue'' refers to the income a business generates, which can rise or fall by a percentage.'),
  ('grammar_vocab', 'B2', 'mcq', 'business_vocab', 'The company announced a new _____ to cut costs.', to_jsonb(ARRAY['strategy','recipe','vacation','melody']::text[]), 'strategy', '''Strategy'' refers to a business plan aimed at achieving a goal such as cost reduction.'),
  ('grammar_vocab', 'C1', 'mcq', 'business_vocab', 'The merger will help the company gain a competitive _____ in the market.', to_jsonb(ARRAY['advantage','headache','vacation','rumor']::text[]), 'advantage', '''Competitive advantage'' is a fixed business term describing an edge over rivals.'),
  ('grammar_vocab', 'C1', 'mcq', 'business_vocab', 'Management decided to _____ the underperforming division.', to_jsonb(ARRAY['restructure','decorate','celebrate','relax']::text[]), 'restructure', '''Restructure'' means to reorganize a business division, often to improve performance.'),
  ('grammar_vocab', 'C2', 'mcq', 'business_vocab', 'The board expressed concerns about the company''s _____ in the current economic climate.', to_jsonb(ARRAY['solvency','hospitality','curiosity','festivity']::text[]), 'solvency', '''Solvency'' refers to a company''s ability to meet its financial obligations, a key concern in economic downturns.'),
  ('grammar_vocab', 'C2', 'mcq', 'business_vocab', 'The CEO''s decision was seen as a bold move to _____ market share from competitors.', to_jsonb(ARRAY['capture','borrow','donate','discard']::text[]), 'capture', '''Capture market share'' is a fixed expression meaning to gain a portion of the market from rivals.'),
  ('grammar_vocab', 'A1', 'mcq', 'phrasal_verbs', 'Please _____ the light before you leave the office.', to_jsonb(ARRAY['turn off','turn up','turn into','turn away']::text[]), 'turn off', '''Turn off'' means to stop a device or light from operating.'),
  ('grammar_vocab', 'A1', 'mcq', 'phrasal_verbs', 'Can you _____ the computer? It''s time to start work.', to_jsonb(ARRAY['turn on','turn down','turn over','turn away']::text[]), 'turn on', '''Turn on'' means to start a device operating.'),
  ('grammar_vocab', 'A2', 'mcq', 'phrasal_verbs', 'I am _____ my glasses; have you seen them?', to_jsonb(ARRAY['looking for','looking at','looking up','looking after']::text[]), 'looking for', '''Look for'' means to search for something that is missing.'),
  ('grammar_vocab', 'A2', 'mcq', 'phrasal_verbs', 'Can you _____ the new employee from the airport?', to_jsonb(ARRAY['pick up','pick on','pick out','pick over']::text[]), 'pick up', '''Pick up'' means to collect someone from a location.'),
  ('grammar_vocab', 'B1', 'mcq', 'phrasal_verbs', 'We need to _____ the meeting until next week.', to_jsonb(ARRAY['put off','put on','put up','put out']::text[]), 'put off', '''Put off'' means to postpone something to a later time.'),
  ('grammar_vocab', 'B1', 'mcq', 'phrasal_verbs', 'Please _____ the details before you send the email.', to_jsonb(ARRAY['fill in','switch on','turn down','give up']::text[]), 'fill in', '''Fill in'' means to add required information, such as details in a document.'),
  ('grammar_vocab', 'B2', 'mcq', 'phrasal_verbs', 'The team will _____ a full risk assessment before launch.', to_jsonb(ARRAY['carry out','carry on','carry over','carry away']::text[]), 'carry out', '''Carry out'' means to perform or execute a task, such as an assessment.'),
  ('grammar_vocab', 'B2', 'mcq', 'phrasal_verbs', 'I''ll _____ with the client after the demo to see if they have questions.', to_jsonb(ARRAY['follow up','follow after','follow on','follow out']::text[]), 'follow up', '''Follow up with someone'' means to contact them again after an initial interaction.'),
  ('grammar_vocab', 'C1', 'mcq', 'phrasal_verbs', 'The new policy will _____ effect from January 1st.', to_jsonb(ARRAY['come into','come up with','come across','come along']::text[]), 'come into', '''Come into effect'' is a fixed phrase meaning to become legally or officially active.'),
  ('grammar_vocab', 'C1', 'mcq', 'phrasal_verbs', 'Management decided to _____ the project due to lack of funding.', to_jsonb(ARRAY['call off','call on','call up','call in']::text[]), 'call off', '''Call off'' means to cancel something that was planned.'),
  ('grammar_vocab', 'C2', 'mcq', 'phrasal_verbs', 'After months of negotiation, the two companies finally _____ an agreement.', to_jsonb(ARRAY['hammered out','knocked out','wiped out','burned out']::text[]), 'hammered out', '''Hammer out'' is an idiom meaning to reach an agreement through prolonged, effortful discussion.'),
  ('grammar_vocab', 'C2', 'mcq', 'phrasal_verbs', 'The scandal caused the CEO to _____ from her position.', to_jsonb(ARRAY['step down','step up','step in','step out']::text[]), 'step down', '''Step down'' means to resign from a position of authority.'),
  ('grammar_vocab', 'A1', 'mcq', 'formal_register', 'In a formal email to a client, which greeting is correct?', to_jsonb(ARRAY['Dear Mr. Smith,','Hey Smith!','Yo Smith,','Hiya']::text[]), 'Dear Mr. Smith,', '''Dear Mr. Smith,'' is the standard formal greeting used to address a client respectfully in writing.'),
  ('grammar_vocab', 'A1', 'mcq', 'formal_register', 'You are writing a formal message to your boss. Which is correct?', to_jsonb(ARRAY['I would like to request a day off.','Gimme a day off.','Can I get a day off, dude?','I wanna day off.']::text[]), 'I would like to request a day off.', 'Formal messages to a superior avoid slang and contractions like ''gimme'' or ''wanna''.'),
  ('grammar_vocab', 'A2', 'mcq', 'formal_register', 'In a formal email, which ending is correct?', to_jsonb(ARRAY['Best regards,','See ya,','Later,','Bye bye']::text[]), 'Best regards,', '''Best regards,'' is a standard formal closing phrase for professional emails.'),
  ('grammar_vocab', 'A2', 'mcq', 'formal_register', 'You are chatting with a close colleague at the coffee machine. Which is natural?', to_jsonb(ARRAY['Hey, how''s it going?','I trust this message finds you well.','I am writing to inform you...','Please be advised']::text[]), 'Hey, how''s it going?', 'Casual spoken conversation with a close colleague calls for informal, everyday phrasing rather than formal written expressions.'),
  ('grammar_vocab', 'B1', 'mcq', 'formal_register', 'In a formal email to a client, complete: ''I am writing _____ the delay in your order.''', to_jsonb(ARRAY['to inform you about','to tell you ''bout','to let you know ''bout','to say sorry ''bout']::text[]), 'to inform you about', 'Formal emails avoid spoken contractions like ''''bout'' and use complete, professional phrasing.'),
  ('grammar_vocab', 'B1', 'mcq', 'formal_register', 'Chatting informally with a close colleague, which is natural?', to_jsonb(ARRAY['Can you help me out with this?','I would be grateful if you could assist me.','I am writing to request your assistance.','Kindly assist me at your earliest convenience.']::text[]), 'Can you help me out with this?', 'Informal spoken requests between close colleagues use simple, everyday phrasal expressions rather than formal written language.'),
  ('grammar_vocab', 'B2', 'mcq', 'formal_register', 'In a formal report to senior management, which phrase is appropriate?', to_jsonb(ARRAY['The results indicate a significant improvement.','The results are pretty great, tbh.','We got awesome results!','Results-wise, it''s lit.']::text[]), 'The results indicate a significant improvement.', 'Formal reports use precise, neutral vocabulary and avoid slang such as ''tbh'' or ''lit''.'),
  ('grammar_vocab', 'B2', 'mcq', 'formal_register', 'Texting a close colleague about being late, which is natural?', to_jsonb(ARRAY['Running a bit late, sorry!','I regret to inform you that I shall be delayed.','Please be advised of my late arrival.','I wish to notify you of a delay.']::text[]), 'Running a bit late, sorry!', 'A quick informal text to a close colleague calls for casual, brief phrasing rather than formal written language.'),
  ('grammar_vocab', 'C1', 'mcq', 'formal_register', 'In a formal letter declining a business proposal, which is most appropriate?', to_jsonb(ARRAY['We regret to inform you that we are unable to proceed with your proposal at this time.','Sorry, but nah, we''re not doing this.','We''re gonna pass on this one.','Not interested, thanks.']::text[]), 'We regret to inform you that we are unable to proceed with your proposal at this time.', 'A formal business letter requires polite, professional phrasing rather than casual refusals.'),
  ('grammar_vocab', 'C1', 'mcq', 'formal_register', 'Emailing a close colleague to ask for quick feedback, which is natural?', to_jsonb(ARRAY['Could you take a quick look and let me know what you think?','I should be grateful if you would kindly review the attached document.','Your prompt attention to this matter would be appreciated.','I am writing to solicit your feedback.']::text[]), 'Could you take a quick look and let me know what you think?', 'A quick, informal email to a close colleague uses direct, conversational phrasing rather than highly formal constructions.'),
  ('grammar_vocab', 'C2', 'mcq', 'formal_register', 'In a formal email to a senior client raising a sensitive billing issue, which phrasing is most appropriate?', to_jsonb(ARRAY['We would like to draw your attention to a discrepancy in the recent invoice.','We noticed you messed up the invoice.','Your invoice''s kind of wrong.','Heads up, the invoice is off.']::text[]), 'We would like to draw your attention to a discrepancy in the recent invoice.', 'A sensitive issue with a senior client requires tactful, formal phrasing that avoids blame and casual wording.'),
  ('grammar_vocab', 'C2', 'mcq', 'formal_register', 'Which sentence best fits a casual internal Slack message to a peer, rather than a client-facing email?', to_jsonb(ARRAY['Quick one — can you check this before EOD?','I would be most grateful if you could review this prior to the close of business.','Kindly review the attached at your earliest convenience.','I am writing to request a timely review.']::text[]), 'Quick one — can you check this before EOD?', 'Internal chat messages between peers favor brief, informal phrasing like ''EOD'', unlike the elevated formality suited to client-facing emails.'),
  ('grammar_vocab', 'A1', 'mcq', 'collocations', 'Please _____ a seat while you wait.', to_jsonb(ARRAY['take','make','do','give']::text[]), 'take', '''Take a seat'' is the fixed collocation used to invite someone to sit down.'),
  ('grammar_vocab', 'A1', 'mcq', 'collocations', 'I need to _____ a phone call to a client before the meeting.', to_jsonb(ARRAY['make','do','take','have']::text[]), 'make', '''Make a phone call'' is the fixed collocation for initiating a call to someone.'),
  ('grammar_vocab', 'A2', 'mcq', 'collocations', 'Can you _____ me a favor?', to_jsonb(ARRAY['do','make','take','have']::text[]), 'do', '''Do someone a favor'' is the fixed collocation, unlike ''make a favor'', which is incorrect in English.'),
  ('grammar_vocab', 'A2', 'mcq', 'collocations', 'We should _____ a break after this task.', to_jsonb(ARRAY['take','make','do','hold']::text[]), 'take', '''Take a break'' is the standard collocation for pausing an activity to rest.'),
  ('grammar_vocab', 'B1', 'mcq', 'collocations', 'The team is starting to _____ progress on the project.', to_jsonb(ARRAY['make','do','take','have']::text[]), 'make', '''Make progress'' is the fixed collocation describing advancement toward a goal.'),
  ('grammar_vocab', 'B1', 'mcq', 'collocations', 'We need to _____ a decision by Friday.', to_jsonb(ARRAY['make','do','give','have']::text[]), 'make', '''Make a decision'' is the fixed collocation meaning to decide on something.'),
  ('grammar_vocab', 'B2', 'mcq', 'collocations', 'The two companies managed to _____ an agreement after weeks of talks.', to_jsonb(ARRAY['reach','catch','hold','win']::text[]), 'reach', '''Reach an agreement'' is the fixed collocation meaning to arrive at a mutual decision after negotiation.'),
  ('grammar_vocab', 'B2', 'mcq', 'collocations', 'It''s important to _____ a good impression during the interview.', to_jsonb(ARRAY['make','do','take','hold']::text[]), 'make', '''Make a good impression'' is the fixed collocation for creating a favorable opinion in someone''s mind.'),
  ('grammar_vocab', 'C1', 'mcq', 'collocations', 'After lengthy discussion, the committee finally _____ a consensus.', to_jsonb(ARRAY['reached','caught','held','took']::text[]), 'reached', '''Reach a consensus'' is the fixed collocation for arriving at general agreement after discussion.'),
  ('grammar_vocab', 'C1', 'mcq', 'collocations', 'The new regulations aim to _____ the risk of financial fraud.', to_jsonb(ARRAY['mitigate','repair','decorate','celebrate']::text[]), 'mitigate', '''Mitigate risk'' is a fixed business collocation meaning to reduce the severity of a potential problem.'),
  ('grammar_vocab', 'C2', 'mcq', 'collocations', 'The company worked quickly to _____ the fallout from the data breach.', to_jsonb(ARRAY['contain','hold','catch','win']::text[]), 'contain', '''Contain the fallout'' is a fixed collocation meaning to limit the negative consequences of an event.'),
  ('grammar_vocab', 'C2', 'mcq', 'collocations', 'The negotiators worked hard to _____ common ground between the two parties.', to_jsonb(ARRAY['find','make','take','do']::text[]), 'find', '''Find common ground'' is the fixed collocation meaning to identify shared interests between parties.');

-- Writing (12 prompt)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, explanation) VALUES
  ('writing', 'A1', 'prompt', 'email', 'Confirm a meeting time

Your manager, Mr. Diallo, asked you to meet on Thursday. Write a short email to confirm the day and time (10:00) and say where (his office). (30–50 words)', 'A strong response uses simple present-tense sentences to state a day, time, and place clearly.'),
  ('writing', 'A1', 'prompt', 'general', 'Out-of-office note

You are away from the office on Friday for a doctor''s appointment. Write a short note for your colleagues. Say you are away, the date, and who to contact instead (Anna). (30–50 words)', 'A strong response gives the absence date and a clear alternative contact using basic vocabulary.'),
  ('writing', 'A2', 'prompt', 'email', 'Ask a colleague for a file

Write an email to your colleague Marco. Ask him to send you the sales report from last week before Wednesday. Explain briefly why you need it. (50–80 words)', 'A strong response makes a clear, polite request with a simple reason and a deadline.'),
  ('writing', 'A2', 'prompt', 'customer_service', 'Reply to a simple customer question

A customer emailed asking what time your shop opens on Saturdays. Write a short reply. Give the opening time (9:30) and thank them for writing. (50–80 words)', 'A strong response answers the question directly and uses polite, simple customer-facing language.'),
  ('writing', 'B1', 'prompt', 'email', 'Explain a delay to a client

Your company''s delivery to client Mrs. Novak will be three days late because of a supplier problem. Write an email explaining the delay, apologizing, and giving the new delivery date. (80–120 words)', 'A strong response explains a cause-and-effect situation clearly and maintains an apologetic, professional tone.'),
  ('writing', 'B1', 'prompt', 'general', 'Summarize a team decision

Your team decided in yesterday''s meeting to move the project deadline from June 1 to June 15 because of extra testing needed. Write a short message to the team explaining the decision and the reason. (80–120 words)', 'A strong response reports past decisions accurately and links the reason to the outcome logically.'),
  ('writing', 'B2', 'prompt', 'customer_service', 'Reply to a customer complaint

A customer, Mr. Hendricks, wrote to complain that his order arrived damaged. Write a reply that acknowledges the problem, apologizes, explains what you will do (replace the item within 5 days), and offers a small discount on his next order. (120–160 words)', 'A strong response balances empathy with a clear resolution plan, using appropriately formal customer-service tone.'),
  ('writing', 'B2', 'prompt', 'email', 'Propose a change to a process

You think your team''s weekly status meeting should move from Monday morning to Friday afternoon, to allow better weekend planning. Write an email to your manager proposing this change, with at least two reasons. (120–160 words)', 'A strong response presents a clear proposal supported by logically organized reasons and a persuasive but professional tone.'),
  ('writing', 'C1', 'prompt', 'negotiation', 'Negotiate a contract deadline diplomatically

A supplier, Kestrel Logistics, has asked to extend a contract deadline by two weeks, but this creates problems for your own client commitments. Write an email that firmly but diplomatically pushes back, proposes a one-week compromise, and preserves the business relationship. (150–200 words)', 'A strong response uses hedging and diplomatic language to assert a firm position while preserving goodwill and offering a workable compromise.'),
  ('writing', 'C1', 'prompt', 'general', 'Address a sensitive performance issue

As a team lead, you need to write to a team member, Priya, whose recent reports have contained repeated errors, affecting client trust. Write a message that raises the issue constructively, offers support, and sets a clear expectation going forward, without being harsh. (150–200 words)', 'A strong response handles a sensitive interpersonal issue with tact, balancing directness about the problem with genuine support and a constructive path forward.'),
  ('writing', 'C2', 'prompt', 'negotiation', 'Write a persuasive partnership proposal

Your company wants to propose a strategic partnership to a larger competitor, Veridian Corp, that would benefit both companies but requires them to share some proprietary data. Write a persuasive proposal email that anticipates their likely objections and addresses them convincingly. (180–250 words)', 'A strong response constructs a nuanced, persuasive argument that anticipates counterarguments and addresses them with sophisticated, precise language.'),
  ('writing', 'C2', 'prompt', 'customer_service', 'Respond to a formal escalated complaint

A long-standing corporate client, Belgrave Holdings, has sent a formal letter threatening to end a five-year contract after a serious service failure. Write a formal response that takes full responsibility, explains the corrective actions taken, and rebuilds confidence in the relationship without being defensive. (180–250 words)', 'A strong response demonstrates sophisticated command of formal register, taking ownership while strategically rebuilding trust through precise, carefully calibrated language.');

-- Speaking (18 prompt)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, explanation) VALUES
  ('speaking', 'A1', 'prompt', 'interview', 'Hello! Let''s talk about your job. What is your job? What do you do every day at work?', 'A strong A1 response names the job and lists 2-3 simple daily tasks using basic present-tense sentences.'),
  ('speaking', 'A2', 'prompt', 'interview', 'Tell me about your workplace. Who do you work with, and what do you like about your job?', 'A strong A2 response gives simple connected sentences about colleagues and one clear reason for liking the job.'),
  ('speaking', 'B1', 'prompt', 'interview', 'Describe a typical challenge you face in your job. How do you usually deal with it?', 'A strong B1 response describes a specific challenge and explains a simple solution using past and present tenses with basic linking words.'),
  ('speaking', 'B2', 'prompt', 'interview', 'Tell me about a project or task you were responsible for. What were your main responsibilities, and how did it turn out?', 'A strong B2 response gives a well-organized account with specific detail, appropriate past tenses, and a clear evaluation of the outcome.'),
  ('speaking', 'C1', 'prompt', 'interview', 'Think about a difficult decision you made at work. What was the situation, why was it difficult, and would you decide differently now?', 'A strong C1 response reflects with nuance on the decision, weighs alternatives, and uses a wide range of structures to express hindsight and reasoning.'),
  ('speaking', 'C2', 'prompt', 'interview', 'How do you typically handle disagreement with a manager or colleague at work? Talk me through your approach, including a specific example.', 'A strong C2 response articulates a sophisticated, nuanced approach to conflict with precise language, subtle distinctions, and a well-structured illustrative example.'),
  ('speaking', 'A1', 'prompt', 'role_play', 'You need a pen from your colleague. Ask your colleague, Sam, if you can borrow a pen.', 'A strong A1 response uses a simple polite request with basic vocabulary such as ''Can I have...?'' or ''Can I borrow...?'''),
  ('speaking', 'A2', 'prompt', 'role_play', 'You are going to be late for work today. Call your manager to explain that you will arrive 30 minutes late and say why.', 'A strong A2 response gives a simple, clear explanation with a reason and an approximate time using familiar everyday vocabulary.'),
  ('speaking', 'B1', 'prompt', 'role_play', 'A client is expecting a delivery today, but it will now arrive two days late. Call the client to explain the delay and suggest what you can do to help.', 'A strong B1 response explains the problem clearly, apologizes appropriately, and offers a simple, reasonable solution.'),
  ('speaking', 'B2', 'prompt', 'role_play', 'Two team members both requested the same week off for vacation, but only one can be approved. As their supervisor, speak to one of them to explain the situation and negotiate an alternative.', 'A strong B2 response negotiates diplomatically, explains constraints clearly, and proposes a fair compromise with appropriate tone.'),
  ('speaking', 'C1', 'prompt', 'role_play', 'You must tell a long-standing client that their project will be delayed by a month due to an internal error. Deliver this news in a way that maintains the client''s trust.', 'A strong C1 response delivers difficult news tactfully, takes appropriate responsibility, and reassures the client using sophisticated, diplomatic language.'),
  ('speaking', 'C2', 'prompt', 'role_play', 'Your manager has set a deadline you believe is unrealistic given your team''s current workload. Push back on the deadline professionally while proposing an alternative plan.', 'A strong C2 response pushes back assertively yet respectfully, anticipates counterarguments, and persuasively proposes a well-reasoned alternative.'),
  ('speaking', 'A1', 'prompt', 'discussion', 'Do you like working alone, or do you prefer working in a team? Why?', 'A strong A1 response states a simple preference and gives one basic reason using short, familiar sentences.'),
  ('speaking', 'A2', 'prompt', 'discussion', 'Is it better to start work early in the morning or later in the day? What do you think, and why?', 'A strong A2 response states an opinion and supports it with one or two simple reasons in connected sentences.'),
  ('speaking', 'B1', 'prompt', 'discussion', 'Do you think working from home makes people more productive, or less? Explain your opinion.', 'A strong B1 response states a clear opinion and supports it with relevant reasons and a simple example.'),
  ('speaking', 'B2', 'prompt', 'discussion', 'Some companies now offer a four-day work week. Do you think this is a good idea for businesses? Why or why not?', 'A strong B2 response presents a clear position, supports it with developed reasoning, and briefly acknowledges an opposing view.'),
  ('speaking', 'C1', 'prompt', 'discussion', 'Should companies be allowed to monitor employees'' computer activity and productivity software? What is your view, and why?', 'A strong C1 response argues a clear position with well-structured reasoning, addresses counterarguments, and uses precise, nuanced language.'),
  ('speaking', 'C2', 'prompt', 'discussion', 'As artificial intelligence automates more jobs, is it ethical for companies to replace workers with automation purely to cut costs? Argue your position.', 'A strong C2 response constructs a sophisticated, well-reasoned argument, engages critically with counterarguments, and shows command of abstract and nuanced language.');

-- Reading (12 passages, 36 mcq questions)
WITH passage_0 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag) VALUES
    ('New Office Hours', 'Subject: New Office Hours
Hello team,
From Monday, our office opens at 8:30 a.m. and closes at 5:30 p.m. We are closed on Saturdays. Please arrive on time. If you have questions, email Sara.
Thank you,
Manager', 'reading', 'A1', 'email')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('reading', 'A1', 'mcq', 'email', 'What time does the office open from Monday?', to_jsonb(ARRAY['8:30 a.m.','5:30 p.m.','9:00 a.m.','8:00 a.m.']::text[]), '8:30 a.m.', 'The email says the office ''opens at 8:30 a.m.'' from Monday.', (SELECT id FROM passage_0)),
  ('reading', 'A1', 'mcq', 'email', 'Which day is the office closed?', to_jsonb(ARRAY['Monday','Friday','Saturday','Sunday']::text[]), 'Saturday', 'The email states ''We are closed on Saturdays.''', (SELECT id FROM passage_0)),
  ('reading', 'A1', 'mcq', 'email', 'Who should staff email with questions?', to_jsonb(ARRAY['Sara','Manager','The team','Monday']::text[]), 'Sara', 'The email says ''If you have questions, email Sara,'' even though the Manager signed the message.', (SELECT id FROM passage_0));

WITH passage_1 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag) VALUES
    ('Lunch Room Notice', 'NOTICE
Please clean your dishes after lunch. Put rubbish in the bin. The lunch room closes at 2 p.m. Do not eat at your desk on Fridays. Thank you for keeping the room tidy.', 'reading', 'A1', 'general')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('reading', 'A1', 'mcq', 'general', 'What time does the lunch room close?', to_jsonb(ARRAY['1 p.m.','2 p.m.','3 p.m.','12 p.m.']::text[]), '2 p.m.', 'The notice says ''The lunch room closes at 2 p.m.''', (SELECT id FROM passage_1)),
  ('reading', 'A1', 'mcq', 'general', 'What should staff do with rubbish?', to_jsonb(ARRAY['Leave it on the table','Take it home','Put it in the bin','Give it to a manager']::text[]), 'Put it in the bin', 'The notice instructs staff to ''Put rubbish in the bin.''', (SELECT id FROM passage_1)),
  ('reading', 'A1', 'mcq', 'general', 'On which day can staff not eat at their desk?', to_jsonb(ARRAY['Monday','Wednesday','Friday','Every day']::text[]), 'Friday', 'The notice says ''Do not eat at your desk on Fridays.''', (SELECT id FROM passage_1));

WITH passage_2 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag) VALUES
    ('Return Policy Reply', 'Subject: Re: Broken Headphones
Dear Mr. Lee,
Thank you for your email. We are sorry your headphones arrived broken. Please send us a photo of the item, and we will post a new pair to you this week. You do not need to pay for the return. If you have more questions, please call us at 555-0199.
Best regards,
Customer Care Team', 'reading', 'A2', 'customer_service')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('reading', 'A2', 'mcq', 'customer_service', 'Why is the customer care team sorry?', to_jsonb(ARRAY['The headphones were the wrong color','The headphones arrived broken','The delivery was late','The price was too high']::text[]), 'The headphones arrived broken', 'The email says ''We are sorry your headphones arrived broken.''', (SELECT id FROM passage_2)),
  ('reading', 'A2', 'mcq', 'customer_service', 'What must Mr. Lee send to the company?', to_jsonb(ARRAY['The receipt','A photo of the item','The broken headphones by post','A written complaint']::text[]), 'A photo of the item', 'The email asks him to ''send us a photo of the item.''', (SELECT id FROM passage_2)),
  ('reading', 'A2', 'mcq', 'customer_service', 'Will Mr. Lee pay to return the item?', to_jsonb(ARRAY['Yes, a small fee','Yes, full price','No, he does not need to pay','Only if it''s late']::text[]), 'No, he does not need to pay', 'The email states ''You do not need to pay for the return.''', (SELECT id FROM passage_2));

WITH passage_3 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag) VALUES
    ('Parking Changes', 'MEMO
From next Tuesday, the car park behind the building will close for repairs. It will stay closed for two weeks. During this time, staff can park on Green Street for free. Please bring your staff card to show the parking guard. We are sorry for any trouble this causes.', 'reading', 'A2', 'general')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('reading', 'A2', 'mcq', 'general', 'Why will the car park close?', to_jsonb(ARRAY['For a staff party','For repairs','For cleaning','For a new building']::text[]), 'For repairs', 'The memo says the car park ''will close for repairs.''', (SELECT id FROM passage_3)),
  ('reading', 'A2', 'mcq', 'general', 'How long will the car park stay closed?', to_jsonb(ARRAY['One week','Two weeks','One month','It never reopens']::text[]), 'Two weeks', 'The memo states ''It will stay closed for two weeks.''', (SELECT id FROM passage_3)),
  ('reading', 'A2', 'mcq', 'general', 'What must staff show the parking guard on Green Street?', to_jsonb(ARRAY['A ticket','Their staff card','Their car keys','A photo ID from home']::text[]), 'Their staff card', 'The memo asks staff to ''bring your staff card to show the parking guard.''', (SELECT id FROM passage_3));

WITH passage_4 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag) VALUES
    ('Team Meeting Rescheduled', 'Subject: Team Meeting Moved to Thursday
Hi all,
Because two managers are attending a conference on Wednesday, this week''s team meeting has been moved from Wednesday to Thursday at 2 p.m. The location is unchanged: Meeting Room B. Please bring your monthly reports, as we will review sales figures and discuss the new client proposal. If Thursday does not work for you, contact Priya before Tuesday so she can arrange another time to update you separately. Lunch will not be provided this week due to budget cuts, but coffee will be available.
Regards,
Operations', 'reading', 'B1', 'email')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('reading', 'B1', 'mcq', 'email', 'Why was the meeting moved?', to_jsonb(ARRAY['Managers are on holiday','Two managers are attending a conference','The meeting room was booked','Staff requested a later time']::text[]), 'Two managers are attending a conference', 'The email explains the move is ''Because two managers are attending a conference on Wednesday.''', (SELECT id FROM passage_4)),
  ('reading', 'B1', 'mcq', 'email', 'What should attendees bring to the meeting?', to_jsonb(ARRAY['Their laptops','The new client contract','Their monthly reports','A signed attendance sheet']::text[]), 'Their monthly reports', 'The email asks staff to ''bring your monthly reports.''', (SELECT id FROM passage_4)),
  ('reading', 'B1', 'mcq', 'email', 'What will be available at the meeting despite budget cuts?', to_jsonb(ARRAY['Lunch','Coffee','Snacks','Nothing']::text[]), 'Coffee', 'The email says lunch is cancelled ''but coffee will be available.''', (SELECT id FROM passage_4));

WITH passage_5 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag) VALUES
    ('Staff Survey Results', 'A recent survey of 150 employees found that 62% feel their workload has increased over the past year, while only 18% believe they have received enough support to manage this change. Most respondents said flexible working hours would help them most, followed by additional training. Interestingly, satisfaction with management communication was higher in smaller departments than in larger ones, suggesting that clearer, more frequent updates could benefit the wider company. The HR department plans to trial flexible hours in two departments starting next month before deciding whether to extend the policy company-wide. Results will be shared with all staff by email once the trial period ends.', 'reading', 'B1', 'general')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('reading', 'B1', 'mcq', 'general', 'What percentage of employees said their workload had increased?', to_jsonb(ARRAY['18%','62%','150%','100%']::text[]), '62%', 'The report states ''62% feel their workload has increased over the past year.''', (SELECT id FROM passage_5)),
  ('reading', 'B1', 'mcq', 'general', 'What did most respondents say would help them the most?', to_jsonb(ARRAY['A pay rise','Flexible working hours','More holiday days','A larger office']::text[]), 'Flexible working hours', 'The report says ''Most respondents said flexible working hours would help them most.''', (SELECT id FROM passage_5)),
  ('reading', 'B1', 'mcq', 'general', 'Where will the flexible hours trial take place first?', to_jsonb(ARRAY['Across the whole company','In two departments','In the HR department only','In smaller departments only']::text[]), 'In two departments', 'The report states HR ''plans to trial flexible hours in two departments starting next month.''', (SELECT id FROM passage_5));

WITH passage_6 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag) VALUES
    ('Contract Renewal Terms', 'Dear Ms. Alvarez,
Following our call last week, I am writing to confirm the revised terms for renewing our supply contract. We can offer a 5% discount on bulk orders over 500 units, provided that payment is made within 30 days rather than the current 60-day term. Alternatively, if you prefer to keep the 60-day payment window, we can only extend a 2% discount. We understand that cash flow may be a concern on your end, so we are open to discussing a phased implementation over the next quarter rather than an immediate switch. Please note that these terms are valid until the end of the month, after which our standard pricing will apply. We value our partnership and hope we can reach an agreement that works well for both companies.
Kind regards,
Daniel Ross', 'reading', 'B2', 'negotiation')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('reading', 'B2', 'mcq', 'negotiation', 'What discount is offered for payment within 30 days?', to_jsonb(ARRAY['2%','5%','30%','60%']::text[]), '5%', 'The letter offers ''5% discount on bulk orders over 500 units, provided that payment is made within 30 days.''', (SELECT id FROM passage_6)),
  ('reading', 'B2', 'mcq', 'negotiation', 'What discount applies if the customer keeps the 60-day payment term?', to_jsonb(ARRAY['5%','2%','No discount','10%']::text[]), '2%', 'The letter says if the 60-day window is kept, ''we can only extend a 2% discount.''', (SELECT id FROM passage_6)),
  ('reading', 'B2', 'mcq', 'negotiation', 'Until when are these terms valid?', to_jsonb(ARRAY['The end of the quarter','The end of the month','The end of the year','Indefinitely']::text[]), 'The end of the month', 'The letter states ''these terms are valid until the end of the month.''', (SELECT id FROM passage_6));

WITH passage_7 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag) VALUES
    ('Delayed Deliveries Notice', 'Due to unusually high demand and ongoing disruption at our main distribution centre, some orders placed after 10 July may experience delivery delays of up to five extra business days. We sincerely apologise for the inconvenience this may cause. Customers awaiting urgent deliveries can contact our support team to request priority dispatch, although this cannot be guaranteed for every order. To help us manage the backlog more efficiently, we kindly ask that you avoid placing duplicate orders, as this only adds further strain to our systems. We are working closely with our courier partners to resolve the situation and expect normal delivery times to resume by the end of the month. Thank you for your patience and continued support during this period.', 'reading', 'B2', 'customer_service')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('reading', 'B2', 'mcq', 'customer_service', 'What caused the delivery delays?', to_jsonb(ARRAY['A courier strike','High demand and disruption at the distribution centre','A change in company ownership','Bad weather']::text[]), 'High demand and disruption at the distribution centre', 'The notice cites ''unusually high demand and ongoing disruption at our main distribution centre.''', (SELECT id FROM passage_7)),
  ('reading', 'B2', 'mcq', 'customer_service', 'What does the company ask customers to avoid doing?', to_jsonb(ARRAY['Contacting support','Placing duplicate orders','Paying by card','Requesting refunds']::text[]), 'Placing duplicate orders', 'The notice asks customers to ''avoid placing duplicate orders, as this only adds further strain to our systems.''', (SELECT id FROM passage_7)),
  ('reading', 'B2', 'mcq', 'customer_service', 'When does the company expect normal delivery times to resume?', to_jsonb(ARRAY['Immediately','After 10 July','By the end of the month','Never']::text[]), 'By the end of the month', 'The notice states it expects ''normal delivery times to resume by the end of the month.''', (SELECT id FROM passage_7));

WITH passage_8 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag) VALUES
    ('Restructuring Announcement', 'Dear Colleagues,
As many of you will be aware, the board approved a restructuring of the regional sales division at yesterday''s meeting. While no positions will be eliminated as a direct result of this change, several roles will be redefined, and reporting lines will shift to reflect the new structure. Employees currently reporting to the regional director will, from 1 September, report instead to their respective team leads, who will in turn report to the newly created position of Head of Sales Operations. We recognise that changes of this nature can generate uncertainty, and we want to be transparent about our reasoning: this restructuring is intended to reduce decision-making delays that have, admittedly, slowed our response to client requests in recent quarters. Nonetheless, we do not expect any disruption to ongoing client projects, and all existing commitments will be honoured. A series of briefings will be held over the coming fortnight to address individual questions, and attendance, while not mandatory, is strongly encouraged. Further details will follow shortly.
With thanks for your patience,
Executive Team', 'reading', 'C1', 'email')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('reading', 'C1', 'mcq', 'email', 'According to the email, will any positions be eliminated?', to_jsonb(ARRAY['Yes, several will be cut','No, none will be eliminated as a direct result','Only regional director roles','The email does not say']::text[]), 'No, none will be eliminated as a direct result', 'The email states ''no positions will be eliminated as a direct result of this change.''', (SELECT id FROM passage_8)),
  ('reading', 'C1', 'mcq', 'email', 'Why is the restructuring being carried out?', to_jsonb(ARRAY['To cut costs','To reduce delays in decision-making','To close the regional sales division','Because of client complaints about staff']::text[]), 'To reduce delays in decision-making', 'The email says the restructuring ''is intended to reduce decision-making delays that have... slowed our response to client requests.''', (SELECT id FROM passage_8)),
  ('reading', 'C1', 'mcq', 'email', 'Is attendance at the briefings mandatory?', to_jsonb(ARRAY['Yes, for all employees','Yes, but only for team leads','No, but it is strongly encouraged','No, briefings are optional and discouraged']::text[]), 'No, but it is strongly encouraged', 'The email says attendance is ''while not mandatory, is strongly encouraged.''', (SELECT id FROM passage_8));

WITH passage_9 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag) VALUES
    ('Remote Work Productivity Study', 'A two-year study tracking productivity across twelve companies that adopted hybrid working arrangements has produced findings that complicate the simple narrative often presented in media coverage. Contrary to expectations, employees working from home two or three days a week reported higher output on individually focused tasks, such as report writing and data analysis, than those working entirely in the office. However, teams relying heavily on spontaneous collaboration, such as product design groups, showed a measurable decline in the speed of decision-making when key members were frequently absent from the office. The researchers note that this discrepancy is not necessarily an argument against hybrid work itself, but rather evidence that policies should be tailored to the nature of the work being performed, rather than applied uniformly across an organisation. Notably, employee satisfaction rose in nearly all departments studied, regardless of team type, suggesting that any productivity trade-offs must be weighed against genuine gains in morale and retention. The study''s authors caution against drawing firm conclusions from a two-year window and recommend further longitudinal research before organisations overhaul their policies entirely.', 'reading', 'C1', 'general')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('reading', 'C1', 'mcq', 'general', 'What did the study find about employees doing individually focused tasks?', to_jsonb(ARRAY['They were less productive at home','They reported higher output working from home','They preferred working fully in the office','Their output was unaffected by location']::text[]), 'They reported higher output working from home', 'The study found these employees ''reported higher output on individually focused tasks... than those working entirely in the office.''', (SELECT id FROM passage_9)),
  ('reading', 'C1', 'mcq', 'general', 'What happened in teams that rely on spontaneous collaboration?', to_jsonb(ARRAY['Decision-making slowed when members were often absent','Productivity increased significantly','Employee satisfaction fell','They were unaffected by hybrid work']::text[]), 'Decision-making slowed when members were often absent', 'These teams ''showed a measurable decline in the speed of decision-making when key members were frequently absent from the office.''', (SELECT id FROM passage_9)),
  ('reading', 'C1', 'mcq', 'general', 'What do the study''s authors recommend?', to_jsonb(ARRAY['That all companies adopt full remote work','That hybrid policies be applied uniformly','Further long-term research before major policy changes','Ending the study immediately']::text[]), 'Further long-term research before major policy changes', 'The authors ''recommend further longitudinal research before organisations overhaul their policies entirely.''', (SELECT id FROM passage_9));

WITH passage_10 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag) VALUES
    ('Merger Terms — Internal Briefing', 'Following three rounds of talks with Halden Group, we have arrived at terms that, while not everything we hoped for at the outset, represent a defensible outcome given the leverage each side brought to the table. Halden has agreed to retain 80% of our current workforce for a minimum of eighteen months post-merger, a concession they resisted until the final session, when it became clear we were prepared to walk away rather than accept anything less. In exchange, we conceded on the valuation, settling roughly 6% below our initial asking price — a gap I would characterise as the cost of certainty in a market that shows every sign of softening further before it improves. Some on the board have questioned whether we moved too quickly; I would counter that the alternative, prolonging negotiations into next quarter, risked Halden reconsidering the deal altogether amid their own internal restructuring. Legal will circulate the full term sheet by Friday, but I wanted senior management to have the headline points beforehand, particularly given how sensitive the workforce guarantee is likely to be once communicated more broadly. I would ask that this remain confidential until the formal announcement.
Regards,
Corporate Development', 'reading', 'C2', 'negotiation')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('reading', 'C2', 'mcq', 'negotiation', 'What did Halden Group agree to regarding the workforce?', to_jsonb(ARRAY['Retain 80% of staff for at least eighteen months','Retain all staff permanently','Cut the workforce by 80%','Make no commitment about staff']::text[]), 'Retain 80% of staff for at least eighteen months', 'The briefing states Halden ''agreed to retain 80% of our current workforce for a minimum of eighteen months post-merger.''', (SELECT id FROM passage_10)),
  ('reading', 'C2', 'mcq', 'negotiation', 'How does the writer justify accepting a lower valuation?', to_jsonb(ARRAY['As a cost of gaining certainty in a weakening market','As a mistake the board forced on them','As Halden''s final and non-negotiable demand','As unrelated to market conditions']::text[]), 'As a cost of gaining certainty in a weakening market', 'The writer calls the valuation gap ''the cost of certainty in a market that shows every sign of softening further before it improves.''', (SELECT id FROM passage_10)),
  ('reading', 'C2', 'mcq', 'negotiation', 'Why did the writer resist prolonging the negotiations?', to_jsonb(ARRAY['Legal required a decision by Friday','Halden might reconsider the deal amid their own restructuring','The board demanded a quick resolution','The workforce guarantee would expire']::text[]), 'Halden might reconsider the deal amid their own restructuring', 'The writer says prolonging negotiations ''risked Halden reconsidering the deal altogether amid their own internal restructuring.''', (SELECT id FROM passage_10));

WITH passage_11 AS (
  INSERT INTO public.passages (title, body, skill, cefr_level, context_tag) VALUES
    ('A Note on Handling Escalations', 'It would be easy to conclude, after reading last month''s escalation figures, that our front-line team is simply overwhelmed and understaffed. The data, examined more closely, tells a somewhat different story. Average resolution time has actually improved by eleven percent since the new ticketing system was introduced, and the proportion of complaints resolved on first contact has held steady despite a twenty percent rise in ticket volume. What has changed is not our team''s competence but the nature of the complaints reaching them: a growing share now involve billing disputes that require input from finance before they can be closed, inflating the headline figures for cases left ''open'' beyond target. This is not, in other words, a performance problem so much as a process one, and treating it as the former risks demoralising a team that is, if anything, outperforming its previous benchmarks under harder conditions. I would rather we invest in a faster handoff mechanism with finance than pursue the additional hiring some have proposed, which addresses a symptom rather than the underlying bottleneck. I am happy to discuss this further at Thursday''s leadership meeting, where I suspect this issue will come up regardless of whether it is on the agenda.', 'reading', 'C2', 'customer_service')
  RETURNING id
)
INSERT INTO public.questions (skill, cefr_level, type, context_tag, prompt_text, options, correct_answer, explanation, passage_id) VALUES
  ('reading', 'C2', 'mcq', 'customer_service', 'What has happened to average resolution time since the new ticketing system was introduced?', to_jsonb(ARRAY['It has worsened by eleven percent','It has improved by eleven percent','It has stayed exactly the same','It cannot be measured']::text[]), 'It has improved by eleven percent', 'The note states ''Average resolution time has actually improved by eleven percent since the new ticketing system was introduced.''', (SELECT id FROM passage_11)),
  ('reading', 'C2', 'mcq', 'customer_service', 'According to the writer, what is the real cause of cases staying open longer?', to_jsonb(ARRAY['An understaffed and incompetent team','A twenty percent drop in ticket volume','Billing disputes needing input from finance','A faulty ticketing system']::text[]), 'Billing disputes needing input from finance', 'The writer explains that ''billing disputes that require input from finance before they can be closed'' are ''inflating the headline figures.''', (SELECT id FROM passage_11)),
  ('reading', 'C2', 'mcq', 'customer_service', 'What solution does the writer prefer over additional hiring?', to_jsonb(ARRAY['Reducing ticket volume','A faster handoff mechanism with finance','Lowering performance targets','Removing billing disputes from the queue entirely']::text[]), 'A faster handoff mechanism with finance', 'The writer says ''I would rather we invest in a faster handoff mechanism with finance than pursue the additional hiring some have proposed.''', (SELECT id FROM passage_11));
